# SPDX-License-Identifier: GPL-2.0
obj-m := drv_devdrv.o

drv_devdrv-objs := \
	ts_drv_common/devdrv_cqsq.o \
	ts_drv_common/devdrv_devinit.o \
	tsdrv_drvops.o \
	tsdrv_get_ssid.o \
	ts_drv_common/devdrv_functional_cqsq.o \
	ts_drv_common/devdrv_mailbox.o \
	ts_drv_common/tsdrv_delay_recycle.o \
	ts_drv_common/devdrv_id.o \
	ts_drv_common/devdrv_recycle.o \
	ts_drv_common/devdrv_shm.o \
	ts_drv_common/tsdrv_dev/tsdrv_device.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx.o \
	ts_drv_common/tsdrv_dev/tsdrv_capacity.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo_platform.o \
	ts_drv_common/tsdrv_dev/tsdrv_dev_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_mailbox_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_comm_fops.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_event_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_config_dfx.o \
	ts_drv_common/tsdrv_id/tsdrv_id.o \
	ts_drv_common/tsdrv_id/tsdrv_sync.o \
	ts_drv_common/tsdrv_nvme/tsdrv_nvme.o \
	ts_drv_common/tsdrv_nvme/shm/shm_sqcq.o \
	ts_drv_common/tsdrv_nvme/logic/logic_cq.o \
	ts_drv_common/tsdrv_nvme/logic/tsdrv_logic_cq.o \
	ts_drv_common/devdrv_ipc_notify.o \
	ts_drv_common/devdrv_nsm.o \
	tsdrv_notify.o \
	ts_drv_common/tsdrv_osal/tsdrv_osal_intr.o \
	ts_drv_common/tsdrv_osal/tsdrv_osal_mm.o \
	ts_drv_common/tsdrv_osal/tsdrv_osal_bbox.o

DRIVER_INC := $(src)/..
ccflags-y += -Wall -Werror
ccflags-y += $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char -Wformat=2
ccflags-y += -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-format-nonliteral -Wno-empty-body
ccflags-y += -DCFG_FEATURE_IPC_NOTIFY
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) -I$(src)/ts_drv_common -I$(src)/ts_drv_common/tsdrv_dev
ccflags-y += -I$(src)/ts_drv_common/tsdrv_id -I$(src)/ts_drv_common/tsdrv_nvme
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme/shm -I$(src)/ts_drv_common/tsdrv_nvme/logic
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme/sync_cb
ccflags-y += -I$(src)/ts_drv_common/devdrv_callback
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend310
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend610
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend910
ccflags-y += -I$(src)/ts_drv_common/tsdrv_cdqm
ccflags-y += -I$(src)/ts_drv_common/tsdrv_osal
ccflags-y += -I$(src)/ascend310 -I$(src)/ascend310/tsdrv_conflict_check
ccflags-y += -I$(src)/ascend610 -I$(src)/ascend610/tsdrv_conflict_check
ccflags-y += -I$(src)/ascend910 -I$(src)/ascend910/tsdrv_conflict_check
ccflags-y += -I$(src)/tsdrv_cdqm -I$(src)/tsdrv_virt -I$(src)/tsdrv_virt_stub
ccflags-y += -I$(src)/soc/cdqm_v1

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifneq ($(filter $(PRODUCT), ascend910 ascend910B ascend920esl ascend920emu),)
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v1
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCFG_FEATURE_PSS_SIGN -DCFG_FEATURE_SURPORT_P2P
ccflags-y += -DCFG_FEATURE_USE_MAILBOX_RECYCLE
ifneq ($(filter $(PRODUCT), ascend910),)
ccflags-y += -DCFG_FEATURE_RUNTIME_NO_THREAD
endif

drv_devdrv-objs += \
	ts_drv_common/devdrv_callback/devdrv_cb.o \
	ts_drv_common/devdrv_callback/devdrv_cbctrl.o \
	ts_drv_common/devdrv_callback/tsdrv_cb_pm.o \
	ascend910/devdrv_config_p2p.o \
	ts_drv_common/tsdrv_conflict_check/ascend910/tsdrv_set_runtime_conflict_check.o \
	ascend910/tsdrv_conflict_check/tsdrv_bar_init.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id_event.o \
	ts_drv_common/tsdrv_id/hvtsdrv_cqsq.o \
	tsdrv_virt_stub/hvtsdrv_proc.o \
	tsdrv_virt_stub/hvtsdrv_cb.o \
	tsdrv_virt_stub/hvtsdrv_logic_cq.o \
	tsdrv_virt_stub/hvtsdrv_shm_sqcq.o

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v2
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA -DVER_CDQM_B607
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2 -DCFG_SOC_PLATFORM_DEVICE
ccflags-y += -DCFG_FEATURE_CDQM -DCFG_FEATURE_CALLBACK_EVENT
ccflags-y += -DCFG_FEATURE_VFIO -DCFG_FEATURE_SUPPORT_VSQ_MNG
ccflags-y += -DCFG_FEATURE_STARS
ifneq ($(filter $(PRODUCT), ascend920esl),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2_ESL
endif
drv_devdrv-objs += \
	tsdrv_cdqm/tsdrv_cdqm_dev.o \
	ts_drv_common/tsdrv_cdqm/tsdrv_cdqm_module.o \
	soc/cdqm_v1/cdq_manager.o \
	ts_drv_common/tsdrv_vsq.o \
	ts_drv_common/hvtsdrv_tsagent.o \
	tsdrv_virt/dvtsdrv_init.o \
	tsdrv_virt/dvtsdrv_sriov_id.o \
	tsdrv_virt/dvtsdrv_sriov_hwinfo.o
else
drv_devdrv-objs += tsdrv_virt_stub/hvtsdrv_tsagent.o
endif

else ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu ascend610 bs9sx1a ascend310p helper310p),)
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
ccflags-y += -DCFG_SOC_PLATFORM_MINI

drv_devdrv-objs += \
	ts_drv_common/devdrv_callback/devdrv_cb.o \
	ts_drv_common/devdrv_callback/devdrv_cbctrl.o \
	ts_drv_common/devdrv_callback/tsdrv_cb_pm.o \
	ascend610/devdrv_config_p2p.o \
	ts_drv_common/tsdrv_conflict_check/ascend610/tsdrv_set_runtime_conflict_check.o \
	ascend610/tsdrv_conflict_check/tsdrv_bar_init.o \
	devdrv_devinfo.o

ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_FEATURE_CDQM -DCFG_FEATURE_CMO
ccflags-y += -DCFG_FEATURE_SURPORT_P2P -DCFG_FEATURE_SUPPORT_VSQ_MNG
ccflags-y += -DCFG_FEATURE_USE_MAILBOX_RECYCLE -DCFG_FEATURE_RUNTIME_NO_THREAD
ccflags-y += -DCFG_FEATURE_STARS -DCFG_FEATURE_CALLBACK_EVENT
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA
endif

ifneq ($(filter $(PRODUCT), ascend310rc ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_RC_MODE
endif

ifneq ($(filter $(PRODUCT), ascend310p),)
ccflags-y += -DCFG_FEATURE_ID_MAPING -DCFG_FEATURE_SURPORT_P2P
endif

ifneq ($(filter $(PRODUCT), ascend310p helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCFG_FEATURE_RUNTIME_NO_THREAD -DCFG_SOC_PLATFORM_DEVICE
ccflags-y += -DCFG_FEATURE_USE_MAILBOX_RECYCLE -DCFG_FEATURE_IPC_NOTIFY_WITH_EVENTID
endif

ifneq ($(filter $(PRODUCT), helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_RUNTIME_NO_THREAD
ccflags-y += -DCFG_SOC_PLATFORM_MDC -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DSUPPORT_FLEXIBLE_BIND_CORE
drv_devdrv-objs += \
	ascend610/bind_core.o \
	ts_drv_common/tsdrv_rts_streamid.o \
	ascend610/tsdrv_ts_node.o
else
drv_devdrv-objs += \
	ts_drv_common/tsdrv_id/hvtsdrv_id.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id_event.o \
	ts_drv_common/tsdrv_id/hvtsdrv_cqsq.o \
	tsdrv_virt_stub/hvtsdrv_proc.o \
	tsdrv_virt_stub/hvtsdrv_cb.o \
	tsdrv_virt_stub/hvtsdrv_logic_cq.o \
	tsdrv_virt_stub/hvtsdrv_shm_sqcq.o
ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
drv_devdrv-objs += \
	tsdrv_cdqm/tsdrv_cdqm_dev.o \
	ts_drv_common/tsdrv_cmo_id.o \
	ts_drv_common/tsdrv_cdqm/tsdrv_cdqm_module.o \
	soc/cdqm_v1/cdq_manager.o \
	ts_drv_common/tsdrv_vsq.o \
	ts_drv_common/hvtsdrv_tsagent.o
else
drv_devdrv-objs += tsdrv_virt_stub/hvtsdrv_tsagent.o
endif
endif

else
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend310
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_SURPORT_P2P
drv_devdrv-objs += \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_sync_cbctrl.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cbcq.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cbsq.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cb_stub.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id_event.o \
	ts_drv_common/tsdrv_id/hvtsdrv_cqsq.o \
	ts_drv_common/tsdrv_conflict_check/ascend310/tsdrv_set_runtime_conflict_check.o \
	ascend310/devdrv_config_p2p.o \
	ascend310/tsdrv_conflict_check/tsdrv_bar_init.o \
	tsdrv_virt_stub/hvtsdrv_proc.o \
	tsdrv_virt_stub/hvtsdrv_cb.o \
	tsdrv_virt_stub/hvtsdrv_logic_cq.o \
	tsdrv_virt_stub/hvtsdrv_shm_sqcq.o \
	tsdrv_virt_stub/hvtsdrv_tsagent.o
endif

ccflags-y += -I$(DRIVER_INC)/include/devmng -I$(DRIVER_INC)/include/internal
ccflags-y += -I$(DRIVER_INC)/include/tsdrv

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
