# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_tsmng.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)

ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
BUILD_PREFIX := ascend310
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend310
else
BUILD_PREFIX := ascend910
ifneq ($(filter $(PRODUCT), ascend910 ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCFG_FEATURE_IMU_ENABLE
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend910
ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DCFG_FEATURE_TS_ALLOC_MEM
ccflags-y += -DCFG_FEATURE_TS_ABNORMAL_INFO
endif
else ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu ascend310p helper310p ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend610
endif
endif

ifneq ($(filter $(PRODUCT), ascend310p helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -DCFG_FEATURE_LP_ENABLE
endif

ifneq ($(filter $(PRODUCT), helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DCFG_FEATURE_IPC_CRC
ccflags-y += -DCFG_FEATURE_LP_ENABLE
endif

ifneq ($(filter $(PRODUCT), as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif

ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -DCFG_FEATURE_IMU_ENABLE
ccflags-y += -DCFG_FEATURE_TS_ABNORMAL_INFO
endif

ccflags-y += -I$(src)/$(BUILD_PREFIX)

ascend_trs_tsmng-objs := \
	tsmng_common.o \
	$(BUILD_PREFIX)/tsmng_pm.o \
	$(BUILD_PREFIX)/tsmng_notifier.o

ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu ascend910B ascend920esl ascend920emu),)
ascend_trs_tsmng-objs += $(BUILD_PREFIX)/tsmng_abnormal_info.o
ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ascend_trs_tsmng-objs += $(BUILD_PREFIX)/tsmng_mem.o
endif
endif

ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu ascend610 bs9sx1a ascend610Lite ascend610Liteesl ascend310p helper310p),)
ascend_trs_tsmng-objs += $(BUILD_PREFIX)/tsmng_group.o
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
