# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_tsmng.o
ascend_trs_tsmng-objs := tsmng_common.o ascend910/tsmng_pm.o ascend910/tsmng_notifier.o ascend910/tsmng_abnormal_info.o ascend910/tsmng_group.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/ascend910
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_IMU_ENABLE -DCFG_FEATURE_TS_ABNORMAL_INFO
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
