/*
 * Copyright     :  Copyright (C) 2022, Huawei Technologies Co. Ltd.
 * File name     :  ffts1_reg_ns_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2013/3/10
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2022/02/28 16:49:42 Create file
 */

#ifndef __FFTS1_REG_NS_REG_OFFSET_FIELD_H__
#define __FFTS1_REG_NS_REG_OFFSET_FIELD_H__

#define FFTS1_REG_NS_SP_LEVEL_LEN      3
#define FFTS1_REG_NS_SP_LEVEL_OFFSET   8
#define FFTS1_REG_NS_LP_MODE_LEN       3
#define FFTS1_REG_NS_LP_MODE_OFFSET    0




#define FFTS1_REG_NS_L2_FRIENDLY_FFTS_LEN    1
#define FFTS1_REG_NS_L2_FRIENDLY_FFTS_OFFSET 8






#define FFTS1_REG_NS_AIV_SKIP_WARN_STATUS_LEN    1
#define FFTS1_REG_NS_AIV_SKIP_WARN_STATUS_OFFSET 1
#define FFTS1_REG_NS_AIC_SKIP_WARN_STATUS_LEN    1
#define FFTS1_REG_NS_AIC_SKIP_WARN_STATUS_OFFSET 0



#define FFTS1_REG_NS_FFTS_SLOT_ENABLE_CTRL_NS_LEN    2
#define FFTS1_REG_NS_FFTS_SLOT_ENABLE_CTRL_NS_OFFSET 0

#define FFTS1_REG_NS_FFTS_SLOT_DISABLE_CTRL_NS_LEN    2
#define FFTS1_REG_NS_FFTS_SLOT_DISABLE_CTRL_NS_OFFSET 0

#define FFTS1_REG_NS_FFTS_SLOT_ENABLED_STATUS_NS_LEN    2
#define FFTS1_REG_NS_FFTS_SLOT_ENABLED_STATUS_NS_OFFSET 0

#define FFTS1_REG_NS_AIC_ENABLE_CTRL_NS_LEN    1
#define FFTS1_REG_NS_AIC_ENABLE_CTRL_NS_OFFSET 0

#define FFTS1_REG_NS_AIC_DISABLE_CTRL_NS_LEN    1
#define FFTS1_REG_NS_AIC_DISABLE_CTRL_NS_OFFSET 0

#define FFTS1_REG_NS_AIC_ENABLED_STATUS_NS_LEN    1
#define FFTS1_REG_NS_AIC_ENABLED_STATUS_NS_OFFSET 0

#define FFTS1_REG_NS_AIV_ENABLE_CTRL_NS_LEN    1
#define FFTS1_REG_NS_AIV_ENABLE_CTRL_NS_OFFSET 0


#define FFTS1_REG_NS_AIV_DISABLE_CTRL_NS_LEN    1
#define FFTS1_REG_NS_AIV_DISABLE_CTRL_NS_OFFSET 0


#define FFTS1_REG_NS_AIV_ENABLED_STATUS_NS_LEN    1
#define FFTS1_REG_NS_AIV_ENABLED_STATUS_NS_OFFSET 0


#define FFTS1_REG_NS_BUS_BLOCK_ENABLE_LEN    1
#define FFTS1_REG_NS_BUS_BLOCK_ENABLE_OFFSET 0

#define FFTS1_REG_NS_BUS_RD_STATE_LEN      1
#define FFTS1_REG_NS_BUS_RD_STATE_OFFSET   24
#define FFTS1_REG_NS_BUS_RD_OST_CNT_LEN    7
#define FFTS1_REG_NS_BUS_RD_OST_CNT_OFFSET 16
#define FFTS1_REG_NS_BUS_WR_STATE_LEN      4
#define FFTS1_REG_NS_BUS_WR_STATE_OFFSET   8
#define FFTS1_REG_NS_BUS_WR_OST_CNT_LEN    7
#define FFTS1_REG_NS_BUS_WR_OST_CNT_OFFSET 0

#define FFTS1_REG_NS_AIV_UTILIZATION_EN_LEN    1
#define FFTS1_REG_NS_AIV_UTILIZATION_EN_OFFSET 1
#define FFTS1_REG_NS_AIC_UTILIZATION_EN_LEN    1
#define FFTS1_REG_NS_AIC_UTILIZATION_EN_OFFSET 0

#define FFTS1_REG_NS_FFTS_UTILIZATION_WIND_LEN    12
#define FFTS1_REG_NS_FFTS_UTILIZATION_WIND_OFFSET 0

#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_0_LEN    28
#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_0_OFFSET 0

#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_1_LEN    28
#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_1_OFFSET 0

#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_2_LEN    28
#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_2_OFFSET 0

#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_3_LEN    28
#define FFTS1_REG_NS_VF_AIC_BUSY_CNT_3_OFFSET 0

#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_0_LEN    28
#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_0_OFFSET 0

#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_1_LEN    28
#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_1_OFFSET 0

#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_2_LEN    28
#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_2_OFFSET 0

#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_3_LEN    28
#define FFTS1_REG_NS_VF_AIV_BUSY_CNT_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_0_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_1_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_2_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_3_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_4_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_5_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_6_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_7_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_8_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_9_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_10_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_11_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_12_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_13_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_14_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_15_LEN    20
#define FFTS1_REG_NS_PROFILE_BUF_LENGTH_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_0_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_1_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_2_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_3_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_4_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_5_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_6_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_7_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_8_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_9_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_10_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_11_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_12_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_13_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_14_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_15_LEN    20
#define FFTS1_REG_NS_PROFILE_AF_THRESHOLD_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_0_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_1_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_2_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_3_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_4_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_5_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_6_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_7_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_8_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_9_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_10_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_11_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_12_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_13_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_14_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_15_LEN    32
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_L_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_0_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_0_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_0_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_1_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_1_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_1_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_2_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_2_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_2_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_3_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_3_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_3_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_4_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_4_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_4_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_5_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_5_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_5_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_6_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_6_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_6_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_7_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_7_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_7_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_8_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_8_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_8_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_9_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_9_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_9_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_10_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_10_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_10_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_10_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_11_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_11_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_11_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_11_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_12_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_12_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_12_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_12_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_13_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_13_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_13_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_13_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_14_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_14_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_14_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_14_OFFSET          0

#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_15_LEN    1
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_IS_VIRTUAL_15_OFFSET 31
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_15_LEN             17
#define FFTS1_REG_NS_PROFILE_BASE_ADDR_H_15_OFFSET          0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_0_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_1_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_2_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_3_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_4_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_5_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_6_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_7_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_8_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_9_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_10_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_11_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_12_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_13_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_14_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_15_LEN    1
#define FFTS1_REG_NS_PROFILE_WPTR_INITIAL_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_0_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_1_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_2_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_3_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_4_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_5_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_6_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_7_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_8_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_9_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_10_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_11_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_12_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_13_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_14_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_WPTR_15_LEN    20
#define FFTS1_REG_NS_PROFILE_WPTR_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_0_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_1_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_2_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_3_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_4_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_5_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_6_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_7_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_8_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_9_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_10_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_11_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_12_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_13_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_14_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_RPTR_15_LEN    20
#define FFTS1_REG_NS_PROFILE_RPTR_15_OFFSET 0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_0_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_0_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_0_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_0_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_1_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_1_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_1_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_1_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_2_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_2_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_2_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_2_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_3_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_3_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_3_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_3_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_4_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_4_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_4_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_4_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_5_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_5_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_5_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_5_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_6_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_6_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_6_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_6_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_7_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_7_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_7_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_7_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_8_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_8_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_8_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_8_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_9_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_9_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_9_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_9_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_10_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_10_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_10_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_10_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_11_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_11_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_11_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_11_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_12_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_12_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_12_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_12_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_13_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_13_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_13_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_13_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_14_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_14_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_14_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_14_OFFSET    0

#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_15_LEN    16
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_15_OFFSET 16
#define FFTS1_REG_NS_PROFILE_STREAMID_15_LEN       16
#define FFTS1_REG_NS_PROFILE_STREAMID_15_OFFSET    0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_0_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_0_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_0_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_0_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_1_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_1_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_1_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_1_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_2_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_2_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_2_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_2_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_3_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_3_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_3_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_3_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_4_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_4_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_4_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_4_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_5_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_5_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_5_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_5_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_6_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_6_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_6_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_6_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_7_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_7_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_7_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_7_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_8_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_8_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_8_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_8_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_9_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_9_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_9_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_9_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_10_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_10_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_10_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_10_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_11_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_11_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_11_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_11_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_12_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_12_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_12_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_12_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_13_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_13_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_13_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_13_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_14_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_14_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_14_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_14_OFFSET 0

#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_15_LEN        1
#define FFTS1_REG_NS_PROFILE_BUF_SEC_EN_15_OFFSET     1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_15_LEN    1
#define FFTS1_REG_NS_PROFILE_SUBSTREAMID_EN_15_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT0_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT1_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT2_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT3_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT4_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT5_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT6_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_0_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_1_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_2_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_3_LEN    12
#define FFTS1_REG_NS_AIC_PMU_CNT7_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT0_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT1_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT2_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT3_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT4_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT5_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT6_IDX_3_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_0_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_0_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_1_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_1_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_2_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_2_OFFSET 0

#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_3_LEN    12
#define FFTS1_REG_NS_AIV_PMU_CNT7_IDX_3_OFFSET 0


#define FFTS1_REG_NS_SLOT_CXT_PROF_DONE_0_LEN    1
#define FFTS1_REG_NS_SLOT_CXT_PROF_DONE_0_OFFSET 17
#define FFTS1_REG_NS_SLOT_CXT_LOG_DONE_0_LEN     1
#define FFTS1_REG_NS_SLOT_CXT_LOG_DONE_0_OFFSET  16
#define FFTS1_REG_NS_SLOT_FFTS_TYPE_0_LEN        3
#define FFTS1_REG_NS_SLOT_FFTS_TYPE_0_OFFSET     8
#define FFTS1_REG_NS_SLOT_STATE_0_LEN            4
#define FFTS1_REG_NS_SLOT_STATE_0_OFFSET         0

#define FFTS1_REG_NS_SLOT_CXT_PROF_DONE_1_LEN    1
#define FFTS1_REG_NS_SLOT_CXT_PROF_DONE_1_OFFSET 17
#define FFTS1_REG_NS_SLOT_CXT_LOG_DONE_1_LEN     1
#define FFTS1_REG_NS_SLOT_CXT_LOG_DONE_1_OFFSET  16
#define FFTS1_REG_NS_SLOT_FFTS_TYPE_1_LEN        3
#define FFTS1_REG_NS_SLOT_FFTS_TYPE_1_OFFSET     8
#define FFTS1_REG_NS_SLOT_STATE_1_LEN            4
#define FFTS1_REG_NS_SLOT_STATE_1_OFFSET         0

#define FFTS1_REG_NS_SLOT_AICDQ_RETURN_STATE_0_LEN    4
#define FFTS1_REG_NS_SLOT_AICDQ_RETURN_STATE_0_OFFSET 8
#define FFTS1_REG_NS_SLOT_AICDQ_KICK_STATE_0_LEN      4
#define FFTS1_REG_NS_SLOT_AICDQ_KICK_STATE_0_OFFSET   0

#define FFTS1_REG_NS_SLOT_AICDQ_RETURN_STATE_1_LEN    4
#define FFTS1_REG_NS_SLOT_AICDQ_RETURN_STATE_1_OFFSET 8
#define FFTS1_REG_NS_SLOT_AICDQ_KICK_STATE_1_LEN      4
#define FFTS1_REG_NS_SLOT_AICDQ_KICK_STATE_1_OFFSET   0

#define FFTS1_REG_NS_SLOT_AIVDQ_RETURN_STATE_0_LEN    4
#define FFTS1_REG_NS_SLOT_AIVDQ_RETURN_STATE_0_OFFSET 8
#define FFTS1_REG_NS_SLOT_AIVDQ_KICK_STATE_0_LEN      4
#define FFTS1_REG_NS_SLOT_AIVDQ_KICK_STATE_0_OFFSET   0

#define FFTS1_REG_NS_SLOT_AIVDQ_RETURN_STATE_1_LEN    4
#define FFTS1_REG_NS_SLOT_AIVDQ_RETURN_STATE_1_OFFSET 8
#define FFTS1_REG_NS_SLOT_AIVDQ_KICK_STATE_1_LEN      4
#define FFTS1_REG_NS_SLOT_AIVDQ_KICK_STATE_1_OFFSET   0

#define FFTS1_REG_NS_SLOT_AIC_OWN_BITMAP_0_LEN    2
#define FFTS1_REG_NS_SLOT_AIC_OWN_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_OWN_BITMAP_1_LEN    2
#define FFTS1_REG_NS_SLOT_AIC_OWN_BITMAP_1_OFFSET 0



#define FFTS1_REG_NS_SLOT_AIC_DONE_BITMAP_0_LEN    2
#define FFTS1_REG_NS_SLOT_AIC_DONE_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_DONE_BITMAP_1_LEN    2
#define FFTS1_REG_NS_SLOT_AIC_DONE_BITMAP_1_OFFSET 0



#define FFTS1_REG_NS_SLOT_AIC_DEBUG_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_DEBUG_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_DEBUG_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_DEBUG_BITMAP_1_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_ERROR_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_ERROR_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_ERROR_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_ERROR_BITMAP_1_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_TRAP_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_TRAP_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIC_TRAP_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIC_TRAP_BITMAP_1_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_OWN_BITMAP_0_LEN    2
#define FFTS1_REG_NS_SLOT_AIV_OWN_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_OWN_BITMAP_1_LEN    2
#define FFTS1_REG_NS_SLOT_AIV_OWN_BITMAP_1_OFFSET 0







#define FFTS1_REG_NS_SLOT_AIV_DONE_BITMAP_0_LEN    2
#define FFTS1_REG_NS_SLOT_AIV_DONE_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_DONE_BITMAP_1_LEN    2
#define FFTS1_REG_NS_SLOT_AIV_DONE_BITMAP_1_OFFSET 0







#define FFTS1_REG_NS_SLOT_AIV_DEBUG_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_DEBUG_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_DEBUG_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_DEBUG_BITMAP_1_OFFSET 0



#define FFTS1_REG_NS_SLOT_AIV_ERROR_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_ERROR_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_ERROR_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_ERROR_BITMAP_1_OFFSET 0



#define FFTS1_REG_NS_SLOT_AIV_TRAP_BITMAP_0_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_TRAP_BITMAP_0_OFFSET 0

#define FFTS1_REG_NS_SLOT_AIV_TRAP_BITMAP_1_LEN    1
#define FFTS1_REG_NS_SLOT_AIV_TRAP_BITMAP_1_OFFSET 0




#define FFTS1_REG_NS_AIC_FSM0_WARN_OST_CNT_LEN      1
#define FFTS1_REG_NS_AIC_FSM0_WARN_OST_CNT_OFFSET   21
#define FFTS1_REG_NS_AIC_FSM0_PMU_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIC_FSM0_PMU_OST_CNT_OFFSET    19
#define FFTS1_REG_NS_AIC_FSM0_LOG_OST_CNT_LEN       2
#define FFTS1_REG_NS_AIC_FSM0_LOG_OST_CNT_OFFSET    17
#define FFTS1_REG_NS_AIC_FSM0_CFG_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIC_FSM0_CFG_OST_CNT_OFFSET    16
#define FFTS1_REG_NS_AIC_FSM0_DONE_WITH_WARN_LEN    1
#define FFTS1_REG_NS_AIC_FSM0_DONE_WITH_WARN_OFFSET 10
#define FFTS1_REG_NS_AIC_FSM0_MIXTYPE_LEN           2
#define FFTS1_REG_NS_AIC_FSM0_MIXTYPE_OFFSET        8
#define FFTS1_REG_NS_AIC_FSM0_STATE_LEN             4
#define FFTS1_REG_NS_AIC_FSM0_STATE_OFFSET          0

#define FFTS1_REG_NS_AIC_FSM0_TSLOTID_LEN    1
#define FFTS1_REG_NS_AIC_FSM0_TSLOTID_OFFSET 0

#define FFTS1_REG_NS_AIC_FSM0_THREADID_0_LEN    16
#define FFTS1_REG_NS_AIC_FSM0_THREADID_0_OFFSET 16
#define FFTS1_REG_NS_AIC_FSM0_CXTID_0_LEN       16
#define FFTS1_REG_NS_AIC_FSM0_CXTID_0_OFFSET    0

#define FFTS1_REG_NS_AIC_FSM0_BLKID_0_LEN      16
#define FFTS1_REG_NS_AIC_FSM0_BLKID_0_OFFSET   16
#define FFTS1_REG_NS_AIC_FSM0_SUBLKID_0_LEN    8
#define FFTS1_REG_NS_AIC_FSM0_SUBLKID_0_OFFSET 0

#define FFTS1_REG_NS_AIC_FSM1_WARN_OST_CNT_LEN      1
#define FFTS1_REG_NS_AIC_FSM1_WARN_OST_CNT_OFFSET   21
#define FFTS1_REG_NS_AIC_FSM1_PMU_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIC_FSM1_PMU_OST_CNT_OFFSET    19
#define FFTS1_REG_NS_AIC_FSM1_LOG_OST_CNT_LEN       2
#define FFTS1_REG_NS_AIC_FSM1_LOG_OST_CNT_OFFSET    17
#define FFTS1_REG_NS_AIC_FSM1_CFG_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIC_FSM1_CFG_OST_CNT_OFFSET    16
#define FFTS1_REG_NS_AIC_FSM1_DONE_WITH_WARN_LEN    1
#define FFTS1_REG_NS_AIC_FSM1_DONE_WITH_WARN_OFFSET 10
#define FFTS1_REG_NS_AIC_FSM1_MIXTYPE_LEN           2
#define FFTS1_REG_NS_AIC_FSM1_MIXTYPE_OFFSET        8
#define FFTS1_REG_NS_AIC_FSM1_STATE_LEN             4
#define FFTS1_REG_NS_AIC_FSM1_STATE_OFFSET          0

#define FFTS1_REG_NS_AIC_FSM1_TSLOTID_LEN    1
#define FFTS1_REG_NS_AIC_FSM1_TSLOTID_OFFSET 0

#define FFTS1_REG_NS_AIC_FSM1_THREADID_0_LEN    16
#define FFTS1_REG_NS_AIC_FSM1_THREADID_0_OFFSET 16
#define FFTS1_REG_NS_AIC_FSM1_CXTID_0_LEN       16
#define FFTS1_REG_NS_AIC_FSM1_CXTID_0_OFFSET    0

#define FFTS1_REG_NS_AIC_FSM1_BLKID_0_LEN      16
#define FFTS1_REG_NS_AIC_FSM1_BLKID_0_OFFSET   16
#define FFTS1_REG_NS_AIC_FSM1_SUBLKID_0_LEN    8
#define FFTS1_REG_NS_AIC_FSM1_SUBLKID_0_OFFSET 0


#define FFTS1_REG_NS_AIV_FSM0_WARN_OST_CNT_LEN      1
#define FFTS1_REG_NS_AIV_FSM0_WARN_OST_CNT_OFFSET   21
#define FFTS1_REG_NS_AIV_FSM0_PMU_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIV_FSM0_PMU_OST_CNT_OFFSET    19
#define FFTS1_REG_NS_AIV_FSM0_LOG_OST_CNT_LEN       2
#define FFTS1_REG_NS_AIV_FSM0_LOG_OST_CNT_OFFSET    17
#define FFTS1_REG_NS_AIV_FSM0_CFG_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIV_FSM0_CFG_OST_CNT_OFFSET    16
#define FFTS1_REG_NS_AIV_FSM0_DONE_WITH_WARN_LEN    1
#define FFTS1_REG_NS_AIV_FSM0_DONE_WITH_WARN_OFFSET 10
#define FFTS1_REG_NS_AIV_FSM0_MIXTYPE_LEN           2
#define FFTS1_REG_NS_AIV_FSM0_MIXTYPE_OFFSET        8
#define FFTS1_REG_NS_AIV_FSM0_STATE_LEN             4
#define FFTS1_REG_NS_AIV_FSM0_STATE_OFFSET          0

#define FFTS1_REG_NS_AIV_FSM0_TSLOTID_LEN    1
#define FFTS1_REG_NS_AIV_FSM0_TSLOTID_OFFSET 0

#define FFTS1_REG_NS_AIV_FSM0_THREADID_0_LEN    16
#define FFTS1_REG_NS_AIV_FSM0_THREADID_0_OFFSET 16
#define FFTS1_REG_NS_AIV_FSM0_CXTID_0_LEN       16
#define FFTS1_REG_NS_AIV_FSM0_CXTID_0_OFFSET    0

#define FFTS1_REG_NS_AIV_FSM0_BLKID_0_LEN      16
#define FFTS1_REG_NS_AIV_FSM0_BLKID_0_OFFSET   16
#define FFTS1_REG_NS_AIV_FSM0_SUBLKID_0_LEN    8
#define FFTS1_REG_NS_AIV_FSM0_SUBLKID_0_OFFSET 0

#define FFTS1_REG_NS_AIV_FSM1_WARN_OST_CNT_LEN      1
#define FFTS1_REG_NS_AIV_FSM1_WARN_OST_CNT_OFFSET   21
#define FFTS1_REG_NS_AIV_FSM1_PMU_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIV_FSM1_PMU_OST_CNT_OFFSET    19
#define FFTS1_REG_NS_AIV_FSM1_LOG_OST_CNT_LEN       2
#define FFTS1_REG_NS_AIV_FSM1_LOG_OST_CNT_OFFSET    17
#define FFTS1_REG_NS_AIV_FSM1_CFG_OST_CNT_LEN       1
#define FFTS1_REG_NS_AIV_FSM1_CFG_OST_CNT_OFFSET    16
#define FFTS1_REG_NS_AIV_FSM1_DONE_WITH_WARN_LEN    1
#define FFTS1_REG_NS_AIV_FSM1_DONE_WITH_WARN_OFFSET 10
#define FFTS1_REG_NS_AIV_FSM1_MIXTYPE_LEN           2
#define FFTS1_REG_NS_AIV_FSM1_MIXTYPE_OFFSET        8
#define FFTS1_REG_NS_AIV_FSM1_STATE_LEN             4
#define FFTS1_REG_NS_AIV_FSM1_STATE_OFFSET          0

#define FFTS1_REG_NS_AIV_FSM1_TSLOTID_LEN    1
#define FFTS1_REG_NS_AIV_FSM1_TSLOTID_OFFSET 0

#define FFTS1_REG_NS_AIV_FSM1_THREADID_0_LEN    16
#define FFTS1_REG_NS_AIV_FSM1_THREADID_0_OFFSET 16
#define FFTS1_REG_NS_AIV_FSM1_CXTID_0_LEN       16
#define FFTS1_REG_NS_AIV_FSM1_CXTID_0_OFFSET    0

#define FFTS1_REG_NS_AIV_FSM1_BLKID_0_LEN      16
#define FFTS1_REG_NS_AIV_FSM1_BLKID_0_OFFSET   16
#define FFTS1_REG_NS_AIV_FSM1_SUBLKID_0_LEN    8
#define FFTS1_REG_NS_AIV_FSM1_SUBLKID_0_OFFSET 0

#endif // __FFTS1_REG_NS_REG_OFFSET_FIELD_H__
