// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_rtsqint_host_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 09:26:03 Create file
// ******************************************************************************

#ifndef __STARS_RTSQINT_HOST_REG_REG_OFFSET_FIELD_H__
#define __STARS_RTSQINT_HOST_REG_REG_OFFSET_FIELD_H__

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_0_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_0_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_0_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_1_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_1_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_1_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_2_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_2_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_2_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_3_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_3_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_3_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_4_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_4_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_4_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_5_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_5_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_5_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_6_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_6_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_6_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_7_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_7_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_7_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_8_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_8_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_8_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_9_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_9_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_9_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_10_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_10_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_10_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_11_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_11_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_11_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_12_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_12_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_12_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_13_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_13_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_13_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_14_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_14_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_14_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_STS2_15_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_STS2_15_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_STS2_15_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_0_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_0_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_0_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_1_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_1_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_1_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_2_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_2_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_2_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_3_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_3_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_3_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_4_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_4_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_4_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_5_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_5_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_5_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_6_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_6_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_6_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_7_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_7_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_7_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_8_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_8_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_8_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_9_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_9_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_9_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_10_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_10_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_10_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_11_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_11_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_11_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_12_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_12_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_12_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_13_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_13_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_13_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_14_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_14_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_14_OFFSET  0

#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_NORMAL_CLR2_15_OFFSET 2
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_ERROR_CLR2_15_OFFSET  1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_STARS_RTSQ_DEBUG_CLR2_15_OFFSET  0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_0_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_0_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_0_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_0_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_0_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_0_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_1_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_1_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_1_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_1_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_1_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_1_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_2_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_2_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_2_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_2_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_2_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_2_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_3_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_3_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_3_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_3_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_3_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_3_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_4_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_4_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_4_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_4_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_4_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_4_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_5_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_5_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_5_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_5_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_5_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_5_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_6_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_6_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_6_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_6_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_6_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_6_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_7_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_7_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_7_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_7_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_7_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_7_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_8_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_8_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_8_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_8_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_8_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_8_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_9_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_9_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_9_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_9_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_9_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_9_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_10_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_10_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_10_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_10_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_10_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_10_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_11_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_11_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_11_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_11_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_11_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_11_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_12_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_12_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_12_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_12_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_12_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_12_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_13_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_13_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_13_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_13_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_13_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_13_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_14_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_14_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_14_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_14_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_14_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_14_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_MASK2_15_OFFSET 22
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_15_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_MASK2_15_OFFSET      20
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_MASK2_15_OFFSET  18
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_15_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_MASK2_15_OFFSET     16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_0_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_1_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_2_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_3_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_4_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_5_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_6_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_7_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_8_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_9_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_10_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_11_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_12_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_13_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_14_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_MASK2_15_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_0_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_1_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_2_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_3_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_4_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_5_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_6_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_7_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_8_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_9_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_10_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_11_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_12_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_13_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_14_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_MASK2_15_OFFSET 16

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_0_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_0_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_0_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_0_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_0_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_0_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_0_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_1_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_1_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_1_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_1_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_1_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_1_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_1_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_2_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_2_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_2_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_2_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_2_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_2_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_2_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_3_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_3_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_3_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_3_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_3_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_3_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_3_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_4_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_4_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_4_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_4_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_4_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_4_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_4_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_5_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_5_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_5_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_5_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_5_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_5_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_5_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_6_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_6_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_6_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_6_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_6_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_6_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_6_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_7_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_7_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_7_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_7_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_7_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_7_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_7_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_8_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_8_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_8_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_8_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_8_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_8_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_8_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_9_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_9_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_9_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_9_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_9_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_9_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_9_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_10_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_10_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_10_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_10_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_10_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_10_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_10_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_11_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_11_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_11_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_11_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_11_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_11_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_11_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_12_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_12_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_12_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_12_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_12_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_12_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_12_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_13_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_13_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_13_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_13_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_13_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_13_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_13_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_14_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_14_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_14_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_14_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_14_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_14_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_14_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_EVENT_RECORD_NS_STATUS2_15_OFFSET 3
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_15_LEN         1
#define STARS_RTSQINT_HOST_REG_L1_SQ_DONE_NS_STATUS2_15_OFFSET      2
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_15_LEN     1
#define STARS_RTSQINT_HOST_REG_L1_TASK_PAUSED_NS_STATUS2_15_OFFSET  1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_15_LEN        1
#define STARS_RTSQINT_HOST_REG_L1_SQE_DONE_NS_STATUS2_15_OFFSET     0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_DEBUG_PAUSED_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_0_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_1_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_2_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_3_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_4_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_5_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_6_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_7_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_8_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_9_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_10_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_11_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_12_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_13_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_14_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_15_LEN    1
#define STARS_RTSQINT_HOST_REG_L1_TASK_TIMEOUT_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQE_DONE_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_PAUSED_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_EVENT_RECORD_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_SQ_DONE_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_DEBUG_PAUSED_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_0_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_1_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_2_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_3_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_4_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_5_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_6_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_7_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_8_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_9_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_10_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_11_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_12_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_13_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_14_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_15_LEN    4
#define STARS_RTSQINT_HOST_REG_MID_TASK_TIMEOUT_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_STATUS2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQE_DONE_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_CLR2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_PAUSED_NS_MASK2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_EVENT_RECORD_NS_MASK2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_SQ_DONE_NS_MASK2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_DEBUG_PAUSED_NS_MASK2_15_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_0_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_0_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_1_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_1_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_2_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_2_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_3_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_3_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_4_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_4_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_5_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_5_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_6_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_6_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_7_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_7_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_8_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_8_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_9_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_9_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_10_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_10_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_11_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_11_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_12_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_12_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_13_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_13_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_14_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_14_OFFSET 0

#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_15_LEN    32
#define STARS_RTSQINT_HOST_REG_L2_TASK_TIMEOUT_NS_MASK2_15_OFFSET 0

#endif // __STARS_RTSQINT_HOST_REG_REG_OFFSET_FIELD_H__
