// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_conds_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:39:08 Create file
// ******************************************************************************

#ifndef __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_CONDS_NS_REG_SP_LEVEL_LEN    3
#define STARS_CONDS_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_CONDS_NS_REG_LP_MODE_LEN     3
#define STARS_CONDS_NS_REG_LP_MODE_OFFSET  0



#define STARS_CONDS_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_CONDS_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_CONDS_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_CONDS_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_CONDS_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_CONDS_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_CONDS_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_CONDS_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_CONDS_NS_REG_SQ_FRIENDLY_PCIEDMA_LEN    1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_PCIEDMA_OFFSET 17
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGD_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGD_OFFSET   16
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGE_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGE_OFFSET   15
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VPC_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VPC_OFFSET     14
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_DSA_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_DSA_OFFSET     13
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_SDMA_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_SDMA_OFFSET    12
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_CONDS_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_CONDS_OFFSET   11
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_ACPU_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_ACPU_OFFSET    10
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VEC_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VEC_OFFSET     9
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_FFTS_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_FFTS_OFFSET    8

#define STARS_CONDS_NS_REG_CONDS_STRM_ERR_LEVEL_LEN    1
#define STARS_CONDS_NS_REG_CONDS_STRM_ERR_LEVEL_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_SEL_LEN    1
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_SEL_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_OST_CNT_LEN    1
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_OST_CNT_OFFSET 8
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_STATE_LEN      5
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_STATE_OFFSET   0

#define STARS_CONDS_NS_REG_CONDS_REDUNDANT_RSP_LEN    1
#define STARS_CONDS_NS_REG_CONDS_REDUNDANT_RSP_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_FREE_BITMAP_LEN    1
#define STARS_CONDS_NS_REG_CONDS_FREE_BITMAP_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_CNT_ENABLE_LEN    1
#define STARS_CONDS_NS_REG_DFX_CONDS_CNT_ENABLE_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_VLD_CNT_LEN    32
#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_VLD_CNT_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_RSP_CNT_LEN    32
#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_RSP_CNT_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_LEN    1
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS0_NS_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_OFFSET       0

#endif // __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__
