// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_profiling_s_cfg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:36:20 Create file
// ******************************************************************************

#ifndef __STARS_PROFILING_S_CFG_REG_OFFSET_H__
#define __STARS_PROFILING_S_CFG_REG_OFFSET_H__

/* STARS_PROFILING_S_CFG Base address of Module's Register */
#define SOC_STARS_PROFILING_S_CFG_BASE                       (0x7000000)

/******************************************************************************/
/*                      SOC STARS_PROFILING_S_CFG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_PROFILING_S_CFG_STARS_PROFILING_AXCACHE_SETTING0_REG     (SOC_STARS_PROFILING_S_CFG_BASE + 0x800)  
#define SOC_STARS_PROFILING_S_CFG_STARS_PROFILING_AXCACHE_SETTING1_REG     (SOC_STARS_PROFILING_S_CFG_BASE + 0x804)  
#define SOC_STARS_PROFILING_S_CFG_STARS_PROFILING_NS_SETTING_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x808)  
#define SOC_STARS_PROFILING_S_CFG_STARS_PROFILING_NS_SQ_AXPROT_SETTING_REG (SOC_STARS_PROFILING_S_CFG_BASE + 0x80C)  
#define SOC_STARS_PROFILING_S_CFG_STARS_PROFILING_AXPROT_SETTING_REG       (SOC_STARS_PROFILING_S_CFG_BASE + 0x814)  
#define SOC_STARS_PROFILING_S_CFG_STARS_VPC_PMU_BASE_ADDR0_0_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1000) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VPC_PMU_BASE_ADDR0_1_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1010) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VPC_PMU_BASE_ADDR1_0_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1004) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VPC_PMU_BASE_ADDR1_1_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1014) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGE_PMU_BASE_ADDR0_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1200) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGE_PMU_BASE_ADDR1_REG           (SOC_STARS_PROFILING_S_CFG_BASE + 0x1204) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGD_PMU_BASE_ADDR0_0_REG         (SOC_STARS_PROFILING_S_CFG_BASE + 0x1400) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGD_PMU_BASE_ADDR0_1_REG         (SOC_STARS_PROFILING_S_CFG_BASE + 0x1410) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGD_PMU_BASE_ADDR1_0_REG         (SOC_STARS_PROFILING_S_CFG_BASE + 0x1404) 
#define SOC_STARS_PROFILING_S_CFG_STARS_JPEGD_PMU_BASE_ADDR1_1_REG         (SOC_STARS_PROFILING_S_CFG_BASE + 0x1414) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR0_0_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1600) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR0_1_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1610) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR0_2_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1620) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR0_3_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1630) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR1_0_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1604) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR1_1_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1614) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR1_2_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1624) 
#define SOC_STARS_PROFILING_S_CFG_STARS_VDEC_PMU_BASE_ADDR1_3_REG          (SOC_STARS_PROFILING_S_CFG_BASE + 0x1634) 
#define SOC_STARS_PROFILING_S_CFG_STARS_PCIE_PMU_BASE_ADDR0_REG            (SOC_STARS_PROFILING_S_CFG_BASE + 0x1818) 
#define SOC_STARS_PROFILING_S_CFG_STARS_PCIE_PMU_BASE_ADDR1_REG            (SOC_STARS_PROFILING_S_CFG_BASE + 0x181C) 

#endif // __STARS_PROFILING_S_CFG_REG_OFFSET_H__
