# SPDX-License-Identifier: GPL-2.0
obj-m := drv_platform.o

drv_platform-objs := devdrv_platform.o
drv_platform-objs += tsdrv_intr/tsdrv_intr.o tsdrv_pdata/tsdrv_pdata.o
drv_platform-objs += tsdrv_fault/tsdrv_fault_init.o tsdrv_fault/tsdrv_fault_comm.o tsdrv_fault/tsdrv_sys_panic.o
drv_platform-objs += tsdrv_fault/tsdrv_ras.o tsdrv_fault/tsdrv_non_ras.o tsdrv_fault/tsdrv_tscpu_fault.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_smc.o tsdrv_soc/config_secure_reg.o
drv_platform-objs += tsdrv_firmware/tsdrv_firmware_load.o tsdrv_firmware/tsdrv_firmware_reader.o
drv_platform-objs += tsdrv_pm/tsdrv_pm.o
drv_platform-objs += tsdrv_parse/tsdrv_parse.o
drv_platform-objs += tsdrv_heartbeat/tsdrv_heartbeat.o tsdrv_heartbeat/tsdrv_heartbeat_dfx.o

CFG_FEATURE_TS_IPC := y
CFG_FEATURE_TS_ALLOC_MEM := y

DRIVER_INC := $(src)/..

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/hiss
ccflags-y += -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/toolchain/bbox/device
ccflags-y += -I$(DRIVER_INC)/libc_sec/include -I$(DRIVER_INC)/include/aicpu/common
ccflags-y += -I$(DRIVER_INC)/tee/inc
ccflags-y += -I$(src)
ccflags-y += -I$(src)/tsdrv_d2h_chan -I$(src)/tsdrv_d2h_chan/pci
ccflags-y += -I$(src)/tsdrv_intr -I$(src)/tsdrv_ipc -I$(src)/tsdrv_mem
ccflags-y += -I$(src)/tsdrv_pdata -I$(src)/tsdrv_fault -I$(src)/tsdrv_pm
ccflags-y += -I$(src)/tsdrv_soc -I$(src)/tsdrv_firmware -I$(src)/tsdrv_parse
ccflags-y += -I$(src)/tsdrv_heartbeat -I$(src)/tsdrv_firmware/tsdrv_file_check

ccflags-y += -DCFG_FEATURE_TS_IPC
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_FEATURE_FAULT
ccflags-y += -DCFG_FEATURE_SYS_PANIC_DFX -DCFG_FEATURE_TS_ALLOC_MEM
ccflags-y += -DCFG_FEATURE_FAULT_FPDC -DCFG_FEATURE_TS_HB_DFX
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v1
ccflags-y += -I$(src)/ascend910 -I$(src)/tsdrv_soc/ascend910
ccflags-y += -I$(src)/tsdrv_firmware/ascend910 -I$(src)/tsdrv_fault/ascend910

drv_platform-objs += ascend910/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_intr/ascend910/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend910/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/ascend910/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_sec.o
drv_platform-objs += tsdrv_pm/ascend910/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend910/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend910/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_tee_check/tsdrv_file_tee_check.o
drv_platform-objs += tsdrv_ipc/ascend910/tsdrv_ipc_platform.o
drv_platform-objs += tsdrv_fault/ascend910/tsdrv_fault_platform.o
drv_platform-objs += tsdrv_d2h_chan/tsdrv_d2h_chan.o tsdrv_d2h_chan/pci/tsdrv_pci_chan.o
else ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_TS_ALLOC_MEM
ccflags-y += -DCFG_FEATURE_FAULT -DCFG_FEATURE_SYS_PANIC_DFX
ccflags-y += -I$(DRIVER_INC)/include/soc/mini_v1
ccflags-y += -I$(src)/ascend310 -I$(src)/tsdrv_soc/ascend310
ccflags-y += -I$(src)/tsdrv_firmware/ascend310 -I$(src)/tsdrv_fault/ascend310

drv_platform-objs += tsdrv_d2h_chan/tsdrv_d2h_chan.o tsdrv_d2h_chan/pci/tsdrv_pci_chan.o
drv_platform-objs += ascend310/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_intr/ascend310/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend310/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/ascend310/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_pm/ascend310/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend310/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend310/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_tee_check/tsdrv_file_tee_check.o
drv_platform-objs += tsdrv_ipc/ascend310/tsdrv_ipc_platform.o
drv_platform-objs += tsdrv_fault/ascend310/tsdrv_fault_platform.o
else ifneq ($(filter $(PRODUCT),ascend310p helper310p ascend610 bs9sx1a),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_FEATURE_FAULT -DCFG_FEATURE_TS_HB_DFX
ccflags-y += -DCFG_FEATURE_AIV_INFO_FROM_PG_INFO_V1
ccflags-y += -I$(src)/ascend610 -I$(src)/tsdrv_soc/ascend610
ccflags-y += -I$(src)/tsdrv_firmware/ascend610 -I$(src)/tsdrv_fault/ascend610

ifneq ($(filter $(PRODUCT),helper310p),)
ccflags-y += -DCFG_FEATURE_AICPU_NUM_CFG_UNLIMIT
endif

ifneq ($(filter $(PRODUCT),ascend310p helper310p),)
ccflags-y += -DCFG_FEATURE_TS_ALLOC_MEM -DCFG_FEATURE_FAULT_FPDC
ifneq ($(filter $(PRODUCT),ascend310p),)
ccflags-y += -DCFG_FEATURE_SYS_PANIC_DFX -DCFG_FEATURE_PROF_HWTS_THROUGH
drv_platform-objs += tsdrv_parse/mini_v2/set_soc_resmng.o
endif
ifneq ($(filter $(PRODUCT),helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER -DCFG_FEATURE_CPU_NUMS_FIXED
endif
endif

ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a),)
CFG_FEATURE_TS_ALLOC_MEM := n
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_FEATURE_FAULT_FPDC
ccflags-y += -DCFG_FEATURE_IPC_CRC -DCFG_FEATURE_BOARD_ID_EXPAND
ccflags-y += -DCFG_FEATURE_SAFETY_FAULT -DSNAPSHOT_ENABLE
ccflags-y += -I$(DRIVER_INC)/include/dbl
drv_platform-objs += drv_snapshot.o
ifeq ($(PRODUCT),bs9sx1a)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_BS9SX1A -DCFG_SOC_SAMPLE_BACK_DEBUG
endif
endif

drv_platform-objs += tsdrv_d2h_chan/tsdrv_d2h_chan.o tsdrv_d2h_chan/pci/tsdrv_pci_chan.o
drv_platform-objs += ascend610/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_intr/ascend610/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend610/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/ascend610/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_sec.o
drv_platform-objs += tsdrv_pm/ascend610/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_soc_check/tsdrv_file_soc_check.o
drv_platform-objs += tsdrv_ipc/ascend610/tsdrv_ipc_platform.o
drv_platform-objs += tsdrv_fault/ascend610/tsdrv_fault_platform.o
else ifneq ($(filter $(PRODUCT),ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
CFG_FEATURE_TS_ALLOC_MEM := n
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DCFG_FEATURE_CPU_NUMS_FIXED -DCFG_FEATURE_USE_ICM_CHAN
ccflags-y += -DCFG_FEATURE_SUPPORT_VSQ_MNG -DCFG_FEATURE_QOS
ccflags-y += -DCFG_FEATURE_FAULT -DCFG_FEATURE_FAULT_FPDC
ccflags-y += -DCFG_FEATURE_HARDWARE_SCHED -DCFG_FEATURE_PG_V2
ccflags-y += -DCFG_TRS_REFACTOR_FEATURE
ccflags-y += -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(src)/ascend610 -I$(src)/tsdrv_soc/ascend310B
ccflags-y += -I$(src)/tsdrv_firmware/ascend310B -I$(src)/tsdrv_fault/ascend310B
ccflags-y += -I$(src)/tsdrv_qos

drv_platform-objs += tsdrv_parse/mini_v3/set_soc_resmng.o
drv_platform-objs += tsdrv_heartbeat/hb_sqcq.o
drv_platform-objs += adapt_devdrv.o

ifneq ($(filter $(PRODUCT),ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_RC_MODE -DCFG_FEATURE_VFIO_DEVICE
ccflags-y += -DSNAPSHOT_ENABLE -DNOT_SUPPORT_OSNAME
drv_platform-objs += drv_snapshot.o
endif

ifneq ($(filter $(PRODUCT),ascend310B as31xm1 ascend310Besl ascend310Brc ascend310Brcesl),)
ccflags-y += -DCFG_FEATURE_PG
endif

ifneq ($(filter $(PRODUCT),as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11 -DCFG_NOT_SURPPORT_PCIE_HOST_DEVICE_COMM
ccflags-y += -DSNAPSHOT_ENABLE -DCFG_FEATURE_USE_FAULT_NEW_FRAME_WORK
ccflags-y += -DCFG_MEMORY_OPTIMIZE
drv_platform-objs += drv_snapshot.o
endif

drv_platform-objs += ascend610/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_qos/tsdrv_qos.o
drv_platform-objs += tsdrv_intr/ascend610/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend610/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_sec.o
drv_platform-objs += tsdrv_soc/ascend310B/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_pm/ascend310B/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_soc_check/tsdrv_file_soc_check.o
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_fault_platform.o
ifneq ($(filter $(PRODUCT),as31xm1),)
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_ipc_fault_init.o
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_ipc_fault_rcv.o
endif
drv_platform-objs += tsdrv_ipc/ascend310B/tsdrv_ipc_platform.o
else ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
CFG_FEATURE_TS_ALLOC_MEM := n
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DCFG_FEATURE_SUPPORT_VSQ_MNG -DCFG_FEATURE_TS_HB_DFX
ccflags-y += -DCFG_FEATURE_QOS -DCFG_FEATURE_HARDWARE_SCHED
ccflags-y += -DCFG_TRS_REFACTOR_FEATURE
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v2
ccflags-y += -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(src)/ascend910 -I$(src)/tsdrv_soc/ascend910
ccflags-y += -I$(src)/tsdrv_firmware/ascend910B -I$(src)/tsdrv_fault/ascend910B
ccflags-y += -I$(src)/tsdrv_qos

ifneq ($(filter $(PRODUCT),ascend920esl),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2_ESL
endif

ifneq ($(filter $(PRODUCT),ascend910B ascend920esl),)
ccflags-y += -DCFG_FEATURE_PG -DCFG_FEATURE_VFIO_DEVICE
ccflags-y += -DCFG_FEATURE_FAULT -DCFG_FEATURE_FAULT_FPDC
ccflags-y += -DCFG_FEATURE_USE_ICM_CHAN -DCFG_FEATURE_HW_INFO_FROM_BIOS
ccflags-y += -DCFG_FEATURE_AIV_INFO_FROM_AIC
endif

drv_platform-objs += tsdrv_parse/cloud_v2/set_soc_resmng.o
drv_platform-objs += tsdrv_heartbeat/hb_sqcq.o
drv_platform-objs += adapt_devdrv.o
drv_platform-objs += ascend910/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_sec.o
drv_platform-objs += tsdrv_qos/tsdrv_qos.o
drv_platform-objs += tsdrv_intr/ascend910/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend910/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/ascend910/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_pm/ascend910/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend910/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend910/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_soc_check/tsdrv_file_soc_check.o
drv_platform-objs += tsdrv_ipc/ascend920/tsdrv_ipc_platform.o
drv_platform-objs += tsdrv_fault/ascend910B/tsdrv_fault_platform.o
endif

ifeq ($(CFG_FEATURE_TS_IPC),y)
drv_platform-objs += tsdrv_ipc/tsdrv_ipc.o tsdrv_ipc/tsdrv_ipc_dfx.o
endif

ifeq ($(CFG_FEATURE_TS_ALLOC_MEM),y)
drv_platform-objs += tsdrv_mem/tsdrv_ts_alloc_mem.o tsdrv_mem/tsdrv_alloc_mem_dfx.o
endif

ccflags-y += -I$(DRIVER_INC)/include/internal

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
