# SPDX-License-Identifier: GPL-2.0
# drv_platform.ko - TS Platform driver (ascend310Brc device)
obj-m := drv_platform.o

# Base objects (common)
drv_platform-objs := devdrv_platform.o
drv_platform-objs += tsdrv_intr/tsdrv_intr.o tsdrv_pdata/tsdrv_pdata.o
drv_platform-objs += tsdrv_fault/tsdrv_fault_init.o tsdrv_fault/tsdrv_fault_comm.o tsdrv_fault/tsdrv_sys_panic.o
drv_platform-objs += tsdrv_fault/tsdrv_ras.o tsdrv_fault/tsdrv_non_ras.o tsdrv_fault/tsdrv_tscpu_fault.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_smc.o tsdrv_soc/config_secure_reg.o
drv_platform-objs += tsdrv_firmware/tsdrv_firmware_load.o tsdrv_firmware/tsdrv_firmware_reader.o
drv_platform-objs += tsdrv_pm/tsdrv_pm.o
drv_platform-objs += tsdrv_parse/tsdrv_parse.o
drv_platform-objs += tsdrv_heartbeat/tsdrv_heartbeat.o tsdrv_heartbeat/tsdrv_heartbeat_dfx.o
drv_platform-objs += tsdrv_d2h_chan/tsdrv_d2h_chan.o tsdrv_d2h_chan/pci/tsdrv_pci_chan.o

# Ascend310Brc-specific objects
drv_platform-objs += tsdrv_parse/mini_v3/set_soc_resmng.o
drv_platform-objs += tsdrv_heartbeat/hb_sqcq.o
drv_platform-objs += adapt_devdrv.o
drv_platform-objs += drv_snapshot.o
drv_platform-objs += ascend610/devdrv_parse_pdata.o
drv_platform-objs += tsdrv_qos/tsdrv_qos.o
drv_platform-objs += tsdrv_intr/ascend610/tsdrv_intr_platform.o
drv_platform-objs += tsdrv_pdata/ascend610/tsdrv_pdata_platform.o
drv_platform-objs += tsdrv_soc/tsdrv_soc_sec.o
drv_platform-objs += tsdrv_soc/ascend310B/tsdrv_soc_pm.o
drv_platform-objs += tsdrv_pm/ascend310B/tsdrv_pm.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_adapt_firmware_load.o
drv_platform-objs += tsdrv_firmware/ascend610/tsdrv_aicpu_config.o
drv_platform-objs += tsdrv_firmware/tsdrv_file_check/tsdrv_soc_check/tsdrv_file_soc_check.o
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_fault_platform.o
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_ipc_fault_init.o
drv_platform-objs += tsdrv_fault/ascend310B/tsdrv_ipc_fault_rcv.o
drv_platform-objs += tsdrv_ipc/ascend310B/tsdrv_ipc_platform.o
drv_platform-objs += tsdrv_ipc/tsdrv_ipc.o tsdrv_ipc/tsdrv_ipc_dfx.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src) -I$(src)/tsdrv_intr -I$(src)/tsdrv_fault -I$(src)/tsdrv_soc -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_firmware -I$(src)/tsdrv_pm -I$(src)/tsdrv_parse
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_heartbeat -I$(src)/tsdrv_qos -I$(src)/tsdrv_pdata
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_d2h_chan -I$(src)/tsdrv_ipc -I$(src)/ascend610
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_soc/ascend310B -I$(src)/tsdrv_pm/ascend310B
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_fault/ascend310B -I$(src)/tsdrv_ipc/ascend310B
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common -I$(src)/tsdrv_parse/mini_v3

ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DCFG_FEATURE_CPU_NUMS_FIXED -DCFG_FEATURE_USE_ICM_CHAN
ccflags-y += -DCFG_FEATURE_SUPPORT_VSQ_MNG -DCFG_FEATURE_QOS
ccflags-y += -DCFG_FEATURE_FAULT -DCFG_FEATURE_FAULT_FPDC
ccflags-y += -DCFG_FEATURE_HARDWARE_SCHED -DCFG_FEATURE_PG_V2
ccflags-y += -DCFG_TRS_REFACTOR_FEATURE -DCFG_FEATURE_RC_MODE
ccflags-y += -DCFG_FEATURE_VFIO_DEVICE -DSNAPSHOT_ENABLE -DNOT_SUPPORT_OSNAME
ccflags-y += -DCFG_FEATURE_PG -DCFG_FEATURE_TS_IPC

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion
