/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */
#ifndef DEVDRV_PLATFORM_REGISTER_H
#define DEVDRV_PLATFORM_REGISTER_H


#ifdef CFG_FEATURE_PG
#define SOC_HARDWARE_VERSION_ASCEND910B1  DEVDRV_PLATFORM_CLOUD_V2_B1
#define SOC_HARDWARE_VERSION_ASCEND910B2  DEVDRV_PLATFORM_CLOUD_V2_B2
#define SOC_HARDWARE_VERSION_ASCEND910B3  DEVDRV_PLATFORM_CLOUD_V2_B3
#define SOC_HARDWARE_VERSION_ASCEND910B4  DEVDRV_PLATFORM_CLOUD_V2_B4
#define SOC_HARDWARE_VERSION_ASCEND910C1  DEVDRV_PLATFORM_CLOUD_V2_C1
#define SOC_HARDWARE_VERSION_ASCEND910C2  DEVDRV_PLATFORM_CLOUD_V2_C2
#define SOC_HARDWARE_VERSION_ASCEND910C3  DEVDRV_PLATFORM_CLOUD_V2_C3
#define SOC_HARDWARE_VERSION_ASCEND910B2C  DEVDRV_PLATFORM_CLOUD_V2_B2C
#endif

#ifdef CFG_SOC_PLATFORM_CLOUD_V2
#define SOC_HARDWARE_VERSION DEVDRV_PLATFORM_CLOUD_V2
#else
#define SOC_HARDWARE_VERSION DEVDRV_PLATFORM_CLOUD_V1
#endif

/* AICPU */
// A04
#define FIRMWARE_CLUSTER_DERESET_REG_OFFSET \
    (CLOUD_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_DREQ_REG - CLOUD_CPU_CLUSTER_CFG_BASE)
// A00
#define FIRMWARE_CLUSTER_RESET_REG_OFFSET (CLOUD_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_REQ_REG - CLOUD_CPU_CLUSTER_CFG_BASE)
// 0x5A00
#define FIRMWARE_CLUSTER_STATUS_OFFSET (CLOUD_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_ST_REG - CLOUD_CPU_CLUSTER_CFG_BASE)
// 0x8004
#define FIRMWARE_CORE_POWERUP_REG_OFFSET (CLOUD_CPU_CLUSTER_CFG_PWR_UP_REQ_PPU0_REG - CLOUD_CPU_CLUSTER_CFG_BASE)
// 0x2128
#define FIRMWARE_CLUSTER_ENTRY_REG_OFFSET (CLOUD_CPU_CLUSTER_CFG_SC_CLUS0_CTRL_RVBA0_REG - CLOUD_CPU_CLUSTER_CFG_BASE)

/* SYSCTL */
#define SOC_SYSCTRL_CFG_BASE                0x0
#define SOC_SYSCTRL_CFG_SC_VER_VER_REG      (SOC_SYSCTRL_CFG_BASE + 0xFFFC)
#define DEVDRV_SYSCTL_BASE(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_SYSCTL_INDEX, chip_id))  // 0x94010000
#define DEVDRV_SYSCTL_VERSION_PLAT_MASK 0x3UL
#define DEVDRV_SYSCTL_VERSION_REG_OFFSET (SOC_SYSCTRL_CFG_SC_VER_VER_REG - SOC_SYSCTRL_CFG_BASE)  // (0xFFFC)
#define DEVDRV_SYSCTL_VERSION_PHYS(chip_id) (DEVDRV_SYSCTL_BASE(chip_id) + DEVDRV_SYSCTL_VERSION_REG_OFFSET)
#define DEVDRV_SYSCTL_REG_SIZE 0x10000
#define DEVDRV_SYSCTL_PLL_CFG1 0x3690

/* TS */
#define SOC_TS_SYSCTRL_BASE             0xaf000000
#define SOC_TS_SYSCTRL_SC_TESTREG0_REG  (SOC_TS_SYSCTRL_BASE + 0xBE0)
#define SOC_TS_SYSCTRL_PERIPHCTRL0_REG  (SOC_TS_SYSCTRL_BASE + 0x9C)
#define SOC_TS_SYSCTRL_PERIPHCTRL6_REG  (SOC_TS_SYSCTRL_BASE + 0xB4)
#define SOC_TS_SYSCTRL_PERIPHCTRL7_REG  (SOC_TS_SYSCTRL_BASE + 0xB8)
#define SOC_TS_SYSCTRL_PERIPHCTRL8_REG  (SOC_TS_SYSCTRL_BASE + 0xBC)
#define SOC_TS_SYSCTRL_PERIPHCTRL9_REG  (SOC_TS_SYSCTRL_BASE + 0xC0)
#define SOC_TS_SYSCTRL_PERIPHCTRL11_REG (SOC_TS_SYSCTRL_BASE + 0xC8)
#define SOC_TS_SYSCTRL_PERIPHCTRL12_REG (SOC_TS_SYSCTRL_BASE + 0xCC)
#define SOC_TS_SYSCTRL_PERIPHCTRL13_REG (SOC_TS_SYSCTRL_BASE + 0xD0)
#define SOC_TS_SYSCTRL_SC_SYSSTAT14_REG (SOC_TS_SYSCTRL_BASE + 0x40)
#define SOC_TS_SYSCTRL_PERIPHCTRL32_REG (SOC_TS_SYSCTRL_BASE + 0x11C)
#define SOC_TS_SYSCTRL_PERIPHCTRL66_REG (SOC_TS_SYSCTRL_BASE + 0x1A4)
#define DEVDRV_TS_SYSCTL(chip_id)   (devdrv_get_addr_base(DEVDRV_DTS_TS_SUBSYSCTL_INDEX, chip_id)) // (0xAF030000)
#define TSCPU_BOOT_ADDR0_REG_OFFSET        (SOC_TS_SYSCTRL_PERIPHCTRL6_REG - SOC_TS_SYSCTRL_BASE)         // (0xB4)
#define TSCPU_BOOT_ADDR1_REG_OFFSET        (SOC_TS_SYSCTRL_PERIPHCTRL7_REG - SOC_TS_SYSCTRL_BASE)         // (0xB8)
#define TSCPU_CLOCK_GATE_ENABLE_REG_OFFSET (SOC_TS_SYSCTRL_PERIPHCTRL8_REG - SOC_TS_SYSCTRL_BASE)         // (0xBC)
#define TSCPU_CLOCK_DISABLE_REG_OFFSET     (SOC_TS_SYSCTRL_PERIPHCTRL9_REG - SOC_TS_SYSCTRL_BASE)         // (0xC0)
#define TSCPU_SOFT_RESET_ENABLE_REG_OFFSET (SOC_TS_SYSCTRL_PERIPHCTRL11_REG - SOC_TS_SYSCTRL_BASE)        // (0xC8)
#define LOW_POWER_DEBUG                    (SOC_TS_SYSCTRL_PERIPHCTRL12_REG - SOC_TS_SYSCTRL_BASE)        // (0xCC)
#define TSCPU_SOFT_STATUS_REG_OFFSET       (SOC_TS_SYSCTRL_PERIPHCTRL13_REG - SOC_TS_SYSCTRL_BASE)        // (0xD0)
#define TSCPU_IDLE_STATUS_REG_OFFSET       (SOC_TS_SYSCTRL_SC_SYSSTAT14_REG - SOC_TS_SYSCTRL_BASE)        // (0x40)
#define DEVDRV_SC_TESTREG_OFFSET           (SOC_TS_SYSCTRL_SC_TESTREG0_REG - SOC_TS_SYSCTRL_BASE)         // (0x0BE0)
#define DEVDRV_TS_SYSCTRL_PERIPHCTRL66     (SOC_TS_SYSCTRL_PERIPHCTRL66_REG - SOC_TS_SYSCTRL_BASE)        // (0x01a4)
#define DEVDRV_TS_PERIPHCTRL0              (SOC_TS_SYSCTRL_PERIPHCTRL0_REG - SOC_TS_SYSCTRL_BASE)         // (0x9c)
#define TSCPU_IDLE_STATUS_VAL 0x3
#define TSCPU_IDLE_STATUS_BIT_INDEX 0x13
/* TSCPU boot address */
#define TSCPU_PERIPHCTRL7(chip_id) (DEVDRV_TS_SYSCTL(chip_id) + TSCPU_BOOT_ADDR1_REG_OFFSET)  // ADDR[39:32]
#define TSCPU_PERIPHCTRL6(chip_id) (DEVDRV_TS_SYSCTL(chip_id) + TSCPU_BOOT_ADDR0_REG_OFFSET)  // ADDR[31:2]
#define DEVDRV_TS_SYSCTL_SIZE 0x10000
#define TSCPU_PERIPHCTRL32_OFFSET (SOC_TS_SYSCTRL_PERIPHCTRL32_REG - SOC_TS_SYSCTRL_BASE)

/* stars */
#ifdef CFG_SOC_PLATFORM_CLOUD_V2
#define TSDRV_STARS_REG_SIZE (272 * 1024 * 1024)
#define TSDRV_STARS_RTSQ_OFFSET 0x8000000
#define TSDRV_STARS_RTSQ_SIZE (128 * 1024 * 1024)
#define TSDRV_STARS_SQCQ_INIR_OFFSET 0x28000
#define TSDRV_STARS_SQCQ_INIR_SIZE (16 * 1024)
#define TSDRV_STARS_TOPIC_SCHED_OFFSET 0x800000
#define TSDRV_STARS_TOPIC_SCHED_SIZE (8 * 1024 * 1024)
#define TSDRV_STARS_CDQ_OFFSET 0x1000000
#define TSDRV_STARS_CDQ_SIZE (16 * 1024 * 1024)
#endif

/* DISP */
#define xxx_cfg_disp_sub0_BASE 0x1000
#define xxx_cfg_disp_sub0_DISP_INTMASK0_REG  (xxx_cfg_disp_sub0_BASE + 0x804)
#define xxx_cfg_disp_sub0_DISP_INTSTAT0_REG  (xxx_cfg_disp_sub0_BASE + 0x808)
#define xxx_cfg_disp_sub0_DISP_INTCLR0_REG   (xxx_cfg_disp_sub0_BASE + 0x80C)
#define xxx_cfg_disp_sub0_DISP_DAW_EN_REG (xxx_cfg_disp_sub0_BASE + 0xD0)
#define DEVDRV_DISP_BASE_ADDR(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_DISPATCH_INDEX, chip_id))  // 0xAC060000
#define DEVDRV_DISP_SIZE 0x4000
#define DEVDRV_DISP_DAW_EN (xxx_cfg_disp_sub0_DISP_DAW_EN_REG - xxx_cfg_disp_sub0_BASE)      // (0x00D0)
#define DEVDRV_DISP_INTMASK0 (xxx_cfg_disp_sub0_DISP_INTMASK0_REG - xxx_cfg_disp_sub0_BASE)  // (0x0804)
#define DEVDRV_DISP_INTSTAT0 (xxx_cfg_disp_sub0_DISP_INTSTAT0_REG - xxx_cfg_disp_sub0_BASE)  // (0x0808)
#define DEVDRV_DISP_INTCLR0 (xxx_cfg_disp_sub0_DISP_INTCLR0_REG - xxx_cfg_disp_sub0_BASE)    // (0x080C)

/* GIC */
#define GIC_BASE_ADDR(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_GIC_BASE_INDEX, chip_id))  // (0xAA000000)
#define GICD_BASE_ADDR 0xAB000000

/* DOORBELL */
#define DEVDRV_TS_DOORBELL_ADDR(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_TS_DOORBELL_INDEX, chip_id))  // (0xAF400000)

#endif
