/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#ifndef __HISI_RPROC_ADAPT_H__
#define __HISI_RPROC_ADAPT_H__

#include <linux/notifier.h>
#include <linux/mutex.h>

#include "drv_ipc.h"

#define MAX_IPCDEV_NUM              4
#define HISI_MBX_SEGMENT_SIZE_BIT   7   /* 128 */
#define MBOX_CHAN_DATA_SIZE         8  /* 24 in minv2 */
#define MAX_BUFFER_LEN   32
#define MAX_FIFO_LEN     32

#define IPC_SI_MBX0_RPID0_Q_RX_ACPU0   "MDC_IPC_SI_MBX0_RPID0_Q_RX_ACPU0" /* irq safe : 227, unsafe : 225 */
#define IPC_SI_MBX1_RPID1_Q_RX_ACPU1   "MDC_IPC_SI_MBX1_RPID1_Q_RX_ACPU1" /* irq safe : 294, unsafe : 292 */
#define IPC_SI_MBX2_RPID2_Q_RX_ACPU2   "MDC_IPC_SI_MBX2_RPID2_Q_RX_ACPU2" /* irq safe : 302, unsafe : 296 */
#define IPC_SI_MBX3_RPID3_Q_RX_ACPU3   "MDC_IPC_SI_MBX3_RPID3_Q_RX_ACPU3" /* irq safe : 314, unsafe : 312 */
#define IPC_SI_MBX14_RPID14_Q_TX_ACPU0 "MDC_IPC_SI_MBX14_RPID14_Q_TX_ACPU0"
#define IPC_SI_MBX15_RPID15_Q_TX_ACPU1 "MDC_IPC_SI_MBX15_RPID15_Q_TX_ACPU1"
#define IPC_SI_MBX16_RPID16_Q_TX_ACPU2 "MDC_IPC_SI_MBX16_RPID16_Q_TX_ACPU2"
#define IPC_SI_MBX17_RPID17_Q_TX_ACPU3 "MDC_IPC_SI_MBX17_RPID17_Q_TX_ACPU3"

/* safe island normal mbx */
#define IPC_SI_MBX28_RPID0_RX_ACPU0  "MDC_IPC_SI_MBX28_RPID0_RX_ACPU0" /* irq safe : 228, unsafe : 226 */
#define IPC_SI_MBX29_RPID1_RX_ACPU1  "MDC_IPC_SI_MBX29_RPID1_RX_ACPU1" /* irq safe : 295, unsafe : 293 */
#define IPC_SI_MBX30_RPID2_RX_ACPU2  "MDC_IPC_SI_MBX30_RPID2_RX_ACPU2" /* irq safe : 303, unsafe : 297 */
#define IPC_SI_MBX31_RPID3_RX_ACPU3  "MDC_IPC_SI_MBX31_RPID3_RX_ACPU3" /* irq safe : 315, unsafe : 313 */
#define IPC_SI_MBX42_RPID14_TX_ACPU0 "MDC_IPC_SI_MBX42_RPID14_TX_ACPU0"
#define IPC_SI_MBX43_RPID15_TX_ACPU1 "MDC_IPC_SI_MBX43_RPID15_TX_ACPU1"
#define IPC_SI_MBX44_RPID16_TX_ACPU2 "MDC_IPC_SI_MBX44_RPID16_TX_ACPU2"
#define IPC_SI_MBX45_RPID17_TX_ACPU3 "MDC_IPC_SI_MBX45_RPID17_TX_ACPU3"

/* ts mbx */
/* tsc normal mbx */
#define IPC_TSC_MBX5_RPID4_RX_ACPU0 "MDC_IPC_TSC_MBX5_RPID4_RX_ACPU0" /* unsafe : 256 */
#define IPC_TSC_MBX6_RPID5_RX_ACPU1 "MDC_IPC_TSC_MBX6_RPID5_RX_ACPU1" /* unsafe : 257 */
#define IPC_TSC_MBX7_RPID6_RX_ACPU2 "MDC_IPC_TSC_MBX7_RPID6_RX_ACPU2" /* unsafe : 258 */
#define IPC_TSC_MBX8_RPID7_RX_ACPU3 "MDC_IPC_TSC_MBX8_RPID7_RX_ACPU3" /* unsafe : 259 */
#define IPC_TSC_MBX1_RPID0_TX_ACPU0 "MDC_IPC_TSC_MBX1_RPID0_TX_ACPU0" /* ns normal irq : 256 */
#define IPC_TSC_MBX2_RPID1_TX_ACPU1 "MDC_IPC_TSC_MBX2_RPID1_TX_ACPU1" /* ns normal irq : 257 */
#define IPC_TSC_MBX3_RPID2_TX_ACPU2 "MDC_IPC_TSC_MBX3_RPID2_TX_ACPU2" /* ns normal irq : 258 */
#define IPC_TSC_MBX4_RPID3_TX_ACPU3 "MDC_IPC_TSC_MBX4_RPID3_TX_ACPU3" /* ns normal irq : 259 */

/* tsv normal mbx */
#define IPC_TSV_MBX5_RPID4_RX_ACPU0 "MDC_IPC_TSV_MBX5_RPID4_RX_ACPU0" /* unsafe : 234 */
#define IPC_TSV_MBX6_RPID5_RX_ACPU1 "MDC_IPC_TSV_MBX6_RPID5_RX_ACPU1" /* unsafe : 235 */
#define IPC_TSV_MBX7_RPID6_RX_ACPU2 "MDC_IPC_TSV_MBX7_RPID6_RX_ACPU2" /* unsafe : 236 */
#define IPC_TSV_MBX8_RPID7_RX_ACPU3 "MDC_IPC_TSV_MBX8_RPID7_RX_ACPU3" /* unsafe : 237 */
#define IPC_TSV_MBX1_RPID0_TX_ACPU0 "MDC_IPC_TSV_MBX1_RPID0_TX_ACPU0" /* ns normal irq : 234 */
#define IPC_TSV_MBX2_RPID1_TX_ACPU1 "MDC_IPC_TSV_MBX2_RPID1_TX_ACPU1" /* ns normal irq : 235 */
#define IPC_TSV_MBX3_RPID2_TX_ACPU2 "MDC_IPC_TSV_MBX3_RPID2_TX_ACPU2" /* ns normal irq : 236 */
#define IPC_TSV_MBX4_RPID3_TX_ACPU3 "MDC_IPC_TSV_MBX4_RPID3_TX_ACPU3" /* ns normal irq : 237 */

/* lp mbx */
/* lp quick mbx */
#define IPC_LP_MBX0_RPID0_Q_RX_ACPU0 "MDC_IPC_LP_MBX0_RPID0_Q_RX_ACPU0" /* unsafe : 210 */
#define IPC_LP_MBX1_RPID1_Q_RX_ACPU1 "MDC_IPC_LP_MBX1_RPID1_Q_RX_ACPU1" /* unsafe : 211 */
#define IPC_LP_MBX2_RPID2_Q_RX_ACPU2 "MDC_IPC_LP_MBX2_RPID2_Q_RX_ACPU2" /* unsafe : 212 */
#define IPC_LP_MBX3_RPID3_Q_RX_ACPU3 "MDC_IPC_LP_MBX3_RPID3_Q_RX_ACPU3" /* unsafe : 213 */
#define IPC_LP_MBX8_RPID4_Q_TX_ACPU0 "MDC_IPC_LP_MBX8_RPID4_Q_TX_ACPU0" /* ns normal irq : 221 */
#define IPC_LP_MBX9_RPID4_Q_TX_ACPU1 "MDC_IPC_LP_MBX9_RPID4_Q_TX_ACPU1" /* ns normal irq : 222 */
#define IPC_LP_MBX10_RPID4_Q_TX_ACPU2 "MDC_IPC_LP_MBX10_RPID4_Q_TX_ACPU2" /* ns normal irq : 223 */
#define IPC_LP_MBX11_RPID4_Q_TX_ACPU3 "MDC_IPC_LP_MBX11_RPID4_Q_TX_ACPU3" /* ns normal irq : 224 */

/* isp mbx */
/* isp0 ipc0 quick mbx */
#define IPC_ISP0_IPC0_MBX0_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC0_MBX0_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC0_MBX1_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC0_MBX1_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC0_MBX2_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC0_MBX2_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC0_MBX6_RPID1_Q_TX_ACPU0 "IPC_ISP0_IPC0_MBX6_RPID0_Q_TX_ACPU0"
#define IPC_ISP0_IPC0_MBX7_RPID2_Q_TX_ACPU0 "IPC_ISP0_IPC0_MBX7_RPID0_Q_TX_ACPU0"
#define IPC_ISP0_IPC0_MBX8_RPID3_Q_TX_ACPU0 "IPC_ISP0_IPC0_MBX8_RPID0_Q_TX_ACPU0"

/* isp0 ipc1 quick mbx */
#define IPC_ISP0_IPC1_MBX0_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC1_MBX0_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC1_MBX1_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC1_MBX1_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC1_MBX2_RPID0_Q_RX_ACPU0 "IPC_ISP0_IPC1_MBX2_RPID0_Q_RX_ACPU0"
#define IPC_ISP0_IPC1_MBX6_RPID1_Q_TX_ACPU0 "IPC_ISP0_IPC1_MBX6_RPID0_Q_TX_ACPU0"
#define IPC_ISP0_IPC1_MBX7_RPID2_Q_TX_ACPU0 "IPC_ISP0_IPC1_MBX7_RPID0_Q_TX_ACPU0"
#define IPC_ISP0_IPC1_MBX8_RPID3_Q_TX_ACPU0 "IPC_ISP0_IPC1_MBX8_RPID0_Q_TX_ACPU0"

/* isp1 ipc0 quick mbx */
#define IPC_ISP1_IPC0_MBX0_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC0_MBX0_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC0_MBX1_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC0_MBX1_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC0_MBX2_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC0_MBX2_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC0_MBX6_RPID1_Q_TX_ACPU0 "IPC_ISP1_IPC0_MBX6_RPID0_Q_TX_ACPU0"
#define IPC_ISP1_IPC0_MBX7_RPID2_Q_TX_ACPU0 "IPC_ISP1_IPC0_MBX7_RPID0_Q_TX_ACPU0"
#define IPC_ISP1_IPC0_MBX8_RPID3_Q_TX_ACPU0 "IPC_ISP1_IPC0_MBX8_RPID0_Q_TX_ACPU0"

/* isp1 ipc1 quick mbx */
#define IPC_ISP1_IPC1_MBX0_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC1_MBX0_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC1_MBX1_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC1_MBX1_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC1_MBX2_RPID0_Q_RX_ACPU0 "IPC_ISP1_IPC1_MBX2_RPID0_Q_RX_ACPU0"
#define IPC_ISP1_IPC1_MBX6_RPID1_Q_TX_ACPU0 "IPC_ISP1_IPC1_MBX6_RPID0_Q_TX_ACPU0"
#define IPC_ISP1_IPC1_MBX7_RPID2_Q_TX_ACPU0 "IPC_ISP1_IPC1_MBX7_RPID0_Q_TX_ACPU0"
#define IPC_ISP1_IPC1_MBX8_RPID3_Q_TX_ACPU0 "IPC_ISP1_IPC1_MBX8_RPID0_Q_TX_ACPU0"

/* TaiShan IPC quick mbx */
/* ACPU0 */
#define IPC_TAISHAN_MBX0_RPID1_RX_ACPU0 "IPC_TAISHAN_MBX0_RPID1_RX_ACPU0"
#define IPC_TAISHAN_MBX0_RPID2_RX_ACPU0 "IPC_TAISHAN_MBX0_RPID2_RX_ACPU0"
#define IPC_TAISHAN_MBX0_RPID3_RX_ACPU0 "IPC_TAISHAN_MBX0_RPID3_RX_ACPU0"
#define IPC_TAISHAN_MBX1_ACPU0_TX_RPID1 "IPC_TAISHAN_MBX1_ACPU0_TX_RPID1"
#define IPC_TAISHAN_MBX2_ACPU0_TX_RPID2 "IPC_TAISHAN_MBX2_ACPU0_TX_RPID2"
#define IPC_TAISHAN_MBX3_ACPU0_TX_RPID3 "IPC_TAISHAN_MBX3_ACPU0_TX_RPID3"
/* ACPU1 */
#define IPC_TAISHAN_MBX1_RPID0_RX_ACPU1 "IPC_TAISHAN_MBX1_RPID0_RX_ACPU1"
#define IPC_TAISHAN_MBX1_RPID2_RX_ACPU1 "IPC_TAISHAN_MBX1_RPID2_RX_ACPU1"
#define IPC_TAISHAN_MBX1_RPID3_RX_ACPU1 "IPC_TAISHAN_MBX1_RPID3_RX_ACPU1"
#define IPC_TAISHAN_MBX0_ACPU1_TX_RPID0 "IPC_TAISHAN_MBX0_ACPU1_TX_RPID0"
#define IPC_TAISHAN_MBX2_ACPU1_TX_RPID2 "IPC_TAISHAN_MBX2_ACPU1_TX_RPID2"
#define IPC_TAISHAN_MBX3_ACPU1_TX_RPID3 "IPC_TAISHAN_MBX3_ACPU1_TX_RPID3"
/* ACPU2 */
#define IPC_TAISHAN_MBX2_RPID0_RX_ACPU2 "IPC_TAISHAN_MBX2_RPID0_RX_ACPU2"
#define IPC_TAISHAN_MBX2_RPID1_RX_ACPU2 "IPC_TAISHAN_MBX2_RPID1_RX_ACPU2"
#define IPC_TAISHAN_MBX2_RPID3_RX_ACPU2 "IPC_TAISHAN_MBX2_RPID3_RX_ACPU2"
#define IPC_TAISHAN_MBX0_ACPU2_TX_RPID0 "IPC_TAISHAN_MBX0_ACPU2_TX_RPID0"
#define IPC_TAISHAN_MBX1_ACPU2_TX_RPID1 "IPC_TAISHAN_MBX1_ACPU2_TX_RPID1"
#define IPC_TAISHAN_MBX3_ACPU2_TX_RPID3 "IPC_TAISHAN_MBX3_ACPU2_TX_RPID3"
/* ACPU3 */
#define IPC_TAISHAN_MBX3_RPID0_RX_ACPU3 "IPC_TAISHAN_MBX3_RPID0_RX_ACPU3"
#define IPC_TAISHAN_MBX3_RPID1_RX_ACPU3 "IPC_TAISHAN_MBX3_RPID1_RX_ACPU3"
#define IPC_TAISHAN_MBX3_RPID2_RX_ACPU3 "IPC_TAISHAN_MBX3_RPID2_RX_ACPU3"
#define IPC_TAISHAN_MBX0_ACPU3_TX_RPID0 "IPC_TAISHAN_MBX0_ACPU3_TX_RPID0"
#define IPC_TAISHAN_MBX1_ACPU3_TX_RPID1 "IPC_TAISHAN_MBX1_ACPU3_TX_RPID1"
#define IPC_TAISHAN_MBX2_ACPU3_TX_RPID2 "IPC_TAISHAN_MBX2_ACPU3_TX_RPID2"

struct hisi_rproc_info {
    rproc_id_t rproc_id;
    const char *mbox_rp;
    struct atomic_notifier_head notifier;
    struct notifier_block nb;
    struct hisi_mbox *mbox;
    rproc_id_t symmetry_id;  // we  need the symmetry id to clear lpi interrupts in sync send
    struct mutex rproc_mutex;
    u32 register_flag;
};

struct hisi_rproc_cfg {
    rproc_id_t rproc_id;
    const char *mbox_rp;
};

#define HISI_HELPER_MAX_LPI_IRQ_NUM 8
#define HISI_MAX_LPI_IRQ_NUM 4

#define HISI_ACPU0_ACK_IRQ_IDX 0 /* aicpu_0 ipc_rcv ack */
#define HISI_ACPU1_ACK_IRQ_IDX 1 /* aicpu_1 ipc_rcv ack */
#define HISI_ACPU2_ACK_IRQ_IDX 2 /* aicpu_2 ipc_rcv ack */
#define HISI_ACPU3_ACK_IRQ_IDX 3 /* aicpu_3 ipc_rcv ack */

/*
 * Table for available remote processors. DTS sub-node, "remote_processor_type",
 * of node, "hisi_mdev", is configured according to the table.
 *
 * If the table was modified, DTS configiuration should be updated accordingly.
 */
/* TS rprocess id is not the same */
typedef enum {
    ACPU0 = 0,
    ACPU1,
    ACPU2,
    ACPU3,
    TS_ACPU0 = 4,
    TS_ACPU1,
    TS_ACPU2,
    TS_ACPU3,
    SI_TX_SI14 = 14,
    SI_TX_SI15,
    SI_TX_SI16,
    SI_TX_SI17,
    UNCERTAIN_REMOTE_PROCESSOR
} remote_processor_type_t;
extern struct hisi_rproc_cfg g_rproc_cfg[HISI_RPROC_MAX];
#endif
