if ((${PRODUCT} STREQUAL ascend610) OR (${PRODUCT} STREQUAL bs9sx1a) OR (${PRODUCT} STREQUAL ascend610Liteesl) OR (${PRODUCT} STREQUAL ascend610Lite))
    add_subdirectory(mdc)
    return()
endif()

if (${PRODUCT_SIDE} STREQUAL device)
add_subdirectory(ts_task_channel)
endif()

add_subdirectory(ts_platform)
if ((${PRODUCT} STREQUAL ascend310B) OR (${PRODUCT} STREQUAL ascend310Brc)
        OR (${PRODUCT} STREQUAL ascend910B) OR (${PRODUCT} STREQUAL as31xm1))
else()
add_subdirectory(ts_drv)
endif()