# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_soc_resmng.o
ascend_soc_resmng-objs := soc_resmng.o soc_subsys_ts.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include/rms -I$(DRIVER_INC)/include
ccflags-y += -I$(DRIVER_INC)/libc_sec/include -I$(src)
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
