// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  ffts1_reg_s_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/11/15 15:35:31 Create file
// ******************************************************************************

#ifndef __FFTS1_REG_S_REG_OFFSET_FIELD_H__
#define __FFTS1_REG_S_REG_OFFSET_FIELD_H__

#define FFTS1_REG_S_FFTS_POOL_SEC_LEN    8
#define FFTS1_REG_S_FFTS_POOL_SEC_OFFSET 0

#define FFTS1_REG_S_ICG_CLK_FC_EN_LEN       1
#define FFTS1_REG_S_ICG_CLK_FC_EN_OFFSET    11
#define FFTS1_REG_S_ICG_CLK_PROF_EN_LEN     1
#define FFTS1_REG_S_ICG_CLK_PROF_EN_OFFSET  10
#define FFTS1_REG_S_ICG_CLK_TSLOT_EN_LEN    1
#define FFTS1_REG_S_ICG_CLK_TSLOT_EN_OFFSET 9
#define FFTS1_REG_S_ICG_CLK_FFTS_EN_LEN     1
#define FFTS1_REG_S_ICG_CLK_FFTS_EN_OFFSET  8
#define FFTS1_REG_S_ICG_CLK_DLY_CNT_LEN     8
#define FFTS1_REG_S_ICG_CLK_DLY_CNT_OFFSET  0

#define FFTS1_REG_S_ECC_SBIT_WB_DISABLE_LEN              1
#define FFTS1_REG_S_ECC_SBIT_WB_DISABLE_OFFSET           30
#define FFTS1_REG_S_ECC_BYPASS_LEN                       1
#define FFTS1_REG_S_ECC_BYPASS_OFFSET                    29
#define FFTS1_REG_S_FCACHE_SINGLE_CMD_LEN                1
#define FFTS1_REG_S_FCACHE_SINGLE_CMD_OFFSET             28
#define FFTS1_REG_S_LOAD_SOFT_VA_LEN                     1
#define FFTS1_REG_S_LOAD_SOFT_VA_OFFSET                  27
#define FFTS1_REG_S_LOAD_SOFT_AUTHORITY_LEN              1
#define FFTS1_REG_S_LOAD_SOFT_AUTHORITY_OFFSET           26
#define FFTS1_REG_S_PARTID_SEL_LEN                       1
#define FFTS1_REG_S_PARTID_SEL_OFFSET                    25
#define FFTS1_REG_S_NOTIFYID_VFID_AUTHORITY_EN_LEN       1
#define FFTS1_REG_S_NOTIFYID_VFID_AUTHORITY_EN_OFFSET    24
#define FFTS1_REG_S_AIV_OST2BLK_ENABLE_LEN               1
#define FFTS1_REG_S_AIV_OST2BLK_ENABLE_OFFSET            17
#define FFTS1_REG_S_AIC_OST2BLK_ENABLE_LEN               1
#define FFTS1_REG_S_AIC_OST2BLK_ENABLE_OFFSET            16
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AR_VA_LEN           1
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AR_VA_OFFSET        9
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AR_AUTHORITY_LEN    1
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AR_AUTHORITY_OFFSET 8
#define FFTS1_REG_S_WRITE_VALUE_AWFP_LEN                 1
#define FFTS1_REG_S_WRITE_VALUE_AWFP_OFFSET              7
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AW_VA_LEN           1
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AW_VA_OFFSET        6
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AW_AUTHORITY_LEN    1
#define FFTS1_REG_S_WRITE_VALUE_SOFT_AW_AUTHORITY_OFFSET 5
#define FFTS1_REG_S_AWFP_CXT_LEN                         1
#define FFTS1_REG_S_AWFP_CXT_OFFSET                      4
#define FFTS1_REG_S_AWFP_PROF_LEN                        1
#define FFTS1_REG_S_AWFP_PROF_OFFSET                     3
#define FFTS1_REG_S_SQ_EXTRA_RAM_CLR_EN_LEN              1
#define FFTS1_REG_S_SQ_EXTRA_RAM_CLR_EN_OFFSET           2
#define FFTS1_REG_S_CFG_AIV_BYPASS_LEN                   1
#define FFTS1_REG_S_CFG_AIV_BYPASS_OFFSET                1
#define FFTS1_REG_S_CFG_AIC_BYPASS_LEN                   1
#define FFTS1_REG_S_CFG_AIC_BYPASS_OFFSET                0

#define FFTS1_REG_S_PREFETCH_DELAY_CNT_LEN    16
#define FFTS1_REG_S_PREFETCH_DELAY_CNT_OFFSET 0

#define FFTS1_REG_S_SLV_ERROR_RDATA0_LEN    32
#define FFTS1_REG_S_SLV_ERROR_RDATA0_OFFSET 0

#define FFTS1_REG_S_SLV_ERROR_RDATA1_LEN    32
#define FFTS1_REG_S_SLV_ERROR_RDATA1_OFFSET 0

#define FFTS1_REG_S_SLV_ERROR_RDATA2_LEN    32
#define FFTS1_REG_S_SLV_ERROR_RDATA2_OFFSET 0

#define FFTS1_REG_S_SLV_ERROR_RDATA3_LEN    32
#define FFTS1_REG_S_SLV_ERROR_RDATA3_OFFSET 0

#define FFTS1_REG_S_AIC_RESET_DLY_CNT_LEN         8
#define FFTS1_REG_S_AIC_RESET_DLY_CNT_OFFSET      8
#define FFTS1_REG_S_AIC_SKIP_WARNING_CHECK_LEN    1
#define FFTS1_REG_S_AIC_SKIP_WARNING_CHECK_OFFSET 3
#define FFTS1_REG_S_AIC_SKIP_RESET_LEN            1
#define FFTS1_REG_S_AIC_SKIP_RESET_OFFSET         2
#define FFTS1_REG_S_AIC_FORCE_ICACHE_INV_LEN      1
#define FFTS1_REG_S_AIC_FORCE_ICACHE_INV_OFFSET   1



#define FFTS1_REG_S_AIC_ADDR_BASE_L_LEN    32
#define FFTS1_REG_S_AIC_ADDR_BASE_L_OFFSET 0

#define FFTS1_REG_S_AIC_ADDR_SHIFT_LEN     6
#define FFTS1_REG_S_AIC_ADDR_SHIFT_OFFSET  17
#define FFTS1_REG_S_AIC_ADDR_BASE_H_LEN    17
#define FFTS1_REG_S_AIC_ADDR_BASE_H_OFFSET 0

#define FFTS1_REG_S_AIV_RESET_DLY_CNT_LEN         8
#define FFTS1_REG_S_AIV_RESET_DLY_CNT_OFFSET      8
#define FFTS1_REG_S_AIV_SKIP_WARNING_CHECK_LEN    1
#define FFTS1_REG_S_AIV_SKIP_WARNING_CHECK_OFFSET 3
#define FFTS1_REG_S_AIV_SKIP_RESET_LEN            1
#define FFTS1_REG_S_AIV_SKIP_RESET_OFFSET         2
#define FFTS1_REG_S_AIV_FORCE_ICACHE_INV_LEN      1
#define FFTS1_REG_S_AIV_FORCE_ICACHE_INV_OFFSET   1



#define FFTS1_REG_S_EVEN_AIV_ADDR_BASE_L_LEN    32
#define FFTS1_REG_S_EVEN_AIV_ADDR_BASE_L_OFFSET 0

#define FFTS1_REG_S_EVEN_AIV_ADDR_SHIFT_LEN     6
#define FFTS1_REG_S_EVEN_AIV_ADDR_SHIFT_OFFSET  17
#define FFTS1_REG_S_EVEN_AIV_ADDR_BASE_H_LEN    17
#define FFTS1_REG_S_EVEN_AIV_ADDR_BASE_H_OFFSET 0

#define FFTS1_REG_S_ODD_AIV_ADDR_BASE_L_LEN    32
#define FFTS1_REG_S_ODD_AIV_ADDR_BASE_L_OFFSET 0

#define FFTS1_REG_S_ODD_AIV_ADDR_SHIFT_LEN     6
#define FFTS1_REG_S_ODD_AIV_ADDR_SHIFT_OFFSET  17
#define FFTS1_REG_S_ODD_AIV_ADDR_BASE_H_LEN    17
#define FFTS1_REG_S_ODD_AIV_ADDR_BASE_H_OFFSET 0

#define FFTS1_REG_S_AWSNOOP_PROF_LEN    1
#define FFTS1_REG_S_AWSNOOP_PROF_OFFSET 20
#define FFTS1_REG_S_AWCACHE_PROF_LEN    4
#define FFTS1_REG_S_AWCACHE_PROF_OFFSET 16
#define FFTS1_REG_S_AWSNOOP_CXT_LEN     1
#define FFTS1_REG_S_AWSNOOP_CXT_OFFSET  12
#define FFTS1_REG_S_AWCACHE_CXT_LEN     4
#define FFTS1_REG_S_AWCACHE_CXT_OFFSET  8
#define FFTS1_REG_S_ARSNOOP_CXT_LEN     1
#define FFTS1_REG_S_ARSNOOP_CXT_OFFSET  4
#define FFTS1_REG_S_ARCACHE_CXT_LEN     4
#define FFTS1_REG_S_ARCACHE_CXT_OFFSET  0

#define FFTS1_REG_S_ARSNOOP_AIV_LEN    1
#define FFTS1_REG_S_ARSNOOP_AIV_OFFSET 28
#define FFTS1_REG_S_ARCACHE_AIV_LEN    4
#define FFTS1_REG_S_ARCACHE_AIV_OFFSET 24
#define FFTS1_REG_S_AWSNOOP_AIV_LEN    1
#define FFTS1_REG_S_AWSNOOP_AIV_OFFSET 20
#define FFTS1_REG_S_AWCACHE_AIV_LEN    4
#define FFTS1_REG_S_AWCACHE_AIV_OFFSET 16
#define FFTS1_REG_S_ARSNOOP_AIC_LEN    1
#define FFTS1_REG_S_ARSNOOP_AIC_OFFSET 12
#define FFTS1_REG_S_ARCACHE_AIC_LEN    4
#define FFTS1_REG_S_ARCACHE_AIC_OFFSET 8
#define FFTS1_REG_S_AWSNOOP_AIC_LEN    1
#define FFTS1_REG_S_AWSNOOP_AIC_OFFSET 4
#define FFTS1_REG_S_AWCACHE_AIC_LEN    4
#define FFTS1_REG_S_AWCACHE_AIC_OFFSET 0

#define FFTS1_REG_S_ARPROT_LOAD_LEN           1
#define FFTS1_REG_S_ARPROT_LOAD_OFFSET        8
#define FFTS1_REG_S_AWPROT_WRITE_VALUE_LEN    1
#define FFTS1_REG_S_AWPROT_WRITE_VALUE_OFFSET 4
#define FFTS1_REG_S_AWPROT_PROF_LEN           3
#define FFTS1_REG_S_AWPROT_PROF_OFFSET        0

#define FFTS1_REG_S_NS_SQ_ARPROT_CXT_LEN    3
#define FFTS1_REG_S_NS_SQ_ARPROT_CXT_OFFSET 20
#define FFTS1_REG_S_NS_SQ_AWPROT_CXT_LEN    3
#define FFTS1_REG_S_NS_SQ_AWPROT_CXT_OFFSET 16
#define FFTS1_REG_S_NS_SQ_ARPROT_AIV_LEN    3
#define FFTS1_REG_S_NS_SQ_ARPROT_AIV_OFFSET 12
#define FFTS1_REG_S_NS_SQ_AWPROT_AIV_LEN    3
#define FFTS1_REG_S_NS_SQ_AWPROT_AIV_OFFSET 8
#define FFTS1_REG_S_NS_SQ_ARPROT_AIC_LEN    3
#define FFTS1_REG_S_NS_SQ_ARPROT_AIC_OFFSET 4
#define FFTS1_REG_S_NS_SQ_AWPROT_AIC_LEN    3
#define FFTS1_REG_S_NS_SQ_AWPROT_AIC_OFFSET 0

#define FFTS1_REG_S_S_SQ_ARPROT_WRITE_VALUE_LEN    1
#define FFTS1_REG_S_S_SQ_ARPROT_WRITE_VALUE_OFFSET 24
#define FFTS1_REG_S_S_SQ_ARPROT_CXT_LEN            3
#define FFTS1_REG_S_S_SQ_ARPROT_CXT_OFFSET         20
#define FFTS1_REG_S_S_SQ_AWPROT_CXT_LEN            3
#define FFTS1_REG_S_S_SQ_AWPROT_CXT_OFFSET         16
#define FFTS1_REG_S_S_SQ_ARPROT_AIV_LEN            3
#define FFTS1_REG_S_S_SQ_ARPROT_AIV_OFFSET         12
#define FFTS1_REG_S_S_SQ_AWPROT_AIV_LEN            3
#define FFTS1_REG_S_S_SQ_AWPROT_AIV_OFFSET         8
#define FFTS1_REG_S_S_SQ_ARPROT_AIC_LEN            3
#define FFTS1_REG_S_S_SQ_ARPROT_AIC_OFFSET         4
#define FFTS1_REG_S_S_SQ_AWPROT_AIC_LEN            3
#define FFTS1_REG_S_S_SQ_AWPROT_AIC_OFFSET         0

#define FFTS1_REG_S_ARNS_WRITE_VALUE_LEN    1
#define FFTS1_REG_S_ARNS_WRITE_VALUE_OFFSET 3
#define FFTS1_REG_S_ARNS_LOAD_LEN           1
#define FFTS1_REG_S_ARNS_LOAD_OFFSET        2
#define FFTS1_REG_S_AWNS_WRITE_VALUE_LEN    1
#define FFTS1_REG_S_AWNS_WRITE_VALUE_OFFSET 1
#define FFTS1_REG_S_AWNS_PROF_LEN           1
#define FFTS1_REG_S_AWNS_PROF_OFFSET        0

#define FFTS1_REG_S_ARNS_CXT_LEN    1
#define FFTS1_REG_S_ARNS_CXT_OFFSET 5
#define FFTS1_REG_S_AWNS_CXT_LEN    1
#define FFTS1_REG_S_AWNS_CXT_OFFSET 4
#define FFTS1_REG_S_ARNS_AIV_LEN    1
#define FFTS1_REG_S_ARNS_AIV_OFFSET 3
#define FFTS1_REG_S_AWNS_AIV_LEN    1
#define FFTS1_REG_S_AWNS_AIV_OFFSET 2
#define FFTS1_REG_S_ARNS_AIC_LEN    1
#define FFTS1_REG_S_ARNS_AIC_OFFSET 1
#define FFTS1_REG_S_AWNS_AIC_LEN    1
#define FFTS1_REG_S_AWNS_AIC_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_0_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_0_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_1_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_1_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_2_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_2_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_3_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_3_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_4_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_4_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_5_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_5_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_6_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_6_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_7_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLE_CTRL_S_7_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_0_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_0_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_1_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_1_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_2_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_2_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_3_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_3_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_4_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_4_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_5_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_5_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_6_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_6_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_7_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_DISABLE_CTRL_S_7_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_0_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_0_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_1_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_1_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_2_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_2_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_3_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_3_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_4_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_4_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_5_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_5_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_6_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_6_OFFSET 0

#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_7_LEN    16
#define FFTS1_REG_S_FFTS_SLOT_ENABLED_STATUS_S_7_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_0_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_0_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_1_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_1_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_2_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_2_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_3_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_3_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_4_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_4_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_5_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_5_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_6_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_6_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_7_LEN    25
#define FFTS1_REG_S_AIC_ENABLE_CTRL_S_7_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_0_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_0_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_1_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_1_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_2_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_2_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_3_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_3_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_4_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_4_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_5_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_5_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_6_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_6_OFFSET 0

#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_7_LEN    25
#define FFTS1_REG_S_AIC_DISABLE_CTRL_S_7_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_0_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_0_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_1_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_1_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_2_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_2_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_3_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_3_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_4_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_4_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_5_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_5_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_6_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_6_OFFSET 0

#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_7_LEN    25
#define FFTS1_REG_S_AIC_ENABLED_STATUS_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_0_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_1_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_2_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_3_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_4_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_5_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_6_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_7_LEN    32
#define FFTS1_REG_S_AIV_ENABLE_CTRL0_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_0_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_1_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_2_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_3_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_4_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_5_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_6_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_7_LEN    18
#define FFTS1_REG_S_AIV_ENABLE_CTRL1_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_0_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_1_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_2_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_3_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_4_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_5_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_6_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_7_LEN    32
#define FFTS1_REG_S_AIV_DISABLE_CTRL0_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_0_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_1_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_2_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_3_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_4_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_5_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_6_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_7_LEN    18
#define FFTS1_REG_S_AIV_DISABLE_CTRL1_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_0_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_1_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_2_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_3_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_4_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_5_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_6_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_7_LEN    32
#define FFTS1_REG_S_AIV_ENABLED_STATUS0_S_7_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_0_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_0_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_1_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_1_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_2_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_2_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_3_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_3_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_4_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_4_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_5_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_5_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_6_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_6_OFFSET 0

#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_7_LEN    18
#define FFTS1_REG_S_AIV_ENABLED_STATUS1_S_7_OFFSET 0

#endif // __FFTS1_REG_S_REG_OFFSET_FIELD_H__
