// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  gic_emu_regs_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V5.1 
// History       :  xxx 2021/06/02 10:30:30 Create file
// ******************************************************************************

#ifndef __GIC_EMU_REGS_REG_OFFSET_FIELD_H__
#define __GIC_EMU_REGS_REG_OFFSET_FIELD_H__

#define GIC_EMU_REGS_EMU_MODE_SEL_LEN    5
#define GIC_EMU_REGS_EMU_MODE_SEL_OFFSET 4
#define GIC_EMU_REGS_SNAP_EN_LEN         1
#define GIC_EMU_REGS_SNAP_EN_OFFSET      1
#define GIC_EMU_REGS_CNT_CLR_CE_LEN      1
#define GIC_EMU_REGS_CNT_CLR_CE_OFFSET   0

#define GIC_EMU_REGS_EMU_PRI_EQ_RDCPT_0_LEN    32
#define GIC_EMU_REGS_EMU_PRI_EQ_RDCPT_0_OFFSET 0

#define GIC_EMU_REGS_EMU_PRI_EQ_RDCPT_1_LEN    32
#define GIC_EMU_REGS_EMU_PRI_EQ_RDCPT_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_NOVLD_INCPT_0_LEN    32
#define GIC_EMU_REGS_EMU_CLR_NOVLD_INCPT_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_NOVLD_INCPT_1_LEN    32
#define GIC_EMU_REGS_EMU_CLR_NOVLD_INCPT_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_NOVLD_INCPT_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_NOVLD_INCPT_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_NOVLD_INCPT_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_NOVLD_INCPT_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_PRI_GT_RDCPT_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_PRI_GT_RDCPT_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_PRI_GT_RDCPT_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_PRI_GT_RDCPT_1_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_VLD_INCPT_0_LEN    32
#define GIC_EMU_REGS_EMU_INV_VLD_INCPT_0_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_VLD_INCPT_1_LEN    32
#define GIC_EMU_REGS_EMU_INV_VLD_INCPT_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_1W_0_LEN    32
#define GIC_EMU_REGS_EMU_CLR_1W_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_1W_1_LEN    32
#define GIC_EMU_REGS_EMU_CLR_1W_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ADD_ENABLE_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_ADD_ENABLE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ADD_ENABLE_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_ADD_ENABLE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CMD_LPI_MOVRTY_DONE_0_LEN    32
#define GIC_EMU_REGS_EMU_CMD_LPI_MOVRTY_DONE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CMD_LPI_MOVRTY_DONE_1_LEN    32
#define GIC_EMU_REGS_EMU_CMD_LPI_MOVRTY_DONE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CMD_LPI_MOV_DONE_0_LEN    32
#define GIC_EMU_REGS_EMU_CMD_LPI_MOV_DONE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CMD_LPI_MOV_DONE_1_LEN    32
#define GIC_EMU_REGS_EMU_CMD_LPI_MOV_DONE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_LPI_CACHE_RPL_0_LEN    32
#define GIC_EMU_REGS_EMU_LPI_CACHE_RPL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_LPI_CACHE_RPL_1_LEN    32
#define GIC_EMU_REGS_EMU_LPI_CACHE_RPL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_LPI_RTY_FLAG_0_LEN    32
#define GIC_EMU_REGS_EMU_LPI_RTY_FLAG_0_OFFSET 0

#define GIC_EMU_REGS_EMU_LPI_RTY_FLAG_1_LEN    32
#define GIC_EMU_REGS_EMU_LPI_RTY_FLAG_1_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_ID_INCACHE_0_LEN    32
#define GIC_EMU_REGS_EMU_MOV_ID_INCACHE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_ID_INCACHE_1_LEN    32
#define GIC_EMU_REGS_EMU_MOV_ID_INCACHE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_ID_INCACHE_0_LEN    32
#define GIC_EMU_REGS_EMU_INV_ID_INCACHE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_ID_INCACHE_1_LEN    32
#define GIC_EMU_REGS_EMU_INV_ID_INCACHE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_ID_INCACHE_0_LEN    32
#define GIC_EMU_REGS_EMU_CLR_ID_INCACHE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_ID_INCACHE_1_LEN    32
#define GIC_EMU_REGS_EMU_CLR_ID_INCACHE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ID_INCACHE_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_ID_INCACHE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ID_INCACHE_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_ID_INCACHE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_CF_INCACHE_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_CF_INCACHE_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_CF_INCACHE_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_CF_INCACHE_1_OFFSET 0

#define GIC_EMU_REGS_EMU_MOVALL_0_LEN    32
#define GIC_EMU_REGS_EMU_MOVALL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_MOVALL_1_LEN    32
#define GIC_EMU_REGS_EMU_MOVALL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_INVALL_0_LEN    32
#define GIC_EMU_REGS_EMU_INVALL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_INVALL_1_LEN    32
#define GIC_EMU_REGS_EMU_INVALL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_0_LEN    32
#define GIC_EMU_REGS_EMU_MOV_0_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_1_LEN    32
#define GIC_EMU_REGS_EMU_MOV_1_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_0_LEN    32
#define GIC_EMU_REGS_EMU_INV_0_OFFSET 0

#define GIC_EMU_REGS_EMU_INV_1_LEN    32
#define GIC_EMU_REGS_EMU_INV_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_0_LEN    32
#define GIC_EMU_REGS_EMU_CLR_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CLR_1_LEN    32
#define GIC_EMU_REGS_EMU_CLR_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_1_OFFSET 0

#define GIC_EMU_REGS_EMU_RTY_MOV_BERR_0_LEN    32
#define GIC_EMU_REGS_EMU_RTY_MOV_BERR_0_OFFSET 0

#define GIC_EMU_REGS_EMU_RTY_MOV_BERR_1_LEN    32
#define GIC_EMU_REGS_EMU_RTY_MOV_BERR_1_OFFSET 0

#define GIC_EMU_REGS_EMU_BUFF_FULL_0_LEN    32
#define GIC_EMU_REGS_EMU_BUFF_FULL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_BUFF_FULL_1_LEN    32
#define GIC_EMU_REGS_EMU_BUFF_FULL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_RTY_MOV_BOK_0_LEN    32
#define GIC_EMU_REGS_EMU_RTY_MOV_BOK_0_OFFSET 0

#define GIC_EMU_REGS_EMU_RTY_MOV_BOK_1_LEN    32
#define GIC_EMU_REGS_EMU_RTY_MOV_BOK_1_OFFSET 0

#define GIC_EMU_REGS_EMU_GICR_INVALL_ACK_LEN    32
#define GIC_EMU_REGS_EMU_GICR_INVALL_ACK_OFFSET 0

#define GIC_EMU_REGS_EMU_GICR_VCMDB_REQ_LEN    32
#define GIC_EMU_REGS_EMU_GICR_VCMDB_REQ_OFFSET 0

#define GIC_EMU_REGS_EMU_VCMD_DOORBELL_GNT_LEN    32
#define GIC_EMU_REGS_EMU_VCMD_DOORBELL_GNT_OFFSET 0

#define GIC_EMU_REGS_EMU_VCMD_DOORBELL_PDING_LEN    32
#define GIC_EMU_REGS_EMU_VCMD_DOORBELL_PDING_OFFSET 0

#define GIC_EMU_REGS_EMU_GICR_CMDB_REQ_LEN    32
#define GIC_EMU_REGS_EMU_GICR_CMDB_REQ_OFFSET 0

#define GIC_EMU_REGS_EMU_CMDID_ALL_1W_0_LEN    32
#define GIC_EMU_REGS_EMU_CMDID_ALL_1W_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CMDID_ALL_1W_1_LEN    32
#define GIC_EMU_REGS_EMU_CMDID_ALL_1W_1_OFFSET 0

#define GIC_EMU_REGS_EMU_CMDB_FIFO_PFULL_0_LEN    32
#define GIC_EMU_REGS_EMU_CMDB_FIFO_PFULL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_CMDB_FIFO_PFULL_1_LEN    32
#define GIC_EMU_REGS_EMU_CMDB_FIFO_PFULL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SYNC_CARE_CNT_FULL_0_LEN    32
#define GIC_EMU_REGS_EMU_SYNC_CARE_CNT_FULL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SYNC_CARE_CNT_FULL_1_LEN    32
#define GIC_EMU_REGS_EMU_SYNC_CARE_CNT_FULL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_CNT_FULL_0_LEN    32
#define GIC_EMU_REGS_EMU_MOV_CNT_FULL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_MOV_CNT_FULL_1_LEN    32
#define GIC_EMU_REGS_EMU_MOV_CNT_FULL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_TWO_CMDB_FIFO_PFULL_0_LEN    32
#define GIC_EMU_REGS_EMU_TWO_CMDB_FIFO_PFULL_0_OFFSET 0

#define GIC_EMU_REGS_EMU_TWO_CMDB_FIFO_PFULL_1_LEN    32
#define GIC_EMU_REGS_EMU_TWO_CMDB_FIFO_PFULL_1_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ADD_SMAETIME_0_LEN    32
#define GIC_EMU_REGS_EMU_SET_ADD_SMAETIME_0_OFFSET 0

#define GIC_EMU_REGS_EMU_SET_ADD_SMAETIME_1_LEN    32
#define GIC_EMU_REGS_EMU_SET_ADD_SMAETIME_1_OFFSET 0

#define GIC_EMU_REGS_EMU_STREAM_IRQ_REPLACE_LEN    32
#define GIC_EMU_REGS_EMU_STREAM_IRQ_REPLACE_OFFSET 0

#define GIC_EMU_REGS_EMU_STREAM_PFULL_LEN    32
#define GIC_EMU_REGS_EMU_STREAM_PFULL_OFFSET 0

#define GIC_EMU_REGS_EMU_STREAM_IRQ_TOUT_LEN    32
#define GIC_EMU_REGS_EMU_STREAM_IRQ_TOUT_OFFSET 0

#define GIC_EMU_REGS_EMU_MOVBUF_PRRSS_LEN    32
#define GIC_EMU_REGS_EMU_MOVBUF_PRRSS_OFFSET 0

#define GIC_EMU_REGS_EMU_CMDFIFO_PRRSS_LEN    32
#define GIC_EMU_REGS_EMU_CMDFIFO_PRRSS_OFFSET 0

#define GIC_EMU_REGS_EMU_1_CPUREQ_PRRSS_LEN    32
#define GIC_EMU_REGS_EMU_1_CPUREQ_PRRSS_OFFSET 0

#define GIC_EMU_REGS_EMU_ALL_CPUREQ_PRRSS_LEN    32
#define GIC_EMU_REGS_EMU_ALL_CPUREQ_PRRSS_OFFSET 0

#endif // __GIC_EMU_REGS_REG_OFFSET_FIELD_H__
