// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  gicr_lowid_regs_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V5.1 
// History       :  xxx 2021/06/02 10:30:29 Create file
// ******************************************************************************

#ifndef __GICR_LOWID_REGS_REG_OFFSET_FIELD_H__
#define __GICR_LOWID_REGS_REG_OFFSET_FIELD_H__

#define GICR_LOWID_REGS_GICR_PPIGROUP_LEN    12
#define GICR_LOWID_REGS_GICR_PPIGROUP_OFFSET 20
#define GICR_LOWID_REGS_GICR_SGIGROUP_LEN    16
#define GICR_LOWID_REGS_GICR_SGIGROUP_OFFSET 0

#define GICR_LOWID_REGS_GICR_SETPPPIENABLE_LEN    12
#define GICR_LOWID_REGS_GICR_SETPPPIENABLE_OFFSET 20
#define GICR_LOWID_REGS_GICR_SETSGIENABLE_LEN     16
#define GICR_LOWID_REGS_GICR_SETSGIENABLE_OFFSET  0

#define GICR_LOWID_REGS_GICR_CLEARPPIENABLE_LEN    12
#define GICR_LOWID_REGS_GICR_CLEARPPIENABLE_OFFSET 20
#define GICR_LOWID_REGS_GICR_CLEARSGIENABLE_LEN    16
#define GICR_LOWID_REGS_GICR_CLEARSGIENABLE_OFFSET 0

#define GICR_LOWID_REGS_GICR_SETPPIPENDING_LEN    12
#define GICR_LOWID_REGS_GICR_SETPPIPENDING_OFFSET 20
#define GICR_LOWID_REGS_GICR_SETSGIPENDING_LEN    16
#define GICR_LOWID_REGS_GICR_SETSGIPENDING_OFFSET 0

#define GICR_LOWID_REGS_GICR_CLEARPPIPENDING_LEN    12
#define GICR_LOWID_REGS_GICR_CLEARPPIPENDING_OFFSET 20
#define GICR_LOWID_REGS_GICR_CLEARSGIPENDING_LEN    16
#define GICR_LOWID_REGS_GICR_CLEARSGIPENDING_OFFSET 0

#define GICR_LOWID_REGS_GICR_SETPPIACTIVE_LEN    12
#define GICR_LOWID_REGS_GICR_SETPPIACTIVE_OFFSET 20
#define GICR_LOWID_REGS_GICR_SETSGIACTIVE_LEN    16
#define GICR_LOWID_REGS_GICR_SETSGIACTIVE_OFFSET 0

#define GICR_LOWID_REGS_GICR_CLEARPPIACTIVE_LEN    12
#define GICR_LOWID_REGS_GICR_CLEARPPIACTIVE_OFFSET 20
#define GICR_LOWID_REGS_GICR_CLEARSGIACTIVE_LEN    16
#define GICR_LOWID_REGS_GICR_CLEARSGIACTIVE_OFFSET 0

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_2_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_2_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_2_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_2_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_3_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_3_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_3_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_3_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_3_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_3_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_3_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_3_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_2_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_2_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_2_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_2_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_2_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_2_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_2_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_2_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_3_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_3_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_3_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_3_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_3_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_3_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_3_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_3_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_OFFSET 28
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_OFFSET 20
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_OFFSET 12
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_LEN    4
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_OFFSET 4

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_0_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_0_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_0_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_0_OFFSET 3

#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT3_1_OFFSET 27
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT2_1_OFFSET 19
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT1_1_OFFSET 11
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_LEN    5
#define GICR_LOWID_REGS_GICR_PRIORITY_INT0_1_OFFSET 3

#define GICR_LOWID_REGS_GICR_SGICONFIG_LEN    32
#define GICR_LOWID_REGS_GICR_SGICONFIG_OFFSET 0

#define GICR_LOWID_REGS_GICR_PPICONFIG_15_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_15_OFFSET 31
#define GICR_LOWID_REGS_GICR_PPICONFIG_14_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_14_OFFSET 29
#define GICR_LOWID_REGS_GICR_PPICONFIG_13_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_13_OFFSET 27
#define GICR_LOWID_REGS_GICR_PPICONFIG_12_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_12_OFFSET 25
#define GICR_LOWID_REGS_GICR_PPICONFIG_11_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_11_OFFSET 23
#define GICR_LOWID_REGS_GICR_PPICONFIG_10_LEN    1
#define GICR_LOWID_REGS_GICR_PPICONFIG_10_OFFSET 21
#define GICR_LOWID_REGS_GICR_PPICONFIG_9_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_9_OFFSET  19
#define GICR_LOWID_REGS_GICR_PPICONFIG_8_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_8_OFFSET  17
#define GICR_LOWID_REGS_GICR_PPICONFIG_7_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_7_OFFSET  15
#define GICR_LOWID_REGS_GICR_PPICONFIG_6_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_6_OFFSET  13
#define GICR_LOWID_REGS_GICR_PPICONFIG_5_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_5_OFFSET  11
#define GICR_LOWID_REGS_GICR_PPICONFIG_4_LEN     1
#define GICR_LOWID_REGS_GICR_PPICONFIG_4_OFFSET  9

#define GICR_LOWID_REGS_GICR_SGINSAC_LEN    32
#define GICR_LOWID_REGS_GICR_SGINSAC_OFFSET 0

#define GICR_LOWID_REGS_GICR_PPIMODE_LEN    12
#define GICR_LOWID_REGS_GICR_PPIMODE_OFFSET 20
#define GICR_LOWID_REGS_GICR_SGIMODE_LEN    16
#define GICR_LOWID_REGS_GICR_SGIMODE_OFFSET 0

#endif // __GICR_LOWID_REGS_REG_OFFSET_FIELD_H__
