// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_rtsq_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:43:51 Create file
// ******************************************************************************

#ifndef __STARS_RTSQ_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_RTSQ_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_RTSQ_NS_REG_SP_LEVEL_LEN    3
#define STARS_RTSQ_NS_REG_SP_LEVEL_OFFSET 8

#define STARS_RTSQ_NS_REG_WAIT_TASK_RUNTIME_LIMIT_L_LEN    32
#define STARS_RTSQ_NS_REG_WAIT_TASK_RUNTIME_LIMIT_L_OFFSET 0

#define STARS_RTSQ_NS_REG_WAIT_TASK_RUNTIME_LIMIT_H_LEN    32
#define STARS_RTSQ_NS_REG_WAIT_TASK_RUNTIME_LIMIT_H_OFFSET 0

#define STARS_RTSQ_NS_REG_ARSNOOP_SWAPBUF_LEN    1
#define STARS_RTSQ_NS_REG_ARSNOOP_SWAPBUF_OFFSET 20
#define STARS_RTSQ_NS_REG_ARCACHE_SWAPBUF_LEN    4
#define STARS_RTSQ_NS_REG_ARCACHE_SWAPBUF_OFFSET 16

#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_BASE_ADDR_L_LEN    32
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_BASE_ADDR_L_OFFSET 0

#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_IS_VIRTUAL_LEN     1
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_IS_VIRTUAL_OFFSET  31
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_SHIFT_LEN          6
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_SHIFT_OFFSET       17
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_BASE_ADDR_H_LEN    17
#define STARS_RTSQ_NS_REG_NS_SQ_SWAP_BUF_BASE_ADDR_H_OFFSET 0

#define STARS_RTSQ_NS_REG_DFX_RTSQ_FSM_SEL_LEN    11
#define STARS_RTSQ_NS_REG_DFX_RTSQ_FSM_SEL_OFFSET 0

#define STARS_RTSQ_NS_REG_DFX_RTSQ_FWRSP_OST_LEN    1
#define STARS_RTSQ_NS_REG_DFX_RTSQ_FWRSP_OST_OFFSET 4
#define STARS_RTSQ_NS_REG_DFX_RTSQ_FSM_STATE_LEN    4
#define STARS_RTSQ_NS_REG_DFX_RTSQ_FSM_STATE_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_0_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_0_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_0_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_0_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_0_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_0_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_0_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_0_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_1_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_1_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_1_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_1_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_1_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_1_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_1_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_1_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_2_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_2_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_2_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_2_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_2_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_2_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_2_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_2_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_3_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_3_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_3_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_3_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_3_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_3_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_3_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_3_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_4_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_4_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_4_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_4_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_4_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_4_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_4_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_4_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_5_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_5_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_5_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_5_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_5_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_5_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_5_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_5_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_6_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_6_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_6_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_6_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_6_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_6_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_6_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_6_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_7_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_SDMA_NS_7_OFFSET    24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_7_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_AICPU_NS_7_OFFSET   16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_7_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_PCIEDMA_NS_7_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_7_LEN       7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_FFTS_NS_7_OFFSET    0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_0_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_0_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_0_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_0_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_0_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_0_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_0_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_0_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_1_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_1_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_1_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_1_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_1_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_1_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_1_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_1_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_2_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_2_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_2_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_2_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_2_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_2_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_2_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_2_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_3_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_3_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_3_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_3_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_3_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_3_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_3_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_3_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_4_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_4_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_4_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_4_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_4_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_4_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_4_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_4_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_5_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_5_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_5_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_5_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_5_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_5_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_5_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_5_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_6_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_6_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_6_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_6_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_6_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_6_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_6_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_6_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_7_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_DSA_NS_7_OFFSET   24
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_7_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGE_NS_7_OFFSET 16
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_7_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_JPEGD_NS_7_OFFSET 8
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_7_LEN      7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_VPC_NS_7_OFFSET   0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_0_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_0_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_1_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_1_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_2_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_2_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_3_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_3_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_4_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_4_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_5_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_5_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_6_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_6_OFFSET 0

#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_7_LEN    7
#define STARS_RTSQ_NS_REG_RTSQ_SWAPIN_MAX_CONDS_NS_7_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_0_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_0_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_1_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_1_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_2_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_2_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_3_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_3_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_4_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_4_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_5_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_5_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_6_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_6_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_7_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_7_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_8_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_8_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_9_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_9_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_10_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_10_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_11_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_11_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_12_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_12_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_13_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_13_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_14_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_14_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_15_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_15_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_16_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_16_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_17_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_17_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_18_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_18_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_19_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_19_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_20_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_20_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_21_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_21_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_22_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_22_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_23_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_23_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_24_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_24_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_25_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_25_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_26_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_26_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_27_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_27_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_28_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_28_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_29_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_29_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_30_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_30_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_31_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_31_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_32_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_32_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_33_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_33_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_34_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_34_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_35_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_35_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_36_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_36_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_37_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_37_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_38_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_38_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_39_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_39_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_40_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_40_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_41_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_41_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_42_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_42_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_43_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_43_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_44_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_44_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_45_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_45_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_46_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_46_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_47_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_47_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_48_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_48_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_49_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_49_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_50_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_50_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_51_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_51_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_52_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_52_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_53_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_53_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_54_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_54_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_55_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_55_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_56_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_56_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_57_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_57_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_58_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_58_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_59_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_59_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_60_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_60_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_61_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_61_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_62_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_62_OFFSET 0

#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_63_LEN    12
#define STARS_RTSQ_NS_REG_MODEL_WEIGHT_63_OFFSET 0

#define STARS_RTSQ_NS_REG_UPD_ZERO_WEIGHT_LEN    1
#define STARS_RTSQ_NS_REG_UPD_ZERO_WEIGHT_OFFSET 1
#define STARS_RTSQ_NS_REG_MODEL_FRIENDLY_LEN     1
#define STARS_RTSQ_NS_REG_MODEL_FRIENDLY_OFFSET  0

#define STARS_GLB_NS_FFTS_TASK_RUNTIME_LIMIT_EXP_LEN 6
#define STARS_GLB_NS_FFTS_TASK_RUNTIME_LIMIT_EXP_OFFSET 0

#endif // __STARS_RTSQ_NS_REG_REG_OFFSET_FIELD_H__
