// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_host_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/04 15:09:36 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_HOST_REG_REG_OFFSET_H__
#define __STARS_CQINT_HOST_REG_REG_OFFSET_H__

/* STARS_CQINT_HOST_REG Base address of Module's Register */
#define SOC_STARS_CQINT_HOST_REG_BASE                       (0x10c00000)

/******************************************************************************/
/*                      SOC STARS_CQINT_HOST_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_0_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x0)      
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_1_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x4)      
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_2_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x8)      
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_3_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0xC)      
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_4_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x10)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_5_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x14)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_6_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x18)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_7_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_8_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x20)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_9_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x24)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_10_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x28)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_11_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x2C)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_12_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x30)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_13_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x34)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_14_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x38)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_INT_CFG_15_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x3C)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_SEC_LOCK_REG                                (SOC_STARS_CQINT_HOST_REG_BASE + 0x40)     
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_0_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x100010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_1_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x110010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_2_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x120010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_3_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x130010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_4_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x140010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_5_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x150010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_6_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x160010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_7_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x170010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_8_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x180010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_9_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x190010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_10_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_11_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_12_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_13_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_14_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_15_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_0_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x100014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_1_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x110014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_2_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x120014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_3_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x130014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_4_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x140014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_5_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x150014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_6_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x160014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_7_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x170014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_8_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x180014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_9_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x190014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_10_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_11_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_12_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_13_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_14_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_15_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_0_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x100020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_1_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x110020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_2_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x120020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_3_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x130020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_4_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x140020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_5_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x150020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_6_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x160020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_7_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x170020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_8_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x180020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_9_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x190020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_10_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_11_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_12_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_13_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_14_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_15_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_0_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_1_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_2_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x120034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_3_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x130034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_4_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x140034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_5_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x150034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_6_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x160034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_7_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x170034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_8_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x180034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_9_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x190034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_10_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_11_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_12_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_13_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_14_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_15_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_0_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x100040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_1_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x110040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_2_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x120040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_3_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x130040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_4_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x140040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_5_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x150040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_6_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x160040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_7_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x170040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_8_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x180040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_9_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x190040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_10_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_11_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_12_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_13_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_14_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_15_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_0_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x100080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_1_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x100084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_2_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x100088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_3_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x10008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_4_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x110080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_5_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x110084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_6_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x110088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_7_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x11008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_8_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x120080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_9_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x120084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_10_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x120088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_11_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x12008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_12_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x130080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_13_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x130084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_14_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x130088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_15_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x13008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_16_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x140080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_17_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x140084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_18_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x140088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_19_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x14008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_20_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x150080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_21_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x150084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_22_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x150088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_23_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x15008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_24_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x160080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_25_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x160084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_26_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x160088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_27_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x16008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_28_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x170080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_29_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x170084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_30_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x170088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_31_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x17008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_32_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x180080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_33_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x180084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_34_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x180088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_35_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x18008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_36_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x190080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_37_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x190084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_38_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x190088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_39_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x19008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_40_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_41_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_42_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_43_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_44_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_45_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_46_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_47_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_48_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_49_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_50_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_51_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_52_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_53_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_54_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_55_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_56_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_57_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_58_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_59_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_60_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0080) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_61_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0084) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_62_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0088) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_RAW2_63_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F008C) /* L2级CQE_WRITTEN原始中断状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_0_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_1_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_2_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_3_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x10009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_4_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_5_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_6_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_7_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x11009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_8_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x120090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_9_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x120094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_10_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x120098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_11_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x12009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_12_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x130090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_13_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x130094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_14_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x130098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_15_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x13009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_16_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x140090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_17_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x140094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_18_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x140098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_19_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x14009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_20_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x150090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_21_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x150094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_22_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x150098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_23_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x15009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_24_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x160090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_25_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x160094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_26_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x160098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_27_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x16009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_28_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x170090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_29_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x170094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_30_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x170098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_31_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x17009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_32_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x180090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_33_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x180094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_34_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x180098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_35_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x18009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_36_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x190090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_37_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x190094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_38_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x190098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_39_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x19009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_40_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_41_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_42_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_43_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_44_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_45_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_46_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_47_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_48_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_49_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_50_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_51_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_52_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_53_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_54_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_55_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_56_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_57_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_58_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_59_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_60_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_61_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0094) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_62_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0098) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_63_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F009C) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_0_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1000A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_1_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1000A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_2_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1000A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_3_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1000AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_4_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1100A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_5_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1100A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_6_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1100A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_7_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1100AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_8_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1200A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_9_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1200A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_10_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1200A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_11_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1200AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_12_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1300A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_13_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1300A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_14_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1300A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_15_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1300AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_16_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1400A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_17_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1400A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_18_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1400A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_19_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1400AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_20_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1500A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_21_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1500A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_22_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1500A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_23_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1500AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_24_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1600A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_25_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1600A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_26_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1600A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_27_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1600AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_28_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1700A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_29_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1700A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_30_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1700A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_31_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1700AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_32_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1800A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_33_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1800A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_34_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1800A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_35_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1800AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_36_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1900A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_37_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1900A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_38_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1900A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_39_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1900AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_40_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_41_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_42_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_43_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_44_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_45_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_46_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_47_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_48_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_49_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_50_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_51_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_52_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_53_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_54_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_55_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_56_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_57_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_58_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_59_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_60_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_61_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F00A4) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_62_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F00A8) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_63_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F00AC) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */

#endif // __STARS_CQINT_HOST_REG_REG_OFFSET_H__
