// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_sdma_s_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:45:16 Create file
// ******************************************************************************

#ifndef __STARS_SDMA_S_REG_REG_OFFSET_H__
#define __STARS_SDMA_S_REG_REG_OFFSET_H__

/* STARS_SDMA_S_REG Base address of Module's Register */
#define SOC_STARS_SDMA_S_REG_BASE                       (0x6c10000)

/******************************************************************************/
/*                      SOC STARS_SDMA_S_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_SDMA_S_REG_STARS_POOL_SEC_REG                   (SOC_STARS_SDMA_S_REG_BASE + 0x0)   
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_AXCACHE_SETTING_REG       (SOC_STARS_SDMA_S_REG_BASE + 0x800) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_S_AXPROT_SETTING_REG      (SOC_STARS_SDMA_S_REG_BASE + 0x804) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_NS_AXPROT_SETTING_REG     (SOC_STARS_SDMA_S_REG_BASE + 0x808) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_0_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x840) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_1_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x844) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_2_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x848) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_3_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x84C) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_4_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x850) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_5_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x854) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_6_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x858) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_ENABLE_CTRL_S_7_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x85C) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_0_REG (SOC_STARS_SDMA_S_REG_BASE + 0x880) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_1_REG (SOC_STARS_SDMA_S_REG_BASE + 0x884) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_2_REG (SOC_STARS_SDMA_S_REG_BASE + 0x888) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_3_REG (SOC_STARS_SDMA_S_REG_BASE + 0x88C) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_4_REG (SOC_STARS_SDMA_S_REG_BASE + 0x890) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_5_REG (SOC_STARS_SDMA_S_REG_BASE + 0x894) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_6_REG (SOC_STARS_SDMA_S_REG_BASE + 0x898) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_DISABLE_CTRL_S_7_REG (SOC_STARS_SDMA_S_REG_BASE + 0x89C) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS0_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8C0) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS1_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8C4) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS2_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8C8) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS3_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8CC) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS4_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8D0) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS5_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8D4) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS6_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8D8) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_POOL_STATUS7_S_REG        (SOC_STARS_SDMA_S_REG_BASE + 0x8DC) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_S_SQ_BASE_ADDR_CFG0_REG   (SOC_STARS_SDMA_S_REG_BASE + 0x900) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_S_SQ_BASE_ADDR_CFG1_REG   (SOC_STARS_SDMA_S_REG_BASE + 0x904) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_NS_SQ_BASE_ADDR_CFG0_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x908) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_NS_SQ_BASE_ADDR_CFG1_REG  (SOC_STARS_SDMA_S_REG_BASE + 0x90C) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_PTR_VAPA_CFG_REG          (SOC_STARS_SDMA_S_REG_BASE + 0x910) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_STREAMID_AUTH_CFG_REG     (SOC_STARS_SDMA_S_REG_BASE + 0x914) 
#define SOC_STARS_SDMA_S_REG_STARS_SDMA_ACSQ_OST_CFG_REG          (SOC_STARS_SDMA_S_REG_BASE + 0x918) 

#endif // __STARS_SDMA_S_REG_REG_OFFSET_H__
