/*
 * Copyright     :  Copyright (C) 2021, Huawei Technologies Co. Ltd.
 * File name     :  stars_profiling_s_cfg_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2020/04/01
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2021/07/26 20:52:02 Create file
 */

#ifndef __STARS_PROFILING_S_CFG_REG_OFFSET_FIELD_H__
#define __STARS_PROFILING_S_CFG_REG_OFFSET_FIELD_H__

#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_SIO_LEN          1
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_SIO_OFFSET       28
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_SIO_LEN          4
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_SIO_OFFSET       24
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_PA_LEN           1
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_PA_OFFSET        20
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_PA_LEN           4
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_PA_OFFSET        16
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_PCIE_LEN         1
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_PCIE_OFFSET      12
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_PCIE_LEN         4
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_PCIE_OFFSET      8
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_SCHEDULER_LEN    1
#define STARS_PROFILING_S_CFG_SOC_ARSNOOP_SCHEDULER_OFFSET 4
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_SCHEDULER_LEN    4
#define STARS_PROFILING_S_CFG_SOC_ARCACHE_SCHEDULER_OFFSET 0

#define STARS_PROFILING_S_CFG_SOC_AWSNOOP_PROF_LEN    1
#define STARS_PROFILING_S_CFG_SOC_AWSNOOP_PROF_OFFSET 12
#define STARS_PROFILING_S_CFG_SOC_AWCACHE_PROF_LEN    4
#define STARS_PROFILING_S_CFG_SOC_AWCACHE_PROF_OFFSET 8
#define STARS_PROFILING_S_CFG_SOC_AWSNOOP_LOG_LEN     1
#define STARS_PROFILING_S_CFG_SOC_AWSNOOP_LOG_OFFSET  4
#define STARS_PROFILING_S_CFG_SOC_AWCACHE_LOG_LEN     4
#define STARS_PROFILING_S_CFG_SOC_AWCACHE_LOG_OFFSET  0

#define STARS_PROFILING_S_CFG_SOC_AWNS_PROF_LEN         1
#define STARS_PROFILING_S_CFG_SOC_AWNS_PROF_OFFSET      17
#define STARS_PROFILING_S_CFG_SOC_AWNS_LOG_LEN          1
#define STARS_PROFILING_S_CFG_SOC_AWNS_LOG_OFFSET       16
#define STARS_PROFILING_S_CFG_SOC_ARNS_SIO_LEN          1
#define STARS_PROFILING_S_CFG_SOC_ARNS_SIO_OFFSET       3
#define STARS_PROFILING_S_CFG_SOC_ARNS_PA_LEN           1
#define STARS_PROFILING_S_CFG_SOC_ARNS_PA_OFFSET        2
#define STARS_PROFILING_S_CFG_SOC_ARNS_PCIE_LEN         1
#define STARS_PROFILING_S_CFG_SOC_ARNS_PCIE_OFFSET      1
#define STARS_PROFILING_S_CFG_SOC_ARNS_SCHEDULER_LEN    1
#define STARS_PROFILING_S_CFG_SOC_ARNS_SCHEDULER_OFFSET 0

#define STARS_PROFILING_S_CFG_SOC_ARPROT_SIO_LEN          3
#define STARS_PROFILING_S_CFG_SOC_ARPROT_SIO_OFFSET       9
#define STARS_PROFILING_S_CFG_SOC_ARPROT_PA_LEN           3
#define STARS_PROFILING_S_CFG_SOC_ARPROT_PA_OFFSET        6
#define STARS_PROFILING_S_CFG_SOC_ARPROT_PCIE_LEN         3
#define STARS_PROFILING_S_CFG_SOC_ARPROT_PCIE_OFFSET      3
#define STARS_PROFILING_S_CFG_SOC_ARPROT_SCHEDULER_LEN    3
#define STARS_PROFILING_S_CFG_SOC_ARPROT_SCHEDULER_OFFSET 0

#define STARS_PROFILING_S_CFG_SOC_AWPROT_PROF_LEN    3
#define STARS_PROFILING_S_CFG_SOC_AWPROT_PROF_OFFSET 3
#define STARS_PROFILING_S_CFG_SOC_AWPROT_LOG_LEN     3
#define STARS_PROFILING_S_CFG_SOC_AWPROT_LOG_OFFSET  0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_4_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_4_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_5_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_5_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_6_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_6_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_7_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_7_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_8_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_8_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_9_LEN    32
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_L_9_OFFSET 0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_4_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_4_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_4_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_5_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_5_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_5_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_6_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_6_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_6_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_7_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_7_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_7_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_8_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_8_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_8_OFFSET          0

#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_IS_VIRTUAL_9_OFFSET 17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_9_LEN             17
#define STARS_PROFILING_S_CFG_VPC_PMU_BASE_ADDR_H_9_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_S_CFG_JPEGE_PMU_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_4_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_4_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_5_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_5_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_6_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_6_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_7_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_7_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_8_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_8_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_9_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_9_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_10_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_10_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_11_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_11_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_12_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_12_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_13_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_13_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_14_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_14_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_15_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_15_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_16_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_16_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_17_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_17_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_18_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_18_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_19_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_19_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_20_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_20_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_21_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_21_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_22_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_22_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_23_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_23_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_24_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_24_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_25_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_25_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_26_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_26_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_27_LEN    32
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_L_27_OFFSET 0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_4_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_4_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_4_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_5_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_5_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_5_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_6_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_6_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_6_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_7_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_7_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_7_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_8_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_8_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_8_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_9_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_9_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_9_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_10_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_10_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_10_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_10_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_11_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_11_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_11_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_11_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_12_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_12_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_12_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_12_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_13_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_13_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_13_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_13_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_14_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_14_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_14_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_14_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_15_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_15_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_15_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_15_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_16_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_16_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_16_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_16_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_17_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_17_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_17_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_17_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_18_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_18_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_18_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_18_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_19_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_19_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_19_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_19_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_20_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_20_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_20_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_20_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_21_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_21_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_21_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_21_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_22_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_22_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_22_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_22_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_23_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_23_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_23_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_23_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_24_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_24_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_24_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_24_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_25_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_25_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_25_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_25_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_26_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_26_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_26_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_26_OFFSET          0

#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_27_LEN    1
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_IS_VIRTUAL_27_OFFSET 17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_27_LEN             17
#define STARS_PROFILING_S_CFG_JPEGD_PMU_BASE_ADDR_H_27_OFFSET          0

#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_VDEC_PMU_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_L_LEN    32
#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_L_OFFSET 0

#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_IS_VIRTUAL_OFFSET 17
#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_H_LEN             17
#define STARS_PROFILING_S_CFG_DSA_PMU_BASE_ADDR_H_OFFSET          0

#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_L_LEN    32
#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_L_OFFSET 0

#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_IS_VIRTUAL_OFFSET 17
#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_H_LEN             17
#define STARS_PROFILING_S_CFG_ROCEE_PMU_BASE_ADDR_H_OFFSET          0

#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_L_LEN    32
#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_L_OFFSET 0

#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_IS_VIRTUAL_OFFSET 17
#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_H_LEN             17
#define STARS_PROFILING_S_CFG_PCIE_PMU_BASE_ADDR_H_OFFSET          0

#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_PA_LINK_PMU_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_S_CFG_SIO_PMU_BASE_ADDR_H_1_OFFSET          0

#endif // __STARS_PROFILING_S_CFG_REG_OFFSET_FIELD_H__
