// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_rtsq_s_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:43:50 Create file
// ******************************************************************************

#ifndef __STARS_RTSQ_S_REG_REG_OFFSET_FIELD_H__
#define __STARS_RTSQ_S_REG_REG_OFFSET_FIELD_H__

#define STARS_RTSQ_S_REG_VFG_SEC_LEN    8
#define STARS_RTSQ_S_REG_VFG_SEC_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_0_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_0_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_1_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_1_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_2_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_2_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_3_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_3_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_4_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_4_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_5_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_5_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_6_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_6_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_7_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_7_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_8_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_8_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_9_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_9_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_10_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_10_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_11_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_11_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_12_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_12_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_13_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_13_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_14_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_14_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_15_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_15_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_16_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_16_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_17_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_17_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_18_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_18_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_19_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_19_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_20_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_20_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_21_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_21_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_22_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_22_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_23_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_23_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_24_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_24_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_25_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_25_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_26_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_26_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_27_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_27_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_28_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_28_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_29_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_29_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_30_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_30_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_31_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_31_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_32_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_32_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_33_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_33_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_34_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_34_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_35_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_35_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_36_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_36_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_37_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_37_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_38_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_38_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_39_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_39_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_40_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_40_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_41_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_41_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_42_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_42_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_43_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_43_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_44_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_44_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_45_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_45_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_46_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_46_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_47_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_47_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_48_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_48_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_49_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_49_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_50_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_50_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_51_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_51_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_52_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_52_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_53_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_53_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_54_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_54_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_55_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_55_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_56_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_56_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_57_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_57_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_58_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_58_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_59_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_59_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_60_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_60_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_61_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_61_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_62_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_62_OFFSET 0

#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_63_LEN    32
#define STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_63_OFFSET 0

#define STARS_RTSQ_S_REG_NS_SQ_ARPROT_SWAPBUF_LEN    3
#define STARS_RTSQ_S_REG_NS_SQ_ARPROT_SWAPBUF_OFFSET 16

#define STARS_RTSQ_S_REG_S_SQ_ARPROT_SWAPBUF_LEN    3
#define STARS_RTSQ_S_REG_S_SQ_ARPROT_SWAPBUF_OFFSET 16

#define STARS_RTSQ_S_REG_ARNS_SWAPBUF_LEN    1
#define STARS_RTSQ_S_REG_ARNS_SWAPBUF_OFFSET 16

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_0_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_0_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_0_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_0_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_0_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_0_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_0_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_0_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_1_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_1_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_1_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_1_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_1_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_1_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_1_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_1_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_2_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_2_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_2_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_2_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_2_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_2_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_2_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_2_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_3_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_3_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_3_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_3_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_3_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_3_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_3_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_3_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_4_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_4_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_4_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_4_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_4_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_4_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_4_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_4_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_5_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_5_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_5_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_5_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_5_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_5_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_5_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_5_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_6_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_6_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_6_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_6_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_6_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_6_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_6_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_6_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_7_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_SDMA_S_7_OFFSET    24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_7_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_AICPU_S_7_OFFSET   16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_7_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_PCIEDMA_S_7_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_7_LEN       7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_FFTS_S_7_OFFSET    0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_0_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_0_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_0_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_0_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_0_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_0_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_0_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_0_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_1_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_1_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_1_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_1_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_1_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_1_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_1_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_1_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_2_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_2_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_2_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_2_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_2_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_2_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_2_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_2_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_3_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_3_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_3_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_3_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_3_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_3_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_3_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_3_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_4_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_4_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_4_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_4_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_4_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_4_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_4_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_4_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_5_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_5_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_5_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_5_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_5_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_5_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_5_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_5_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_6_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_6_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_6_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_6_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_6_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_6_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_6_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_6_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_7_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_DSA_S_7_OFFSET   24
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_7_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGE_S_7_OFFSET 16
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_7_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_JPEGD_S_7_OFFSET 8
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_7_LEN      7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_VPC_S_7_OFFSET   0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_0_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_0_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_1_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_1_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_2_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_2_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_3_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_3_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_4_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_4_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_5_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_5_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_6_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_6_OFFSET 0

#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_7_LEN    7
#define STARS_RTSQ_S_REG_RTSQ_SWAPIN_MAX_CONDS_S_7_OFFSET 0

#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_BASE_ADDR_L_LEN    32
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_BASE_ADDR_L_OFFSET 0

#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_IS_VIRTUAL_LEN     1
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_IS_VIRTUAL_OFFSET  31
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_SHIFT_LEN          6
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_SHIFT_OFFSET       17
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_BASE_ADDR_H_LEN    17
#define STARS_RTSQ_S_REG_S_SQ_SWAP_BUF_BASE_ADDR_H_OFFSET 0

#endif // __STARS_RTSQ_S_REG_REG_OFFSET_FIELD_H__
