// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_jpeg_ns_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 09:44:36 Create file
// ******************************************************************************

#ifndef __STARS_JPEG_NS_REG_OFFSET_FIELD_H__
#define __STARS_JPEG_NS_REG_OFFSET_FIELD_H__

#define STARS_JPEG_NS_SP_LEVEL_LEN    3
#define STARS_JPEG_NS_SP_LEVEL_OFFSET 8
#define STARS_JPEG_NS_LP_MODE_LEN     3
#define STARS_JPEG_NS_LP_MODE_OFFSET  0



#define STARS_JPEG_NS_WRR_WEIGHT3_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT3_OFFSET 24
#define STARS_JPEG_NS_WRR_WEIGHT2_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT2_OFFSET 16
#define STARS_JPEG_NS_WRR_WEIGHT1_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT1_OFFSET 8
#define STARS_JPEG_NS_WRR_WEIGHT0_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT0_OFFSET 0

#define STARS_JPEG_NS_WRR_WEIGHT7_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT7_OFFSET 24
#define STARS_JPEG_NS_WRR_WEIGHT6_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT6_OFFSET 16
#define STARS_JPEG_NS_WRR_WEIGHT5_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT5_OFFSET 8
#define STARS_JPEG_NS_WRR_WEIGHT4_LEN    8
#define STARS_JPEG_NS_WRR_WEIGHT4_OFFSET 0

#define STARS_JPEG_NS_SQ_FRIENDLY_JPEGD_LEN    1
#define STARS_JPEG_NS_SQ_FRIENDLY_JPEGD_OFFSET 16
#define STARS_JPEG_NS_SQ_FRIENDLY_JPEGE_LEN    1
#define STARS_JPEG_NS_SQ_FRIENDLY_JPEGE_OFFSET 15

#define STARS_JPEG_NS_DFX_JPEG_FSM_SEL_LEN    5
#define STARS_JPEG_NS_DFX_JPEG_FSM_SEL_OFFSET 0

#define STARS_JPEG_NS_DFX_JPEG_FSM_OST_CNT_LEN    2
#define STARS_JPEG_NS_DFX_JPEG_FSM_OST_CNT_OFFSET 8
#define STARS_JPEG_NS_DFX_JPEG_FSM_STATE_LEN      5
#define STARS_JPEG_NS_DFX_JPEG_FSM_STATE_OFFSET   0

#define STARS_JPEG_NS_JPEG_REDUNDANT_RSP_LEN    28
#define STARS_JPEG_NS_JPEG_REDUNDANT_RSP_OFFSET 0

#define STARS_JPEG_NS_JPEG_FREE_BITMAP_LEN    28
#define STARS_JPEG_NS_JPEG_FREE_BITMAP_OFFSET 0

#define STARS_JPEG_NS_DFX_JPEG_CNT_ENABLE_LEN    1
#define STARS_JPEG_NS_DFX_JPEG_CNT_ENABLE_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_0_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_1_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_2_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_3_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_4_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_5_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_6_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_7_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLE_CTRL_NS_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_0_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_1_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_2_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_3_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_4_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_5_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_6_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_7_LEN    28
#define STARS_JPEG_NS_JPEG_DISABLE_CTRL_NS_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS0_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS1_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS1_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS2_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS2_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS3_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS3_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS4_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS4_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS5_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS5_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS6_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS6_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_ENABLED_STATUS7_NS_LEN    28
#define STARS_JPEG_NS_JPEG_ENABLED_STATUS7_NS_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_0_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_1_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_2_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_3_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_4_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_5_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_6_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_7_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_8_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_8_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_9_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_9_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_10_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_10_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_11_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_11_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_12_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_12_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_13_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_13_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_14_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_14_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_15_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_15_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_16_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_16_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_17_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_17_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_18_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_18_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_19_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_19_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_20_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_20_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_21_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_21_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_22_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_22_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_23_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_23_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_24_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_24_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_25_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_25_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_26_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_26_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_27_LEN    32
#define STARS_JPEG_NS_JPEG_BASE_ADDR_LOW_27_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_0_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_1_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_2_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_3_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_4_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_5_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_6_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_7_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_8_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_8_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_9_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_9_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_10_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_10_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_11_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_11_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_12_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_12_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_13_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_13_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_14_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_14_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_15_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_15_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_16_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_16_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_17_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_17_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_18_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_18_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_19_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_19_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_20_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_20_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_21_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_21_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_22_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_22_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_23_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_23_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_24_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_24_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_25_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_25_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_26_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_26_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_27_LEN    17
#define STARS_JPEG_NS_JPEG_BASE_ADDR_HIGH_27_OFFSET 0

#define STARS_JPEG_NS_JPEG_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_JPEG_NS_JPEG_BASE_ADDR_IS_VIRTUAL_OFFSET 0

#define STARS_JPEG_NS_ADDR_SEC_LOCKER_LEN    32
#define STARS_JPEG_NS_ADDR_SEC_LOCKER_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_0_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_1_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_2_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_3_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_4_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_5_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_6_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_7_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_8_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_8_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_9_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_9_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_10_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_10_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_11_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_11_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_12_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_12_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_13_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_13_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_14_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_14_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_15_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_15_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_16_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_16_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_17_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_17_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_18_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_18_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_19_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_19_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_20_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_20_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_21_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_21_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_22_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_22_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_23_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_23_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_24_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_24_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_25_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_25_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_26_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_26_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_27_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT0_27_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_0_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_1_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_2_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_3_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_4_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_5_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_6_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_7_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_8_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_8_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_9_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_9_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_10_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_10_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_11_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_11_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_12_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_12_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_13_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_13_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_14_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_14_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_15_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_15_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_16_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_16_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_17_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_17_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_18_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_18_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_19_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_19_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_20_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_20_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_21_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_21_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_22_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_22_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_23_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_23_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_24_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_24_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_25_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_25_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_26_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_26_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_27_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_INIT1_27_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_0_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_0_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_1_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_1_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_2_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_2_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_3_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_3_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_4_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_4_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_5_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_5_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_6_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_6_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_7_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_7_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_8_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_8_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_9_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_9_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_10_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_10_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_11_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_11_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_12_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_12_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_13_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_13_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_14_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_14_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_15_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_15_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_16_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_16_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_17_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_17_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_18_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_18_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_19_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_19_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_20_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_20_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_21_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_21_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_22_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_22_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_23_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_23_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_24_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_24_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_25_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_25_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_26_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_26_OFFSET 0

#define STARS_JPEG_NS_JPEG_CMDLST_KICK_27_LEN    32
#define STARS_JPEG_NS_JPEG_CMDLST_KICK_27_OFFSET 0

#endif // __STARS_JPEG_NS_REG_OFFSET_FIELD_H__
