// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:36:47 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_ACSQINT_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_MASK0_LEN        1
#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_MASK0_OFFSET     2
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_MASK0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_MASK0_OFFSET 1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_MASK0_LEN     1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_MASK0_OFFSET  0

#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_MASK0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_MASK0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_MASK0_LEN       1
#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_MASK0_OFFSET    4
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_MASK0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_MASK0_OFFSET 3
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_MASK0_LEN          1
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_MASK0_OFFSET       2
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_MASK0_LEN          1
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_MASK0_OFFSET       1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_MASK0_LEN         1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_MASK0_OFFSET      0

#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_STATUS0_LEN        1
#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_STATUS0_OFFSET     2
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_STATUS0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_STATUS0_OFFSET 1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_STATUS0_LEN     1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_STATUS0_OFFSET  0

#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_STATUS0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_STATUS0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_STATUS0_LEN       1
#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_STATUS0_OFFSET    4
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_STATUS0_LEN    1
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_STATUS0_OFFSET 3
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_STATUS0_LEN          1
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_STATUS0_OFFSET       2
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_STATUS0_LEN          1
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_STATUS0_OFFSET       1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_STATUS0_LEN         1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_STATUS0_OFFSET      0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR0_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_MASK1_LEN        1
#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_MASK1_OFFSET     2
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_MASK1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_MASK1_OFFSET 1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_MASK1_LEN     1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_MASK1_OFFSET  0

#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_MASK1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_MASK1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_MASK1_LEN       1
#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_MASK1_OFFSET    4
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_MASK1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_MASK1_OFFSET 3
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_MASK1_LEN          1
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_MASK1_OFFSET       2
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_MASK1_LEN          1
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_MASK1_OFFSET       1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_MASK1_LEN         1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_MASK1_OFFSET      0

#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_STATUS1_LEN        1
#define STARS_ACSQINT_NS_REG_L1_CQ_FULL_NS_STATUS1_OFFSET     2
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_STATUS1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_POST_PAUSED_NS_STATUS1_OFFSET 1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_STATUS1_LEN     1
#define STARS_ACSQINT_NS_REG_L1_PRE_PAUSED_NS_STATUS1_OFFSET  0

#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_STATUS1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_TASK_DEBUG_NS_STATUS1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_STATUS1_LEN       1
#define STARS_ACSQINT_NS_REG_L1_SQ_SEC_ERROR_NS_STATUS1_OFFSET    4
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_STATUS1_LEN    1
#define STARS_ACSQINT_NS_REG_L1_SW_STATUS_ERROR_NS_STATUS1_OFFSET 3
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_STATUS1_LEN          1
#define STARS_ACSQINT_NS_REG_L1_SQE_ERROR_NS_STATUS1_OFFSET       2
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_STATUS1_LEN          1
#define STARS_ACSQINT_NS_REG_L1_TASK_TRAP_NS_STATUS1_OFFSET       1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_STATUS1_LEN         1
#define STARS_ACSQINT_NS_REG_L1_TASK_ERROR_NS_STATUS1_OFFSET      0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_RAW1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_STS1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_PRE_PAUSED_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_POST_PAUSED_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_CQ_FULL_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_DEBUG_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_ERROR_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_TASK_TRAP_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQE_ERROR_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SW_STATUS_ERROR_NS_CLR1_3_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_0_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_0_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_1_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_1_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_2_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_2_OFFSET 0

#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_3_LEN    32
#define STARS_ACSQINT_NS_REG_L2_SQ_SEC_ERROR_NS_CLR1_3_OFFSET 0

#endif // __STARS_ACSQINT_NS_REG_REG_OFFSET_FIELD_H__
