// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_shim_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1.0
// Date          :  2003/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/12/04 10:42:26 Create file
// ******************************************************************************

#ifndef __STARS_SHIM_REG_REG_OFFSET_FIELD_H__
#define __STARS_SHIM_REG_REG_OFFSET_FIELD_H__

#define STARS_SHIM_REG_AWADDR_EXT_STARS_LEN    32
#define STARS_SHIM_REG_AWADDR_EXT_STARS_OFFSET 0

#define STARS_SHIM_REG_ARADDR_EXT_STARS_LEN    32
#define STARS_SHIM_REG_ARADDR_EXT_STARS_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_0_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_0_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_1_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_1_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_2_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_2_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_3_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_3_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_4_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_4_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_5_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_5_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_6_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_6_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_7_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_7_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_8_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_8_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_9_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_9_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_10_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_10_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_11_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_11_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_12_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_12_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_13_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_13_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_14_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_14_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_15_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_15_OFFSET 0

#define STARS_SHIM_REG_SHIM_CTRL_STARS_16_LEN    32
#define STARS_SHIM_REG_SHIM_CTRL_STARS_16_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_0_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_0_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_0_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_0_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_1_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_1_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_1_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_1_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_2_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_2_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_2_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_2_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_3_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_3_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_3_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_3_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_4_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_4_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_4_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_4_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_5_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_5_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_5_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_5_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_6_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_6_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_6_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_6_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_7_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_7_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_7_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_7_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_8_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_8_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_8_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_8_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_9_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_9_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_9_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_9_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_10_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_10_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_10_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_10_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_11_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_11_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_11_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_11_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_12_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_12_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_12_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_12_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_13_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_13_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_13_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_13_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_14_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_14_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_14_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_14_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_15_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_15_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_15_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_15_OFFSET 0

#define STARS_SHIM_REG_AWCACHE_STARS_16_LEN    4
#define STARS_SHIM_REG_AWCACHE_STARS_16_OFFSET 4
#define STARS_SHIM_REG_ARCACHE_STARS_16_LEN    4
#define STARS_SHIM_REG_ARCACHE_STARS_16_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC00_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN00_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES00_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC01_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN01_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES01_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC02_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN02_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES02_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC03_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN03_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES03_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC04_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN04_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES04_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC05_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN05_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES05_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC06_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN06_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES06_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC07_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN07_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES07_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC08_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN08_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES08_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC09_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN09_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES09_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC10_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN10_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES10_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC11_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN11_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES11_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC12_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN12_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES12_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC13_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN13_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES13_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC14_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN14_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES14_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_SRC15_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_SRC15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_LEN15_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_ARADDR_LEN15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_ARADDR_DES15_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_ARADDR_DES15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC00_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN00_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES00_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES00_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC01_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN01_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES01_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES01_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC02_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN02_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES02_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES02_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC03_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN03_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES03_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES03_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC04_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN04_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES04_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES04_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC05_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN05_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES05_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES05_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC06_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN06_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES06_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES06_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC07_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN07_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES07_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES07_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC08_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN08_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES08_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES08_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC09_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN09_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES09_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES09_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC10_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN10_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES10_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES10_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC11_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN11_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES11_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES11_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC12_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN12_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES12_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES12_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC13_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN13_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES13_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES13_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC14_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN14_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES14_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES14_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_SRC15_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_SRC15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_LEN15_STARS_M_LEN    27
#define STARS_SHIM_REG_ATS_AWADDR_LEN15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_ATS_AWADDR_DES15_STARS_M_LEN    32
#define STARS_SHIM_REG_ATS_AWADDR_DES15_STARS_M_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_0_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_0_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_1_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_1_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_2_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_2_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_3_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_3_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_4_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_4_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_5_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_5_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_6_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_6_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_7_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_7_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_8_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_8_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_9_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_9_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_10_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_10_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_11_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_11_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_12_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_12_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_13_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_13_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_14_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_14_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_15_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_15_OFFSET 0

#define STARS_SHIM_REG_AWUSER_0_STARS_16_LEN    32
#define STARS_SHIM_REG_AWUSER_0_STARS_16_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_0_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_0_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_1_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_1_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_2_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_2_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_3_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_3_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_4_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_4_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_5_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_5_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_6_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_6_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_7_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_7_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_8_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_8_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_9_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_9_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_10_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_10_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_11_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_11_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_12_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_12_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_13_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_13_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_14_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_14_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_15_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_15_OFFSET 0

#define STARS_SHIM_REG_AWUSER_1_STARS_16_LEN    32
#define STARS_SHIM_REG_AWUSER_1_STARS_16_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_0_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_0_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_1_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_1_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_2_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_2_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_3_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_3_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_4_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_4_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_5_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_5_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_6_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_6_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_7_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_7_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_8_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_8_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_9_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_9_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_10_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_10_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_11_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_11_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_12_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_12_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_13_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_13_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_14_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_14_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_15_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_15_OFFSET 0

#define STARS_SHIM_REG_AWUSER_2_STARS_16_LEN    32
#define STARS_SHIM_REG_AWUSER_2_STARS_16_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_0_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_0_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_1_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_1_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_2_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_2_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_3_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_3_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_4_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_4_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_5_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_5_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_6_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_6_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_7_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_7_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_8_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_8_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_9_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_9_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_10_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_10_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_11_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_11_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_12_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_12_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_13_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_13_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_14_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_14_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_15_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_15_OFFSET 0

#define STARS_SHIM_REG_AWUSER_3_STARS_16_LEN    32
#define STARS_SHIM_REG_AWUSER_3_STARS_16_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_0_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_0_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_1_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_1_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_2_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_2_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_3_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_3_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_4_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_4_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_5_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_5_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_6_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_6_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_7_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_7_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_8_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_8_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_9_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_9_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_10_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_10_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_11_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_11_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_12_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_12_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_13_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_13_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_14_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_14_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_15_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_15_OFFSET 0

#define STARS_SHIM_REG_ARUSER_0_STARS_16_LEN    32
#define STARS_SHIM_REG_ARUSER_0_STARS_16_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_0_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_0_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_1_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_1_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_2_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_2_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_3_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_3_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_4_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_4_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_5_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_5_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_6_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_6_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_7_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_7_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_8_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_8_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_9_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_9_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_10_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_10_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_11_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_11_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_12_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_12_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_13_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_13_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_14_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_14_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_15_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_15_OFFSET 0

#define STARS_SHIM_REG_ARUSER_1_STARS_16_LEN    32
#define STARS_SHIM_REG_ARUSER_1_STARS_16_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_0_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_0_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_1_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_1_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_2_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_2_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_3_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_3_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_4_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_4_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_5_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_5_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_6_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_6_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_7_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_7_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_8_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_8_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_9_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_9_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_10_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_10_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_11_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_11_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_12_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_12_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_13_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_13_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_14_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_14_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_15_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_15_OFFSET 0

#define STARS_SHIM_REG_ARUSER_2_STARS_16_LEN    32
#define STARS_SHIM_REG_ARUSER_2_STARS_16_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_0_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_0_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_1_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_1_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_2_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_2_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_3_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_3_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_4_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_4_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_5_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_5_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_6_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_6_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_7_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_7_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_8_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_8_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_9_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_9_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_10_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_10_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_11_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_11_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_12_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_12_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_13_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_13_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_14_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_14_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_15_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_15_OFFSET 0

#define STARS_SHIM_REG_ARUSER_3_STARS_16_LEN    32
#define STARS_SHIM_REG_ARUSER_3_STARS_16_OFFSET 0

#endif // __STARS_SHIM_REG_REG_OFFSET_FIELD_H__
