// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_db_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2019/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:37:51 Create file
// ******************************************************************************

#ifndef __STARS_DB_REG_REG_OFFSET_FIELD_H__
#define __STARS_DB_REG_REG_OFFSET_FIELD_H__

#define STARS_DB_REG_ECC_PARITY_LEN      6
#define STARS_DB_REG_ECC_PARITY_OFFSET   16
#define STARS_DB_REG_ECC_ON_BRESP_LEN    1
#define STARS_DB_REG_ECC_ON_BRESP_OFFSET 1
#define STARS_DB_REG_ECC_BYPASS_LEN      1
#define STARS_DB_REG_ECC_BYPASS_OFFSET   0

#define STARS_DB_REG_ECC_ERR_SYN_LATCHED_LEN    6
#define STARS_DB_REG_ECC_ERR_SYN_LATCHED_OFFSET 16
#define STARS_DB_REG_ERR_ADDR_LATCHED_LEN       11
#define STARS_DB_REG_ERR_ADDR_LATCHED_OFFSET    0

#define STARS_DB_REG_ECC_2BIT_ERR_MASK_LEN    1
#define STARS_DB_REG_ECC_2BIT_ERR_MASK_OFFSET 1
#define STARS_DB_REG_ECC_1BIT_ERR_MASK_LEN    1
#define STARS_DB_REG_ECC_1BIT_ERR_MASK_OFFSET 0

#define STARS_DB_REG_ECC_2BIT_ERR_STATUS_LEN    1
#define STARS_DB_REG_ECC_2BIT_ERR_STATUS_OFFSET 1
#define STARS_DB_REG_ECC_1BIT_ERR_STATUS_LEN    1
#define STARS_DB_REG_ECC_1BIT_ERR_STATUS_OFFSET 0

#define STARS_DB_REG_DB_INT0_SUMMARY0_LEN    32
#define STARS_DB_REG_DB_INT0_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT0_SUMMARY1_LEN    32
#define STARS_DB_REG_DB_INT0_SUMMARY1_OFFSET 0

#define STARS_DB_REG_DB_INT1_SUMMARY0_LEN    32
#define STARS_DB_REG_DB_INT1_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT1_SUMMARY1_LEN    32
#define STARS_DB_REG_DB_INT1_SUMMARY1_OFFSET 0

#define STARS_DB_REG_DB_INT2_SUMMARY0_LEN    32
#define STARS_DB_REG_DB_INT2_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT2_SUMMARY1_LEN    32
#define STARS_DB_REG_DB_INT2_SUMMARY1_OFFSET 0

#define STARS_DB_REG_DB_INT3_SUMMARY0_LEN    32
#define STARS_DB_REG_DB_INT3_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT3_SUMMARY1_LEN    32
#define STARS_DB_REG_DB_INT3_SUMMARY1_OFFSET 0

#define STARS_DB_REG_DB_SEC_EN_LEN    1
#define STARS_DB_REG_DB_SEC_EN_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS0_LEN    32
#define STARS_DB_REG_DB_INT_STATUS0_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS1_LEN    32
#define STARS_DB_REG_DB_INT_STATUS1_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS2_LEN    32
#define STARS_DB_REG_DB_INT_STATUS2_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS3_LEN    32
#define STARS_DB_REG_DB_INT_STATUS3_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS4_LEN    32
#define STARS_DB_REG_DB_INT_STATUS4_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS5_LEN    32
#define STARS_DB_REG_DB_INT_STATUS5_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS6_LEN    32
#define STARS_DB_REG_DB_INT_STATUS6_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS7_LEN    32
#define STARS_DB_REG_DB_INT_STATUS7_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS8_LEN    32
#define STARS_DB_REG_DB_INT_STATUS8_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS9_LEN    32
#define STARS_DB_REG_DB_INT_STATUS9_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS10_LEN    32
#define STARS_DB_REG_DB_INT_STATUS10_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS11_LEN    32
#define STARS_DB_REG_DB_INT_STATUS11_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS12_LEN    32
#define STARS_DB_REG_DB_INT_STATUS12_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS13_LEN    32
#define STARS_DB_REG_DB_INT_STATUS13_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS14_LEN    32
#define STARS_DB_REG_DB_INT_STATUS14_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS15_LEN    32
#define STARS_DB_REG_DB_INT_STATUS15_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS16_LEN    32
#define STARS_DB_REG_DB_INT_STATUS16_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS17_LEN    32
#define STARS_DB_REG_DB_INT_STATUS17_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS18_LEN    32
#define STARS_DB_REG_DB_INT_STATUS18_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS19_LEN    32
#define STARS_DB_REG_DB_INT_STATUS19_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS20_LEN    32
#define STARS_DB_REG_DB_INT_STATUS20_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS21_LEN    32
#define STARS_DB_REG_DB_INT_STATUS21_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS22_LEN    32
#define STARS_DB_REG_DB_INT_STATUS22_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS23_LEN    32
#define STARS_DB_REG_DB_INT_STATUS23_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS24_LEN    32
#define STARS_DB_REG_DB_INT_STATUS24_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS25_LEN    32
#define STARS_DB_REG_DB_INT_STATUS25_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS26_LEN    32
#define STARS_DB_REG_DB_INT_STATUS26_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS27_LEN    32
#define STARS_DB_REG_DB_INT_STATUS27_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS28_LEN    32
#define STARS_DB_REG_DB_INT_STATUS28_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS29_LEN    32
#define STARS_DB_REG_DB_INT_STATUS29_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS30_LEN    32
#define STARS_DB_REG_DB_INT_STATUS30_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS31_LEN    32
#define STARS_DB_REG_DB_INT_STATUS31_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS32_LEN    32
#define STARS_DB_REG_DB_INT_STATUS32_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS33_LEN    32
#define STARS_DB_REG_DB_INT_STATUS33_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS34_LEN    32
#define STARS_DB_REG_DB_INT_STATUS34_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS35_LEN    32
#define STARS_DB_REG_DB_INT_STATUS35_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS36_LEN    32
#define STARS_DB_REG_DB_INT_STATUS36_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS37_LEN    32
#define STARS_DB_REG_DB_INT_STATUS37_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS38_LEN    32
#define STARS_DB_REG_DB_INT_STATUS38_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS39_LEN    32
#define STARS_DB_REG_DB_INT_STATUS39_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS40_LEN    32
#define STARS_DB_REG_DB_INT_STATUS40_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS41_LEN    32
#define STARS_DB_REG_DB_INT_STATUS41_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS42_LEN    32
#define STARS_DB_REG_DB_INT_STATUS42_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS43_LEN    32
#define STARS_DB_REG_DB_INT_STATUS43_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS44_LEN    32
#define STARS_DB_REG_DB_INT_STATUS44_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS45_LEN    32
#define STARS_DB_REG_DB_INT_STATUS45_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS46_LEN    32
#define STARS_DB_REG_DB_INT_STATUS46_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS47_LEN    32
#define STARS_DB_REG_DB_INT_STATUS47_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS48_LEN    32
#define STARS_DB_REG_DB_INT_STATUS48_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS49_LEN    32
#define STARS_DB_REG_DB_INT_STATUS49_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS50_LEN    32
#define STARS_DB_REG_DB_INT_STATUS50_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS51_LEN    32
#define STARS_DB_REG_DB_INT_STATUS51_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS52_LEN    32
#define STARS_DB_REG_DB_INT_STATUS52_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS53_LEN    32
#define STARS_DB_REG_DB_INT_STATUS53_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS54_LEN    32
#define STARS_DB_REG_DB_INT_STATUS54_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS55_LEN    32
#define STARS_DB_REG_DB_INT_STATUS55_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS56_LEN    32
#define STARS_DB_REG_DB_INT_STATUS56_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS57_LEN    32
#define STARS_DB_REG_DB_INT_STATUS57_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS58_LEN    32
#define STARS_DB_REG_DB_INT_STATUS58_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS59_LEN    32
#define STARS_DB_REG_DB_INT_STATUS59_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS60_LEN    32
#define STARS_DB_REG_DB_INT_STATUS60_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS61_LEN    32
#define STARS_DB_REG_DB_INT_STATUS61_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS62_LEN    32
#define STARS_DB_REG_DB_INT_STATUS62_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS63_LEN    32
#define STARS_DB_REG_DB_INT_STATUS63_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK0_LEN    32
#define STARS_DB_REG_DB_INT0_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK1_LEN    32
#define STARS_DB_REG_DB_INT0_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK2_LEN    32
#define STARS_DB_REG_DB_INT0_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK3_LEN    32
#define STARS_DB_REG_DB_INT0_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK4_LEN    32
#define STARS_DB_REG_DB_INT0_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK5_LEN    32
#define STARS_DB_REG_DB_INT0_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK6_LEN    32
#define STARS_DB_REG_DB_INT0_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK7_LEN    32
#define STARS_DB_REG_DB_INT0_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK8_LEN    32
#define STARS_DB_REG_DB_INT0_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK9_LEN    32
#define STARS_DB_REG_DB_INT0_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK10_LEN    32
#define STARS_DB_REG_DB_INT0_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK11_LEN    32
#define STARS_DB_REG_DB_INT0_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK12_LEN    32
#define STARS_DB_REG_DB_INT0_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK13_LEN    32
#define STARS_DB_REG_DB_INT0_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK14_LEN    32
#define STARS_DB_REG_DB_INT0_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK15_LEN    32
#define STARS_DB_REG_DB_INT0_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK16_LEN    32
#define STARS_DB_REG_DB_INT0_MASK16_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK17_LEN    32
#define STARS_DB_REG_DB_INT0_MASK17_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK18_LEN    32
#define STARS_DB_REG_DB_INT0_MASK18_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK19_LEN    32
#define STARS_DB_REG_DB_INT0_MASK19_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK20_LEN    32
#define STARS_DB_REG_DB_INT0_MASK20_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK21_LEN    32
#define STARS_DB_REG_DB_INT0_MASK21_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK22_LEN    32
#define STARS_DB_REG_DB_INT0_MASK22_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK23_LEN    32
#define STARS_DB_REG_DB_INT0_MASK23_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK24_LEN    32
#define STARS_DB_REG_DB_INT0_MASK24_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK25_LEN    32
#define STARS_DB_REG_DB_INT0_MASK25_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK26_LEN    32
#define STARS_DB_REG_DB_INT0_MASK26_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK27_LEN    32
#define STARS_DB_REG_DB_INT0_MASK27_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK28_LEN    32
#define STARS_DB_REG_DB_INT0_MASK28_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK29_LEN    32
#define STARS_DB_REG_DB_INT0_MASK29_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK30_LEN    32
#define STARS_DB_REG_DB_INT0_MASK30_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK31_LEN    32
#define STARS_DB_REG_DB_INT0_MASK31_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK32_LEN    32
#define STARS_DB_REG_DB_INT0_MASK32_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK33_LEN    32
#define STARS_DB_REG_DB_INT0_MASK33_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK34_LEN    32
#define STARS_DB_REG_DB_INT0_MASK34_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK35_LEN    32
#define STARS_DB_REG_DB_INT0_MASK35_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK36_LEN    32
#define STARS_DB_REG_DB_INT0_MASK36_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK37_LEN    32
#define STARS_DB_REG_DB_INT0_MASK37_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK38_LEN    32
#define STARS_DB_REG_DB_INT0_MASK38_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK39_LEN    32
#define STARS_DB_REG_DB_INT0_MASK39_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK40_LEN    32
#define STARS_DB_REG_DB_INT0_MASK40_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK41_LEN    32
#define STARS_DB_REG_DB_INT0_MASK41_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK42_LEN    32
#define STARS_DB_REG_DB_INT0_MASK42_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK43_LEN    32
#define STARS_DB_REG_DB_INT0_MASK43_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK44_LEN    32
#define STARS_DB_REG_DB_INT0_MASK44_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK45_LEN    32
#define STARS_DB_REG_DB_INT0_MASK45_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK46_LEN    32
#define STARS_DB_REG_DB_INT0_MASK46_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK47_LEN    32
#define STARS_DB_REG_DB_INT0_MASK47_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK48_LEN    32
#define STARS_DB_REG_DB_INT0_MASK48_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK49_LEN    32
#define STARS_DB_REG_DB_INT0_MASK49_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK50_LEN    32
#define STARS_DB_REG_DB_INT0_MASK50_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK51_LEN    32
#define STARS_DB_REG_DB_INT0_MASK51_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK52_LEN    32
#define STARS_DB_REG_DB_INT0_MASK52_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK53_LEN    32
#define STARS_DB_REG_DB_INT0_MASK53_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK54_LEN    32
#define STARS_DB_REG_DB_INT0_MASK54_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK55_LEN    32
#define STARS_DB_REG_DB_INT0_MASK55_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK56_LEN    32
#define STARS_DB_REG_DB_INT0_MASK56_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK57_LEN    32
#define STARS_DB_REG_DB_INT0_MASK57_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK58_LEN    32
#define STARS_DB_REG_DB_INT0_MASK58_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK59_LEN    32
#define STARS_DB_REG_DB_INT0_MASK59_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK60_LEN    32
#define STARS_DB_REG_DB_INT0_MASK60_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK61_LEN    32
#define STARS_DB_REG_DB_INT0_MASK61_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK62_LEN    32
#define STARS_DB_REG_DB_INT0_MASK62_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK63_LEN    32
#define STARS_DB_REG_DB_INT0_MASK63_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK0_LEN    32
#define STARS_DB_REG_DB_INT1_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK1_LEN    32
#define STARS_DB_REG_DB_INT1_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK2_LEN    32
#define STARS_DB_REG_DB_INT1_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK3_LEN    32
#define STARS_DB_REG_DB_INT1_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK4_LEN    32
#define STARS_DB_REG_DB_INT1_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK5_LEN    32
#define STARS_DB_REG_DB_INT1_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK6_LEN    32
#define STARS_DB_REG_DB_INT1_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK7_LEN    32
#define STARS_DB_REG_DB_INT1_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK8_LEN    32
#define STARS_DB_REG_DB_INT1_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK9_LEN    32
#define STARS_DB_REG_DB_INT1_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK10_LEN    32
#define STARS_DB_REG_DB_INT1_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK11_LEN    32
#define STARS_DB_REG_DB_INT1_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK12_LEN    32
#define STARS_DB_REG_DB_INT1_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK13_LEN    32
#define STARS_DB_REG_DB_INT1_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK14_LEN    32
#define STARS_DB_REG_DB_INT1_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK15_LEN    32
#define STARS_DB_REG_DB_INT1_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK16_LEN    32
#define STARS_DB_REG_DB_INT1_MASK16_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK17_LEN    32
#define STARS_DB_REG_DB_INT1_MASK17_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK18_LEN    32
#define STARS_DB_REG_DB_INT1_MASK18_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK19_LEN    32
#define STARS_DB_REG_DB_INT1_MASK19_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK20_LEN    32
#define STARS_DB_REG_DB_INT1_MASK20_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK21_LEN    32
#define STARS_DB_REG_DB_INT1_MASK21_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK22_LEN    32
#define STARS_DB_REG_DB_INT1_MASK22_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK23_LEN    32
#define STARS_DB_REG_DB_INT1_MASK23_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK24_LEN    32
#define STARS_DB_REG_DB_INT1_MASK24_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK25_LEN    32
#define STARS_DB_REG_DB_INT1_MASK25_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK26_LEN    32
#define STARS_DB_REG_DB_INT1_MASK26_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK27_LEN    32
#define STARS_DB_REG_DB_INT1_MASK27_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK28_LEN    32
#define STARS_DB_REG_DB_INT1_MASK28_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK29_LEN    32
#define STARS_DB_REG_DB_INT1_MASK29_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK30_LEN    32
#define STARS_DB_REG_DB_INT1_MASK30_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK31_LEN    32
#define STARS_DB_REG_DB_INT1_MASK31_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK32_LEN    32
#define STARS_DB_REG_DB_INT1_MASK32_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK33_LEN    32
#define STARS_DB_REG_DB_INT1_MASK33_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK34_LEN    32
#define STARS_DB_REG_DB_INT1_MASK34_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK35_LEN    32
#define STARS_DB_REG_DB_INT1_MASK35_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK36_LEN    32
#define STARS_DB_REG_DB_INT1_MASK36_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK37_LEN    32
#define STARS_DB_REG_DB_INT1_MASK37_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK38_LEN    32
#define STARS_DB_REG_DB_INT1_MASK38_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK39_LEN    32
#define STARS_DB_REG_DB_INT1_MASK39_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK40_LEN    32
#define STARS_DB_REG_DB_INT1_MASK40_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK41_LEN    32
#define STARS_DB_REG_DB_INT1_MASK41_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK42_LEN    32
#define STARS_DB_REG_DB_INT1_MASK42_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK43_LEN    32
#define STARS_DB_REG_DB_INT1_MASK43_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK44_LEN    32
#define STARS_DB_REG_DB_INT1_MASK44_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK45_LEN    32
#define STARS_DB_REG_DB_INT1_MASK45_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK46_LEN    32
#define STARS_DB_REG_DB_INT1_MASK46_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK47_LEN    32
#define STARS_DB_REG_DB_INT1_MASK47_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK48_LEN    32
#define STARS_DB_REG_DB_INT1_MASK48_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK49_LEN    32
#define STARS_DB_REG_DB_INT1_MASK49_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK50_LEN    32
#define STARS_DB_REG_DB_INT1_MASK50_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK51_LEN    32
#define STARS_DB_REG_DB_INT1_MASK51_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK52_LEN    32
#define STARS_DB_REG_DB_INT1_MASK52_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK53_LEN    32
#define STARS_DB_REG_DB_INT1_MASK53_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK54_LEN    32
#define STARS_DB_REG_DB_INT1_MASK54_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK55_LEN    32
#define STARS_DB_REG_DB_INT1_MASK55_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK56_LEN    32
#define STARS_DB_REG_DB_INT1_MASK56_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK57_LEN    32
#define STARS_DB_REG_DB_INT1_MASK57_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK58_LEN    32
#define STARS_DB_REG_DB_INT1_MASK58_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK59_LEN    32
#define STARS_DB_REG_DB_INT1_MASK59_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK60_LEN    32
#define STARS_DB_REG_DB_INT1_MASK60_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK61_LEN    32
#define STARS_DB_REG_DB_INT1_MASK61_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK62_LEN    32
#define STARS_DB_REG_DB_INT1_MASK62_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK63_LEN    32
#define STARS_DB_REG_DB_INT1_MASK63_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK0_LEN    32
#define STARS_DB_REG_DB_INT2_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK1_LEN    32
#define STARS_DB_REG_DB_INT2_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK2_LEN    32
#define STARS_DB_REG_DB_INT2_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK3_LEN    32
#define STARS_DB_REG_DB_INT2_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK4_LEN    32
#define STARS_DB_REG_DB_INT2_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK5_LEN    32
#define STARS_DB_REG_DB_INT2_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK6_LEN    32
#define STARS_DB_REG_DB_INT2_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK7_LEN    32
#define STARS_DB_REG_DB_INT2_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK8_LEN    32
#define STARS_DB_REG_DB_INT2_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK9_LEN    32
#define STARS_DB_REG_DB_INT2_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK10_LEN    32
#define STARS_DB_REG_DB_INT2_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK11_LEN    32
#define STARS_DB_REG_DB_INT2_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK12_LEN    32
#define STARS_DB_REG_DB_INT2_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK13_LEN    32
#define STARS_DB_REG_DB_INT2_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK14_LEN    32
#define STARS_DB_REG_DB_INT2_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK15_LEN    32
#define STARS_DB_REG_DB_INT2_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK16_LEN    32
#define STARS_DB_REG_DB_INT2_MASK16_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK17_LEN    32
#define STARS_DB_REG_DB_INT2_MASK17_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK18_LEN    32
#define STARS_DB_REG_DB_INT2_MASK18_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK19_LEN    32
#define STARS_DB_REG_DB_INT2_MASK19_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK20_LEN    32
#define STARS_DB_REG_DB_INT2_MASK20_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK21_LEN    32
#define STARS_DB_REG_DB_INT2_MASK21_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK22_LEN    32
#define STARS_DB_REG_DB_INT2_MASK22_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK23_LEN    32
#define STARS_DB_REG_DB_INT2_MASK23_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK24_LEN    32
#define STARS_DB_REG_DB_INT2_MASK24_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK25_LEN    32
#define STARS_DB_REG_DB_INT2_MASK25_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK26_LEN    32
#define STARS_DB_REG_DB_INT2_MASK26_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK27_LEN    32
#define STARS_DB_REG_DB_INT2_MASK27_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK28_LEN    32
#define STARS_DB_REG_DB_INT2_MASK28_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK29_LEN    32
#define STARS_DB_REG_DB_INT2_MASK29_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK30_LEN    32
#define STARS_DB_REG_DB_INT2_MASK30_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK31_LEN    32
#define STARS_DB_REG_DB_INT2_MASK31_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK32_LEN    32
#define STARS_DB_REG_DB_INT2_MASK32_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK33_LEN    32
#define STARS_DB_REG_DB_INT2_MASK33_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK34_LEN    32
#define STARS_DB_REG_DB_INT2_MASK34_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK35_LEN    32
#define STARS_DB_REG_DB_INT2_MASK35_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK36_LEN    32
#define STARS_DB_REG_DB_INT2_MASK36_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK37_LEN    32
#define STARS_DB_REG_DB_INT2_MASK37_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK38_LEN    32
#define STARS_DB_REG_DB_INT2_MASK38_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK39_LEN    32
#define STARS_DB_REG_DB_INT2_MASK39_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK40_LEN    32
#define STARS_DB_REG_DB_INT2_MASK40_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK41_LEN    32
#define STARS_DB_REG_DB_INT2_MASK41_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK42_LEN    32
#define STARS_DB_REG_DB_INT2_MASK42_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK43_LEN    32
#define STARS_DB_REG_DB_INT2_MASK43_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK44_LEN    32
#define STARS_DB_REG_DB_INT2_MASK44_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK45_LEN    32
#define STARS_DB_REG_DB_INT2_MASK45_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK46_LEN    32
#define STARS_DB_REG_DB_INT2_MASK46_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK47_LEN    32
#define STARS_DB_REG_DB_INT2_MASK47_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK48_LEN    32
#define STARS_DB_REG_DB_INT2_MASK48_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK49_LEN    32
#define STARS_DB_REG_DB_INT2_MASK49_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK50_LEN    32
#define STARS_DB_REG_DB_INT2_MASK50_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK51_LEN    32
#define STARS_DB_REG_DB_INT2_MASK51_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK52_LEN    32
#define STARS_DB_REG_DB_INT2_MASK52_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK53_LEN    32
#define STARS_DB_REG_DB_INT2_MASK53_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK54_LEN    32
#define STARS_DB_REG_DB_INT2_MASK54_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK55_LEN    32
#define STARS_DB_REG_DB_INT2_MASK55_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK56_LEN    32
#define STARS_DB_REG_DB_INT2_MASK56_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK57_LEN    32
#define STARS_DB_REG_DB_INT2_MASK57_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK58_LEN    32
#define STARS_DB_REG_DB_INT2_MASK58_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK59_LEN    32
#define STARS_DB_REG_DB_INT2_MASK59_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK60_LEN    32
#define STARS_DB_REG_DB_INT2_MASK60_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK61_LEN    32
#define STARS_DB_REG_DB_INT2_MASK61_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK62_LEN    32
#define STARS_DB_REG_DB_INT2_MASK62_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK63_LEN    32
#define STARS_DB_REG_DB_INT2_MASK63_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK0_LEN    32
#define STARS_DB_REG_DB_INT3_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK1_LEN    32
#define STARS_DB_REG_DB_INT3_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK2_LEN    32
#define STARS_DB_REG_DB_INT3_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK3_LEN    32
#define STARS_DB_REG_DB_INT3_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK4_LEN    32
#define STARS_DB_REG_DB_INT3_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK5_LEN    32
#define STARS_DB_REG_DB_INT3_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK6_LEN    32
#define STARS_DB_REG_DB_INT3_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK7_LEN    32
#define STARS_DB_REG_DB_INT3_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK8_LEN    32
#define STARS_DB_REG_DB_INT3_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK9_LEN    32
#define STARS_DB_REG_DB_INT3_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK10_LEN    32
#define STARS_DB_REG_DB_INT3_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK11_LEN    32
#define STARS_DB_REG_DB_INT3_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK12_LEN    32
#define STARS_DB_REG_DB_INT3_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK13_LEN    32
#define STARS_DB_REG_DB_INT3_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK14_LEN    32
#define STARS_DB_REG_DB_INT3_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK15_LEN    32
#define STARS_DB_REG_DB_INT3_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK16_LEN    32
#define STARS_DB_REG_DB_INT3_MASK16_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK17_LEN    32
#define STARS_DB_REG_DB_INT3_MASK17_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK18_LEN    32
#define STARS_DB_REG_DB_INT3_MASK18_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK19_LEN    32
#define STARS_DB_REG_DB_INT3_MASK19_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK20_LEN    32
#define STARS_DB_REG_DB_INT3_MASK20_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK21_LEN    32
#define STARS_DB_REG_DB_INT3_MASK21_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK22_LEN    32
#define STARS_DB_REG_DB_INT3_MASK22_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK23_LEN    32
#define STARS_DB_REG_DB_INT3_MASK23_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK24_LEN    32
#define STARS_DB_REG_DB_INT3_MASK24_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK25_LEN    32
#define STARS_DB_REG_DB_INT3_MASK25_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK26_LEN    32
#define STARS_DB_REG_DB_INT3_MASK26_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK27_LEN    32
#define STARS_DB_REG_DB_INT3_MASK27_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK28_LEN    32
#define STARS_DB_REG_DB_INT3_MASK28_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK29_LEN    32
#define STARS_DB_REG_DB_INT3_MASK29_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK30_LEN    32
#define STARS_DB_REG_DB_INT3_MASK30_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK31_LEN    32
#define STARS_DB_REG_DB_INT3_MASK31_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK32_LEN    32
#define STARS_DB_REG_DB_INT3_MASK32_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK33_LEN    32
#define STARS_DB_REG_DB_INT3_MASK33_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK34_LEN    32
#define STARS_DB_REG_DB_INT3_MASK34_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK35_LEN    32
#define STARS_DB_REG_DB_INT3_MASK35_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK36_LEN    32
#define STARS_DB_REG_DB_INT3_MASK36_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK37_LEN    32
#define STARS_DB_REG_DB_INT3_MASK37_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK38_LEN    32
#define STARS_DB_REG_DB_INT3_MASK38_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK39_LEN    32
#define STARS_DB_REG_DB_INT3_MASK39_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK40_LEN    32
#define STARS_DB_REG_DB_INT3_MASK40_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK41_LEN    32
#define STARS_DB_REG_DB_INT3_MASK41_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK42_LEN    32
#define STARS_DB_REG_DB_INT3_MASK42_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK43_LEN    32
#define STARS_DB_REG_DB_INT3_MASK43_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK44_LEN    32
#define STARS_DB_REG_DB_INT3_MASK44_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK45_LEN    32
#define STARS_DB_REG_DB_INT3_MASK45_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK46_LEN    32
#define STARS_DB_REG_DB_INT3_MASK46_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK47_LEN    32
#define STARS_DB_REG_DB_INT3_MASK47_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK48_LEN    32
#define STARS_DB_REG_DB_INT3_MASK48_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK49_LEN    32
#define STARS_DB_REG_DB_INT3_MASK49_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK50_LEN    32
#define STARS_DB_REG_DB_INT3_MASK50_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK51_LEN    32
#define STARS_DB_REG_DB_INT3_MASK51_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK52_LEN    32
#define STARS_DB_REG_DB_INT3_MASK52_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK53_LEN    32
#define STARS_DB_REG_DB_INT3_MASK53_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK54_LEN    32
#define STARS_DB_REG_DB_INT3_MASK54_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK55_LEN    32
#define STARS_DB_REG_DB_INT3_MASK55_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK56_LEN    32
#define STARS_DB_REG_DB_INT3_MASK56_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK57_LEN    32
#define STARS_DB_REG_DB_INT3_MASK57_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK58_LEN    32
#define STARS_DB_REG_DB_INT3_MASK58_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK59_LEN    32
#define STARS_DB_REG_DB_INT3_MASK59_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK60_LEN    32
#define STARS_DB_REG_DB_INT3_MASK60_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK61_LEN    32
#define STARS_DB_REG_DB_INT3_MASK61_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK62_LEN    32
#define STARS_DB_REG_DB_INT3_MASK62_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK63_LEN    32
#define STARS_DB_REG_DB_INT3_MASK63_OFFSET 0

#endif // __STARS_DB_REG_REG_OFFSET_FIELD_H__
