// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_vpc_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 09:45:53 Create file
// ******************************************************************************

#ifndef __STARS_VPC_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_VPC_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_VPC_NS_REG_SP_LEVEL_LEN    3
#define STARS_VPC_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_VPC_NS_REG_LP_MODE_LEN     3
#define STARS_VPC_NS_REG_LP_MODE_OFFSET  0



#define STARS_VPC_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_VPC_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_VPC_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_VPC_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_VPC_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_VPC_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_VPC_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_VPC_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_VPC_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_VPC_NS_REG_SQ_FRIENDLY_VPC_LEN    1
#define STARS_VPC_NS_REG_SQ_FRIENDLY_VPC_OFFSET 14

#define STARS_VPC_NS_REG_DFX_VPC_FSM_SEL_LEN    4
#define STARS_VPC_NS_REG_DFX_VPC_FSM_SEL_OFFSET 0

#define STARS_VPC_NS_REG_DFX_VPC_FSM_OST_CNT_LEN    2
#define STARS_VPC_NS_REG_DFX_VPC_FSM_OST_CNT_OFFSET 8
#define STARS_VPC_NS_REG_DFX_VPC_FSM_STATE_LEN      5
#define STARS_VPC_NS_REG_DFX_VPC_FSM_STATE_OFFSET   0

#define STARS_VPC_NS_REG_VPC_REDUNDANT_RSP_LEN    10
#define STARS_VPC_NS_REG_VPC_REDUNDANT_RSP_OFFSET 0

#define STARS_VPC_NS_REG_VPC_FREE_BITMAP_LEN    10
#define STARS_VPC_NS_REG_VPC_FREE_BITMAP_OFFSET 0

#define STARS_VPC_NS_REG_DFX_VPC_CNT_ENABLE_LEN    1
#define STARS_VPC_NS_REG_DFX_VPC_CNT_ENABLE_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_0_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_1_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_2_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_3_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_4_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_5_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_6_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_7_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLE_CTRL_NS_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_0_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_1_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_2_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_3_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_4_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_5_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_6_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_7_LEN    10
#define STARS_VPC_NS_REG_VPC_DISABLE_CTRL_NS_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS0_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS1_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS1_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS2_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS2_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS3_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS3_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS4_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS4_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS5_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS5_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS6_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS6_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS7_NS_LEN    10
#define STARS_VPC_NS_REG_VPC_ENABLED_STATUS7_NS_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_0_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_1_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_2_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_3_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_4_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_5_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_6_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_7_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_8_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_9_LEN    32
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_LOW_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_0_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_1_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_2_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_3_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_4_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_5_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_6_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_7_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_8_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_9_LEN    17
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_HIGH_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_VPC_NS_REG_VPC_BASE_ADDR_IS_VIRTUAL_OFFSET 0

#define STARS_VPC_NS_REG_ADDR_SEC_LOCKER_LEN    32
#define STARS_VPC_NS_REG_ADDR_SEC_LOCKER_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT0_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT1_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT2_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT3_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_INIT4_9_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_0_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_0_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_1_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_1_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_2_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_2_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_3_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_3_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_4_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_4_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_5_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_5_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_6_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_6_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_7_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_7_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_8_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_8_OFFSET 0

#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_9_LEN    32
#define STARS_VPC_NS_REG_VPC_CMDLST_KICK_9_OFFSET 0

#endif // __STARS_VPC_NS_REG_REG_OFFSET_FIELD_H__
