/*
 * Copyright     :  Copyright (C) 2022, Huawei Technologies Co. Ltd.
 * File name     :  stars_topic_sche_s_cfg_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2020/04/01
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2022/03/16 10:49:21 Create file
 */

#ifndef __STARS_TOPIC_SCHE_S_CFG_REG_OFFSET_FIELD_H__
#define __STARS_TOPIC_SCHE_S_CFG_REG_OFFSET_FIELD_H__

#define STARS_TOPIC_SCHE_S_CFG_CFG_POOL_SEC_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_CFG_POOL_SEC_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWSNOOP_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWSNOOP_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWCACHE_LEN    4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWCACHE_OFFSET 4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWNS_LEN       1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_AWNS_OFFSET    0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_S_SQ_AWPROT_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_S_SQ_AWPROT_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_NS_SQ_AWPROT_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_MB_NS_SQ_AWPROT_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWSNOOP_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWSNOOP_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWCACHE_LEN    4
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWCACHE_OFFSET 4
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWNS_LEN       1
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_AWNS_OFFSET    0

#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_S_SQ_AWPROT_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_S_SQ_AWPROT_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_NS_SQ_AWPROT_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_HOST_MB_NS_SQ_AWPROT_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_ARSNOOP_TOPIC_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_ARSNOOP_TOPIC_OFFSET 4
#define STARS_TOPIC_SCHE_S_CFG_ARCACHE_TOPIC_LEN    4
#define STARS_TOPIC_SCHE_S_CFG_ARCACHE_TOPIC_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_S_SQ_ARPROT_TOPIC_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_S_SQ_ARPROT_TOPIC_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_NS_SQ_ARPROT_TOPIC_LEN    3
#define STARS_TOPIC_SCHE_S_CFG_NS_SQ_ARPROT_TOPIC_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_AICPU_POOL_FLAG_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_AICPU_POOL_FLAG_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_0_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_0_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_0_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_0_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_0_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_0_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_0_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_0_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_1_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_1_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_1_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_1_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_1_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_1_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_1_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_1_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_2_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_2_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_2_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_2_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_2_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_2_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_2_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_2_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_3_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_3_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_3_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_3_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_3_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_3_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_3_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_3_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_4_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_4_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_4_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_4_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_4_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_4_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_4_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_4_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_5_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_5_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_5_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_5_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_5_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_5_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_5_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_5_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_6_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_6_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_6_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_6_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_6_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_6_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_6_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_6_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_7_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_ENABLE_CTRL_S_7_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_7_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_ENABLE_CTRL_S_7_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_7_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_ENABLE_CTRL_S_7_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_7_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_ENABLE_CTRL_S_7_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_ENABLE_CTRL_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_0_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_0_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_0_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_0_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_0_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_0_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_0_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_0_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_1_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_1_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_1_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_1_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_1_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_1_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_1_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_1_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_2_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_2_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_2_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_2_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_2_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_2_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_2_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_2_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_3_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_3_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_3_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_3_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_3_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_3_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_3_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_3_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_4_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_4_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_4_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_4_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_4_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_4_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_4_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_4_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_5_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_5_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_5_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_5_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_5_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_5_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_5_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_5_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_6_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_6_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_6_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_6_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_6_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_6_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_6_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_6_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_7_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_DVPP_CPU_DISABLE_CTRL_S_7_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_7_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_TS_CPU_DISABLE_CTRL_S_7_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_7_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_CTRL_CPU_DISABLE_CTRL_S_7_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_7_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_DATA_CPU_DISABLE_CTRL_S_7_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_ACPU_DISABLE_CTRL_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL0_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL0_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL0_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL0_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL0_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL0_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL0_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL0_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL0_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL0_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL1_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL1_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL1_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL1_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL1_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL1_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL1_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL1_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL1_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL1_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL2_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL2_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL2_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL2_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL2_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL2_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL2_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL2_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL2_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL2_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL3_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL3_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL3_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL3_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL3_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL3_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL3_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL3_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL3_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL3_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL4_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL4_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL4_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL4_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL4_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL4_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL4_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL4_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL4_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL4_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL5_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL5_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL5_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL5_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL5_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL5_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL5_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL5_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL5_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL5_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL6_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL6_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL6_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL6_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL6_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL6_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL6_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL6_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL6_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL6_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_POOL7_DVPP_CPU_ENABLED_STATUS_S_LEN       2
#define STARS_TOPIC_SCHE_S_CFG_POOL7_DVPP_CPU_ENABLED_STATUS_S_OFFSET    26
#define STARS_TOPIC_SCHE_S_CFG_POOL7_TS_CPU_ENABLED_STATUS_S_LEN         2
#define STARS_TOPIC_SCHE_S_CFG_POOL7_TS_CPU_ENABLED_STATUS_S_OFFSET      24
#define STARS_TOPIC_SCHE_S_CFG_POOL7_CTRL_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL7_CTRL_CPU_ENABLED_STATUS_S_OFFSET    16
#define STARS_TOPIC_SCHE_S_CFG_POOL7_DATA_CPU_ENABLED_STATUS_S_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_POOL7_DATA_CPU_ENABLED_STATUS_S_OFFSET    8
#define STARS_TOPIC_SCHE_S_CFG_POOL7_DEVICE_ACPU_ENABLED_STATUS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_POOL7_DEVICE_ACPU_ENABLED_STATUS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_0_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_0_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_0_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_0_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_0_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_0_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_0_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_0_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_0_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_1_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_1_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_1_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_1_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_1_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_1_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_1_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_1_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_1_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_2_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_2_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_2_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_2_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_2_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_2_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_2_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_2_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_2_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_3_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_3_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_3_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_3_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_3_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_3_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_3_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_3_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_3_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_4_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_4_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_4_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_4_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_4_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_4_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_4_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_4_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_4_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_5_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_5_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_5_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_5_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_5_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_5_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_5_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_5_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_5_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_6_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_6_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_6_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_6_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_6_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_6_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_6_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_6_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_6_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_7_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_WARNING_S_7_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_7_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_TRAP_S_7_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_EXCEPTION_S_7_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_7_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DEBUG_S_7_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_7_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_DONE_S_7_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_WAIT_TOPIC_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_EN_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_0_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_1_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_2_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_3_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_4_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_5_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_6_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_7_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_STATUS_ERROR_CODE_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_STATUS_DONE_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_0_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_0_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_0_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_1_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_1_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_1_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_2_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_2_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_2_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_3_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_3_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_3_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_4_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_4_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_4_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_5_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_5_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_5_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_6_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_6_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_6_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_S_7_OFFSET 1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_7_LEN               1
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_GET_TOPIC_S_7_OFFSET            0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_WARNING_S_0_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_WARNING_S_0_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_TRAP_S_0_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_TRAP_S_0_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_EXCEPTION_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_EXCEPTION_S_0_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DEBUG_S_0_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DEBUG_S_0_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DONE_S_0_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DONE_S_0_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_WARNING_S_1_LEN      1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_WARNING_S_1_OFFSET   4
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_TRAP_S_1_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_TRAP_S_1_OFFSET      3
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_EXCEPTION_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_EXCEPTION_S_1_OFFSET 2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DEBUG_S_1_LEN        1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DEBUG_S_1_OFFSET     1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DONE_S_1_LEN         1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_DONE_S_1_OFFSET      0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_WAIT_TOPIC_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_WAIT_TOPIC_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_WAIT_TOPIC_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_WAIT_TOPIC_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_EN_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_EN_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_EN_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_EN_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_ERROR_CODE_S_0_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_ERROR_CODE_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_ERROR_CODE_S_1_LEN    16
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_STATUS_ERROR_CODE_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_0_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_0_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_0_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_0_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_0_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_0_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_1_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_1_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_1_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_1_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_1_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_1_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_2_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_2_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_2_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_2_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_2_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_2_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_3_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_3_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_3_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_3_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_3_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_3_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_4_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_4_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_4_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_4_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_4_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_4_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_5_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_5_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_5_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_5_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_5_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_5_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_6_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_6_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_6_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_6_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_6_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_6_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_7_LEN    1
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_EN_S_7_OFFSET 12
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_7_LEN       8
#define STARS_TOPIC_SCHE_S_CFG_TIMEOUT_S_7_OFFSET    4
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_7_LEN     3
#define STARS_TOPIC_SCHE_S_CFG_QOS_LEVEL_S_7_OFFSET  0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_0_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_0_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_0_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_1_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_1_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_1_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_2_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_2_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_2_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_3_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_3_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_3_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_4_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_4_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_4_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_5_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_5_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_5_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_6_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_6_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_6_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS3_WEIGHT_S_7_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS2_WEIGHT_S_7_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS1_WEIGHT_S_7_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS0_WEIGHT_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_0_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_0_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_0_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_0_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_0_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_1_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_1_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_1_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_1_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_1_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_2_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_2_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_2_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_2_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_2_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_3_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_3_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_3_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_3_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_3_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_4_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_4_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_4_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_4_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_4_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_5_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_5_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_5_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_5_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_5_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_6_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_6_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_6_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_6_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_6_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS7_WEIGHT_S_7_OFFSET 24
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS6_WEIGHT_S_7_OFFSET 16
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS5_WEIGHT_S_7_OFFSET 8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_7_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_QOS4_WEIGHT_S_7_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_STS_S_LEN     2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_STS_S_OFFSET  16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_STS_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_STS_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_FORCE_S_LEN     2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_FORCE_S_OFFSET  16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_FORCE_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_FORCE_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_CLR_S_LEN     2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_CLR_S_OFFSET  16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_CLR_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_CLR_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_MASK_S_LEN     2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_MASK_S_OFFSET  16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_MASK_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_MASK_S_OFFSET 0

#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_RAW_S_LEN     2
#define STARS_TOPIC_SCHE_S_CFG_STARS_CPU_INT_RAW_S_OFFSET  16
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_RAW_S_LEN    8
#define STARS_TOPIC_SCHE_S_CFG_DEVICE_CPU_INT_RAW_S_OFFSET 0

#endif // __STARS_TOPIC_SCHE_S_CFG_REG_OFFSET_FIELD_H__
