// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_conds_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/11/12 15:20:40 Create file
// ******************************************************************************

#ifndef __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_CONDS_NS_REG_SP_LEVEL_LEN    3
#define STARS_CONDS_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_CONDS_NS_REG_LP_MODE_LEN     3
#define STARS_CONDS_NS_REG_LP_MODE_OFFSET  0



#define STARS_CONDS_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_CONDS_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_CONDS_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_CONDS_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_CONDS_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_CONDS_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_CONDS_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_CONDS_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_CONDS_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_CONDS_NS_REG_SQ_FRIENDLY_PCIEDMA_LEN    1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_PCIEDMA_OFFSET 17
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGD_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGD_OFFSET   16
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGE_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_JPEGE_OFFSET   15
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VPC_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VPC_OFFSET     14
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_DSA_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_DSA_OFFSET     13
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_SDMA_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_SDMA_OFFSET    12
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_CONDS_LEN      1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_CONDS_OFFSET   11
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_ACPU_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_ACPU_OFFSET    10
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VEC_LEN        1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_VEC_OFFSET     9
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_FFTS_LEN       1
#define STARS_CONDS_NS_REG_SQ_FRIENDLY_FFTS_OFFSET    8

#define STARS_CONDS_NS_REG_CONDS_STRM_ERR_LEVEL_LEN    1
#define STARS_CONDS_NS_REG_CONDS_STRM_ERR_LEVEL_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_SEL_LEN    3
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_SEL_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_OST_CNT_LEN    1
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_OST_CNT_OFFSET 8
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_STATE_LEN      5
#define STARS_CONDS_NS_REG_DFX_CONDS_FSM_STATE_OFFSET   0

#define STARS_CONDS_NS_REG_CONDS_REDUNDANT_RSP_LEN    8
#define STARS_CONDS_NS_REG_CONDS_REDUNDANT_RSP_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_FREE_BITMAP_LEN    8
#define STARS_CONDS_NS_REG_CONDS_FREE_BITMAP_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_CNT_ENABLE_LEN    1
#define STARS_CONDS_NS_REG_DFX_CONDS_CNT_ENABLE_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_VLD_CNT_LEN    32
#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_VLD_CNT_OFFSET 0

#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_RSP_CNT_LEN    32
#define STARS_CONDS_NS_REG_DFX_CONDS_TASK_RSP_CNT_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_0_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_1_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_2_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_3_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_4_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_5_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_6_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_7_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLE_CTRL_NS_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_0_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_1_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_2_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_3_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_4_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_5_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_6_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_7_LEN    8
#define STARS_CONDS_NS_REG_CONDS_DISABLE_CTRL_NS_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS0_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS1_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS1_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS2_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS2_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS3_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS3_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS4_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS4_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS5_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS5_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS6_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS6_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS7_NS_LEN    8
#define STARS_CONDS_NS_REG_CONDS_ENABLED_STATUS7_NS_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_0_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_0_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_0_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_0_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_0_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_0_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_0_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_0_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_0_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_0_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_0_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_0_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_0_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_1_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_1_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_1_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_1_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_1_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_1_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_1_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_1_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_1_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_1_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_1_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_1_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_1_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_2_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_2_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_2_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_2_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_2_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_2_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_2_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_2_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_2_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_2_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_2_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_2_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_2_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_3_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_3_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_3_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_3_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_3_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_3_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_3_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_3_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_3_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_3_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_3_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_3_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_3_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_4_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_4_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_4_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_4_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_4_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_4_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_4_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_4_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_4_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_4_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_4_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_4_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_4_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_5_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_5_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_5_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_5_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_5_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_5_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_5_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_5_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_5_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_5_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_5_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_5_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_5_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_6_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_6_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_6_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_6_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_6_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_6_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_6_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_6_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_6_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_6_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_6_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_6_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_6_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AR_SSV_7_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AR_SSV_7_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_7_LEN        3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_NS_7_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_7_LEN         3
#define STARS_CONDS_NS_REG_CONDS_ARPROT_S_7_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_7_LEN          1
#define STARS_CONDS_NS_REG_CONDS_ARSNOOP_7_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_7_LEN          4
#define STARS_CONDS_NS_REG_CONDS_ARCACHE_7_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_ARNS_7_LEN             1
#define STARS_CONDS_NS_REG_CONDS_ARNS_7_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_7_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AR_IS_VIRTUAL_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_0_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_0_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_0_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_0_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_0_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_0_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_0_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_0_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_0_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_0_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_0_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_0_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_0_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_1_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_1_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_1_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_1_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_1_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_1_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_1_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_1_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_1_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_1_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_1_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_1_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_1_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_2_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_2_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_2_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_2_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_2_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_2_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_2_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_2_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_2_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_2_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_2_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_2_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_2_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_3_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_3_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_3_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_3_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_3_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_3_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_3_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_3_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_3_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_3_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_3_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_3_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_3_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_4_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_4_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_4_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_4_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_4_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_4_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_4_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_4_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_4_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_4_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_4_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_4_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_4_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_5_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_5_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_5_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_5_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_5_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_5_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_5_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_5_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_5_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_5_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_5_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_5_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_5_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_6_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_6_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_6_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_6_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_6_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_6_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_6_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_6_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_6_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_6_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_6_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_6_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_6_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_AW_SSV_7_LEN           1
#define STARS_CONDS_NS_REG_CONDS_AW_SSV_7_OFFSET        13
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_7_LEN        3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_NS_7_OFFSET     10
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_7_LEN         3
#define STARS_CONDS_NS_REG_CONDS_AWPROT_S_7_OFFSET      7
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_7_LEN          1
#define STARS_CONDS_NS_REG_CONDS_AWSNOOP_7_OFFSET       6
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_7_LEN          4
#define STARS_CONDS_NS_REG_CONDS_AWCACHE_7_OFFSET       2
#define STARS_CONDS_NS_REG_CONDS_AWNS_7_LEN             1
#define STARS_CONDS_NS_REG_CONDS_AWNS_7_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_7_LEN    1
#define STARS_CONDS_NS_REG_CONDS_AW_IS_VIRTUAL_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_0_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_1_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_2_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_3_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_4_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_5_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_6_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_7_LEN    32
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_0_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_0_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_1_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_2_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_3_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_4_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_5_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_6_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_7_LEN    16
#define STARS_CONDS_NS_REG_CONDS_CQE_STATUS_1_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_0_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_0_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_0_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_0_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_0_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_0_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_0_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_0_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_0_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_0_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_0_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_0_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_1_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_1_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_1_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_1_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_1_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_1_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_1_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_1_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_1_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_1_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_1_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_1_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_2_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_2_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_2_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_2_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_2_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_2_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_2_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_2_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_2_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_2_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_2_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_2_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_3_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_3_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_3_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_3_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_3_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_3_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_3_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_3_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_3_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_3_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_3_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_3_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_4_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_4_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_4_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_4_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_4_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_4_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_4_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_4_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_4_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_4_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_4_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_4_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_5_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_5_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_5_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_5_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_5_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_5_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_5_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_5_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_5_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_5_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_5_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_5_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_6_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_6_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_6_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_6_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_6_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_6_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_6_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_6_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_6_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_6_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_6_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_6_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_FC_STATE_7_LEN             3
#define STARS_CONDS_NS_REG_CONDS_FC_STATE_7_OFFSET          9
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_7_LEN      3
#define STARS_CONDS_NS_REG_CONDS_MEM_STAGE_STATE_7_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_7_LEN    3
#define STARS_CONDS_NS_REG_CONDS_FETCH_STAGE_STATE_7_OFFSET 3
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_7_LEN            1
#define STARS_CONDS_NS_REG_CONDS_STORE_OST_7_OFFSET         2
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_7_LEN             1
#define STARS_CONDS_NS_REG_CONDS_LOAD_OST_7_OFFSET          1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_7_LEN         1
#define STARS_CONDS_NS_REG_CONDS_DEBUG_STATUS_7_OFFSET      0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_0_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_1_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_2_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_3_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_4_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_5_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_6_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_7_LEN    20
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_INDEX_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_0_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_0_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_0_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_0_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_0_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_0_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_0_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_0_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_0_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_0_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_0_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_0_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_0_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_1_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_1_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_1_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_1_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_1_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_1_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_1_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_1_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_1_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_1_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_1_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_1_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_1_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_2_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_2_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_2_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_2_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_2_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_2_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_2_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_2_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_2_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_2_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_2_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_2_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_2_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_3_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_3_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_3_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_3_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_3_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_3_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_3_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_3_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_3_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_3_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_3_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_3_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_3_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_4_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_4_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_4_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_4_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_4_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_4_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_4_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_4_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_4_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_4_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_4_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_4_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_4_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_5_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_5_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_5_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_5_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_5_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_5_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_5_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_5_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_5_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_5_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_5_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_5_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_5_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_6_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_6_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_6_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_6_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_6_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_6_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_6_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_6_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_6_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_6_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_6_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_6_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_6_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_7_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ST_VA_ERROR_7_OFFSET   6
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_7_LEN      1
#define STARS_CONDS_NS_REG_CONDS_FC_VA_ERROR_7_OFFSET   5
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_7_LEN      1
#define STARS_CONDS_NS_REG_CONDS_LD_VA_ERROR_7_OFFSET   4
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_7_LEN      1
#define STARS_CONDS_NS_REG_CONDS_CLOSE_OTHER_7_OFFSET   3
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_7_LEN      1
#define STARS_CONDS_NS_REG_CONDS_ACTIVE_SELF_7_OFFSET   2
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_7_LEN     1
#define STARS_CONDS_NS_REG_CONDS_VF_NOT_MATCH_7_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_7_LEN    1
#define STARS_CONDS_NS_REG_CONDS_ILLEGAL_INSTR_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_0_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_1_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_2_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_3_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_4_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_5_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_6_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_7_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_LOW_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_0_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_0_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_1_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_1_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_2_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_2_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_3_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_3_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_4_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_4_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_5_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_5_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_6_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_6_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_7_LEN    32
#define STARS_CONDS_NS_REG_CONDS_EXEC_INSTR_DATA_HIGH_7_OFFSET 0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_0_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_0_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_0_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_0_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_0_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_0_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_1_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_1_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_1_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_1_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_1_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_1_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_2_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_2_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_2_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_2_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_2_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_2_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_3_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_3_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_3_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_3_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_3_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_3_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_4_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_4_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_4_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_4_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_4_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_4_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_5_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_5_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_5_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_5_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_5_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_5_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_6_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_6_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_6_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_6_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_6_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_6_OFFSET       0

#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_7_LEN    1
#define STARS_CONDS_NS_REG_CONDS_SINGLE_CORE_RST_7_OFFSET 2
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_7_LEN     1
#define STARS_CONDS_NS_REG_CONDS_TASK_TERMINATE_7_OFFSET  1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_7_LEN          1
#define STARS_CONDS_NS_REG_CONDS_TASK_KILL_7_OFFSET       0

#endif // __STARS_CONDS_NS_REG_REG_OFFSET_FIELD_H__
