/*
 * Copyright     :  Copyright (C) 2021, Huawei Technologies Co. Ltd.
 * File name     :  stars_glb_ns_reg_reg_offset.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2020/04/01
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2021/07/27 11:26:50 Create file
 */

#ifndef __STARS_GLB_NS_REG_REG_OFFSET_H__
#define __STARS_GLB_NS_REG_REG_OFFSET_H__

/* STARS_GLB_NS_REG Base address of Module's Register */
#define STARS_GLB_NS_REG_BASE                       (0x0)

/******************************************************************************/
/*                      SOC STARS_GLB_NS_REG Registers' Definitions                            */
/******************************************************************************/

#define STARS_GLB_NS_REG_STARS_PRIORITY_CTRL0_REG                     (STARS_GLB_NS_REG_BASE + 0x0)    
#define STARS_GLB_NS_REG_STARS_PRIORITY_CTRL1_REG                     (STARS_GLB_NS_REG_BASE + 0x4)    
#define STARS_GLB_NS_REG_STARS_PRIORITY_CTRL2_REG                     (STARS_GLB_NS_REG_BASE + 0x8)    
#define STARS_GLB_NS_REG_STARS_PRIORITY_CTRL3_REG                     (STARS_GLB_NS_REG_BASE + 0xC)    
#define STARS_GLB_NS_REG_STARS_FRIENDLY_CTRL_REG                      (STARS_GLB_NS_REG_BASE + 0x20)   
#define STARS_GLB_NS_REG_STARS_FFTS_PLUS_EN_REG                       (STARS_GLB_NS_REG_BASE + 0x24)   
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_0_REG                    (STARS_GLB_NS_REG_BASE + 0x100)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_1_REG                    (STARS_GLB_NS_REG_BASE + 0x104)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_2_REG                    (STARS_GLB_NS_REG_BASE + 0x108)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_3_REG                    (STARS_GLB_NS_REG_BASE + 0x10C)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_4_REG                    (STARS_GLB_NS_REG_BASE + 0x110)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_5_REG                    (STARS_GLB_NS_REG_BASE + 0x114)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_6_REG                    (STARS_GLB_NS_REG_BASE + 0x118)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_7_REG                    (STARS_GLB_NS_REG_BASE + 0x11C)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_8_REG                    (STARS_GLB_NS_REG_BASE + 0x120)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_9_REG                    (STARS_GLB_NS_REG_BASE + 0x124)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_10_REG                   (STARS_GLB_NS_REG_BASE + 0x128)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_11_REG                   (STARS_GLB_NS_REG_BASE + 0x12C)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_12_REG                   (STARS_GLB_NS_REG_BASE + 0x130)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_13_REG                   (STARS_GLB_NS_REG_BASE + 0x134)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_14_REG                   (STARS_GLB_NS_REG_BASE + 0x138)  
#define STARS_GLB_NS_REG_STARS_NOTIFYID_VFID_15_REG                   (STARS_GLB_NS_REG_BASE + 0x13C)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_0_REG                  (STARS_GLB_NS_REG_BASE + 0x180)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_1_REG                  (STARS_GLB_NS_REG_BASE + 0x184)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_2_REG                  (STARS_GLB_NS_REG_BASE + 0x188)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_3_REG                  (STARS_GLB_NS_REG_BASE + 0x18C)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_4_REG                  (STARS_GLB_NS_REG_BASE + 0x190)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_5_REG                  (STARS_GLB_NS_REG_BASE + 0x194)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_6_REG                  (STARS_GLB_NS_REG_BASE + 0x198)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_7_REG                  (STARS_GLB_NS_REG_BASE + 0x19C)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_8_REG                  (STARS_GLB_NS_REG_BASE + 0x1A0)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_9_REG                  (STARS_GLB_NS_REG_BASE + 0x1A4)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_10_REG                 (STARS_GLB_NS_REG_BASE + 0x1A8)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_11_REG                 (STARS_GLB_NS_REG_BASE + 0x1AC)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_12_REG                 (STARS_GLB_NS_REG_BASE + 0x1B0)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_13_REG                 (STARS_GLB_NS_REG_BASE + 0x1B4)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_14_REG                 (STARS_GLB_NS_REG_BASE + 0x1B8)  
#define STARS_GLB_NS_REG_STARS_RTSQ_SLICE_VFID_15_REG                 (STARS_GLB_NS_REG_BASE + 0x1BC)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_0_REG                   (STARS_GLB_NS_REG_BASE + 0x200)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_1_REG                   (STARS_GLB_NS_REG_BASE + 0x204)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_2_REG                   (STARS_GLB_NS_REG_BASE + 0x208)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_3_REG                   (STARS_GLB_NS_REG_BASE + 0x20C)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_4_REG                   (STARS_GLB_NS_REG_BASE + 0x210)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_5_REG                   (STARS_GLB_NS_REG_BASE + 0x214)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_6_REG                   (STARS_GLB_NS_REG_BASE + 0x218)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_7_REG                   (STARS_GLB_NS_REG_BASE + 0x21C)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_8_REG                   (STARS_GLB_NS_REG_BASE + 0x220)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_9_REG                   (STARS_GLB_NS_REG_BASE + 0x224)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_10_REG                  (STARS_GLB_NS_REG_BASE + 0x228)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_11_REG                  (STARS_GLB_NS_REG_BASE + 0x22C)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_12_REG                  (STARS_GLB_NS_REG_BASE + 0x230)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_13_REG                  (STARS_GLB_NS_REG_BASE + 0x234)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_14_REG                  (STARS_GLB_NS_REG_BASE + 0x238)  
#define STARS_GLB_NS_REG_STARS_CDQ_SLICE_VFID_15_REG                  (STARS_GLB_NS_REG_BASE + 0x23C)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL0_REG                          (STARS_GLB_NS_REG_BASE + 0x800)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL1_REG                          (STARS_GLB_NS_REG_BASE + 0x804)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL2_REG                          (STARS_GLB_NS_REG_BASE + 0x808)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL3_REG                          (STARS_GLB_NS_REG_BASE + 0x80C)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL4_REG                          (STARS_GLB_NS_REG_BASE + 0x810)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL5_REG                          (STARS_GLB_NS_REG_BASE + 0x814)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL6_REG                          (STARS_GLB_NS_REG_BASE + 0x818)  
#define STARS_GLB_NS_REG_STARS_GLB_CTRL7_REG                          (STARS_GLB_NS_REG_BASE + 0x81C)  
#define STARS_GLB_NS_REG_STARS_HL_PRIORITY_OVERRIDE_TIME_SETTING0_REG (STARS_GLB_NS_REG_BASE + 0x820)  
#define STARS_GLB_NS_REG_STARS_HL_PRIORITY_OVERRIDE_TIME_SETTING1_REG (STARS_GLB_NS_REG_BASE + 0x824)  
#define STARS_GLB_NS_REG_STARS_HL_PRIORITY_OVERRIDE_TIME_SETTING2_REG (STARS_GLB_NS_REG_BASE + 0x828)  
#define STARS_GLB_NS_REG_STARS_HL_PRIORITY_OVERRIDE_TIME_SETTING3_REG (STARS_GLB_NS_REG_BASE + 0x82C)  
#define STARS_GLB_NS_REG_STARS_AXCACHE_SETTING0_REG                   (STARS_GLB_NS_REG_BASE + 0x830)  
#define STARS_GLB_NS_REG_STARS_AXCACHE_SETTING1_REG                   (STARS_GLB_NS_REG_BASE + 0x834)  
#define STARS_GLB_NS_REG_STARS_PCIE_THROUGH_SETTING_REG               (STARS_GLB_NS_REG_BASE + 0x838)  
#define STARS_GLB_NS_REG_STARS_ACSQ_CTRL_REG                          (STARS_GLB_NS_REG_BASE + 0x83C)  
#define STARS_GLB_NS_REG_STARS_SLV_DECODER_DEBUG_INFO_REG             (STARS_GLB_NS_REG_BASE + 0x840)  /* 用于显示错误信息 */
#define STARS_GLB_NS_REG_STARS_NOC0_PARTID_CFG_REG                    (STARS_GLB_NS_REG_BASE + 0x844)  /* set the high\low mpam */
#define STARS_GLB_NS_REG_STARS_NOC0_PMG_CFG_REG                       (STARS_GLB_NS_REG_BASE + 0x848)  /* set the high\low mpam */
#define STARS_GLB_NS_REG_STARS_NOC0_CHNL_SET_REG                      (STARS_GLB_NS_REG_BASE + 0x84C)  /* set the chnl use high/low mpam */
#define STARS_GLB_NS_REG_STARS_NOC1_PARTID_CFG_REG                    (STARS_GLB_NS_REG_BASE + 0x850)  /* set the high\low mpam */
#define STARS_GLB_NS_REG_STARS_NOC1_PMG_CFG_REG                       (STARS_GLB_NS_REG_BASE + 0x854)  /* set the high\low mpam */
#define STARS_GLB_NS_REG_STARS_NOC1_CHNL_SET_REG                      (STARS_GLB_NS_REG_BASE + 0x858)  /* set the chnl use high/low mpam */
#define STARS_GLB_NS_REG_STARS_SLV_DECODER_CTRL_REG                   (STARS_GLB_NS_REG_BASE + 0x85C)  /* 用于控制译码器 */
#define STARS_GLB_NS_REG_STARS_AWUSER0_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x860)  /* 配置USER位[31:0] */
#define STARS_GLB_NS_REG_STARS_AWUSER1_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x864)  /* 配置USER位[63:32] */
#define STARS_GLB_NS_REG_STARS_AWUSER2_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x868)  /* 配置USER位[96:64] */
#define STARS_GLB_NS_REG_STARS_AWUSER3_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x86C)  /* 配置USER位[103:96] */
#define STARS_GLB_NS_REG_STARS_ARUSER0_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x870)  /* 配置USER位[31:0] */
#define STARS_GLB_NS_REG_STARS_ARUSER1_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x874)  /* 配置USER位[63:32] */
#define STARS_GLB_NS_REG_STARS_ARUSER2_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x878)  /* 配置USER位[96:64] */
#define STARS_GLB_NS_REG_STARS_ARUSER3_SETTING_REG                    (STARS_GLB_NS_REG_BASE + 0x87C)  /* 配置USER位[103:96] */
#define STARS_GLB_NS_REG_STARS_NOC0_ERR_INFO_REG                      (STARS_GLB_NS_REG_BASE + 0x880)  /* 控制NOC_ARB0错误信息 */
#define STARS_GLB_NS_REG_STARS_NOC1_ERR_INFO_REG                      (STARS_GLB_NS_REG_BASE + 0x884)  /* 控制NOC_ARB1错误信息 */
#define STARS_GLB_NS_REG_STARS_ECC_ERR_INFO0_REG                      (STARS_GLB_NS_REG_BASE + 0x88C)  
#define STARS_GLB_NS_REG_STARS_ECC_ERR_INFO1_REG                      (STARS_GLB_NS_REG_BASE + 0x890)  
#define STARS_GLB_NS_REG_STARS_ECC_ERR_INFO2_REG                      (STARS_GLB_NS_REG_BASE + 0x894)  
#define STARS_GLB_NS_REG_STARS_ECC_ERR_INFO3_REG                      (STARS_GLB_NS_REG_BASE + 0x898)  
#define STARS_GLB_NS_REG_STARS_1BIT_ECC_INFO0_REG                     (STARS_GLB_NS_REG_BASE + 0x89C)  
#define STARS_GLB_NS_REG_STARS_1BIT_ECC_INFO1_REG                     (STARS_GLB_NS_REG_BASE + 0x8A0)  
#define STARS_GLB_NS_REG_STARS_1BIT_ECC_INFO2_REG                     (STARS_GLB_NS_REG_BASE + 0x8A4)  
#define STARS_GLB_NS_REG_STARS_1BIT_ECC_INFO3_REG                     (STARS_GLB_NS_REG_BASE + 0x8A8)  
#define STARS_GLB_NS_REG_STARS_PREFETCH_ECC_PATTERN0_REG              (STARS_GLB_NS_REG_BASE + 0x8AC)  
#define STARS_GLB_NS_REG_STARS_PREFETCH_ECC_PATTERN1_REG              (STARS_GLB_NS_REG_BASE + 0x8B0)  
#define STARS_GLB_NS_REG_STARS_PREFETCH_ECC_PATTERN2_REG              (STARS_GLB_NS_REG_BASE + 0x8B4)  
#define STARS_GLB_NS_REG_STARS_PREFETCH_ECC_PATTERN3_REG              (STARS_GLB_NS_REG_BASE + 0x8B8)  
#define STARS_GLB_NS_REG_STARS_PREFETCH_ECC_PATTERN4_REG              (STARS_GLB_NS_REG_BASE + 0x8BC)  
#define STARS_GLB_NS_REG_STARS_CFG_ECO0_RESERVED_REG                  (STARS_GLB_NS_REG_BASE + 0x8C0)  
#define STARS_GLB_NS_REG_STARS_CFG_ECO1_RESERVED_REG                  (STARS_GLB_NS_REG_BASE + 0x8C4)  
#define STARS_GLB_NS_REG_STARS_CFG_ECO2_RESERVED_REG                  (STARS_GLB_NS_REG_BASE + 0x8C8)  
#define STARS_GLB_NS_REG_STARS_CFG_ECO3_RESERVED_REG                  (STARS_GLB_NS_REG_BASE + 0x8CC)  
#define STARS_GLB_NS_REG_STARS_ECO0_STATE_RESERVED_REG                (STARS_GLB_NS_REG_BASE + 0x8D0)  
#define STARS_GLB_NS_REG_STARS_ECO1_STATE_RESERVED_REG                (STARS_GLB_NS_REG_BASE + 0x8D4)  
#define STARS_GLB_NS_REG_STARS_ECO2_STATE_RESERVED_REG                (STARS_GLB_NS_REG_BASE + 0x8D8)  
#define STARS_GLB_NS_REG_STARS_ECO3_STATE_RESERVED_REG                (STARS_GLB_NS_REG_BASE + 0x8DC)  
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_QOS_W0_REG                  (STARS_GLB_NS_REG_BASE + 0x8F4)  /* 配置写通道0-7 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_QOS_W1_REG                  (STARS_GLB_NS_REG_BASE + 0x8F8)  /* 配置写通道15-8 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_QOS_R0_REG                  (STARS_GLB_NS_REG_BASE + 0x8FC)  /* 配置读通道0-7 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_QOS_R1_REG                  (STARS_GLB_NS_REG_BASE + 0x900)  /* 配置读通道15-8 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_PRESCALER_W0_REG            (STARS_GLB_NS_REG_BASE + 0x904)  /* 配置写通道0-7 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_PRESCALER_W1_REG            (STARS_GLB_NS_REG_BASE + 0x908)  /* 配置写通道15-8 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_PRESCALER_R0_REG            (STARS_GLB_NS_REG_BASE + 0x90C)  /* 配置读通道0-7 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_PRESCALER_R1_REG            (STARS_GLB_NS_REG_BASE + 0x910)  /* 配置读通道15-8 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_0__ARB_CNT_W0_REG                  (STARS_GLB_NS_REG_BASE + 0x914)  /* 配置NOC0 超时计数器 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_QOS_W0_REG                  (STARS_GLB_NS_REG_BASE + 0x918)  /* 配置写通道0-7 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_QOS_W1_REG                  (STARS_GLB_NS_REG_BASE + 0x91C)  /* 配置写通道15-8 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_QOS_R0_REG                  (STARS_GLB_NS_REG_BASE + 0x920)  /* 配置读通道0-7 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_QOS_R1_REG                  (STARS_GLB_NS_REG_BASE + 0x924)  /* 配置读通道15-8 QOS设定 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_PRESCALER_W0_REG            (STARS_GLB_NS_REG_BASE + 0x928)  /* 配置写通道0-7 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_PRESCALER_W1_REG            (STARS_GLB_NS_REG_BASE + 0x92C)  /* 配置写通道15-8 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_PRESCALER_R0_REG            (STARS_GLB_NS_REG_BASE + 0x930)  /* 配置读通道0-7 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_PRESCALER_R1_REG            (STARS_GLB_NS_REG_BASE + 0x934)  /* 配置读通道15-8 预设计数 */
#define STARS_GLB_NS_REG_STARS_NOC_1__ARB_CNT_W0_REG                  (STARS_GLB_NS_REG_BASE + 0x938)  /* 配置NOC1 超时计数器 */
#define STARS_GLB_NS_REG_STARS_MEMORY_CTRL_REG                        (STARS_GLB_NS_REG_BASE + 0x93C)  
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_0_REG          (STARS_GLB_NS_REG_BASE + 0x1000) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_1_REG          (STARS_GLB_NS_REG_BASE + 0x1030) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_2_REG          (STARS_GLB_NS_REG_BASE + 0x1060) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_3_REG          (STARS_GLB_NS_REG_BASE + 0x1090) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_4_REG          (STARS_GLB_NS_REG_BASE + 0x10C0) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_5_REG          (STARS_GLB_NS_REG_BASE + 0x10F0) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_6_REG          (STARS_GLB_NS_REG_BASE + 0x1120) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL0_NS_7_REG          (STARS_GLB_NS_REG_BASE + 0x1150) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_0_REG          (STARS_GLB_NS_REG_BASE + 0x1004) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_1_REG          (STARS_GLB_NS_REG_BASE + 0x1034) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_2_REG          (STARS_GLB_NS_REG_BASE + 0x1064) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_3_REG          (STARS_GLB_NS_REG_BASE + 0x1094) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_4_REG          (STARS_GLB_NS_REG_BASE + 0x10C4) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_5_REG          (STARS_GLB_NS_REG_BASE + 0x10F4) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_6_REG          (STARS_GLB_NS_REG_BASE + 0x1124) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL1_NS_7_REG          (STARS_GLB_NS_REG_BASE + 0x1154) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_0_REG          (STARS_GLB_NS_REG_BASE + 0x1008) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_1_REG          (STARS_GLB_NS_REG_BASE + 0x1038) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_2_REG          (STARS_GLB_NS_REG_BASE + 0x1068) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_3_REG          (STARS_GLB_NS_REG_BASE + 0x1098) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_4_REG          (STARS_GLB_NS_REG_BASE + 0x10C8) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_5_REG          (STARS_GLB_NS_REG_BASE + 0x10F8) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_6_REG          (STARS_GLB_NS_REG_BASE + 0x1128) 
#define STARS_GLB_NS_REG_STARS_STRICT_SWAPOUT_CTRL2_NS_7_REG          (STARS_GLB_NS_REG_BASE + 0x1158) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_0_REG           (STARS_GLB_NS_REG_BASE + 0x1010) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_1_REG           (STARS_GLB_NS_REG_BASE + 0x1040) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_2_REG           (STARS_GLB_NS_REG_BASE + 0x1070) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_3_REG           (STARS_GLB_NS_REG_BASE + 0x10A0) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_4_REG           (STARS_GLB_NS_REG_BASE + 0x10D0) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_5_REG           (STARS_GLB_NS_REG_BASE + 0x1100) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_6_REG           (STARS_GLB_NS_REG_BASE + 0x1130) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL0_NS_7_REG           (STARS_GLB_NS_REG_BASE + 0x1160) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_0_REG           (STARS_GLB_NS_REG_BASE + 0x1014) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_1_REG           (STARS_GLB_NS_REG_BASE + 0x1044) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_2_REG           (STARS_GLB_NS_REG_BASE + 0x1074) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_3_REG           (STARS_GLB_NS_REG_BASE + 0x10A4) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_4_REG           (STARS_GLB_NS_REG_BASE + 0x10D4) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_5_REG           (STARS_GLB_NS_REG_BASE + 0x1104) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_6_REG           (STARS_GLB_NS_REG_BASE + 0x1134) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL1_NS_7_REG           (STARS_GLB_NS_REG_BASE + 0x1164) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_0_REG           (STARS_GLB_NS_REG_BASE + 0x1018) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_1_REG           (STARS_GLB_NS_REG_BASE + 0x1048) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_2_REG           (STARS_GLB_NS_REG_BASE + 0x1078) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_3_REG           (STARS_GLB_NS_REG_BASE + 0x10A8) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_4_REG           (STARS_GLB_NS_REG_BASE + 0x10D8) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_5_REG           (STARS_GLB_NS_REG_BASE + 0x1108) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_6_REG           (STARS_GLB_NS_REG_BASE + 0x1138) 
#define STARS_GLB_NS_REG_STARS_RELAX_SWAPOUT_CTRL2_NS_7_REG           (STARS_GLB_NS_REG_BASE + 0x1168) 
#define STARS_GLB_NS_REG_STARS_CQE_STATUS_REG                         (STARS_GLB_NS_REG_BASE + 0x1204) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_0_REG                     (STARS_GLB_NS_REG_BASE + 0x1300) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_1_REG                     (STARS_GLB_NS_REG_BASE + 0x1304) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_2_REG                     (STARS_GLB_NS_REG_BASE + 0x1308) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_3_REG                     (STARS_GLB_NS_REG_BASE + 0x130C) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_4_REG                     (STARS_GLB_NS_REG_BASE + 0x1310) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_5_REG                     (STARS_GLB_NS_REG_BASE + 0x1314) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_6_REG                     (STARS_GLB_NS_REG_BASE + 0x1318) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_7_REG                     (STARS_GLB_NS_REG_BASE + 0x131C) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_8_REG                     (STARS_GLB_NS_REG_BASE + 0x1320) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_9_REG                     (STARS_GLB_NS_REG_BASE + 0x1324) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_10_REG                    (STARS_GLB_NS_REG_BASE + 0x1328) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_11_REG                    (STARS_GLB_NS_REG_BASE + 0x132C) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_12_REG                    (STARS_GLB_NS_REG_BASE + 0x1330) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_13_REG                    (STARS_GLB_NS_REG_BASE + 0x1334) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_14_REG                    (STARS_GLB_NS_REG_BASE + 0x1338) 
#define STARS_GLB_NS_REG_STARS_EVENTID_VFID_15_REG                    (STARS_GLB_NS_REG_BASE + 0x133C) 
#define STARS_GLB_NS_REG_STARS_WRVAULE_CFG_REG                        (STARS_GLB_NS_REG_BASE + 0x1340) 
#define STARS_GLB_NS_REG_NOC0_DFX_CFG_10_REG                          (STARS_GLB_NS_REG_BASE + 0x1428) 
#define STARS_GLB_NS_REG_NOC1_DFX_CFG_10_REG                          (STARS_GLB_NS_REG_BASE + 0x1454) 

#endif // __STARS_GLB_NS_REG_REG_OFFSET_H__
