// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_vpc_s_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 09:45:53 Create file
// ******************************************************************************

#ifndef __STARS_VPC_S_REG_REG_OFFSET_FIELD_H__
#define __STARS_VPC_S_REG_REG_OFFSET_FIELD_H__

#define STARS_VPC_S_REG_CFG_POOL_SEC_LEN    8
#define STARS_VPC_S_REG_CFG_POOL_SEC_OFFSET 0

#define STARS_VPC_S_REG_CFG_ARCACHE_DVPP_DESC_LEN    4
#define STARS_VPC_S_REG_CFG_ARCACHE_DVPP_DESC_OFFSET 1
#define STARS_VPC_S_REG_CFG_ARSNOOP_DVPP_DESC_LEN    1
#define STARS_VPC_S_REG_CFG_ARSNOOP_DVPP_DESC_OFFSET 0

#define STARS_VPC_S_REG_ARNS_DVPP_DESC_LEN            1
#define STARS_VPC_S_REG_ARNS_DVPP_DESC_OFFSET         3
#define STARS_VPC_S_REG_NS_SQ_ARPROT_DVPP_DESC_LEN    3
#define STARS_VPC_S_REG_NS_SQ_ARPROT_DVPP_DESC_OFFSET 0

#define STARS_VPC_S_REG_S_SQ_ARPROT_DVPP_DESC_LEN    3
#define STARS_VPC_S_REG_S_SQ_ARPROT_DVPP_DESC_OFFSET 0

#define STARS_VPC_S_REG_VPC_AWSNOOP_LEN    1
#define STARS_VPC_S_REG_VPC_AWSNOOP_OFFSET 5
#define STARS_VPC_S_REG_VPC_AWCACHE_LEN    4
#define STARS_VPC_S_REG_VPC_AWCACHE_OFFSET 1
#define STARS_VPC_S_REG_VPC_AWNS_LEN       1
#define STARS_VPC_S_REG_VPC_AWNS_OFFSET    0

#define STARS_VPC_S_REG_VPC_AWPROT_S_LEN    3
#define STARS_VPC_S_REG_VPC_AWPROT_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_AWPROT_NS_LEN    3
#define STARS_VPC_S_REG_VPC_AWPROT_NS_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_0_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_0_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_1_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_1_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_2_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_2_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_3_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_3_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_4_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_4_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_5_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_5_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_6_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_6_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_7_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLE_CTRL_S_7_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_0_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_0_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_1_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_1_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_2_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_2_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_3_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_3_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_4_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_4_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_5_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_5_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_6_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_6_OFFSET 0

#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_7_LEN    10
#define STARS_VPC_S_REG_VPC_DISABLE_CTRL_S_7_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS0_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS0_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS1_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS1_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS2_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS2_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS3_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS3_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS4_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS4_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS5_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS5_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS6_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS6_S_OFFSET 0

#define STARS_VPC_S_REG_VPC_ENABLED_STATUS7_S_LEN    10
#define STARS_VPC_S_REG_VPC_ENABLED_STATUS7_S_OFFSET 0

#endif // __STARS_VPC_S_REG_REG_OFFSET_FIELD_H__
