# SPDX-License-Identifier: GPL-2.0
obj-m := drv_spi_uniform.o
drv_spi_uniform-objs := hispi.o spi_hisiv500.o spi_api.o spi_misc.o

ifneq ($(filter $(PRODUCT), ascend610Lite),)
ccflags-y += -DASCEND_MDC_LITE
drv_spi_uniform-objs += spi_misc_610.o
else
drv_spi_uniform-objs += spi_misc_310.o
endif

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)  -I$(DRIVER_INC)/include/kerndrv_api
ccflags-y += -DCONFIG_SPI_UDRV
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
