# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_sec_eh_agent.o
obj-m += ascend_trs_sec_eh_adapt.o

ascend_trs_sec_eh_agent-objs := agent/trs_sec_eh_agent_init.o
ascend_trs_sec_eh_agent-objs += agent/trs_sec_eh_cfg.o agent/trs_sec_eh_id.o agent/trs_sec_eh_sq.o
ascend_trs_sec_eh_agent-objs += agent/trs_sec_eh_agent_msg.o agent/trs_sec_eh_mbox.o

ascend_trs_sec_eh_adapt-objs := adapt/trs_sec_eh.o adapt/trs_sec_eh_init.o adapt/trs_sec_eh_vpc.o
ascend_trs_sec_eh_adapt-objs += adapt/trs_sec_eh_chan/trs_sec_eh_chan.o adapt/trs_sec_eh_core/trs_sec_eh_core.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/soc_adapt/soc_adapt.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/soc_adapt/cloud_v2/soc_adapt_res_cloud_v2.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/soc_adapt/mini_v3/soc_adapt_res_mini_v3.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/soc_adapt/mini_v2/soc_adapt_res_mini_v2.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_core/trs_core_near_ops_mbox.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_chan/stars_v1/trs_chan_stars_v1_ops.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_chan/trs_chan_near_ops_mbox.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_chan/trs_chan_near_ops_rsv_mem.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_chan/stars_v1/trs_chan_stars_v1_ops_stars.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_chan/trs_chan_near_ops_mem.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_core/tscpu/trs_tscpu_core_near_ops.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_core/stars_v1/trs_core_stars_v1_ops.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_db.o adapt/near_comm/trs_host_id.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_msg.o adapt/near_comm/trs_host_comm.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_near_adapt_init.o
ascend_trs_sec_eh_adapt-objs += adapt/near_comm/trs_host_core/trs_core_near_ops.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/trs_chan_irq.o adapt/comm/trs_chan_mbox.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/trs_chan_mem.o adapt/comm/trs_chan_update.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/trs_rsv_mem.o adapt/comm/trs_ts_db.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/trs_ts_status.o adapt/comm/trs_chan_maint_sqcq.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/stars_v1/trs_chan_sqcq.o adapt/comm/stars_v1/trs_stars.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/stars_v1/trs_stars_cq.o adapt/comm/stars_v1/trs_stars_sq.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/tscpu/trs_tscpu_sq.o adapt/comm/tscpu/trs_tscpu_cq.o
ascend_trs_sec_eh_adapt-objs += adapt/comm/tscpu/trs_tscpu_chan_sqcq.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) -I$(src)/inc -I$(src)/agent -I$(src)/adapt
ccflags-y += -I$(src)/adapt/trs_sec_eh_chan -I$(src)/adapt/trs_sec_eh_core
ccflags-y += -I$(src)/adapt/comm -I$(src)/adapt/comm/stars_v1 -I$(src)/adapt/comm/tscpu
ccflags-y += -I$(src)/adapt/near_comm -I$(src)/adapt/near_comm/soc_adapt
ccflags-y += -I$(src)/adapt/near_comm/soc_adapt/cloud_v2 -I$(src)/adapt/near_comm/soc_adapt/mini_v3
ccflags-y += -I$(src)/adapt/near_comm/soc_adapt/mini_v2
ccflags-y += -I$(src)/adapt/near_comm/trs_host_chan -I$(src)/adapt/near_comm/trs_host_chan/stars_v1
ccflags-y += -I$(src)/adapt/near_comm/trs_host_chan/tscpu
ccflags-y += -I$(src)/adapt/near_comm/trs_host_core -I$(src)/adapt/near_comm/trs_host_core/stars_v1
ccflags-y += -I$(src)/adapt/near_comm/trs_host_core/tscpu -I$(DRIVER_INC)/urd

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion


KBUILD_EXTRA_SYMBOLS := $(src)/../dms/Module.symvers \
	$(src)/../pcie/Module.symvers \
	$(src)/../soc_resmng/Module.symvers \
	$(src)/../trs_chan/Module.symvers \
	$(src)/../trs_core/Module.symvers \
	$(src)/../trs_id_allocator/Module.symvers \
	$(src)/../trs_pm_adapt/Module.symvers \
	$(src)/../uda/Module.symvers \
	$(src)/../urd/Module.symvers \
	$(src)/../virtmng_host_stub/Module.symvers \
	$(src)/../vpc_agent/Module.symvers
