# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_adapt_agent.o
ascend_trs_adapt_agent-objs := pcie/trs_agent.o pcie/trs_d2h_msg_ops.o comm/trs_cache_id_recycle.o trs_pm_agent.o trs_agent_ops.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(DRIVER_INC)/trs_pm_adapt -I$(DRIVER_INC)/trs_pm_adapt/core -I$(DRIVER_INC)/trs_pm_adapt/core/stars_v1 -I$(DRIVER_INC)/trs_pm_adapt/chan -I$(DRIVER_INC)/trs_pm_adapt/soc/mini_v3 -I$(src)/pcie -I$(src)/comm

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
