/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2022-01-20
 */
#ifndef SAFETY_RAS_CONVERGE_610_H
#define SAFETY_RAS_CONVERGE_610_H

#include "dms_define.h"
#include "safety_ras_init_610.h"

#define MEM_ERR_STATUS 0x1U

// detail err code, inner use
enum {
	MEMORY_EXP_OB = 0x01U,           // 地址膨胀后越界中断
	MEMORY_SBRAM_1ERR = 0x02U,       // SBRAM 1bit错误中断
	MEMORY_SBRAM_DERR = 0x03U,       // SBRAM 2bit错误中断
	MEMORY_RBUF_SERR = 0x04U,        // IECC_RBUF 1bit错误中断
	MEMORY_RBUF_DERR = 0x05U,        // IECC_RBUF 2bit错误中断
	MEMORY_WBUF_SERR = 0x06U,        // IECC_WBUF 1bit错误中断
	MEMORY_WBUF_DERR = 0x07U,        // IECC_WBUF 2bit错误中断
	MEMORY_IECC_SERR = 0x08U,        // IECC 1bit错误中断
	MEMORY_IECC_DERR = 0x09U,        // IECC 2bit错误中断
	MEMORY_RD_TIME_OUT = 0x11U,      // DDRPHY 读数据超时中断
	MEMORY_AREF_ALARM = 0x12U,       // DDR AREF命令错误中断
	MEMORY_SBRAM_MERR = 0x13U,       // SBRAM多比特错误中断
	MEMORY_RPRAM_MERR = 0x14U,       // RPRAM多比特错误中断
	MEMORY_SREF_ERR = 0x15U,         // 自刷新接口有命令访问中断
	MEMORY_WSRAM_MERR = 0x16U,       // WSRAM多比特错误中断
	MEMORY_PHYRAM_MERR = 0x17U,      // phyram多bit中断
	MEMORY_UCERAM_MERR = 0x18U,      // uceram多bit中断
	MEMORY_WSRAM_SERR = 0x21U,       // WSRAM单比特错误中断
	MEMORY_SBRAM_SERR = 0x22U,       // SBRAM单比特错误中断
	MEMORY_RPRAM_SERR = 0x23U,       // RPRAM单比特错误中断
	MEMORY_PHYRAM_SERR = 0x24U,      // phyram单bit中断状态
	MEMORY_UCERAM_SERR = 0x25U,      // uceram单bit中断状态
	MEMORY_HIGH_TEMPERATURE = 0x31U, // 高温中断状态
	DMC_REG_PARITY_ERR = 0x40U,      // 0x40开始为bs9sx1a的内部异常码
	DMC_PCFG_PARITY_ERR,
	DMC_UCE_SEC_VIO,
	DMC_UCERAM_MERR,
	DMC_UCERAM_SERR,
	DMC_RPFIFO_OFLOW,
	DMC_RPFIFO_UFLOW,
	DMC_SBFIFO_OFLOW,
	DMC_SBFIFO_UFLOW,
	DMC_GRTFIFO_OFLOW,
	DMC_GRTFIFO_UFLOW,
	DMC_SREF_ERR,
	DMC_TMON_ERR,
	DMC_TMON_UPD,
	DMC_AREF_ALARM,
	DMC_RDTIMEOUT,
	DMC_WDATA_CNT_ERR,
	DMC_WDATA_LEN_ERR,
	DMC_CMD_CNT_ERR,
	DMC_CMD_PAYLOAD_ERR,
	DMC_ADDR_ERR,
	DMC_PHYRAM_MERR,
	DMC_PHYRAM_SERR,
	DMC_RPRAM_MERR,
	DMC_RPRAM_SERR,
	DMC_SBRAM_MERR,
	DMC_SBRAM_SERR,
	DMC_WSRAM_MERR,
	DMC_WSRAM_SERR,
	DMC_ECCWB_RFIFO_OFLOW,
	DMC_ECCWB_RFIFO_UFLOW,
	DMC_ECCWB_WFIFO_OFLOW,
	DMC_ECCWB_WFIFO_UFLOW,
	DMC_ECCWB_INFOFIFO_OFLOW,
	DMC_ECCWB_INFOFIFO_UFLOW,
	DMC_LECC_MERR,
	DMC_LECC_SERR,
	DMC_LECC_RFIFO_OFLOW,
	DMC_LECC_RFIFO_UFLOW,
	DMC_DAS_WFIFO_OFLOW,
	DMC_DAS_WFIFO_UFLOW,
	DMC_DAS_RFIFO_OFLOW,
	DMC_DAS_RFIFO_UFLOW,
	IECC_REG_PARITY_ERR,
	IECC_IECC_SERR_ADDR,
	IECC_RDATA_POISON_ERR,
	IECC_RDATA_TYPE_ERR,
	IECC_RDATA_LEN_ERR,
	IECC_RDATA_ID_ERR,
	IECC_SB_PAYLOAD_ERR,
	IECC_CMD_PAYLOAD_ERR,
	IECC_WDATA_POISON_ERR,
	IECC_DEC_ADDR_ERR,
	IECC_ENC_ADDR_ERR,
	IECC_EXP_OP_ERR,
	IECC_EXP_ADDR_ERR,
	IECC_IECC_MERR,
	IECC_IECC_DERR,
	IECC_IECC_SERR,
	IECC_ADDRFIFO_OFLOW,
	IECC_ADDRFIFO_UFLOW,
	IECC_SBFIFO_OFLOW,
	IECC_SBFIFO_UFLOW,
	IECC_GRTFIFO_OFLOW,
	IECC_GRTFIFO_UFLOW,
	IECC_ADDRRAM_DERR,
	IECC_ADDRRAM_SERR,
	IECC_SBRAM_DERR,
	IECC_SBRAM_SERR,
	IECC_RBUF_DERR,
	IECC_RBUF_SERR,
	IECC_WBUF_DERR,
	IECC_WBUF_SERR,
	TREG_REG_PARITY_ERR,
	TREG_GRTFIFO_OFLOW,
	TREG_GRTFIFO_UFLOW,
	TREG_RSPFIFO_OFLOW,
	TREG_RSPFIFO_UFLOW,
	TREG_SB_PAYLOAD_ERR,
	TREG_ADDR_ERR,
	UCE_SCTRL_REG_PARITY_ERR,
	UCE_SCTRL_SW_ERR3,
	UCE_SCTRL_SW_ERR2,
	UCE_SCTRL_SW_ERR1,
	UCE_SCTRL_SW_ERR0,
	UCE_SCTRL_TIMER1_LOCKSTEP_ERR,
	UCE_SCTRL_TIMER0_LOCKSTEP_ERR,
	UCE_SCTRL_DBUS_PARITY_ERR,
	UCE_SCTRL_IBUS_PARITY_ERR,
	UCE_SCTRL_WDG_RESETREQ,
	UCE_SCTRL_WDG_INTR,
	DUMREG_REG_PARITY_ERR,
	DUMREG_CMD_PAYLOAD_ERR,
	PACKPHY_INT_STATUS_PAR,
	PACKPHY_DX_STATUS_PAR,
	PACKPHY_AC_STATUS_PAR,
	PACKPHY_MISC_PAR,
	PACKPHY_PHY_AC_DLY_PAR,
	PACKPHY_PHY_TX_DLY_PAR,
	PACKPHY_PHY_RX_DLY_PAR,
	PACKPHY_PACK_AC_DLY_PAR,
	PACKPHY_PACK_TX_DLY_PAR,
	PACKPHY_PACK_RX_DLY_PAR,
	PACKPHY_PHY_UPD_TIMEOUT,
	PACKPHY_PLL_UNLOCK,
	PACKPHY_GATE_ERR1,
	PACKPHY_GATE_ERR0
};
#endif /* SAFETY_RAS_CONVERGE_610_H */