# SPDX-License-Identifier: GPL-2.0
obj-m := drv_lpm_devmng.o

drv_lpm_devmng-objs := init/lpm_devmng_init.o
drv_lpm_devmng-objs += public/lpm_devmng_common.o
drv_lpm_devmng-objs += api/lpm_devmng_dsmi.o
drv_lpm_devmng-objs += dfx/statistics/lpm_devmng_statistics.o
drv_lpm_devmng-objs += dfx/debugfs/lpm_devmng_debugfs.o
drv_lpm_devmng-objs += dfx/debugfs/lpm_debugfs_base.o

DRIVER_INC := $(src)/../..

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/public -I$(src)/dfx -I$(src)/dfx/debugfs
ccflags-y += -I$(src)/dfx/statistics -I$(src)/init -I$(src)/srv -I$(src)/api
ccflags-y += -I$(src)/drv -I$(src)/drv/include -I$(src)/drv/idle_drv
ccflags-y += -I$(src)/drv/frequency_drv -I$(src)/drv/temperature_drv
ccflags-y += -I$(src)/drv/aic_freq_drv -I$(src)/drv/sharemem_drv
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion
ccflags-y += -fstack-protector-all

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DLPM_BUILD_DEBUG -DLPM_POWER_SAMPLING
endif

ifneq ($(filter $(PRODUCT), ascend910B),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_temperature.o
drv_lpm_devmng-objs += drv/temperature_drv/lpm_devmng_temperature_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_power.o
drv_lpm_devmng-objs += srv/lpm_devmng_tool.o
drv_lpm_devmng-objs += srv/lpm_devmng_turbo.o
drv_lpm_devmng-objs += srv/lpm_devmng_idle.o
drv_lpm_devmng-objs += drv/idle_drv/lpm_devmng_idle_ascend910b.o
drv_lpm_devmng-objs += srv/lpm_devmng_frequency.o
drv_lpm_devmng-objs += drv/frequency_drv/lpm_devmng_frequency_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_soc_stress.o
drv_lpm_devmng-objs += drv/aic_freq_drv/lpm_devmng_aic_freq_sharemem_v2.o
drv_lpm_devmng-objs += api/lpm_devmng_api.o
drv_lpm_devmng-objs += srv/lpm_devmng_aic_freq.o
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DLPM_SHAREMEM_V2 -DLPM_IPC_V3 -DLPM_TEMPERATURE
ccflags-y += -DLPM_LPTEST -DLPM_SOC_STRESS -DLPM_POWER -DLPM_TURBO
ccflags-y += -DLPM_IDLE -DLPM_FREQUENCY -DLPM_AIC_FREQ_SYSCNT
ccflags-y += -DLPM_AIC_FREQ -DLPM_DSMI_MAIN_CMD_LP
endif

ifneq ($(filter $(PRODUCT), ascend920esl ascend920emu),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_temperature.o
drv_lpm_devmng-objs += drv/temperature_drv/lpm_devmng_temperature_sharemem_v2.o
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DLPM_SHAREMEM_V2 -DLPM_IPC_V3 -DLPM_TEMPERATURE
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a BS9SX1A),)
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += srv/lpm_devmng_frequency.o
drv_lpm_devmng-objs += drv/frequency_drv/lpm_devmng_frequency_ascend610.o
drv_lpm_devmng-objs += srv/lpm_devmng_temperature.o
drv_lpm_devmng-objs += drv/temperature_drv/lpm_devmng_temperature_ascend610.o
drv_lpm_devmng-objs += public/lpm_log_base.o
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DLPM_IPC_V2 -DLPM_FREQUENCY -DLPM_TEMPERATURE
ccflags-y += -DLPM_BUILD_DEBUG -DLPM_VPRINTK
endif

ifneq ($(filter $(PRODUCT), ascend610Lite),)
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += srv/lpm_devmng_tool.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v2.o
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += public/lpm_log_base.o
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51_LITE
ccflags-y += -DLPM_IPC_V3 -DLPM_BUILD_DEBUG -DLPM_LPTEST
ccflags-y += -DLPM_START_DIRECT -DLPM_SHAREMEM_V2 -DLPM_VPRINTK
endif

ifneq ($(filter $(PRODUCT), ascend310p),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v1.o
drv_lpm_devmng-objs += srv/lpm_devmng_aic_freq.o
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DLPM_SHAREMEM_V1 -DLPM_AIC_FREQ -DLPM_DSMI_MAIN_CMD_LP
endif

ifneq ($(filter $(PRODUCT), helper310p),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v1.o
drv_lpm_devmng-objs += srv/lpm_devmng_aic_freq.o
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_HELPER
ccflags-y += -DLPM_START_DIRECT -DLPM_SHAREMEM_V1
ccflags-y += -DLPM_AIC_FREQ -DLPM_DSMI_MAIN_CMD_LP
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310Brc),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += public/lpm_devmng_flash.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_profile.o
drv_lpm_devmng-objs += srv/lpm_devmng_tool.o
drv_lpm_devmng-objs += srv/lpm_devmng_idle.o
drv_lpm_devmng-objs += drv/idle_drv/lpm_devmng_idle_ascend310b.o
drv_lpm_devmng-objs += srv/lpm_devmng_frequency.o
drv_lpm_devmng-objs += drv/frequency_drv/lpm_devmng_frequency_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_temperature.o
drv_lpm_devmng-objs += drv/temperature_drv/lpm_devmng_temperature_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_aic_freq.o
drv_lpm_devmng-objs += drv/aic_freq_drv/lpm_devmng_aic_freq_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_acg_cnt.o
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DLPM_IPC_V3 -DLPM_IDLE -DLPM_PROFILE -DLPM_FLASH
ccflags-y += -DLPM_LPTEST -DLPM_SHAREMEM_V2 -DLPM_FREQUENCY
ccflags-y += -DLPM_TEMPERATURE -DLPM_AIC_FREQ_SYSCNT -DLPM_AIC_FREQ
ccflags-y += -DLPM_ACG_CNT -DLPM_DSMI_MAIN_CMD_LP
endif

ifneq ($(filter $(PRODUCT), ascend310Brc),)
drv_lpm_devmng-objs += srv/lpm_devmng_suspend.o
drv_lpm_devmng-objs += srv/lpm_devmng_vrd_upgrade.o
ccflags-y += -DLPM_SUSPEND -DLPM_VRD_UPGRADE -DLPM_TRANSFORM_DEVID
endif

ifneq ($(filter $(PRODUCT), as31xm1),)
drv_lpm_devmng-objs += public/lpm_devmng_sharemem.o
drv_lpm_devmng-objs += public/lpm_devmng_ipc.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_drv.o
drv_lpm_devmng-objs += drv/sharemem_drv/lpm_devmng_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_tool.o
drv_lpm_devmng-objs += srv/lpm_devmng_suspend.o
drv_lpm_devmng-objs += srv/lpm_devmng_frequency.o
drv_lpm_devmng-objs += drv/frequency_drv/lpm_devmng_frequency_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_temperature.o
drv_lpm_devmng-objs += drv/temperature_drv/lpm_devmng_temperature_sharemem_v2.o
drv_lpm_devmng-objs += srv/lpm_devmng_health_status.o
drv_lpm_devmng-objs += srv/lpm_devmng_volt_current.o
drv_lpm_devmng-objs += srv/lpm_devmng_acg_cnt.o
drv_lpm_devmng-objs += srv/lpm_devmng_aic_freq.o
drv_lpm_devmng-objs += srv/lpm_devmng_temp_threshold.o
drv_lpm_devmng-objs += public/lpm_log_base.o
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_SOC_PLATFORM_MDC_V11
ccflags-y += -DCFG_FEATURE_DMS_SUPPORT_ALL
ccflags-y += -DLPM_IPC_V3 -DLPM_LPTEST -DLPM_SHAREMEM_V2
ccflags-y += -DLPM_FREQUENCY -DLPM_TEMPERATURE -DLPM_HEALTH_STATUS
ccflags-y += -DLPM_VOLT_CURRENT -DLPM_ACG_CNT -DLPM_AIC_FREQ
ccflags-y += -DLPM_SUSPEND -DLPM_DSMI_MAIN_CMD_LP
ccflags-y += -DLPM_TEMP_THRESHOLD -DLPM_VPRINTK
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h


KBUILD_EXTRA_SYMBOLS := $(src)/../../dms/Module.symvers \
	$(src)/../../icm/Module.symvers \
	$(src)/../../uda/Module.symvers \
	$(src)/../../urd/Module.symvers \
	$(src)/../../user_cfg/Module.symvers
