LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := drv_pm
LOCAL_DEPEND_KO := drv_serdes

LOCAL_KO_SRC_FOLDER := $(LOCAL_PATH)
LOCAL_INSTALLED_KO_FILES := $(LOCAL_MODULE).ko

include $(BUILD_DEVICE_KO)
