/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2021. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */

#ifndef _NVME_DRV_H_
#define _NVME_DRV_H_

#include "hipciec_soc_doorbell_reg_reg_offset.h"

#define AGENTDRV_CORE_NUM 1
#define AGENTDRV_PORT_NUM 0

#define MAX_AGENTDEV_CNT 4  /* ctrl common */
#define MAX_AGENTFUNC_CNT 1
#define AGENTDRV_1PF_OF_FUNC_TOTAL 1 /* one chip has one die(function) now */

#define HISI_IEP_NVME_DEVICE_ID 0xa124

#define PCI_BAR_RSV_MEM 0
#define PCI_BAR_IO 2
#define PCI_BAR_MEM 4

#define DEVDRV_PF_NUM 0
#define DEVDRV_CORE_NUM 0x1
#define DEVDRV_PORT_NUM 0x0

#define AGENTDRV_SOC_DB_IRQ_ADDR 0xA0170000
#define AGENTDRV_SOC_DB_IRQ_SIZE 0x10000
#define AGENTDRV_SOC_DB_RAISE_INIT_ADDR 0xA020C0A0U
#define AGENTDRV_SOC_DB_RAISE_INIT_SIZE 0x10
#define AGENTDRV_SOC_DB_IRQ_NUM 4

#define DEVDRV_CHIP_ADDR_SPACE_SIZE 0

#define DEVDRV_IO_TS_DB_OFFSET 0xA00000
#define DEVDRV_IO_TS_DB_SIZE 0x400000
#define DEVDRV_IO_TS_SRAM_OFFSET 0xE00000
#define DEVDRV_IO_TS_SRAM_SIZE 0x20000
#define DEVDRV_IO_HWTS_OFFSET 0xE60000
#define DEVDRV_IO_HWTS_SIZE 0x10000

#ifdef CFG_SOC_PLATFORM_MDC_V11
#define DEVDRV_PCIE_RESERVE_MEM_ADDR 0xB100000ULL
#define DEVDRV_PCIE_RESERVE_MEM_SIZE (8 * 1024 * 1024 - 128 * 1024)
#else
#define DEVDRV_PCIE_RESERVE_MEM_ADDR 0x21000000ULL
#define DEVDRV_PCIE_RESERVE_MEM_SIZE (16 * 1024 * 1024)
#endif

#define AGENTDRV_DB_MEM_ADDRESS 0xa0170000U
#define AGENTDRV_DB_MEM_SIZE 0x10000
#define AGENTDRV_DB_STRDE 8

#define DEVDRV_RESERVE_MEM_DRV_BASE 0x80000   /* driver use merroy base */

#define AGENTDRV_NVME_SQ_DB_IRQ_NUM 2
#define AGENTDRV_NVME_DB_IRQ_BASE 32
#define AGENTDRV_NVME_DB_IRQ_NUM 4
#define AGENTDRV_VF_SOC_DB_IRQ_NUM AGENTDRV_NVME_DB_IRQ_NUM
#define AGENTDRV_NVME_LOW_LEVEL_DB_IRQ_NUM 4
#define AGENTDRV_NVME_DB_IRQ_STRDE 8
#define AGENTDRV_QCNT_EACH_IRQ 32
#define AGENTDRV_TOTALE_DB_IRQ_NUM 64

#define AGENTDRV_MAX_IO_MSG_CHAN 60

#define AGENTDRV_MSG_CHAN_USED_DB_START 0
#define AGENTDRV_MSG_CHAN_USED_DB_END AGENTDRV_MAX_IO_MSG_CHAN

#define AGENTDRV_P2P_MSG_USED_DB_START 61
#define AGENTDRV_P2P_MSG_USED_DB_END 62
#define AGENTDRV_P2P_MSG_USED_DB_NUM (AGENTDRV_P2P_MSG_USED_DB_END - AGENTDRV_P2P_MSG_USED_DB_START)

#define AGENTDRV_GENERAL_INTR_USED_DB_START 62
#define AGENTDRV_GENERAL_INTR_USED_DB_END 63
#define AGENTDRV_GENERAL_INTR_USED_DB_NUM (AGENTDRV_GENERAL_INTR_USED_DB_END - AGENTDRV_GENERAL_INTR_USED_DB_START)

#define AGENTDRV_TEST_USED_DB_ID 63
#define AGENTDRV_TEST_USED_INTR_NUM 2

#define NVME_INT_REQ_OFFSET 0
#define NVME_INT_VECTOR_OFFSET 1
#define NVME_INT_PF_NUM_OFFSET 26
#define NVME_INT_VF_NUM_OFFSET 16

#define AGENTDRV_NVME_INT_REQ 0
#define AGENTDRV_NVME_SQ_DB_STS_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_STATUS_PF_REG
#define AGENTDRV_NVME_CQ_DB_STS_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_STATUS_PF_REG
#define AGENTDRV_NVME_INT_VECTOR_MASK_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_MASK_PF_SYS_REG

#define DEVDRV_NVME_CTRL_PF_OFST 0x2000

#endif
