# SPDX-License-Identifier: GPL-2.0

obj-m := drv_dp_proc_mng_host.o

drv_dp_proc_mng_host-objs := \
	dp_proc_mng_msg_client.o \
	common/dp_proc_mng_module_ops.o \
	comm/dp_proc_mng_proc_info.o \
	comm/dp_proc_mng_master_register_ops.o \
	comm/dp_proc_mng_channel.o \
	common/dp_proc_mng_pci_dev_tbl.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -Wall -Werror
ccflags-y += -Wtrampolines -Wfloat-equal -Wvla -Wundef
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers

ccflags-y += -DCFG_FEATURE_SHARE_LOG

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/common -I$(src)/comm

KBUILD_EXTRA_SYMBOLS := $(src)/../pcie/Module.symvers $(src)/../davinci_intf/Module.symvers

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/internal/host_config.h
ccflags-y += -include $(DRIVER_INC)/include/compat.h
