# SPDX-License-Identifier: GPL-2.0
obj-m := ipc_drv.o
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o drv_snapshot.o miniv3/hisi_rproc_adapt.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/miniv3
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DSNAPSHOT_ENABLE -DNOT_SUPPORT_OSNAME
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
