# SPDX-License-Identifier: GPL-2.0
obj-m := ipc_drv.o

DRIVER_INC := $(src)/..

ccflags-y += -Wall -Werror -Wtrampolines -Wfloat-equal -Wvla -Wundef
ccflags-y += -funsigned-char -Wformat=2 -Wstack-usage=2048 -Wcast-align
ccflags-y += -Wextra -Wno-unused-parameter -Wno-sign-compare
ccflags-y += -Wno-missing-field-initializers

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)

ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -I$(src)/cloud_v2
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o cloud_v2/hisi_rproc_adapt.o
else ifneq ($(filter $(PRODUCT),ascend910),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -I$(src)/cloud
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o cloud/hisi_rproc_adapt.o
else ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2_MDC -DSNAPSHOT_ENABLE
ccflags-y += -I$(src)/mdc
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o drv_cpu_type.o mdc/hisi_rproc_adapt.o
else ifneq ($(filter $(PRODUCT),ascend310p helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DIPC_ACPI_SUPPORT
ccflags-y += -I$(src)/mdc
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o mdc/hisi_rproc_adapt.o
else ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -I$(src)/miniv3 -I$(DRIVER_INC)/include/soc/mini_v3

ifneq ($(filter $(PRODUCT),ascend310Brc ascend310Brcesl ascend310Brcemu as31xm1),)
ccflags-y += -DSNAPSHOT_ENABLE -DNOT_SUPPORT_OSNAME
endif

ifneq ($(filter $(PRODUCT),as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif

ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o miniv3/hisi_rproc_adapt.o
else
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(src)/mini
ipc_drv-objs := hisi_mailbox.o hisi_rproc.o hisi_mailbox_dev.o hisi_mailbox_asm.o
ipc_drv-objs += drv_snapshot.o mini/hisi_rproc_adapt.o
endif

ifneq ($(filter $(PRODUCT),ascend310p),)
ccflags-y += -DCFG_EDP_MSG
endif

ifneq ($(filter $(PRODUCT),helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
