# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_core.o
ascend_trs_core-objs := trs_fops.o trs_ts_inst.o trs_proc.o trs_res_mng.o trs_sqcq_map.o trs_hw_sqcq.o trs_sw_sqcq.o trs_logic_cq.o trs_cb_sqcq.o trs_shm_sqcq.o trs_proc_fs.o

ifeq ($(TARGET_BUILD_TYPE),debug)
ascend_trs_core-objs += trs_core_trace.o
ccflags-y += -DCFG_BUILD_DEBUG
endif

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) 

KBUILD_EXTRA_SYMBOLS := $(src)/../davinci_intf/Module.symvers \
	$(src)/../dms/Module.symvers \
	$(src)/../event_sched/Module.symvers \
	$(src)/../trs_chan/Module.symvers \
	$(src)/../trs_id_allocator/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
