# SPDX-License-Identifier: GPL-2.0
obj-m := drv_ts.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss
ccflags-y += -I$(DRIVER_INC)/include/aicpu/common
ccflags-y += -I$(DRIVER_INC)/event_sched -I$(DRIVER_INC)/event_sched/comm
ccflags-y += -I$(src) -I$(DRIVER_INC)/include/soc/cloud_v1
KBUILD_EXTRA_SYMBOLS := $(src)/../dfm/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -I$(src)/cloud -I$(src)/cloudv2 -I$(DRIVER_INC)/include/soc/cloud_v2
drv_ts-objs := ts_drv_init.o cloudv2/hwts_drv_cloudv2.o
else ifneq ($(filter $(PRODUCT), ascend910),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -I$(src)/cloud
drv_ts-objs := ts_drv_init.o cloud/ts_drv_sysfs.o cloud/hwts_drv_cloud.o cloud/ts_aisle_queue.o
else ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -I$(src)/miniv3 -I$(DRIVER_INC)/include/soc/mini_v3
ifneq ($(filter $(PRODUCT), as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif
drv_ts-objs := ts_drv_init.o miniv3/hwts_drv_miniv3.o
else ifneq ($(filter $(PRODUCT), ascend310p helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_ASCEND_FLORENCE_ASCEND610
ccflags-y += -I$(src)/miniv2 -I$(src)/cloud
ifneq ($(filter $(PRODUCT), helper310p),)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER
endif
drv_ts-objs := ts_drv_init.o miniv2/ts_drv_sysfs.o miniv2/hwts_drv_miniv2.o miniv2/ts_aisle_ipc.o
else ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MDC_V51 -DSUPPORT_FLEXIBLE_BIND_CORE
ccflags-y += -I$(src)/miniv2 -I$(src)/cloud
ifneq ($(filter $(PRODUCT), ascend610),)
ccflags-y += -DCFG_ASCEND_FLORENCE_ASCEND610
else ifneq ($(filter $(PRODUCT), bs9sx1a),)
ccflags-y += -DCFG_ASCEND_FLORENCE_BS9SX1A
endif
drv_ts-objs := ts_drv_init.o miniv2/ts_drv_sysfs.o miniv2/bind_core.o miniv2/hwts_drv_miniv2.o miniv2/ts_aisle_ipc.o
else ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(src)/mini
drv_ts-objs := mini/ts_drv_init.o mini/hwts_drv_ascend310.o mini/ts_aisle_queue.o mini/ts_drv_sysfs.o
else
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(src)/mini
drv_ts-objs := mini/ts_drv_init.o mini/hwts_drv_ascend310.o mini/ts_aisle_queue.o mini/ts_drv_sysfs.o
endif

ccflags-y += -I$(DRIVER_INC)/include/internal
