# SPDX-License-Identifier: GPL-2.0
obj-m := dbl_board_config.o
dbl_board_config-objs := board_config_module.o serdes/board_serdes_info.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/dbl -I$(DRIVER_INC)/include
ccflags-y += -I$(DRIVER_INC)/include/driver -I$(src) -I$(src)/serdes
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
