# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_vdp_hifb.o
ascend_vdp_hifb-objs := src/gfbg_main.o src/init/linux/gfbg_init.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(DRIVER_INC)/include/media -I$(src) -I$(src)/include -I$(src)/src -I$(src)/src/init -I$(src)/src/init/linux -I$(src)/common
ccflags-y += -I$(src)/drv/adp -I$(src)/drv/include -I$(src)/drv/tde/include -I$(src)/drv/tde/adp/tde_v2_0
ccflags-y += -I$(src)/mkp -I$(src)/mkp/hal -I$(src)/mkp/hal/ctrl/v200 -I$(src)/mkp/hal/phy/v200
ccflags-y += -I$(src)/mkp/product/archv200 -I$(src)/mkp/init/archv200/include -I$(src)/mkp/osal/v600 -I$(src)/mkp/dfx
ccflags-y += -I$(src)/api/tde/include -I$(src)/mpi -I$(src)/drv/init/include -I$(src)/stub

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-pointer-types -Wno-return-type -Wno-date-time
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion


KBUILD_EXTRA_SYMBOLS := $(src)/../dvpp_osal/Module.symvers