/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#ifndef MEMORY_FAULT_CONVERGE_H
#define MEMORY_FAULT_CONVERGE_H

/* OEM: RAS IERR ERR TYPE */
#define RAS_ECC_SINGLE_BIT_ING_BUF_MEM	   0x0E
#define RAS_ECC_SINGLE_BIT_SDIR_MEM		  0x0F
#define RAS_ECC_SINGLE_BIT_SDMAA_MEM		 0x10
#define RAS_ECC_SINGLE_BIT_DATA_BUF_MEM	  0x11
#define RAS_ECC_SINGLE_BIT_REQDAT_BUF_MEM	0x14
#define RAS_ECC_SINGLE_BIT_SHARE_BUF_MEM	 0x1A
#define RAS_ECC_MULTI_BIT_ING_BUF_MEM		0x02
#define RAS_ECC_MULTI_BIT_SDIR_MEM		   0x03
#define RAS_ECC_MULTI_BIT_DATA_BUF_MEM	   0x07
#define RAS_ECC_MULTI_BIT_SDMAA_MEM		  0x12
#define RAS_ECC_MULTI_BIT_REQDAT_BUF_MEM	 0x13
#define RAS_ECC_MULTI_BIT_SHARE_BUF_MEM	  0x19
#define RAS_ILLEGAL_REQUEST				  0x01
#define RAS_NON_SEC_REQ_ACCESS_SEC_ZONE	  0x06
#define RAS_SEC_REQ_ACCESS_NON_SEC_ZONE	  0x0C
#define RAS_DEFAULT_SLAVE					0x05
#define RAS_INVERT_MSD					   0x0B
#define RAS_OVERLAP_MSD					  0x0A
#define RAS_MISS_MSD						 0x09
#define RAS_DMC_RDATA_MAIN_ERROR			 0x17
#define RAS_DMC_RDATA_MIRROR_ERROR		   0x18
#define RAS_REDUCE_ATOMIC_BOTHNAN_ERROR	  0x1F
#define RAS_REDUCE_ATOMIC_SRCNAN_ERROR	   0x1D
#define RAS_REDUCE_ATOMIC_DSTNAN_ERROR	   0x1E
#define RAS_REDUCE_ATOMIC_INPUT_INF_ERROR	0x1C
#define RAS_REDUCE_ATOMIC_FP_OVERFLOW_ERROR  0x1B
#define RAS_REDUCE_ATOMIC_INT_OVERFLOW_ERROR 0x20

#define RAS_ECC_SINGLE_BIT_OF_BUF_MEM  0x0D02
#define RAS_ECC_SINGLE_BIT_OF_DIR_MEM  0x0D07
#define RAS_ECC_SINGLE_BIT_CMD_BUF_MEM  0x0E02
#define RAS_ECC_SINGLE_BIT_CMD_DIR_MEM  0x0E07
#define RAS_ECC_SINGLE_BIT_DATA_DIR_MEM  0x0F07
#define RAS_ECC_SINGLE_BIT_SDIR_BUF_MEM  0x1002
#define RAS_ECC_SINGLE_BIT_SDIR_DIR_MEM  0x1007
#define RAS_ECC_SINGLE_BIT_EDIR_BUF_MEM  0x1102
#define RAS_ECC_SINGLE_BIT_EDIR_DIR_MEM  0x1107
#define RAS_ECC_MULTI_BIT_CMD_BUF_MEM  0x0202
#define RAS_ECC_MULTI_BIT_CMD_DIR_MEM  0x0207
#define RAS_ECC_MULTI_BIT_SDIR_BUF_MEM  0x0302
#define RAS_ECC_MULTI_BIT_SDIR_DIR_MEM  0x0307
#define RAS_ECC_MULTI_BIT_EDIR_BUF_MEM  0x0402
#define RAS_ECC_MULTI_BIT_EDIR_DIR_MEM  0x0407
#define RAS_HIT_CCIX_MSD  0x120D

/* memory error */
#define RAS_MEM_CE_BELOW_THRESHOLD	  0x03
#define RAS_MEM_CE_UPPER_THRESHOLD	  0x04
#define RAS_MEM_UER_STANDARD			0x60
#define RAS_MEM_UEO_RD_PATROL		   0x41
#define RAS_MEM_UEO_RD_DS			   0x42
/* common error */
#define RAS_UER_DFI_RDDAT_VALID_TIMEOUT 0xA0
#define RAS_UEU_FATAL_HIGH_TEMPER_INT   0xA1
#define RAS_UEU_DRAM_LACK_SREF		  0xA2
#define RAS_UEU_SBRAM_UNCORRECT		 0xA3

#define RAS_UEU_RPRAM_UNCORRECT		 0xA5
#define RAS_UER_CA_PARITY			   0xE9
#define RAS_UER_RD_PARITY			   0xEB
#define RAS_UER_WR_PARITY			   0xEA
#define RAS_UEU_SRAM_UNCORRECT		  0xED

#define RAS_UEO_DAT_FLUX_OVERFLOW	   0xCF
#define RAS_UEO_DAT_FLUX_UNDERFLOW	  0xD0
#define RAS_UEO_CMD_FLUX_OVERFLOW	   0xD1
#define RAS_UEO_CMD_FLUX_UNDERFLOW	  0xD2
#define RAS_UEU_HIGH_TEMPER_INT		 0xD4

#define RAS_CE_SRAM_CORRECT			 0x96
#define RAS_CE_SBRAM_CORRECT			0x97
#define RAS_CE_RPRAM_CORRECT			0x99

static struct ras_fault_converge_item g_memory_fault_converge_table[] __attribute__((unused)) = {
	/* HBMC */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SINGLE_BIT_ECC_THOLD,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "ecc corr err")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SCRUB_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_SCRUB_UNCORRECT, "patrol scrub uncorrect err")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_MEM, STANDARD_ERR_TYPE_DSCRUB_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_SCRUB_UNCORRECT, "demand scrub uncorrect err")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_SRAM_UNCORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "wsram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_CE_SRAM_CORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "wsram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_SBRAM_UNCORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "sbram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_RPRAM_UNCORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "rpram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_CE_SBRAM_CORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "sbram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_CE_RPRAM_CORRECT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "rpram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UER_RD_PARITY,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_PARITY, "read data parity ecc error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UER_WR_PARITY,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_PARITY, "write data parity ecc error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UER_DFI_RDDAT_VALID_TIMEOUT,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "read data timeout int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UER_CA_PARITY,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_PARITY, "dimm ca parity error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_DRAM_LACK_SREF,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_ERROR, "dram lack self refresh error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEO_DAT_FLUX_OVERFLOW,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "dat flux timeout overflow int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEO_DAT_FLUX_UNDERFLOW,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "dat flux timeout underflow int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEO_CMD_FLUX_OVERFLOW,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "cmd flux timeout overflow int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEO_CMD_FLUX_UNDERFLOW,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "cmd flux timeout underflow int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_HIGH_TEMPER_INT,
		DMS_SEN_TYPE_TEMPERATURE, TEMP_ERROR_TYPE_L2H_OCCUR, "temper int resume error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_GENERIC, RAS_UEU_FATAL_HIGH_TEMPER_INT,
		DMS_SEN_TYPE_TEMPERATURE, TEMP_ERROR_TYPE_L3H_OCCUR, "fatal high temper int error")
	/* MATA */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_OF_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_OF_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_DATA_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ILLEGAL_REQUEST,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "illegal operation")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_NON_SEC_REQ_ACCESS_SEC_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "non sec req access sec zone")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_SEC_REQ_ACCESS_NON_SEC_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "sec req access non sec zone")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_DEFAULT_SLAVE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "decoding error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_HIT_CCIX_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD hit CCIX error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_INVERT_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD invert error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_OVERLAP_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD overlap error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_MISS_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD miss error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_ING_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_SDIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_SDMAA_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_REQDAT_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_SINGLE_BIT_SHARE_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_ING_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_SDIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_SDMAA_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_REQDAT_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_ECC_MULTI_BIT_SHARE_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_DMC_RDATA_MAIN_ERROR,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "Mirror main error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_MEM, RAS_DMC_RDATA_MIRROR_ERROR,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_MIRROR_SUB_ERROR, "Mirror sub error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_REDUCE_ATOMIC_BOTHNAN_ERROR,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "reduce atomic bothnan error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_REDUCE_ATOMIC_SRCNAN_ERROR,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "reduce atomic srcnan error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_REDUCE_ATOMIC_DSTNAN_ERROR,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "reduce atomic dstnan error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC, RAS_REDUCE_ATOMIC_INPUT_INF_ERROR,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "reduce atomic input inf error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC,
		RAS_REDUCE_ATOMIC_FP_OVERFLOW_ERROR, DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR,
		"reduce atomic fp overflow error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_GENERIC,
		RAS_REDUCE_ATOMIC_INT_OVERFLOW_ERROR, DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR,
		"reduce atomic int overflow error")
};
#endif /* MEMORY_FAULT_CONVERGE_H */
