/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */
#ifndef PROF_COMM_H
#define PROF_COMM_H

/* add for ascd310p */
#define PROF_CHIP_ADDR_OFFSET 0x8000000000
#define PROF_VFID_NUM_MAX 9
#define PROF_CHANNEL_HW_NUM 8 /* add for 43&45 channel, describe hardware num */
#define PROF_SUB_CHANNEL_NUM_MAX     PROF_VFID_NUM_MAX
#define PROF_TS_BUF_VIR_ONE_ZONE_SIZE (2 * PROF_TS_BUFFER_LEN) /* size should 2^n Byte */
#define PROF_TS_BUF_VIR_TOTAL_SIZE (PROF_TS_BUF_VIR_ONE_ZONE_SIZE * PROF_CHANNEL_HW_NUM)
#define PROF_TS_BUF_PHY_AIC_BUF_SIZE (2 * PROF_TS_BUFFER_LEN_MAX)
#define PROF_DC_AICORE_RESERVED_MEM_ADDR 0x26D00000
#define PROF_DC_HWTS0_RESERVED_MEM_ADDR (PROF_DC_AICORE_RESERVED_MEM_ADDR + PROF_TS_BUF_VIR_TOTAL_SIZE)

/* add for ascd610 */
#define PROF_GROUP_NUM_MAX 4
#define PROF_TS_BUF_ONE_GROUP_SIZE PROF_TS_BUFFER_LEN
#define PROF_TS_BUF_TOTAL_GROUP_SIZE (PROF_TS_BUF_ONE_GROUP_SIZE * PROF_GROUP_NUM_MAX) // 4 * 1024 * 1024
#define PROF_MDC_AICORE_RESERVED_MEM_ADDR 0x26D00000
#define PROF_MDC_AIV_RESERVED_MEM_ADDR (PROF_MDC_AICORE_RESERVED_MEM_ADDR + PROF_TS_BUF_TOTAL_GROUP_SIZE)
#define PROF_MDC_HWTS0_RESERVED_MEM_ADDR (PROF_MDC_AIV_RESERVED_MEM_ADDR + PROF_TS_BUF_TOTAL_GROUP_SIZE)
#define PROF_MDC_HWTS1_RESERVED_MEM_ADDR (PROF_MDC_HWTS0_RESERVED_MEM_ADDR + PROF_TS_BUF_TOTAL_GROUP_SIZE)
#define PROF_MDC_TSCPU_RESERVED_MEM_ADDR (PROF_MDC_HWTS1_RESERVED_MEM_ADDR + PROF_TS_BUF_TOTAL_GROUP_SIZE)
#define PROF_MDC_TSFW_RESERVED_MEM_ADDR (PROF_MDC_TSCPU_RESERVED_MEM_ADDR + PROF_TS_BUFFER_LEN)
#define PROF_MDC_TSFW1_RESERVED_MEM_ADDR (PROF_MDC_TSFW_RESERVED_MEM_ADDR + PROF_TS_BUFFER_LEN)
#define PROF_MDC_KEY_POINT_RESERVED_MEM_ADDR (PROF_MDC_TSFW1_RESERVED_MEM_ADDR + PROF_TS_BUFFER_LEN)
#define PROF_MDC_TSFW_L2_RESERVED_MEM_ADDR (PROF_MDC_KEY_POINT_RESERVED_MEM_ADDR + PROF_TS_BUFFER_LEN)

#endif // PROF_COMM_H
