/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#ifndef SERDES_SNAPSHOT_H
#define SERDES_SNAPSHOT_H

#include <linux/types.h>
#include "drv_snapshot.h"

typedef enum {
    SERDES_SUSPEND_BEGIN = 0,
    SERDES_SUSPEND_CHECK_MACRO0_HILINK_REG_BASE_FAIL = 1,
    SERDES_SUSPEND_CHECK_MACRO1_HILINK_REG_BASE_FAIL = 2,
    SERDES_SUSPEND_EXPECT = 9,

    SERDES_REMOVE_BEGIN = 10,
    SERDES_REMOVE_EXPECT = 19,

    SERDES_STARTUP_BEGIN = 20,
    SERDES_RESUME_BEGIN = 21,

    SERDES_INIT_REMAP_SUBCTRL0_FAIL = 22,
    SERDES_INIT_REMAP_REG0_FAIL = 23,
    SERDES_INIT_REMAP_SUBCTRL1_FAIL = 24,
    SERDES_INIT_REMAP_REG1_FAIL = 25,
    SERDES_INIT_REMAP_IO_FAIL = 26,

    SERDES_CFG_REMAP_SRAM_FAIL = 27,

    SERDES_CFG_SHMG_HEAD_CHECK_FAIL = 28,
    SERDES_CFG_FIND_NODE_FAIL = 29,
    SERDES_CFG_NODE_ADDR_EXCEED_FAIL = 30,
    SERDES_CFG_NODE_CHECK_FAIL = 31,
    SERDES_CFG_NODE_INVALID_FAIL = 32,

    SERDES_CFG_REMAP_DDR_FAIL = 33,

    SERDES_INFO_CHECK_DDR_NODE_FAIL = 34,

    SERDES_INFO_CHECK_FLAG_FAIL = 35,
    SERDES_INFO_CHECK_INDEX_FAIL = 36,
    SERDES_INFO_CHECK_PCIE_FREQ_FAIL = 37,
    SERDES_INFO_CHECK_SATA_FREQ_FAIL = 38,
    SERDES_INFO_CHECK_USB_FREQ_FAIL = 39,
    SERDES_INFO_CHECK_ETH_FREQ_FAIL = 40,
    SERDES_INFO_CHECK_BANDWIDTH_FAIL = 41,
    SERDES_INFO_CHECK_SSC_FAIL = 42,
    SERDES_INFO_CHECK_FAIL = 43,
    SERDES_INFO_CHECK_M0_PROTOCOL_TYPE_FAIL = 44,
    SERDES_INFO_CHECK_M1_PROTOCOL_TYPE_FAIL = 45,
    SERDES_INFO_CHECK_M1_PROTOCOL_NUM_FAIL = 46,

    SERDES_INFO_CHECK_PCIE_SSC_FAIL = 47,
    SERDES_INFO_CHECK_SATA_SSC_FAIL = 48,

    SERDES_INFO_CHECK_ETH_SAME_FREQ_FAIL = 49,

    SERDES_INFO_CHECK_USB_AND_PCIE_SSC_FAIL = 50,

    SERDES_INFO_CHECK_MACRO_CFG_FAIL = 51,
    SERDES_INFO_CHECK_MACRO_NUM_FAIL = 52,
    SERDES_INFO_CHECK_BID_FAIL = 53,

    SERDES_POWER_ON_CREATE_THREAD0_FAIL = 54,
    SERDES_POWER_ON_CREATE_THREAD1_FAIL = 55,
    SERDES_POWER_ON_CHECK_MACRO_CFG_FAIL = 56,
    SERDES_POWER_ON_READ_REG_FAIL = 57,
    SERDES_POWER_ON_WRITE_REG_FAIL = 58,
    SERDES_POWER_ON_CHECK_REG_FAIL = 59,
    SERDES_POWER_ON_REG0_WRITE_TIMEOUT_FAIL = 60,
    SERDES_POWER_ON_REG1_WRITE_TIMEOUT_FAIL = 61,
    SERDES_POWER_ON_REG0_WRITE_FAIL = 62,
    SERDES_POWER_ON_REG1_WRITE_FAIL = 63,

    SERDES_GET_FSM_DONE_FAIL = 64,
    SERDES_WAIT_FSM_DONE_FAIL = 65,

    SERDES_START_TOP_FSW_TIMEOUT_FAIL = 66,

    SERDES_STOP_SLICE_FW_TASK_TIMEOUT_FAIL = 67,

    SERDES_ETH_RX_PARA_CONFIG_MACRO_CHECK_FAIL = 68,
    SERDES_ETH_RX_PARA_CONFIG_DS_CHECK_FAIL = 69,
    SERDES_ETH_RX_PARA_CONFIG_RATE_CHECK_FAIL = 70,

    SERDES_RESUME_FAIL = 96,
    SERDES_STARTUP_FAIL = 97,
    SERDES_RESUME_EXPECT = 98,
    SERDES_STARTUP_EXPECT = 99
} SERDES_SNAPSHOT_TYPE;

#endif