# Describe the include path, using the full path

# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_PNGD_ROOT)/mkp/src/pngd.c
SRCS += $(CBB_PNGD_ROOT)/mkp/src/pngd_buf.c
SRCS += $(CBB_PNGD_ROOT)/mkp/src/pngd_ext.c
SRCS += $(CBB_PNGD_ROOT)/mkp/src/pngd_proc.c
SRCS += $(CBB_PNGD_ROOT)/mkp/src/pngd_intf.c
