#add_subdirectory(near)
if (${PRODUCT_SIDE} STREQUAL host)
    add_subdirectory(near)
else ()
    add_subdirectory(local)
    if(${PRODUCT} STREQUAL ascend310B OR ${PRODUCT} STREQUAL ascend310Besl
            OR ${PRODUCT} STREQUAL ascend910B OR ${PRODUCT} STREQUAL as31xm1)
        add_subdirectory(near)
        endif()
endif()