LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := hns3

LOCAL_KO_SRC_FOLDER := $(LOCAL_PATH)
LOCAL_DEPEND_KO := hnae3

LOCAL_INSTALLED_KO_FILES := hns3.ko

include $(BUILD_DEVICE_KO)

