# SPDX-License-Identifier: GPL-2.0
obj-m := drv_pm.o
drv_pm-objs := pm.o

DRIVER_INC := $(src)/../..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/internal
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)
ccflags-y += -DHAL_KERNEL_SUSPEND_RESUME
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
