/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2021. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */

#ifndef _NVME_DRV_H_
#define _NVME_DRV_H_

#include "hipciec_soc_doorbell_reg_reg_offset.h"

#define AGENTDRV_CORE_NUM 1
#define AGENTDRV_PORT_NUM 0

#define MAX_AGENTDEV_CNT 64  /* ctrl common */
#define MAX_AGENTFUNC_CNT 17
#define AGENTDRV_1PF_OF_FUNC_TOTAL 2 /* one chip has two die(function) now */

#define HISI_IEP_NVME_DEVICE_ID 0xa124

#define PCI_BAR_RSV_MEM 0
#define PCI_BAR_IO 2
#define PCI_BAR_MEM 4

#define DEVDRV_PF_NUM 0

#define DEVDRV_PCIE_HBM_MEM_ADDR 0x80000000ULL
#define DEVDRV_PCIE_HBM_MEM_SIZE 0x3E00000ULL

#define DEVDRV_DIE_TX_ATU_SPACE_OFFSET 0x100000000000ULL
#define DEVDRV_DIE_ADDR_SPACE_SIZE 0x10000000000ULL
#define DEVDRV_CHIP_ADDR_SPACE_SIZE 0x10000000000ULL
#define DEVDRV_PCIE_RESERVE_MEM_ADDR 0x34A00000ULL
#define DEVDRV_DIE_RESERVE_MEM_OFFSET 0x1000000000ULL
#define DEVDRV_PCIE_RESERVE_MEM_SIZE (1 * 1024 * 1024)

#define DEVDRV_TOPIC_SCHED_RES_MEM_SIZE 0x100000
/* device offset:0; host offset:0x40000 */
#define DEVDRV_TOPIC_SCHED_RES_MEM_BASE 0x36D00000ULL

#define DEVDRV_IO_TS_DB_OFFSET 0x0
#define DEVDRV_IO_TS_DB_SIZE 0x4000000
#define DEVDRV_IO_TS_SRAM_OFFSET 0x18300000
#define DEVDRV_IO_TS_SRAM_SIZE 0x20000
#define DEVDRV_IO_HWTS_OFFSET 0x4100000
#define DEVDRV_IO_HWTS_SIZE 0x400000

#define AGENTDRV_PEH_SOC_DB_RAISE_INIT_ADDR 0x4001d1100
#define AGENTDRV_SOC_DB_RAISE_INIT_ADDR 0x80100c0A0
#define AGENTDRV_SOC_DB_RAISE_INIT_SIZE 0x10
#define AGENTDRV_DB_MEM_ADDRESS 0x4001e1000 /* nvme reg */
#define AGENTDRV_PF_DB_STATE_ADDRESS 0x4001e0000 /* nvme reg */
#define AGENTDRV_VF_DB_STATE_ADDRESS 0x4001e0030 /* nvme reg */
#define AGENTDRV_VF_DB_STATE_OFFSET 0x10
#define AGENTDRV_DB_MEM_SIZE 0x1000
#define AGENTDRV_VF_SOC_DOORBELL_OFFSET 0x1000

#define AGENTDRV_DB_STRDE 8

#define DEVDRV_RESERVE_MEM_DB_BASE 0x0 /*  doorbell base */
#define DEVDRV_MSG_CHAN_DB_OFFSET 0x4  /* doorbell offset */

#define AGENTDRV_NVME_SQ_DB_IRQ_NUM 2
#define AGENTDRV_NVME_DB_IRQ_NUM 4
#define AGENTDRV_SOC_DB_IRQ_NUM 6
#define AGENTDRV_VF_SOC_DB_IRQ_NUM 1

#define AGENTDRV_NVME_DB_IRQ_BASE 11
#define AGENTDRV_NVME_DB_IRQ_BASE_1 11
#define AGENTDRV_NVME_DB_IRQ_END_1 18
#define AGENTDRV_NVME_DB_IRQ_BASE_2 21
#define AGENTDRV_NVME_DB_IRQ_END_2 28

#define AGENTDRV_NVME_LOW_LEVEL_DB_IRQ_NUM 4

#define AGENTDRV_NVME_DB_IRQ_STRDE 8
#define AGENTDRV_QCNT_EACH_IRQ 32
#define AGENTDRV_VF_QCNT_EACH_IRQ 16
#define AGENTDRV_VF_SQ_MASK 0xFFFF
#define AGENTDRV_VF_CQ_MASK 0xFFFF0000
#define AGENTDRV_NVME_DB_QID_STRDE 128

#define AGENTDRV_TOTALE_DB_IRQ_NUM 256
#define AGENTDRV_SINGLE_PF_DB_IRQ_NUM 128

#define AGENTDRV_MAX_IO_MSG_CHAN 46

#define AGENTDRV_PF_MAX_IO_MSG_CHAN 46
#define AGENTDRV_VF_MAX_IO_MSG_CHAN 8

#define AGENTDRV_MSG_CHAN_USED_DB_START 0
#define AGENTDRV_MSG_CHAN_USED_DB_END AGENTDRV_PF_MAX_IO_MSG_CHAN

#define AGENTDRV_VF_P2P_MSG_USED_DB_START 8
#define AGENTDRV_VF_P2P_MSG_USED_DB_END 15

#define AGENTDRV_P2P_MSG_USED_DB_START 46
#define AGENTDRV_P2P_MSG_USED_DB_END 62
#define AGENTDRV_P2P_MSG_USED_DB_NUM (AGENTDRV_P2P_MSG_USED_DB_END - AGENTDRV_P2P_MSG_USED_DB_START)

#define AGENTDRV_GENERAL_INTR_USED_DB_START 62
#define AGENTDRV_GENERAL_INTR_USED_DB_END 63
#define AGENTDRV_GENERAL_INTR_USED_DB_NUM (AGENTDRV_GENERAL_INTR_USED_DB_END - AGENTDRV_GENERAL_INTR_USED_DB_START)

#define AGENTDRV_TEST_USED_DB_ID 63
#define AGENTDRV_TEST_USED_INTR_NUM 2

#define NVME_INT_REQ_OFFSET 0
#define NVME_INT_VECTOR_OFFSET 1
#define NVME_INT_PF_NUM_OFFSET 26
#define NVME_INT_VF_NUM_OFFSET 16

#define NVME_PF_QUEUE_NUM_OFFSET 12

#define AGENTDRV_NVME_INT_REQ 0
#define AGENTDRV_NVME_SQ_DB_STS_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_STATUS_PF_REG
#define AGENTDRV_NVME_CQ_DB_STS_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_STATUS_PF_REG
#define AGENTDRV_NVME_INT_VECTOR_MASK_BASE HIPCIEC_SOC_DOORBELL_REG_DB_INT0_MASK_PF_SYS_REG

#endif
