if (${PRODUCT_SIDE} STREQUAL host)
add_subdirectory(vmng_agent)
add_subdirectory(vmng_host)
add_subdirectory(vmng_host_stub)
add_subdirectory(vmng_vpc_drv)
else ()
add_subdirectory(vmng_dev)
    if(${PRODUCT} STREQUAL ascend910B OR ${PRODUCT} STREQUAL ascend910 OR ${PRODUCT} STREQUAL ascend310p)
        add_subdirectory(vmng_resource_mgr)
    endif()
endif()
