/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#ifndef MEMORY_FAULT_CONVERGE_H
#define MEMORY_FAULT_CONVERGE_H

/* OEM: RAS IERR ERR TYPE */
#define RAS_EBRAM_SINGLE_BIT_CE  0x0E02
#define RAS_EBRAM_MULTI_BIT_UER  0x6602
#define RAS_RVLS_CE  0x0D0C
#define RAS_RVLS_UER  0x650C
#define RAS_VLS_CE  0x0C0C
#define RAS_VLS_UER  0x640C
#define RAS_HA_ALARM_CE  0x0B0C
#define RAS_HA_UE  0x600C
#define RAS_SP_RNK_COMPLETE  0x4A01
#define RAS_SP_DEVICE_COMPLETE  0x4901
#define RAS_VLS_LOCKSTEP  0x4801
#define RAS_PA_SCRUB_READ_CE  0x410C
#define RAS_PA_SCRUB_READ_UER  0x610C
#define RAS_SP_READBACK_UER  0x630C
#define RAS_SP_UER  0x620C
#define RAS_FWDRAM_SINGLE_BIT_CE  0x9602
#define RAS_FWDRAM_MULTI_BIT_UEU  0xA502
#define RAS_RPRAM_SINGLE_BIT_CE  0x9902
#define RAS_RPRAM_MULTI_BIT_UEU  0xA402
#define RAS_SBRAM_SINGLE_BIT_CE  0x9302
#define RAS_SBRAM_MULTI_BIT_UEU  0xA202
#define RAS_WSRAM_MULTI_BIT_UER  0xED02
#define RAS_WSRAM_SINGLE_BIT_CE  0x9202
#define RAS_ECC_MULTI_BIT_UER  0xEC0C
#define RAS_ECC_SINGLE_BIT_CE  0x950C
#define RAS_RD_PARITY_ECC_UER  0xEB0A
#define RAS_WR_PARITY_ECC_UER  0xEA
#define RAS_DIMM_PARITY_UER  0xE80B
#define RAS_SREF_UER  0xE70E
#define RAS_RECRAM_SINGLE_BIT_CE  0x9402
#define RAS_RECRAM_MULTI_BIT_UEU  0xA302
#define RAS_REC_ERR_UEU  0xA60C
#define RAS_REC_COMPLETE_UEO  0xCB0C
#define RAS_DFI_RDTIMEOUT_UEU  0xA014
#define RAS_CATTRAP_UEU  0xA1
#define RAS_TEMP_UEU  0xD4
#define RAS_STADAT_MIN_UEO  0xCD14
#define RAS_STADAT_MAX_UEO  0xCC14
#define RAS_STACMD_MIN_UEO  0xCF14
#define RAS_STACMD_MAX_UEO  0xCE14
#define RAS_FLUX_UEO  0xD014

#define RAS_L1H_TEMP_RESUME  0xA1
#define RAS_ECC_MULTI_BIT_UNCRRECT  0x12E9
#define RAS_ECC_SINGLE_BIT_OF_BUF_MEM  0x0D02
#define RAS_ECC_SINGLE_BIT_OF_DIR_MEM  0x0D07
#define RAS_ECC_SINGLE_BIT_CMD_BUF_MEM  0x0E02
#define RAS_ECC_SINGLE_BIT_CMD_DIR_MEM  0x0E07
#define RAS_ECC_SINGLE_BIT_DATA_BUF_MEM  0x0F02
#define RAS_ECC_SINGLE_BIT_DATA_DIR_MEM  0x0F07
#define RAS_ECC_SINGLE_BIT_SDIR_BUF_MEM  0x1002
#define RAS_ECC_SINGLE_BIT_SDIR_DIR_MEM  0x1007
#define RAS_ECC_SINGLE_BIT_EDIR_BUF_MEM  0x1102
#define RAS_ECC_SINGLE_BIT_EDIR_DIR_MEM  0x1107
#define RAS_ECC_MULTI_BIT_DATA_BUF_MEM  0x0702
#define RAS_ECC_MULTI_BIT_CMD_BUF_MEM  0x0202
#define RAS_ECC_MULTI_BIT_CMD_DIR_MEM  0x0207
#define RAS_ECC_MULTI_BIT_SDIR_BUF_MEM  0x0302
#define RAS_ECC_MULTI_BIT_SDIR_DIR_MEM  0x0307
#define RAS_ECC_MULTI_BIT_EDIR_BUF_MEM  0x0402
#define RAS_ECC_MULTI_BIT_EDIR_DIR_MEM  0x0407
#define RAS_NON_SECURE_ACCESS_ZONE  0x060E
#define RAS_ACCESS_NON_SECURE_ZONE  0x0C0E
#define RAS_ILLEGAL_REQUEST  0x010E
#define RAS_DEFAULT_SLAVE  0x050E
#define RAS_MISS_MSD  0x090D
#define RAS_OVERLAP_MSD  0x0A0D
#define RAS_INVERT_MSD  0x0B0D
#define RAS_HIT_CCIX_MSD  0x120D

static struct ras_fault_converge_item g_memory_fault_converge_table[] = {
	/* HBMC */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_RPRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "rpram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_RPRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "rpram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_SBRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "sbram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_SBRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "sbram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_WSRAM_MULTI_BIT_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "wsram muilti bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_WSRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "wsram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_RD_PARITY_ECC_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_PARITY, "read data parity ecc error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_WR_PARITY_ECC_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_PARITY, "write data parity ecc error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_DFI_RDTIMEOUT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "read data timeout int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_DIMM_PARITY_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "dimm ca parity error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_FLUX_UEO,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "flux timeout int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SINGLE_BIT_ECC,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBM, MEMORY_SENSOR_HBMC, RAS_SEC_OEM, RAS_L1H_TEMP_RESUME,
		DMS_SEN_TYPE_TEMPERATURE, TEMP_ERROR_TYPE_L1H_RESUME, " l1htemp resume error")
	/* DDRC */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, HISI_ERR_TYPE_HA_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "ha uncorrect error interrupte")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, STANDARD_ERR_TYPE_DSCRUB_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_SCRUB_FAILED, "demand scrubbing read ue error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, HISI_ERR_TYPE_VLS_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "vls uncorrect error interrupte")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, HISI_ERR_TYPE_RVLS_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "rvls uncorrect error interrupte")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_UNCRRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "ecc enable multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_SP_UER,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "sparing uncorrect error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_SP_READBACK_UER,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_UCEECC, "sparing readback ue error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_EBRAM_MULTI_BIT_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ebram multi bit ecc error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_EBRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ebram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_DFI_RDTIMEOUT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_TIMEOUT_ERR, "dfi_rddata_valid timeout int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_SBRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "sbram multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_SBRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "sbram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_FWDRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "forward ram multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_FWDRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "forward ram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_RPRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "rpram multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_RPRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "rpram single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_RECRAM_MULTI_BIT_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "cmd or data multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_RECRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "cmd or data single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_REC_ERR_UEU,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_ERROR, "cmd or data repeat fail error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_DIMM_PARITY_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_ERROR, "dimm ca parity error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_WSRAM_MULTI_BIT_UER,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "write data multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_WSRAM_SINGLE_BIT_CE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "write data single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_OEM, RAS_REC_COMPLETE_UEO,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_ERROR, "rec complete int")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SCRUB_UNCORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_SCRUB_FAILED, "patrol scrubbing read ue error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SCRUB_CORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "patrol scrubbing read ce error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, HISI_ERR_TYPE_VLS_CORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "vls correct error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, HISI_ERR_TYPE_RVLS_CORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "rvls correct error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, HISI_ERR_TYPE_HA_CORRECT,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "ha access correct error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDR, MEMORY_SENSOR_DDRC, RAS_SEC_MEM, STANDARD_ERR_TYPE_SINGLE_BIT_ECC,
		DMS_SEN_TYPE_MEMORY, MEMORY_ERROR_TYPE_CECC_OVER_THOLD, "ecc single bit error")
	/* HHA */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_OF_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_OF_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_DATA_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ILLEGAL_REQUEST,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "illegal operation")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_NON_SECURE_ACCESS_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "non-secure access space")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_ACCESS_NON_SECURE_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "access non-secure space")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_DEFAULT_SLAVE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "decoding error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_HIT_CCIX_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD hit CCIX error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_INVERT_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD invert error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_OVERLAP_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD overlap error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_HBMA, MEMORY_SENSOR_HHA, RAS_SEC_OEM, RAS_MISS_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD miss error")
	/* DHA */
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_OF_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_OF_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_DATA_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_SINGLE_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_SBECCOverThold, "ecc single bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_DATA_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_CMD_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_CMD_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_SDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_SDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_EDIR_BUF_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ECC_MULTI_BIT_EDIR_DIR_MEM,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_MBECC, "ecc multi bit error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ILLEGAL_REQUEST,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "illegal operation")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_NON_SECURE_ACCESS_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "non-secure access space")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_ACCESS_NON_SECURE_ZONE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "access non-secure space")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_DEFAULT_SLAVE,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "decoding error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_HIT_CCIX_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD hit CCIX error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_INVERT_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD invert error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_OVERLAP_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD overlap error")
	DMS_FAULT_CONVERGE_CONFIG(DMS_DEV_TYPE_DDRA, MEMORY_SENSOR_DHA, RAS_SEC_OEM, RAS_MISS_MSD,
		DMS_SEN_TYPE_RAS_SENSOR, RAS_ERROR_TYPE_IN_CFG_ERR, "MSD miss error")
};
#endif /* MEMORY_FAULT_CONVERGE_H */
