# SPDX-License-Identifier: GPL-2.0
obj-m := drv_pkicms.o
drv_pkicms-objs := pkicms_module.o pkicms/cmscbb.o pkicms/pkicms_common.o pkicms/soc_verify.o

DRIVER_INC := $(src)/..
PKICMS_CMSCBB_INC := -I$(src)/cmscbb/asn1 -I$(src)/cmscbb/cms
PKICMS_CMSCBB_INC += -I$(src)/cmscbb/cmscbb_common -I$(src)/cmscbb/include
PKICMS_CMSCBB_INC += -I$(src)/cmscbb/pki -I$(src)/cmscbb/src -I$(src)/cmscbb/x509
PKICMS_CMSCBB_OBJS := cmscbb/cms_verify.o cmscbb/cmscbb_asn1_decode.o cmscbb/cmscbb_asn1_def.o
PKICMS_CMSCBB_OBJS += cmscbb/cmscbb_templ.o cmscbb/cmscbb_crl_compare.o cmscbb/cmscbb_pem_util.o
PKICMS_CMSCBB_OBJS += cmscbb/cmscbb_asn1_utils.o cmscbb/cmscbb_base64.o cmscbb/cmscbb_buf.o
PKICMS_CMSCBB_OBJS += cmscbb/cmscbb_cms_parse.o cmscbb/cmscbb_list.o cmscbb/cmscbb_pki.o
PKICMS_CMSCBB_OBJS += cmscbb/cmscbb_plt_proxy.o cmscbb/cmscbb_x509.o

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/pkicms
ccflags-y += -DLINUX_KERNEL_BUILD

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ifeq ($(PRODUCT), ascend920esl)
ccflags-y += -DCFG_ENV_ESL
endif
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2 -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCMSCBB_SUPPORT_RSAPSS=0 -DCFG_FEATURE_SIGN_VERSION_1 -DCFG_FEATURE_RSA_4096
else ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl as31xm1),)
ifneq ($(filter $(PRODUCT), ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_LITE_ESL
endif
ifneq ($(filter $(PRODUCT), as31xm1),)
ccflags-y += -DCFG_FEATURE_NOT_SUPPORT_SOC_VERIFY -DCFG_FEATURE_GET_ENABLE_FLAG
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11 -DCFG_FEATURE_SIGN_VERSION_1
endif
ccflags-y += $(PKICMS_CMSCBB_INC) -I$(DRIVER_INC)/common
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCMSCBB_SUPPORT_RSAPSS=1
ccflags-y += -DCFG_FEATURE_PKCS_SIGN -DCFG_FEATURE_RSA_2048 -DCFG_FEATURE_RSA_4096
drv_pkicms-objs += pkicms/pkicms.o pkicms/pkicms_api.o pkicms/drv_cpu_type.o
else ifneq ($(filter $(PRODUCT), ascend310p helper310p ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ifeq ($(PRODUCT), ascend310Besl)
ccflags-y += -DCFG_ENV_ESL
endif
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_PKCS_SIGN -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCMSCBB_SUPPORT_RSAPSS=0 -DCFG_FEATURE_RSA_2048 -DCFG_FEATURE_RSA_4096
else ifeq ($(PRODUCT), ascend910)
ccflags-y += $(PKICMS_CMSCBB_INC) -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCFG_FEATURE_PKCS_SIGN -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCMSCBB_SUPPORT_RSAPSS=0 -DCFG_FEATURE_RSA_2048 -DCFG_FEATURE_RSA_4096
drv_pkicms-objs += $(PKICMS_CMSCBB_OBJS) pkicms/pkicms.o pkicms/pkicms_api.o
else
ccflags-y += $(PKICMS_CMSCBB_INC) -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCMSCBB_SUPPORT_RSAPSS=0 -DCFG_FEATURE_PKCS_SIGN
ccflags-y += -DCFG_FEATURE_RSA_2048 -DCFG_FEATURE_RSA_4096
drv_pkicms-objs += $(PKICMS_CMSCBB_OBJS) pkicms/pkicms.o pkicms/pkicms_api.o
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
