# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_event_sched_host.o

ascend_event_sched_host-objs := \
	comm/esched_fops.o \
	comm/esched.o \
	comm/esched_sysfs.o

DRIVER_INC := $(src)/..
ccflags-y += -Wall -Werror
ccflags-y += $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char -Wformat=2
ccflags-y += -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-format-nonliteral -Wno-empty-body
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/comm
ccflags-y += -DESCHED_HOST

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ifneq ($(filter $(PRODUCT), helper310p),)
ccflags-y += -DCFG_FEATURE_DEEPER_EVENT_QUE
else
ascend_event_sched_host-objs += esched_host_msg.o
ccflags-y += -DCFG_FEATURE_IDENTIFY_CP -DCFG_FEATURE_REMOTE_SUBMIT
ccflags-y += -DCFG_FEATURE_EXTERNAL_CDEV

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -I$(src)/comm/hard_sched
ccflags-y += -DCFG_FEATURE_HARDWARE_SCHED -DCFG_FEATURE_SOFT_NON_SCHED_ONLY
ccflags-y += -DCFG_FEATURE_HARDWARE_MIA
ifneq ($(filter $(PRODUCT), ascend920esl),)
ccflags-y += -DCFG_SOC_PLATFORM_ESL
endif
ascend_event_sched_host-objs += esched_drv_adapt.o comm/hard_sched/esched_drv.o
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310Besl ascend310Bemu),)
ccflags-y += -I$(src)/comm/hard_sched
ccflags-y += -DCFG_FEATURE_HARDWARE_SCHED -DCFG_FEATURE_SOFT_NON_SCHED_ONLY
ccflags-y += -DCFG_FEATURE_SIA_MAP_TOPIC_TABLE
ifneq ($(filter $(PRODUCT), ascend310Besl),)
ccflags-y += -DCFG_SOC_PLATFORM_ESL
endif
ascend_event_sched_host-objs += esched_drv_adapt.o comm/hard_sched/esched_drv.o
endif
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
