#add_subdirectory(cdqm)
add_subdirectory(chan)
add_subdirectory(trs_core)
add_subdirectory(shr_id)
add_subdirectory(id_allocator)
add_subdirectory(lba)
add_subdirectory(trs_stars)

if (${PRODUCT_SIDE} STREQUAL host)
    #add_subdirectory(host)
else ()
    add_subdirectory(id_pool)
    add_subdirectory(tsmng)
endif()
