# SPDX-License-Identifier: GPL-2.0
obj-m := drv_upgrade.o

DRIVER_INC := $(src)/..

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/toolchain/bbox/device
ccflags-y += -I$(DRIVER_INC)/dfm -I$(DRIVER_INC)/pkicms/pkicms -I$(DRIVER_INC)/user_cfg
ccflags-y += -I$(DRIVER_INC)/tee/inc
ccflags-y += -I$(src) -I$(src)/common

ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
ccflags-y += -I$(src)/ascd310
ccflags-y += -DCFG_SOC_PLATFORM_MINI
drv_upgrade-objs := ascd310/dev_upgrade_core.o ascd310/dev_upgrade_adapt.o
else
ccflags-y += -I$(src)/ascd610
ccflags-y += -Wall -Werror
drv_upgrade-objs := common/dev_upgrade_core.o common/dev_upgrade_adapt.o

ifeq ($(PRODUCT),ascend310p)
ccflags-y += -I$(src)/ascd310p
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DSUPPORT_TEE_SECURE_UPGRADE
ccflags-y += -DCFG_FEATURE_PSS_SIGN
endif

ifeq ($(PRODUCT),helper310p)
ccflags-y += -I$(src)/helper310p
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -DCFG_SOC_PLATFORM_HELPER
ccflags-y += -DSUPPORT_TEE_SECURE_UPGRADE
ccflags-y += -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCFG_FEATURE_UPGRADE_CRL
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310Brc),)
ccflags-y += -I$(src)/ascd310b
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DSUPPORT_TEE_SECURE_UPGRADE
ccflags-y += -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCFG_FEATURE_ROLL_BACK
drv_upgrade-objs += common/dev_upgrade_crc.o
ifeq ($(PRODUCT),ascend310Brc)
ccflags-y += -DCFG_FEATURE_RC_MODE
endif
endif

ifeq ($(PRODUCT),ascend910)
ccflags-y += -I$(src)/ascd910
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCFG_FEATURE_PSS_SIGN
endif

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -I$(src)/ascd910b
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DSUPPORT_TEE_SECURE_UPGRADE
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DSUPPORT_TEE_SECURE_UPGRADE
ccflags-y += -DLINUX_KERNEL_BUILD
ccflags-y += -DCFG_FEATURE_UPGRADE_CRL
ifneq ($(filter $(PRODUCT), ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_LITE_ESL
endif
ifeq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
ccflags-y += -DCFG_FEATURE_SIGN_VERSION_1
endif
endif
endif

ccflags-y += -I$(DRIVER_INC)/include/internal

ifneq ($(filter $(PRODUCT), ascend310p helper310p ascend310B ascend310Brc ascend910B ascend920esl ascend920emu),)
drv_upgrade-objs += ascd610/dev_upgrade_sec.o
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl as31xm1),)
drv_upgrade-objs += ascd610/dev_upgrade_sec.o ascd610/dev_upgrade_mdccore.o
drv_upgrade-objs += ascd610/dev_upgrade_crl.o ascd610/dev_upgrade_ufs.o
drv_upgrade-objs += ascd610/dev_upgrade_ssd.o
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion
