# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_cdqm.o

ifeq ($(PRODUCT_SIDE),host)
ascend_trs_cdqm-objs := \
	host_comm/cdqm_core.o \
	host_comm/cdqm_proc.o \
	host_comm/cdqm_fops.o \
	host/cdq_manager.o \
	host/cdqm_host.o
else
ascend_trs_cdqm-objs := \
	comm/cdqm_core.o \
	comm/cdqm_proc.o \
	comm/cdqm_fops.o \
	cdq_manager.o \
	cdqm_dev.o
endif

DRIVER_INC := $(src)/..

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifneq ($(NOT_SUPPORT_SP), y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src)

ifeq ($(PRODUCT_SIDE),host)
ccflags-y += -I$(src)/host -I$(src)/host_comm
ccflags-y += -DCFG_MANAGER_HOST_ENV
else
ccflags-y += -I$(src)/comm
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
endif

ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
endif

KBUILD_EXTRA_SYMBOLS := $(src)/../davinci_intf/Module.symvers \
	$(src)/../dms/Module.symvers \
	$(src)/../pcie/Module.symvers \
	$(src)/../soc_resmng/Module.symvers \
	$(src)/../trs_id_allocator/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
