# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_cdqm.o
ascend_trs_cdqm-objs := comm/cdqm_core.o comm/cdqm_proc.o comm/cdqm_fops.o cdq_manager.o cdqm_dev.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) -I$(src)/comm
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
# KBUILD_EXTRA_SYMBOLS := $(src)/../davinci_intf/Module.symvers $(src)/../trs_id_allocator/Module.symvers $(src)/../soc_resmng/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
