# SPDX-License-Identifier: GPL-2.0
obj-m := drv_osal.o
drv_osal-objs := osal_mutex.o osal_notifier.o osal_workqueue.o osal_spinlock.o osal_acpi.o osal_debug.o osal_cache.o osal_of.o osal_property.o osal_task.o osal_barrier.o osal_timer.o osal_addr.o osal_math.o osal_bootdot.o osal_atomic.o osal_interrupt.o osal_iommu.o osal_device.o osal_semaphore.o osal_string.o osal.o osal_schedule.o osal_vmalloc.o osal_wait.o osal_proc.o osal_fileops.o osal_platform.o 

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/user_config
ccflags-y += -I/mnt/sda1/yihao/opiai/Ascend310B-source-opi/driver/ace/dvpp/dvpp/HiDvpp/cbb/include -I/mnt/sda1/yihao/opiai/Ascend310B-source-opi/driver/ace/dvpp/dvpp/HiDvpp/cbb/ext_inc -I$(src) 
ccflags-y += -DBUILD_DRV_OSAL -DDVPP_MINI
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-pointer-types -Wno-return-type
ccflags-y += -Wno-implicit-function-declaration -Wno-int-conversion
