# SPDX-License-Identifier: GPL-2.0

obj-m := svm.o

DRIVER_INC := $(src)/..

ccflags-y += -Wall -Werror
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -include $(DRIVER_INC)/include/compat.h
