# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_mia_agent.o
ascend_trs_mia_agent-objs := trs_near_mia_agent.o agent_comm/trs_cache_id_recycle.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/agent_comm

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers


KBUILD_EXTRA_SYMBOLS := $(src)/../pcie/Module.symvers \
	$(src)/../trs_adapt_agent/Module.symvers \
	$(src)/../trs_id_pool/Module.symvers \
	$(src)/../trs_kunpeng/Module.symvers \
	$(src)/../trs_mia_adapt/Module.symvers
