/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */

#ifndef HILINK_FW_MARCOAPI_CSR_REG_OFFSET_FIELD_H
#define HILINK_FW_MARCOAPI_CSR_REG_OFFSET_FIELD_H

/* FW_MARCOAPI_CSR0_REG */
#define FW_MARCOAPI_CSR_0_BIT30_LEN 2
#define FW_MARCOAPI_CSR_0_BIT30_OFFSET 30
#define FW_MARCOAPI_CSR_0_BIT29_LEN 1
#define FW_MARCOAPI_CSR_0_BIT29_OFFSET 29
#define FW_MARCOAPI_CSR_0_BIT25_LEN 4
#define FW_MARCOAPI_CSR_0_BIT25_OFFSET 25
#define FW_MARCOAPI_CSR_0_BIT24_LEN 1
#define FW_MARCOAPI_CSR_0_BIT24_OFFSET 24
#define FW_MARCOAPI_CSR_0_BIT21_LEN 3
#define FW_MARCOAPI_CSR_0_BIT21_OFFSET 21
#define FW_MARCOAPI_CSR_0_BIT17_LEN 4
#define FW_MARCOAPI_CSR_0_BIT17_OFFSET 17
#define FW_MARCOAPI_CSR_0_BIT16_LEN 1
#define FW_MARCOAPI_CSR_0_BIT16_OFFSET 16
#define FW_MARCOAPI_CSR_0_BIT13_LEN 3
#define FW_MARCOAPI_CSR_0_BIT13_OFFSET 13
#define FW_MARCOAPI_CSR_0_BIT5_LEN 8
#define FW_MARCOAPI_CSR_0_BIT5_OFFSET 5
#define FW_MARCOAPI_CSR_0_BIT4_LEN 1
#define FW_MARCOAPI_CSR_0_BIT4_OFFSET 4
#define FW_MARCOAPI_CSR_0_BIT1_LEN 3
#define FW_MARCOAPI_CSR_0_BIT1_OFFSET 1
#define FW_MARCOAPI_CSR_0_BIT0_LEN 1
#define FW_MARCOAPI_CSR_0_BIT0_OFFSET 0

/* FW_MARCOAPI_CSR1_REG */
#define FW_MARCOAPI_CSR_1_BIT31_LEN 1
#define FW_MARCOAPI_CSR_1_BIT31_OFFSET 31
#define FW_MARCOAPI_CSR_1_BIT27_LEN 4
#define FW_MARCOAPI_CSR_1_BIT27_OFFSET 27
#define FW_MARCOAPI_CSR_1_BIT24_LEN 3
#define FW_MARCOAPI_CSR_1_BIT24_OFFSET 24
#define FW_MARCOAPI_CSR_1_BIT23_LEN 1
#define FW_MARCOAPI_CSR_1_BIT23_OFFSET 23
#define FW_MARCOAPI_CSR_1_BIT19_LEN 4
#define FW_MARCOAPI_CSR_1_BIT19_OFFSET 19
#define FW_MARCOAPI_CSR_1_BIT18_LEN 1
#define FW_MARCOAPI_CSR_1_BIT18_OFFSET 18
#define FW_MARCOAPI_CSR_1_BIT14_LEN 4
#define FW_MARCOAPI_CSR_1_BIT14_OFFSET 14
#define FW_MARCOAPI_CSR_1_BIT13_LEN 1
#define FW_MARCOAPI_CSR_1_BIT13_OFFSET 13
#define FW_MARCOAPI_CSR_1_BIT0_LEN 13
#define FW_MARCOAPI_CSR_1_BIT0_OFFSET 0

#endif