/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */

#ifndef HILINK_ADAP_LANE_CSR_REG_OFFSET_FIELD_H
#define HILINK_ADAP_LANE_CSR_REG_OFFSET_FIELD_H

#define ADAP_LANE_CSR_0_BIT10_LEN 4
#define ADAP_LANE_CSR_0_BIT10_OFFSET 10
#define ADAP_LANE_CSR_0_BIT3_LEN 7
#define ADAP_LANE_CSR_0_BIT3_OFFSET 3
#define ADAP_LANE_CSR_0_BIT2_LEN 1
#define ADAP_LANE_CSR_0_BIT2_OFFSET 2
#define ADAP_LANE_CSR_0_BIT1_LEN 1
#define ADAP_LANE_CSR_0_BIT1_OFFSET 1
#define ADAP_LANE_CSR_0_BIT0_LEN 1
#define ADAP_LANE_CSR_0_BIT0_OFFSET 0

#define ADAP_LANE_CSR_1_BIT3_LEN 1
#define ADAP_LANE_CSR_1_BIT3_OFFSET 3
#define ADAP_LANE_CSR_1_BIT2_LEN 1
#define ADAP_LANE_CSR_1_BIT2_OFFSET 2
#define ADAP_LANE_CSR_1_BIT1_LEN 1
#define ADAP_LANE_CSR_1_BIT1_OFFSET 1
#define ADAP_LANE_CSR_1_BIT0_LEN 1
#define ADAP_LANE_CSR_1_BIT0_OFFSET 0

#define ADAP_LANE_CSR_2_BIT30_LEN 1
#define ADAP_LANE_CSR_2_BIT30_OFFSET 30
#define ADAP_LANE_CSR_2_BIT28_LEN 2
#define ADAP_LANE_CSR_2_BIT28_OFFSET 28
#define ADAP_LANE_CSR_2_BIT27_LEN 1
#define ADAP_LANE_CSR_2_BIT27_OFFSET 27
#define ADAP_LANE_CSR_2_BIT24_LEN 3
#define ADAP_LANE_CSR_2_BIT24_OFFSET 24
#define ADAP_LANE_CSR_2_BIT18_LEN 6
#define ADAP_LANE_CSR_2_BIT18_OFFSET 18
#define ADAP_LANE_CSR_2_BIT12_LEN 6
#define ADAP_LANE_CSR_2_BIT12_OFFSET 12
#define ADAP_LANE_CSR_2_BIT11_LEN 1
#define ADAP_LANE_CSR_2_BIT11_OFFSET 11
#define ADAP_LANE_CSR_2_BIT10_LEN 1
#define ADAP_LANE_CSR_2_BIT10_OFFSET 10
#define ADAP_LANE_CSR_2_BIT9_LEN 1
#define ADAP_LANE_CSR_2_BIT9_OFFSET 9
#define ADAP_LANE_CSR_2_BIT8_LEN 1
#define ADAP_LANE_CSR_2_BIT8_OFFSET 8
#define ADAP_LANE_CSR_2_BIT7_LEN 1
#define ADAP_LANE_CSR_2_BIT7_OFFSET 7
#define ADAP_LANE_CSR_2_BIT0_LEN 7
#define ADAP_LANE_CSR_2_BIT0_OFFSET 0

#define ADAP_LANE_CSR_3_BIT31_LEN 1
#define ADAP_LANE_CSR_3_BIT31_OFFSET 31
#define ADAP_LANE_CSR_3_BIT30_LEN 1
#define ADAP_LANE_CSR_3_BIT30_OFFSET 30
#define ADAP_LANE_CSR_3_BIT24_LEN 6
#define ADAP_LANE_CSR_3_BIT24_OFFSET 24
#define ADAP_LANE_CSR_3_BIT18_LEN 6
#define ADAP_LANE_CSR_3_BIT18_OFFSET 18
#define ADAP_LANE_CSR_3_BIT0_LEN 18
#define ADAP_LANE_CSR_3_BIT0_OFFSET 0

#define ADAP_LANE_CSR_4_BIT16_LEN 16
#define ADAP_LANE_CSR_4_BIT16_OFFSET 16
#define ADAP_LANE_CSR_4_BIT9_LEN 6
#define ADAP_LANE_CSR_4_BIT9_OFFSET 9
#define ADAP_LANE_CSR_4_BIT2_LEN 7
#define ADAP_LANE_CSR_4_BIT2_OFFSET 2
#define ADAP_LANE_CSR_4_BIT1_LEN 1
#define ADAP_LANE_CSR_4_BIT1_OFFSET 1
#define ADAP_LANE_CSR_4_BIT0_LEN 1
#define ADAP_LANE_CSR_4_BIT0_OFFSET 0

#define ADAP_LANE_CSR_5_BIT31_LEN 1
#define ADAP_LANE_CSR_5_BIT31_OFFSET 31
#define ADAP_LANE_CSR_5_BIT30_LEN 1
#define ADAP_LANE_CSR_5_BIT30_OFFSET 30
#define ADAP_LANE_CSR_5_BIT28_LEN 2
#define ADAP_LANE_CSR_5_BIT28_OFFSET 28
#define ADAP_LANE_CSR_5_BIT16_LEN 12
#define ADAP_LANE_CSR_5_BIT16_OFFSET 16
#define ADAP_LANE_CSR_5_BIT8_LEN 8
#define ADAP_LANE_CSR_5_BIT8_OFFSET 8
#define ADAP_LANE_CSR_5_BIT0_LEN 8
#define ADAP_LANE_CSR_5_BIT0_OFFSET 0

#define ADAP_LANE_CSR_6_BIT8_LEN 1
#define ADAP_LANE_CSR_6_BIT8_OFFSET 8
#define ADAP_LANE_CSR_6_BIT0_LEN 8
#define ADAP_LANE_CSR_6_BIT0_OFFSET 0

#define ADAP_LANE_CSR_7_BIT27_LEN 1
#define ADAP_LANE_CSR_7_BIT27_OFFSET 27
#define ADAP_LANE_CSR_7_BIT24_LEN 3
#define ADAP_LANE_CSR_7_BIT24_OFFSET 24
#define ADAP_LANE_CSR_7_BIT6_LEN 18
#define ADAP_LANE_CSR_7_BIT6_OFFSET 6
#define ADAP_LANE_CSR_7_BIT5_LEN 1
#define ADAP_LANE_CSR_7_BIT5_OFFSET 5
#define ADAP_LANE_CSR_7_BIT0_LEN 5
#define ADAP_LANE_CSR_7_BIT0_OFFSET 0

#define ADAP_LANE_CSR_8_BIT0_LEN 32
#define ADAP_LANE_CSR_8_BIT0_OFFSET 0

#define ADAP_LANE_CSR_9_BIT15_LEN 16
#define ADAP_LANE_CSR_9_BIT15_OFFSET 15
#define ADAP_LANE_CSR_9_BIT14_LEN 1
#define ADAP_LANE_CSR_9_BIT14_OFFSET 14
#define ADAP_LANE_CSR_9_BIT13_LEN 1
#define ADAP_LANE_CSR_9_BIT13_OFFSET 13
#define ADAP_LANE_CSR_9_BIT12_LEN 1
#define ADAP_LANE_CSR_9_BIT12_OFFSET 12
#define ADAP_LANE_CSR_9_BIT11_LEN 1
#define ADAP_LANE_CSR_9_BIT11_OFFSET 11
#define ADAP_LANE_CSR_9_BIT9_LEN 2
#define ADAP_LANE_CSR_9_BIT9_OFFSET 9
#define ADAP_LANE_CSR_9_BIT8_LEN 1
#define ADAP_LANE_CSR_9_BIT8_OFFSET 8
#define ADAP_LANE_CSR_9_BIT0_LEN 8
#define ADAP_LANE_CSR_9_BIT0_OFFSET 0

#define ADAP_LANE_CSR_10_BIT0_LEN 32
#define ADAP_LANE_CSR_10_BIT0_OFFSET 0

#define ADAP_LANE_CSR_11_BIT25_LEN 1
#define ADAP_LANE_CSR_11_BIT25_OFFSET 25
#define ADAP_LANE_CSR_11_BIT24_LEN 1
#define ADAP_LANE_CSR_11_BIT24_OFFSET 24
#define ADAP_LANE_CSR_11_BIT23_LEN 1
#define ADAP_LANE_CSR_11_BIT23_OFFSET 23
#define ADAP_LANE_CSR_11_BIT20_LEN 3
#define ADAP_LANE_CSR_11_BIT20_OFFSET 20
#define ADAP_LANE_CSR_11_BIT17_LEN 3
#define ADAP_LANE_CSR_11_BIT17_OFFSET 17
#define ADAP_LANE_CSR_11_BIT14_LEN 3
#define ADAP_LANE_CSR_11_BIT14_OFFSET 14
#define ADAP_LANE_CSR_11_BIT13_LEN 1
#define ADAP_LANE_CSR_11_BIT13_OFFSET 13
#define ADAP_LANE_CSR_11_BIT12_LEN 1
#define ADAP_LANE_CSR_11_BIT12_OFFSET 12
#define ADAP_LANE_CSR_11_BIT11_LEN 1
#define ADAP_LANE_CSR_11_BIT11_OFFSET 11
#define ADAP_LANE_CSR_11_BIT10_LEN 1
#define ADAP_LANE_CSR_11_BIT10_OFFSET 10
#define ADAP_LANE_CSR_11_BIT9_LEN 1
#define ADAP_LANE_CSR_11_BIT9_OFFSET 9
#define ADAP_LANE_CSR_11_BIT8_LEN 1
#define ADAP_LANE_CSR_11_BIT8_OFFSET 8
#define ADAP_LANE_CSR_11_BIT5_LEN 3
#define ADAP_LANE_CSR_11_BIT5_OFFSET 5
#define ADAP_LANE_CSR_11_BIT3_LEN 2
#define ADAP_LANE_CSR_11_BIT3_OFFSET 3
#define ADAP_LANE_CSR_11_BIT0_LEN 3
#define ADAP_LANE_CSR_11_BIT0_OFFSET 0

#define ADAP_LANE_CSR_12_BIT18_LEN 6
#define ADAP_LANE_CSR_12_BIT18_OFFSET 18
#define ADAP_LANE_CSR_12_BIT0_LEN 18
#define ADAP_LANE_CSR_12_BIT0_OFFSET 0

#define ADAP_LANE_CSR_13_BIT18_LEN 6
#define ADAP_LANE_CSR_13_BIT18_OFFSET 18
#define ADAP_LANE_CSR_13_BIT0_LEN 18
#define ADAP_LANE_CSR_13_BIT0_OFFSET 0

#define ADAP_LANE_CSR_14_BIT0_LEN 18
#define ADAP_LANE_CSR_14_BIT0_OFFSET 0

#define ADAP_LANE_CSR_15_BIT8_LEN 5
#define ADAP_LANE_CSR_15_BIT8_OFFSET 8
#define ADAP_LANE_CSR_15_BIT0_LEN 8
#define ADAP_LANE_CSR_15_BIT0_OFFSET 0

#endif // __HILINK_ADAP_LANE_CSR_REG_OFFSET_FIELD_H__
