/*
 * Copyright     :  Copyright (C) 2021, Huawei Technologies Co. Ltd.
 * File name     :  its_cfg_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2013/3/10
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2021/10/25 08:35:55 Create file
 */

#ifndef __ITS_CFG_REG_OFFSET_FIELD_H__
#define __ITS_CFG_REG_OFFSET_FIELD_H__

#define ITS_CFG_CTLR_QUIESCENT_LEN     1
#define ITS_CFG_CTLR_QUIESCENT_OFFSET  31
#define ITS_CFG_CTLR_ITSNUMBER_LEN     4
#define ITS_CFG_CTLR_ITSNUMBER_OFFSET  4
#define ITS_CFG_CTLR_VLPIENABLE_LEN    1
#define ITS_CFG_CTLR_VLPIENABLE_OFFSET 1
#define ITS_CFG_CTLR_ENABLE_LEN        1
#define ITS_CFG_CTLR_ENABLE_OFFSET     0

#define ITS_CFG_PRODUCTID_LEN             8
#define ITS_CFG_PRODUCTID_OFFSET          24
#define ITS_CFG_VARIANT_LEN               4
#define ITS_CFG_VARIANT_OFFSET            16
#define ITS_CFG_REVISION_LEN              4
#define ITS_CFG_REVISION_OFFSET           12
#define ITS_CFG_JEDEC_CONTINUATION_LEN    4
#define ITS_CFG_JEDEC_CONTINUATION_OFFSET 8
#define ITS_CFG_JEDEC_ID_LEN              7
#define ITS_CFG_JEDEC_ID_OFFSET           0

#define ITS_CFG_TYPER_HCC_LEN            8
#define ITS_CFG_TYPER_HCC_OFFSET         24
#define ITS_CFG_TYPER_PTA_LEN            1
#define ITS_CFG_TYPER_PTA_OFFSET         19
#define ITS_CFG_TYPER_SEIS_LEN           1
#define ITS_CFG_TYPER_SEIS_OFFSET        18
#define ITS_CFG_TYPER_DEVBITS_LEN        5
#define ITS_CFG_TYPER_DEVBITS_OFFSET     13
#define ITS_CFG_TYPER_IDBITS_LEN         5
#define ITS_CFG_TYPER_IDBITS_OFFSET      8
#define ITS_CFG_TYPER_ITTES_LEN          4
#define ITS_CFG_TYPER_ITTES_OFFSET       4
#define ITS_CFG_TYPER_DISTRIBUTED_LEN    1
#define ITS_CFG_TYPER_DISTRIBUTED_OFFSET 3
#define ITS_CFG_TYPER_DIRECT_LEN         1
#define ITS_CFG_TYPER_DIRECT_OFFSET      2
#define ITS_CFG_TYPER_VIRTUAL_LEN        1
#define ITS_CFG_TYPER_VIRTUAL_OFFSET     1
#define ITS_CFG_TYPER_PHYSICAL_LEN       1
#define ITS_CFG_TYPER_PHYSICAL_OFFSET    0

#define ITS_CFG_CBASER_PA_L_LEN            20
#define ITS_CFG_CBASER_PA_L_OFFSET         12
#define ITS_CFG_CBASER_SHAREABILITY_LEN    2
#define ITS_CFG_CBASER_SHAREABILITY_OFFSET 10
#define ITS_CFG_CBASER_SIZE_LEN            8
#define ITS_CFG_CBASER_SIZE_OFFSET         0

#define ITS_CFG_CBASER_VALID_LEN           1
#define ITS_CFG_CBASER_VALID_OFFSET        31
#define ITS_CFG_CBASER_CACHEABILITY_LEN    3
#define ITS_CFG_CBASER_CACHEABILITY_OFFSET 27
#define ITS_CFG_CBASER_PA_H_LEN            16
#define ITS_CFG_CBASER_PA_H_OFFSET         0

#define ITS_CFG_CWRITER_OFFSET_LEN    15
#define ITS_CFG_CWRITER_OFFSET_OFFSET 5
#define ITS_CFG_CWRITER_RETRY_LEN     1
#define ITS_CFG_CWRITER_RETRY_OFFSET  0



#define ITS_CFG_CREADR_OFFSET_LEN    15
#define ITS_CFG_CREADR_OFFSET_OFFSET 5
#define ITS_CFG_CREADR_STALL_LEN     1
#define ITS_CFG_CREADR_STALL_OFFSET  0



#define ITS_CFG_BASER_PA_L0_LEN            20
#define ITS_CFG_BASER_PA_L0_OFFSET         12
#define ITS_CFG_BASER_SHAREABILITY0_LEN    2
#define ITS_CFG_BASER_SHAREABILITY0_OFFSET 10
#define ITS_CFG_BASER_PAGESIZE0_LEN        2
#define ITS_CFG_BASER_PAGESIZE0_OFFSET     8
#define ITS_CFG_BASER_SIZE0_LEN            8
#define ITS_CFG_BASER_SIZE0_OFFSET         0

#define ITS_CFG_BASER_VALID0_LEN           1
#define ITS_CFG_BASER_VALID0_OFFSET        31
#define ITS_CFG_BASER_INDIRECT0_LEN        1
#define ITS_CFG_BASER_INDIRECT0_OFFSET     30
#define ITS_CFG_BASER_CACHEABILITY0_LEN    3
#define ITS_CFG_BASER_CACHEABILITY0_OFFSET 27
#define ITS_CFG_BASER_TYPE0_LEN            3
#define ITS_CFG_BASER_TYPE0_OFFSET         24
#define ITS_CFG_BASER_ENTRYSIZE0_LEN       8
#define ITS_CFG_BASER_ENTRYSIZE0_OFFSET    16
#define ITS_CFG_BASER_PA_H0_LEN            16
#define ITS_CFG_BASER_PA_H0_OFFSET         0

#define ITS_CFG_BASER_PA_L1_LEN            20
#define ITS_CFG_BASER_PA_L1_OFFSET         12
#define ITS_CFG_BASER_SHAREABILITY1_LEN    2
#define ITS_CFG_BASER_SHAREABILITY1_OFFSET 10
#define ITS_CFG_BASER_PAGESIZE1_LEN        2
#define ITS_CFG_BASER_PAGESIZE1_OFFSET     8
#define ITS_CFG_BASER_SIZE1_LEN            8
#define ITS_CFG_BASER_SIZE1_OFFSET         0

#define ITS_CFG_BASER_VALID1_LEN           1
#define ITS_CFG_BASER_VALID1_OFFSET        31
#define ITS_CFG_BASER_INDIRECT1_LEN        1
#define ITS_CFG_BASER_INDIRECT1_OFFSET     30
#define ITS_CFG_BASER_CACHEABILITY1_LEN    3
#define ITS_CFG_BASER_CACHEABILITY1_OFFSET 27
#define ITS_CFG_BASER_TYPE1_LEN            3
#define ITS_CFG_BASER_TYPE1_OFFSET         24
#define ITS_CFG_BASER_ENTRYSIZE1_LEN       8
#define ITS_CFG_BASER_ENTRYSIZE1_OFFSET    16
#define ITS_CFG_BASER_PA_H1_LEN            16
#define ITS_CFG_BASER_PA_H1_OFFSET         0

#define ITS_CFG_BASER_PA_L2_LEN            20
#define ITS_CFG_BASER_PA_L2_OFFSET         12
#define ITS_CFG_BASER_SHAREABILITY2_LEN    2
#define ITS_CFG_BASER_SHAREABILITY2_OFFSET 10
#define ITS_CFG_BASER_PAGESIZE2_LEN        2
#define ITS_CFG_BASER_PAGESIZE2_OFFSET     8
#define ITS_CFG_BASER_SIZE2_LEN            8
#define ITS_CFG_BASER_SIZE2_OFFSET         0

#define ITS_CFG_BASER_VALID2_LEN           1
#define ITS_CFG_BASER_VALID2_OFFSET        31
#define ITS_CFG_BASER_INDIRECT2_LEN        1
#define ITS_CFG_BASER_INDIRECT2_OFFSET     30
#define ITS_CFG_BASER_CACHEABILITY2_LEN    3
#define ITS_CFG_BASER_CACHEABILITY2_OFFSET 27
#define ITS_CFG_BASER_TYPE2_LEN            3
#define ITS_CFG_BASER_TYPE2_OFFSET         24
#define ITS_CFG_BASER_ENTRYSIZE2_LEN       8
#define ITS_CFG_BASER_ENTRYSIZE2_OFFSET    16
#define ITS_CFG_BASER_PA_H2_LEN            16
#define ITS_CFG_BASER_PA_H2_OFFSET         0

#define ITS_CFG_COMPONENT_ID0_LEN    8
#define ITS_CFG_COMPONENT_ID0_OFFSET 0

#define ITS_CFG_COMPONENT_ID1_LEN    8
#define ITS_CFG_COMPONENT_ID1_OFFSET 0

#define ITS_CFG_COMPONENT_ID2_LEN    8
#define ITS_CFG_COMPONENT_ID2_OFFSET 0

#define ITS_CFG_COMPONENT_ID3_LEN    8
#define ITS_CFG_COMPONENT_ID3_OFFSET 0

#define ITS_CFG_PIDR0_DEVID_L_LEN    8
#define ITS_CFG_PIDR0_DEVID_L_OFFSET 0

#define ITS_CFG_PIDR1_JEP_L_LEN      4
#define ITS_CFG_PIDR1_JEP_L_OFFSET   4
#define ITS_CFG_PIDR1_DEVID_H_LEN    4
#define ITS_CFG_PIDR1_DEVID_H_OFFSET 0

#define ITS_CFG_PIDR2_ITS_VER_LEN    4
#define ITS_CFG_PIDR2_ITS_VER_OFFSET 4
#define ITS_CFG_PIDR2_JEPEN_LEN      1
#define ITS_CFG_PIDR2_JEPEN_OFFSET   3
#define ITS_CFG_PIDR2_JEP_H_LEN      3
#define ITS_CFG_PIDR2_JEP_H_OFFSET   0

#define ITS_CFG_PIDR3_USER_VER_LEN    4
#define ITS_CFG_PIDR3_USER_VER_OFFSET 4
#define ITS_CFG_PIDR3_USER_LEN        4
#define ITS_CFG_PIDR3_USER_OFFSET     0

#define ITS_CFG_PIDR4_CONTINUATIONCODE_LEN    4
#define ITS_CFG_PIDR4_CONTINUATIONCODE_OFFSET 0







#define ITS_CFG_TRANSLATER_ID_LEN    32
#define ITS_CFG_TRANSLATER_ID_OFFSET 0

#define ITS_CFG_TRANSLATER_DID_LEN    32
#define ITS_CFG_TRANSLATER_DID_OFFSET 0

#define ITS_CFG_SL3_WR_BERR_LEN         1
#define ITS_CFG_SL3_WR_BERR_OFFSET      4
#define ITS_CFG_SL2_RDDATA_NULL_LEN     1
#define ITS_CFG_SL2_RDDATA_NULL_OFFSET  3
#define ITS_CFG_SL1_RDDATA_NULL_LEN     1
#define ITS_CFG_SL1_RDDATA_NULL_OFFSET  2
#define ITS_CFG_SL0_RDDATA_NULL_LEN     1
#define ITS_CFG_SL0_RDDATA_NULL_OFFSET  1
#define ITS_CFG_CMDQ_RDDATA_NULL_LEN    1
#define ITS_CFG_CMDQ_RDDATA_NULL_OFFSET 0

#define ITS_CFG_SNAP_EN_LEN       1
#define ITS_CFG_SNAP_EN_OFFSET    1
#define ITS_CFG_CNT_CLR_CE_LEN    1
#define ITS_CFG_CNT_CLR_CE_OFFSET 0

#define ITS_CFG_SL3_RD_ACK_CNT_LEN      1
#define ITS_CFG_SL3_RD_ACK_CNT_OFFSET   30
#define ITS_CFG_SL3_RD_REQ_CNT_LEN      1
#define ITS_CFG_SL3_RD_REQ_CNT_OFFSET   29
#define ITS_CFG_SL3_RD_RPOP_CNT_LEN     1
#define ITS_CFG_SL3_RD_RPOP_CNT_OFFSET  28
#define ITS_CFG_SL3_WR_BRESP_CNT_LEN    4
#define ITS_CFG_SL3_WR_BRESP_CNT_OFFSET 24
#define ITS_CFG_SL3_WR_ACK_CNT_LEN      4
#define ITS_CFG_SL3_WR_ACK_CNT_OFFSET   20
#define ITS_CFG_SL3_WR_REQ_CNT_LEN      4
#define ITS_CFG_SL3_WR_REQ_CNT_OFFSET   16
#define ITS_CFG_SL2_RD_RPOP_CNT_LEN     1
#define ITS_CFG_SL2_RD_RPOP_CNT_OFFSET  14
#define ITS_CFG_SL2_RD_ACK_CNT_LEN      1
#define ITS_CFG_SL2_RD_ACK_CNT_OFFSET   13
#define ITS_CFG_SL2_RD_REQ_CNT_LEN      1
#define ITS_CFG_SL2_RD_REQ_CNT_OFFSET   12
#define ITS_CFG_SL1_RD_RPOP_CNT_LEN     1
#define ITS_CFG_SL1_RD_RPOP_CNT_OFFSET  10
#define ITS_CFG_SL1_RD_ACK_CNT_LEN      1
#define ITS_CFG_SL1_RD_ACK_CNT_OFFSET   9
#define ITS_CFG_SL1_RD_REQ_CNT_LEN      1
#define ITS_CFG_SL1_RD_REQ_CNT_OFFSET   8
#define ITS_CFG_SL0_RD_RPOP_CNT_LEN     1
#define ITS_CFG_SL0_RD_RPOP_CNT_OFFSET  6
#define ITS_CFG_SL0_RD_ACK_CNT_LEN      1
#define ITS_CFG_SL0_RD_ACK_CNT_OFFSET   5
#define ITS_CFG_SL0_RD_REQ_CNT_LEN      1
#define ITS_CFG_SL0_RD_REQ_CNT_OFFSET   4
#define ITS_CFG_CMDQ_RD_RPOP_CNT_LEN    1
#define ITS_CFG_CMDQ_RD_RPOP_CNT_OFFSET 2
#define ITS_CFG_CMDQ_RD_ACK_CNT_LEN     1
#define ITS_CFG_CMDQ_RD_ACK_CNT_OFFSET  1
#define ITS_CFG_CMDQ_RD_REQ_CNT_LEN     1
#define ITS_CFG_CMDQ_RD_REQ_CNT_OFFSET  0

#define ITS_CFG_SYS_ERR0_LEN    32
#define ITS_CFG_SYS_ERR0_OFFSET 0

#define ITS_CFG_SYS_ERR1_LEN    32
#define ITS_CFG_SYS_ERR1_OFFSET 0

#define ITS_CFG_SYS_ERR2_LEN    32
#define ITS_CFG_SYS_ERR2_OFFSET 0

#define ITS_CFG_SL3_FSM_ST_LEN          2
#define ITS_CFG_SL3_FSM_ST_OFFSET       28
#define ITS_CFG_SL2_FSM_ST_LEN          3
#define ITS_CFG_SL2_FSM_ST_OFFSET       24
#define ITS_CFG_SL1_FSM_ST_LEN          3
#define ITS_CFG_SL1_FSM_ST_OFFSET       20
#define ITS_CFG_SL0_FSM_ST_LEN          3
#define ITS_CFG_SL0_FSM_ST_OFFSET       16
#define ITS_CFG_TRANSLATER_RQ_ST_LEN    1
#define ITS_CFG_TRANSLATER_RQ_ST_OFFSET 10

#define ITS_CFG_CMDQ_FIFO_STATUS_LEN    2
#define ITS_CFG_CMDQ_FIFO_STATUS_OFFSET 0

#define ITS_CFG_USER_FP_LEN           1
#define ITS_CFG_USER_FP_OFFSET        30
#define ITS_CFG_USER_CLEANINV_LEN     1
#define ITS_CFG_USER_CLEANINV_OFFSET  27
#define ITS_CFG_USER_FNA_LEN          1
#define ITS_CFG_USER_FNA_OFFSET       26
#define ITS_CFG_USER_FA_LEN           1
#define ITS_CFG_USER_FA_OFFSET        25
#define ITS_CFG_USER_TYPE_LEN         4
#define ITS_CFG_USER_TYPE_OFFSET      18
#define ITS_CFG_USER_SNAPATTR_LEN     2
#define ITS_CFG_USER_SNAPATTR_OFFSET  16
#define ITS_CFG_USER_REQUESTID_LEN    16
#define ITS_CFG_USER_REQUESTID_OFFSET 0

#define ITS_CFG_DFX_RX_LPIID_LEN    16
#define ITS_CFG_DFX_RX_LPIID_OFFSET 0

#define ITS_CFG_DFX_RX_CMDID_LEN    8
#define ITS_CFG_DFX_RX_CMDID_OFFSET 20
#define ITS_CFG_DFX_RX_DID_LEN      20
#define ITS_CFG_DFX_RX_DID_OFFSET   0

#define ITS_CFG_DFX_CACHE_CNT_CS_LEN    2
#define ITS_CFG_DFX_CACHE_CNT_CS_OFFSET 0

#define ITS_CFG_DFX_CACHE_MISS_CNT_LEN    32
#define ITS_CFG_DFX_CACHE_MISS_CNT_OFFSET 0

#define ITS_CFG_IIDR_PRODUCTID_LEN               8
#define ITS_CFG_IIDR_PRODUCTID_OFFSET            24
#define ITS_CFG_BD_PIDR4_CONTINUATIONCODE_LEN    4
#define ITS_CFG_BD_PIDR4_CONTINUATIONCODE_OFFSET 20
#define ITS_CFG_PIDR01_DEVID_LEN                 12
#define ITS_CFG_PIDR01_DEVID_OFFSET              8
#define ITS_CFG_PIDR2_JEDECEN_LEN                1
#define ITS_CFG_PIDR2_JEDECEN_OFFSET             7
#define ITS_CFG_PIDR12_JEDECID_LEN               7
#define ITS_CFG_PIDR12_JEDECID_OFFSET            0

#define ITS_CFG_DFX_LPIRX_CNT_LEN    32
#define ITS_CFG_DFX_LPIRX_CNT_OFFSET 0

#define ITS_CFG_LPI_DISCARD_CNT_LEN    32
#define ITS_CFG_LPI_DISCARD_CNT_OFFSET 0

#define ITS_CFG_LPITX_CNT_LEN    32
#define ITS_CFG_LPITX_CNT_OFFSET 0

#define ITS_CFG_SL2_CACHE_INV_SUCC_LEN    1
#define ITS_CFG_SL2_CACHE_INV_SUCC_OFFSET 21
#define ITS_CFG_SL1_CACHE_INV_SUCC_LEN    1
#define ITS_CFG_SL1_CACHE_INV_SUCC_OFFSET 20
#define ITS_CFG_SL0_CACHE_INV_SUCC_LEN    1
#define ITS_CFG_SL0_CACHE_INV_SUCC_OFFSET 19
#define ITS_CFG_SLX_CACHE_INV_LEN         3
#define ITS_CFG_SLX_CACHE_INV_OFFSET      16
#define ITS_CFG_FETURE_EN_LEN             16
#define ITS_CFG_FETURE_EN_OFFSET          0

#define ITS_CFG_DFX_DEVID_CS_LEN      16
#define ITS_CFG_DFX_DEVID_CS_OFFSET   16
#define ITS_CFG_DFX_EVENTID_CS_LEN    16
#define ITS_CFG_DFX_EVENTID_CS_OFFSET 0

#define ITS_CFG_DFX_INFO0_LEN    32
#define ITS_CFG_DFX_INFO0_OFFSET 0

#define ITS_CFG_DFX_INFO1_LEN    32
#define ITS_CFG_DFX_INFO1_OFFSET 0

#define ITS_CFG_DFX_INFO2_LEN    32
#define ITS_CFG_DFX_INFO2_OFFSET 0

#define ITS_CFG_DFX_INFO3_LEN    32
#define ITS_CFG_DFX_INFO3_OFFSET 0

#define ITS_CFG_DFX_INFO4_LEN    32
#define ITS_CFG_DFX_INFO4_OFFSET 0

#define ITS_CFG_DFX_INFO5_LEN    32
#define ITS_CFG_DFX_INFO5_OFFSET 0

#define ITS_CFG_DFX_RAS_MASK0_LEN    32
#define ITS_CFG_DFX_RAS_MASK0_OFFSET 0

#define ITS_CFG_DFX_RAS_MASK1_LEN    32
#define ITS_CFG_DFX_RAS_MASK1_OFFSET 0

#define ITS_CFG_DFX_RAS_MASK2_LEN    16
#define ITS_CFG_DFX_RAS_MASK2_OFFSET 0

#define ITS_CFG_DFX_RAS_INJECT0_LEN    32
#define ITS_CFG_DFX_RAS_INJECT0_OFFSET 0

#define ITS_CFG_DFX_RAS_INJECT1_LEN    32
#define ITS_CFG_DFX_RAS_INJECT1_OFFSET 0

#define ITS_CFG_DFX_RAS_INJECT_EN_LEN    1
#define ITS_CFG_DFX_RAS_INJECT_EN_OFFSET 31
#define ITS_CFG_DFX_RAS_INJECT2_LEN      16
#define ITS_CFG_DFX_RAS_INJECT2_OFFSET   0

#define ITS_CFG_SYNC_TIMEOUT_CNT_LEN    32
#define ITS_CFG_SYNC_TIMEOUT_CNT_OFFSET 0

#define ITS_CFG_SL3_OSTD_CNT_LEN    4
#define ITS_CFG_SL3_OSTD_CNT_OFFSET 0

#define ITS_CFG_DFX_AXIM_WDATA64_L_LEN    32
#define ITS_CFG_DFX_AXIM_WDATA64_L_OFFSET 0

#define ITS_CFG_DFX_AXIM_WDATA64_H_LEN    32
#define ITS_CFG_DFX_AXIM_WDATA64_H_OFFSET 0

#define ITS_CFG_DFX_AXIM_WDATA64_L_LEN    32
#define ITS_CFG_DFX_AXIM_WDATA64_L_OFFSET 0

#define ITS_CFG_DFX_AXIM_WDATA64_H_LEN    32
#define ITS_CFG_DFX_AXIM_WDATA64_H_OFFSET 0

#define ITS_CFG_DFX_AXIM_ADDR_L_LEN    32
#define ITS_CFG_DFX_AXIM_ADDR_L_OFFSET 0

#define ITS_CFG_DFX_AXIM_ADDR_H_LEN    16
#define ITS_CFG_DFX_AXIM_ADDR_H_OFFSET 0

#endif // __ITS_CFG_REG_OFFSET_FIELD_H__
