// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  sdmam_common_regs_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/23 09:19:00 Create file
// ******************************************************************************

#ifndef __SDMAM_COMMON_REGS_REG_OFFSET_H__
#define __SDMAM_COMMON_REGS_REG_OFFSET_H__

/* SDMAM_COMMON_REGS Base address of Module's Register */
#define SOC_SDMAM_COMMON_REGS_BASE                       (0x0)

/******************************************************************************/
/*                      SOC SDMAM_COMMON_REGS Registers' Definitions                            */
/******************************************************************************/

#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO0_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x0)   /* SDMAM EMU PRESS CNT寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO1_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x4)   /* SDMAM EMU PRESS CNT寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO2_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x8)   /* SDMAM EMU PRESS CNT寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO3_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0xC)   /* SDMAM EMU PRESS CNT寄存器3 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO4_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x10)  /* SDMAM EMU PRESS CNT寄存器4 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO5_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x14)  /* SDMAM EMU PRESS CNT寄存器5 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO6_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x18)  /* SDMAM EMU PRESS CNT寄存器6 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO7_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x1C)  /* SDMAM EMU PRESS CNT寄存器7 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO8_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x20)  /* SDMAM EMU PRESS CNT寄存器8 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO9_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x24)  /* SDMAM EMU PRESS CNT寄存器9 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO10_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x28)  /* SDMAM EMU PRESS CNT寄存器10 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO11_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x2C)  /* SDMAM EMU PRESS CNT寄存器11 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO12_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x30)  /* SDMAM EMU PRESS CNT寄存器12 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO13_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x34)  /* SDMAM EMU PRESS CNT寄存器13 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO14_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x38)  /* SDMAM EMU PRESS CNT寄存器14 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO15_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x3C)  /* SDMAM EMU PRESS CNT寄存器15 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO0_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x100) /* 探测SDMAM运行信息寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO1_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x104) /* 探测SDMAM运行信息寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO2_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x108) /* 探测SDMAM运行信息寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO3_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x10C) /* 探测SDMAM运行信息寄存器3 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO4_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x110) /* 探测SDMAM运行信息寄存器4 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO5_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x114) /* 探测SDMAM运行信息寄存器5 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO6_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x118) /* 探测SDMAM运行信息寄存器6 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO7_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x11C) /* 探测SDMAM运行信息寄存器7 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO8_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x120) /* 探测SDMAM运行信息寄存器8 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO9_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x134) /* 探测SDMAM运行信息寄存器9 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO10_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x138) /* 探测SDMAM运行信息寄存器10 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO11_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x13C) /* 探测SDMAM运行信息寄存器11 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO12_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x140) /* 探测SDMAM运行信息寄存器12 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO13_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x144) /* 探测SDMAM运行信息寄存器13 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO14_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x148) /* 探测SDMAM运行信息寄存器14 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO15_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x14C) /* 探测SDMAM运行信息寄存器15 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO16_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x150) /* 探测SDMAM运行信息寄存器16 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO17_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x154) /* 探测SDMAM运行信息寄存器17 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO18_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x158) /* 探测SDMAM运行信息寄存器18 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO19_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x15C) /* 探测SDMAM运行信息寄存器19 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO20_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x160) /* 探测SDMAM运行信息寄存器20 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO21_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x164) /* 探测SDMAM运行信息寄存器21 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO22_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x168) /* 探测SDMAM运行信息寄存器22 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO24_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x170) /* 探测SDMAM运行信息寄存器24 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO25_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x174) /* 探测SDMAM运行信息寄存器25 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO26_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x178) /* 探测SDMAM运行信息寄存器26 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO27_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x17C) /* 探测SDMAM运行信息寄存器27 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO28_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x180) /* 探测SDMAM运行信息寄存器28 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO29_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x184) /* 探测SDMAM运行信息寄存器29 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO30_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x188) /* 探测SDMAM运行信息寄存器30 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO31_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x18C) /* 探测SDMAM运行信息寄存器31 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO32_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x190) /* 探测SDMAM运行信息寄存器32 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO34_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x198) /* 探测SDMAM运行信息寄存器34 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO35_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x19C) /* 探测SDMAM运行信息寄存器35 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_MASK_NS_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x300) /* 非安全中断屏蔽寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_MASK_S_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x304) /* 安全中断屏蔽寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_STATUS_IOE_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x308) /* 安全和非安全通道中断状态寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_STATUS_IOE_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x30C) /* 安全和非安全通道中断状态寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_STATUS_IOC_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x310) /* 安全和非安全通道中断状态寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_STATUS_IOC_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x314) /* 安全和非安全通道中断状态寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL0_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x318) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL0_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x31C) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL1_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x320) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL1_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x324) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL2_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x328) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL2_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x32C) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL3_L_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x330) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_INT_GROUP_SEL3_H_REG (SOC_SDMAM_COMMON_REGS_BASE + 0x334) /* 中断分组选择寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_MEM_TEST_REG         (SOC_SDMAM_COMMON_REGS_BASE + 0x338) /* memory测试寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_ECC_INJECT_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x33C) /* ECC注错寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_SP_ARB_TIMEOUT_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0x340) /* SP调度QoS超时阈值寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_MPAMID_CFG_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x344) /* MPAM ID全局替换寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_DIRECT_SQE_BAL_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0x3C0) /* direct sqe基地址低32bit */
#define SOC_SDMAM_COMMON_REGS_DMA_DIRECT_SQE_BAH_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0x3C4) /* direct sqe基地址高16bit */
#define SOC_SDMAM_COMMON_REGS_DMA_ATSREQ_REG_H_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x3C8) /* 向SMMU发送ATS请求属性配置高位寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_ATSREQ_REG_L_REG     (SOC_SDMAM_COMMON_REGS_BASE + 0x3CC) /* 向SMMU发送ATS请求属性配置低位寄存器 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL0_REG            (SOC_SDMAM_COMMON_REGS_BASE + 0x3D0) /* DFX ctrl Register0 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL1_REG            (SOC_SDMAM_COMMON_REGS_BASE + 0x3D4) /* DFX ctrl Register1 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL2_REG            (SOC_SDMAM_COMMON_REGS_BASE + 0x3D8) /* DFX ctrl Register2 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG0_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x3E0) /* AXUSER配置寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG1_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x3E4) /* AXUSER配置寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG2_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x3E8) /* AXUSER配置寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG3_REG      (SOC_SDMAM_COMMON_REGS_BASE + 0x3EC) /* AXUSER配置寄存器3 */
#define SOC_SDMAM_COMMON_REGS_DFX_CNT_CLR_CE_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x3F4) /* CNT_CYC类型寄存器读清控制信号 */
#define SOC_SDMAM_COMMON_REGS_DFX_TEST_CTRL_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0x3F8) /* DFX和计数器控制寄存器 */
#define SOC_SDMAM_COMMON_REGS_DFX_FEATURE_EN_REG       (SOC_SDMAM_COMMON_REGS_BASE + 0x3FC) /* 功能使能开关寄存器 */

#endif // __SDMAM_COMMON_REGS_REG_OFFSET_H__
