// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_s_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:39:25 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_S_REG_REG_OFFSET_FIELD_H__
#define __STARS_CQINT_S_REG_REG_OFFSET_FIELD_H__

#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_S_MASK0_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_S_MASK0_OFFSET 0

#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_AFT_S_STATUS0_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_AFT_S_STATUS0_OFFSET 1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_PRE_S_STATUS0_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_PRE_S_STATUS0_OFFSET 0

#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_PRE_S_STATUS0_LEN    32
#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_PRE_S_STATUS0_OFFSET 0

#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_AFT_S_STATUS0_LEN    32
#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_AFT_S_STATUS0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_0_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_1_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_2_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_2_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_3_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_3_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_4_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_4_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_5_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_5_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_6_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_6_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_7_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_7_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_8_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_8_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_9_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_9_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_10_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_10_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_11_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_11_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_12_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_12_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_13_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_13_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_14_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_14_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_15_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS0_15_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_0_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_1_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_2_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_2_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_3_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_3_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_4_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_4_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_5_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_5_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_6_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_6_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_7_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_7_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_8_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_8_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_9_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_9_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_10_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_10_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_11_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_11_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_12_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_12_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_13_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_13_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_14_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_14_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_15_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR0_15_OFFSET 0

#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_S_MASK1_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_S_MASK1_OFFSET 0

#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_AFT_S_STATUS1_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_AFT_S_STATUS1_OFFSET 1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_PRE_S_STATUS1_LEN    1
#define STARS_CQINT_S_REG_L1_CQE_WRITTEN_PRE_S_STATUS1_OFFSET 0

#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_PRE_S_STATUS1_LEN    32
#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_PRE_S_STATUS1_OFFSET 0

#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_AFT_S_STATUS1_LEN    32
#define STARS_CQINT_S_REG_MID_CQE_WRITTEN_AFT_S_STATUS1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_0_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_1_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_2_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_2_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_3_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_3_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_4_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_4_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_5_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_5_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_6_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_6_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_7_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_7_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_8_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_8_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_9_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_9_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_10_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_10_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_11_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_11_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_12_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_12_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_13_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_13_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_14_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_14_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_15_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_STATUS1_15_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_0_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_1_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_2_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_2_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_3_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_3_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_4_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_4_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_5_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_5_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_6_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_6_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_7_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_7_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_8_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_8_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_9_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_9_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_10_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_10_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_11_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_11_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_12_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_12_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_13_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_13_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_14_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_14_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_15_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_CLR1_15_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_0_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_0_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_1_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_1_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_2_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_2_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_3_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_3_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_4_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_4_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_5_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_5_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_6_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_6_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_7_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_7_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_8_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_8_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_9_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_9_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_10_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_10_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_11_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_11_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_12_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_12_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_13_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_13_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_14_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_14_OFFSET 0

#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_15_LEN    32
#define STARS_CQINT_S_REG_L2_CQE_WRITTEN_S_RAW0_15_OFFSET 0

#endif // __STARS_CQINT_S_REG_REG_OFFSET_FIELD_H__
