// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cdqm_cfg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:38:51 Create file
// ******************************************************************************

#ifndef __STARS_CDQM_CFG_REG_OFFSET_FIELD_H__
#define __STARS_CDQM_CFG_REG_OFFSET_FIELD_H__

#define STARS_CDQM_CFG_STARS_AWSNOOP_CDQM_INTERDIE_LEN    1
#define STARS_CDQM_CFG_STARS_AWSNOOP_CDQM_INTERDIE_OFFSET 17
#define STARS_CDQM_CFG_STARS_AWCACHE_CDQM_INTERDIE_LEN    4
#define STARS_CDQM_CFG_STARS_AWCACHE_CDQM_INTERDIE_OFFSET 13
#define STARS_CDQM_CFG_STARS_AWNS_CDQM_INTERDIE_LEN       1
#define STARS_CDQM_CFG_STARS_AWNS_CDQM_INTERDIE_OFFSET    12
#define STARS_CDQM_CFG_STARS_ARSNOOP_CDQM_LEN             1
#define STARS_CDQM_CFG_STARS_ARSNOOP_CDQM_OFFSET          11
#define STARS_CDQM_CFG_STARS_ARCACHE_CDQM_LEN             4
#define STARS_CDQM_CFG_STARS_ARCACHE_CDQM_OFFSET          7
#define STARS_CDQM_CFG_STARS_ARNS_CDQM_LEN                1
#define STARS_CDQM_CFG_STARS_ARNS_CDQM_OFFSET             6
#define STARS_CDQM_CFG_STARS_AWSNOOP_CDQM_LEN             1
#define STARS_CDQM_CFG_STARS_AWSNOOP_CDQM_OFFSET          5
#define STARS_CDQM_CFG_STARS_AWCACHE_CDQM_LEN             4
#define STARS_CDQM_CFG_STARS_AWCACHE_CDQM_OFFSET          1
#define STARS_CDQM_CFG_STARS_AWNS_CDQM_LEN                1
#define STARS_CDQM_CFG_STARS_AWNS_CDQM_OFFSET             0

#define STARS_CDQM_CFG_STARS_NS_AWPROT_CDQM_INTERDIE_LEN    3
#define STARS_CDQM_CFG_STARS_NS_AWPROT_CDQM_INTERDIE_OFFSET 6
#define STARS_CDQM_CFG_STARS_NS_ARPROT_CDQM_LEN             3
#define STARS_CDQM_CFG_STARS_NS_ARPROT_CDQM_OFFSET          3
#define STARS_CDQM_CFG_STARS_NS_AWPROT_CDQM_LEN             3
#define STARS_CDQM_CFG_STARS_NS_AWPROT_CDQM_OFFSET          0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_ID_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_ID_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_KERNEL_TYPE_LEN    8
#define STARS_CDQM_CFG_CDQM_CDQ_KERNEL_TYPE_OFFSET 0

#define STARS_CDQM_CFG_CDQM_VA_CFG_LEN        1
#define STARS_CDQM_CFG_CDQM_VA_CFG_OFFSET     4
#define STARS_CDQM_CFG_CDQM_VA_CFG_SEL_LEN    1
#define STARS_CDQM_CFG_CDQM_VA_CFG_SEL_OFFSET 0

#define STARS_CDQM_CFG_CDQM_OTHER_DIE_CDQM_ADDR_LOW_LEN    32
#define STARS_CDQM_CFG_CDQM_OTHER_DIE_CDQM_ADDR_LOW_OFFSET 0

#define STARS_CDQM_CFG_CDQM_OTHER_DIE_CDQM_ADDR_HIGH_LEN    32
#define STARS_CDQM_CFG_CDQM_OTHER_DIE_CDQM_ADDR_HIGH_OFFSET 0

#define STARS_CDQM_CFG_CDQM_TOPIC_BYPASS_LEN    1
#define STARS_CDQM_CFG_CDQM_TOPIC_BYPASS_OFFSET 0

#define STARS_CDQM_CFG_CDQM_TOPIC_OST_BLOCK_SENDING_LEN    1
#define STARS_CDQM_CFG_CDQM_TOPIC_OST_BLOCK_SENDING_OFFSET 1
#define STARS_CDQM_CFG_CDQM_TOPIC_OST_CLR_OPTION_LEN       1
#define STARS_CDQM_CFG_CDQM_TOPIC_OST_CLR_OPTION_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CFG_SEC_LOCK_LEN    32
#define STARS_CDQM_CFG_CDQM_CFG_SEC_LOCK_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE0_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE1_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE2_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE3_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQ_ID_LEN     16
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQ_ID_OFFSET  16
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_ID_LEN    16
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_ID_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_RSV0_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_RSV0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_RSV1_LEN    32
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_CDQE_RSV1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_INTER_WRITE_DOORBELL_LEN    1
#define STARS_CDQM_CFG_CDQM_INTER_WRITE_DOORBELL_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK0_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK0_L1_OFFSET 4
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK0_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK0_L1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS0_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS0_L1_OFFSET 4
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS0_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS0_L1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK1_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK1_L1_OFFSET 4
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK1_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK1_L1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS1_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STATUS1_L1_OFFSET 4
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS1_L1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STATUS1_L1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_FORCE_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_FORCE_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_FORCE_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_FORCE_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ3_RTCDQID_LEN    7
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ3_RTCDQID_OFFSET 21
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ2_RTCDQID_LEN    7
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ2_RTCDQID_OFFSET 14
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ1_RTCDQID_LEN    7
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ1_RTCDQID_OFFSET 7
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ0_RTCDQID_LEN    7
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ0_RTCDQID_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ3_FSM_STATE_LEN    4
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ3_FSM_STATE_OFFSET 12
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ2_FSM_STATE_LEN    4
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ2_FSM_STATE_OFFSET 8
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ1_FSM_STATE_LEN    4
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ1_FSM_STATE_OFFSET 4
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ0_FSM_STATE_LEN    4
#define STARS_CDQM_CFG_CDQM_DFX_ACCDQ0_FSM_STATE_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_CDQ_IMG_NO_RDY_LEN    16
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_IMG_NO_RDY_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_CDQ_ARRV_BOUND_LEN    16
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_ARRV_BOUND_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_CDQ_BUF_CNT_LEN    4
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_BUF_CNT_OFFSET 0

#define STARS_CDQM_CFG_CDQM_DFX_CDQ_WR_OST_CNT_LEN    5
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_WR_OST_CNT_OFFSET 5
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_RD_OST_CNT_LEN    5
#define STARS_CDQM_CFG_CDQM_DFX_CDQ_RD_OST_CNT_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_0_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_1_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_2_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_3_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_4_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_5_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_6_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_7_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_8_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_9_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_10_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_11_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_12_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_13_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_14_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_15_LEN    32
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_LOW_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_0_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_1_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_2_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_3_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_4_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_5_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_6_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_7_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_8_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_9_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_10_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_11_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_12_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_13_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_14_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_15_LEN    17
#define STARS_CDQM_CFG_CDQM_BASE_ADDR_HIGH_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_EN_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_EN_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_0_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_0_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_1_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_1_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_2_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_2_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_3_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_3_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_4_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_4_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_5_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_5_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_6_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_6_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_7_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_7_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_8_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_8_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_9_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_9_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_10_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_10_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_11_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_11_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_12_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_12_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_13_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_13_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_14_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_14_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_STATUS_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_15_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_NOTIFY_SET_15_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_0_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_0_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_1_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_1_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_2_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_2_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_3_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_3_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_4_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_4_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_5_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_5_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_6_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_6_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_7_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_7_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_8_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_8_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_9_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_9_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_10_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_10_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_11_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_11_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_12_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_12_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_13_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_13_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_14_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_14_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_STATUS_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_15_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NOTIFY_SET_15_OFFSET    0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_0_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_0_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_0_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_0_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_1_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_1_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_1_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_1_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_2_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_2_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_2_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_2_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_3_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_3_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_3_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_3_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_4_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_4_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_4_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_4_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_5_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_5_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_5_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_5_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_6_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_6_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_6_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_6_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_7_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_7_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_7_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_7_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_8_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_8_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_8_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_8_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_9_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_9_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_9_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_9_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_10_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_10_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_10_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_10_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_11_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_11_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_11_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_11_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_12_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_12_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_12_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_12_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_13_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_13_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_13_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_13_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_14_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_14_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_14_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_14_OFFSET   0

#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_15_LEN    16
#define STARS_CDQM_CFG_CDQM_RTCDQ_LENGTH_15_OFFSET 16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_15_LEN      16
#define STARS_CDQM_CFG_CDQM_BATCH_SIZE_15_OFFSET   0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_0_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_1_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_2_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_3_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_4_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_5_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_6_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_7_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_8_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_9_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_10_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_11_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_12_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_13_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_14_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_15_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_NUM_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_0_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_1_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_2_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_3_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_4_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_5_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_6_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_7_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_8_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_9_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_10_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_11_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_12_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_13_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_14_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_15_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_RDY_IDX_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_BATCH_GET_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_0_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_1_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_2_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_3_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_4_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_5_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_6_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_7_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_8_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_9_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_10_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_11_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_12_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_13_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_14_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_PID_15_LEN    32
#define STARS_CDQM_CFG_CDQM_CDQ_PID_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_0_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_0_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_0_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_0_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_0_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_0_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_0_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_0_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_0_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_0_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_0_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_1_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_1_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_1_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_1_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_1_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_1_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_1_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_1_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_1_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_1_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_1_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_2_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_2_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_2_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_2_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_2_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_2_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_2_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_2_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_2_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_2_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_2_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_3_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_3_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_3_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_3_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_3_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_3_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_3_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_3_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_3_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_3_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_3_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_4_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_4_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_4_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_4_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_4_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_4_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_4_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_4_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_4_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_4_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_4_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_5_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_5_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_5_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_5_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_5_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_5_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_5_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_5_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_5_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_5_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_5_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_6_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_6_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_6_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_6_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_6_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_6_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_6_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_6_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_6_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_6_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_6_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_7_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_7_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_7_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_7_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_7_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_7_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_7_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_7_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_7_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_7_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_7_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_8_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_8_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_8_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_8_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_8_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_8_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_8_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_8_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_8_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_8_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_8_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_9_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_9_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_9_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_9_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_9_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_9_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_9_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_9_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_9_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_9_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_9_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_10_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_10_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_10_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_10_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_10_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_10_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_10_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_10_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_10_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_10_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_10_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_11_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_11_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_11_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_11_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_11_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_11_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_11_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_11_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_11_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_11_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_11_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_12_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_12_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_12_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_12_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_12_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_12_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_12_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_12_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_12_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_12_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_12_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_13_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_13_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_13_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_13_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_13_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_13_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_13_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_13_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_13_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_13_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_13_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_14_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_14_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_14_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_14_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_14_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_14_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_14_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_14_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_14_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_14_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_14_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_15_LEN          1
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_EN_15_OFFSET       31
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_15_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_LOG_BUF_ID_15_OFFSET   26
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_15_LEN      4
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_TYPE_15_OFFSET   22
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_15_LEN             4
#define STARS_CDQM_CFG_CDQM_CDQ_QOS_15_OFFSET          18
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_15_LEN          6
#define STARS_CDQM_CFG_CDQM_CDQ_GRP_ID_15_OFFSET       12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_15_LEN    12
#define STARS_CDQM_CFG_CDQM_CDQ_SUB_TOPIC_ID_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_0_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_0_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_0_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_0_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_1_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_1_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_1_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_1_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_2_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_2_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_2_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_2_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_3_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_3_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_3_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_3_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_4_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_4_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_4_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_4_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_5_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_5_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_5_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_5_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_6_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_6_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_6_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_6_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_7_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_7_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_7_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_7_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_8_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_8_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_8_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_8_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_9_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_9_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_9_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_9_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_10_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_10_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_10_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_10_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_11_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_11_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_11_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_11_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_12_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_12_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_12_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_12_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_13_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_13_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_13_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_13_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_14_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_14_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_14_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_14_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_15_LEN    16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_SUBSTREAMID_15_OFFSET 16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_15_LEN       16
#define STARS_CDQM_CFG_CDQM_CDQ_SMMU_STREAMID_15_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_0_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_0_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_1_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_1_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_2_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_2_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_3_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_3_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_4_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_4_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_5_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_5_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_6_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_6_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_7_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_7_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_8_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_8_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_9_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_9_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_10_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_10_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_11_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_11_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_12_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_12_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_13_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_13_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_14_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_14_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_STATUS_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_15_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_OST_CLR_15_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_0_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_0_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_1_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_1_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_2_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_2_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_3_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_3_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_4_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_4_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_5_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_5_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_6_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_6_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_7_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_7_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_8_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_8_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_9_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_9_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_10_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_10_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_11_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_11_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_12_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_12_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_13_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_13_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_14_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_14_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_STATUS_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_15_LEN       1
#define STARS_CDQM_CFG_CDQM_CDQ_TOPIC_PID_ERROR_CLR_15_OFFSET    0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_STS2_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_INT_CLR2_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_L1_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_L1_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_0_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_1_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_2_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_3_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_4_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_5_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_6_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_7_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_8_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_9_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_10_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_11_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_12_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_13_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_14_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_L1_15_OFFSET 1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_L1_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_0_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_1_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_2_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_3_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_4_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_5_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_6_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_7_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_8_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_9_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_10_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_11_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_12_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_13_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_14_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_MASK2_15_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_MASK2_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_0_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_1_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_2_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_3_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_4_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_5_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_6_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_7_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_8_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_9_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_10_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_11_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_12_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_13_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_14_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_STS2_15_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_STS2_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_0_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_1_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_2_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_3_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_4_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_5_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_6_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_7_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_8_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_9_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_10_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_11_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_12_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_13_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_14_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_RAW2_15_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_RAW2_15_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_0_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_0_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_0_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_1_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_1_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_1_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_2_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_2_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_2_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_3_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_3_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_3_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_4_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_4_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_4_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_5_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_5_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_5_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_6_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_6_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_6_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_7_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_7_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_7_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_8_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_8_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_8_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_9_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_9_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_9_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_10_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_10_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_10_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_11_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_11_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_11_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_12_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_12_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_12_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_13_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_13_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_13_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_14_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_14_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_14_OFFSET 0

#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_E2NE_INT_CLR2_15_OFFSET 8
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_15_LEN    1
#define STARS_CDQM_CFG_CDQM_CDQ_F2NF_INT_CLR2_15_OFFSET 0

#endif // __STARS_CDQM_CFG_REG_OFFSET_FIELD_H__
