// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cmo_ns_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/22 14:35:24 Create file
// ******************************************************************************

#ifndef __STARS_CMO_NS_REG_REG_OFFSET_H__
#define __STARS_CMO_NS_REG_REG_OFFSET_H__

/* STARS_CMO_NS_REG Base address of Module's Register */
#define SOC_STARS_CMO_NS_REG_BASE                       (0x2c0c000)

/******************************************************************************/
/*                      SOC STARS_CMO_NS_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_CMO_NS_REG_STARS_PRIORITY_CTRL0_REG                (SOC_STARS_CMO_NS_REG_BASE + 0x0)
#define SOC_STARS_CMO_NS_REG_STARS_PRIORITY_CTRL1_REG                (SOC_STARS_CMO_NS_REG_BASE + 0x4)
#define SOC_STARS_CMO_NS_REG_STARS_PRIORITY_CTRL2_REG                (SOC_STARS_CMO_NS_REG_BASE + 0x8)
#define SOC_STARS_CMO_NS_REG_STARS_PRIORITY_CTRL3_REG                (SOC_STARS_CMO_NS_REG_BASE + 0xC)
#define SOC_STARS_CMO_NS_REG_STARS_FRIENDLY_CTRL_REG                 (SOC_STARS_CMO_NS_REG_BASE + 0x20)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_BLK_FSM_SEL_REG               (SOC_STARS_CMO_NS_REG_BASE + 0x810)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_BLK_FSM_STATE_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x814)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_REDUNDANT_RSP_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x820)
#define SOC_STARS_CMO_NS_REG_STARS_FREE_CMO_SQ_BITMAP_REG            (SOC_STARS_CMO_NS_REG_BASE + 0x824)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_CNT_ENABLE_REG            (SOC_STARS_CMO_NS_REG_BASE + 0x830)  /* CMO调度器任务总数统计使能寄存器 */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_TASK_VLD_CNT_REG          (SOC_STARS_CMO_NS_REG_BASE + 0x834)  /* CMO调度器下发任务总数 */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_TASK_RSP_CNT_REG          (SOC_STARS_CMO_NS_REG_BASE + 0x838)  /* CMO调度器收到加速器完成响应总数 */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_POOL_ENABLE_CTRL_NS_REG       (SOC_STARS_CMO_NS_REG_BASE + 0x840)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_POOL_DISABLE_CTRL_NS_REG      (SOC_STARS_CMO_NS_REG_BASE + 0x880)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_POOL_STATUS0_NS_REG           (SOC_STARS_CMO_NS_REG_BASE + 0x8C0)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_LOG_REG                       (SOC_STARS_CMO_NS_REG_BASE + 0x900)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS0_0_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x940)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS0_1_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x980)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS1_0_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x944)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS1_1_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x984)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS2_0_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x948)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS2_1_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x988)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS3_0_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x94C)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_CQE_STATUS3_1_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x98C)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_PREFETCH_BUF_CMO_ID_0_REG (SOC_STARS_CMO_NS_REG_BASE + 0x1150) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_PREFETCH_BUF_CMO_ID_1_REG (SOC_STARS_CMO_NS_REG_BASE + 0x1154) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_PREFETCH_BUF_CMO_ID_2_REG (SOC_STARS_CMO_NS_REG_BASE + 0x1158) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_PREFETCH_BUF_CMO_ID_3_REG (SOC_STARS_CMO_NS_REG_BASE + 0x115C) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_INVALID_BUF_CMO_ID_0_REG  (SOC_STARS_CMO_NS_REG_BASE + 0x1160) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_INVALID_BUF_CMO_ID_1_REG  (SOC_STARS_CMO_NS_REG_BASE + 0x1164) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_INVALID_BUF_CMO_ID_2_REG  (SOC_STARS_CMO_NS_REG_BASE + 0x1168) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_INVALID_BUF_CMO_ID_3_REG  (SOC_STARS_CMO_NS_REG_BASE + 0x116C) /* cmo BUFFFER中的CMOID和RT STREAM ID */
#define SOC_STARS_CMO_NS_REG_STARS_CMO_DFX_BUF_EMPTY_REG             (SOC_STARS_CMO_NS_REG_BASE + 0x1170)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_WORK_STOP_REG                 (SOC_STARS_CMO_NS_REG_BASE + 0x1174)
#define SOC_STARS_CMO_NS_REG_STARS_CMO_BUF_CLR_REG                   (SOC_STARS_CMO_NS_REG_BASE + 0x1178)

#endif // __STARS_CMO_NS_REG_REG_OFFSET_H__
