// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cmo_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:35:24 Create file
// ******************************************************************************

#ifndef __STARS_CMO_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_CMO_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_CMO_NS_REG_SP_LEVEL_LEN    3
#define STARS_CMO_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_CMO_NS_REG_LP_MODE_LEN     3
#define STARS_CMO_NS_REG_LP_MODE_OFFSET  0



#define STARS_CMO_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_CMO_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_CMO_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_CMO_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_CMO_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_CMO_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_CMO_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_CMO_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_CMO_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_CMO_NS_REG_SQ_FRIENDLY_JPEGD_LEN    1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_JPEGD_OFFSET 16
#define STARS_CMO_NS_REG_SQ_FRIENDLY_JPEGE_LEN    1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_JPEGE_OFFSET 15
#define STARS_CMO_NS_REG_SQ_FRIENDLY_VPC_LEN      1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_VPC_OFFSET   14
#define STARS_CMO_NS_REG_SQ_FRIENDLY_DSA_LEN      1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_DSA_OFFSET   13
#define STARS_CMO_NS_REG_SQ_FRIENDLY_SDMA_LEN     1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_SDMA_OFFSET  12
#define STARS_CMO_NS_REG_SQ_FRIENDLY_HCPU_LEN     1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_HCPU_OFFSET  11
#define STARS_CMO_NS_REG_SQ_FRIENDLY_AICPU_LEN    1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_AICPU_OFFSET 10
#define STARS_CMO_NS_REG_SQ_FRIENDLY_VEC_LEN      1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_VEC_OFFSET   9
#define STARS_CMO_NS_REG_SQ_FRIENDLY_AIC_LEN      1
#define STARS_CMO_NS_REG_SQ_FRIENDLY_AIC_OFFSET   8

#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_SEL_LEN    1
#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_SEL_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_OST_CNT_LEN    1
#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_OST_CNT_OFFSET 8
#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_STATE_LEN      5
#define STARS_CMO_NS_REG_DFX_CMO_BLK_FSM_STATE_OFFSET   0

#define STARS_CMO_NS_REG_CMO_REDUNDANT_RSP_LEN    2
#define STARS_CMO_NS_REG_CMO_REDUNDANT_RSP_OFFSET 0

#define STARS_CMO_NS_REG_CMO_CH_FREE_BITMAP_LEN    2
#define STARS_CMO_NS_REG_CMO_CH_FREE_BITMAP_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CNT_ENABLE_LEN    1
#define STARS_CMO_NS_REG_DFX_CMO_CNT_ENABLE_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_TASK_VLD_CNT_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_TASK_VLD_CNT_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_TASK_RSP_CNT_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_TASK_RSP_CNT_OFFSET 0

#define STARS_CMO_NS_REG_CMO_ENABLE_CTRL_NS_LEN    2
#define STARS_CMO_NS_REG_CMO_ENABLE_CTRL_NS_OFFSET 0

#define STARS_CMO_NS_REG_CMO_DISABLE_CTRL_NS_LEN    2
#define STARS_CMO_NS_REG_CMO_DISABLE_CTRL_NS_OFFSET 0

#define STARS_CMO_NS_REG_CMO_ENABLED_STATUS0_NS_LEN    2
#define STARS_CMO_NS_REG_CMO_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_CMO_NS_REG_STARS_CMO_LOG_EN_LEN        1
#define STARS_CMO_NS_REG_STARS_CMO_LOG_EN_OFFSET     31
#define STARS_CMO_NS_REG_STARS_CMO_LOG_BUF_ID_LEN    4
#define STARS_CMO_NS_REG_STARS_CMO_LOG_BUF_ID_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS0_0_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS0_0_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS0_1_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS0_1_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS1_0_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS1_0_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS1_1_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS1_1_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS2_0_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS2_0_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS2_1_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS2_1_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS3_0_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS3_0_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS3_1_LEN    32
#define STARS_CMO_NS_REG_DFX_CMO_CQE_STATUS3_1_OFFSET 0

#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_0_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_0_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_0_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_0_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_1_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_1_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_1_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_1_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_2_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_2_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_2_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_2_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_3_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_RT_STREAM_ID_3_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_3_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_CMO_ID_3_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_0_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_0_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_0_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_0_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_1_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_1_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_1_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_1_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_2_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_2_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_2_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_2_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_3_LEN    16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_RT_STREAM_ID_3_OFFSET 16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_3_LEN          16
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_CMO_ID_3_OFFSET       0

#define STARS_CMO_NS_REG_DFX_CMO_INVALID_BUF_EMPTY_LEN     1
#define STARS_CMO_NS_REG_DFX_CMO_INVALID_BUF_EMPTY_OFFSET  1
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_BUF_EMPTY_LEN    1
#define STARS_CMO_NS_REG_DFX_CMO_PREFETCH_BUF_EMPTY_OFFSET 0

#define STARS_CMO_NS_REG_STARS_CMO_STOP_STATUS_LEN    1
#define STARS_CMO_NS_REG_STARS_CMO_STOP_STATUS_OFFSET 1
#define STARS_CMO_NS_REG_STARS_CMO_STOP_EN_LEN        1
#define STARS_CMO_NS_REG_STARS_CMO_STOP_EN_OFFSET     0

#define STARS_CMO_NS_REG_STARS_CMO_INVALID_BUF_CLR_LEN     1
#define STARS_CMO_NS_REG_STARS_CMO_INVALID_BUF_CLR_OFFSET  1
#define STARS_CMO_NS_REG_STARS_CMO_PREFETCH_BUF_CLR_LEN    1
#define STARS_CMO_NS_REG_STARS_CMO_PREFETCH_BUF_CLR_OFFSET 0

#endif // __STARS_CMO_NS_REG_REG_OFFSET_FIELD_H__
