// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_profiling_ns_cfg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:36:20 Create file
// ******************************************************************************

#ifndef __STARS_PROFILING_NS_CFG_REG_OFFSET_FIELD_H__
#define __STARS_PROFILING_NS_CFG_REG_OFFSET_FIELD_H__

#define STARS_PROFILING_NS_CFG_SOC_PROFILE_EN_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROFILE_EN_OFFSET 0

#define STARS_PROFILING_NS_CFG_VPC_SAMPLE_MODE_LEN      1
#define STARS_PROFILING_NS_CFG_VPC_SAMPLE_MODE_OFFSET   4
#define STARS_PROFILING_NS_CFG_JPEGE_SAMPLE_MODE_LEN    1
#define STARS_PROFILING_NS_CFG_JPEGE_SAMPLE_MODE_OFFSET 3
#define STARS_PROFILING_NS_CFG_JPEGD_SAMPLE_MODE_LEN    1
#define STARS_PROFILING_NS_CFG_JPEGD_SAMPLE_MODE_OFFSET 2
#define STARS_PROFILING_NS_CFG_VDEC_SAMPLE_MODE_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_SAMPLE_MODE_OFFSET  1

#define STARS_PROFILING_NS_CFG_WRITE_VALUE_LOG_EN_LEN    1
#define STARS_PROFILING_NS_CFG_WRITE_VALUE_LOG_EN_OFFSET 13
#define STARS_PROFILING_NS_CFG_CONDS_LOG_EN_LEN          1
#define STARS_PROFILING_NS_CFG_CONDS_LOG_EN_OFFSET       12
#define STARS_PROFILING_NS_CFG_CDQM_LOG_EN_LEN           1
#define STARS_PROFILING_NS_CFG_CDQM_LOG_EN_OFFSET        11
#define STARS_PROFILING_NS_CFG_AICV_LOG_EN_LEN           1
#define STARS_PROFILING_NS_CFG_AICV_LOG_EN_OFFSET        10
#define STARS_PROFILING_NS_CFG_CTRL_TASK_LOG_EN_LEN      1
#define STARS_PROFILING_NS_CFG_CTRL_TASK_LOG_EN_OFFSET   9
#define STARS_PROFILING_NS_CFG_SDMA_LOG_EN_LEN           1
#define STARS_PROFILING_NS_CFG_SDMA_LOG_EN_OFFSET        8
#define STARS_PROFILING_NS_CFG_PCIE_DMA_LOG_EN_LEN       1
#define STARS_PROFILING_NS_CFG_PCIE_DMA_LOG_EN_OFFSET    6
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_EN_LEN          1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_EN_OFFSET       5
#define STARS_PROFILING_NS_CFG_VPC_LOG_EN_LEN            1
#define STARS_PROFILING_NS_CFG_VPC_LOG_EN_OFFSET         4
#define STARS_PROFILING_NS_CFG_JPEGE_LOG_EN_LEN          1
#define STARS_PROFILING_NS_CFG_JPEGE_LOG_EN_OFFSET       3
#define STARS_PROFILING_NS_CFG_JPEGD_LOG_EN_LEN          1
#define STARS_PROFILING_NS_CFG_JPEGD_LOG_EN_OFFSET       2
#define STARS_PROFILING_NS_CFG_VDEC_LOG_EN_LEN           1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_EN_OFFSET        1
#define STARS_PROFILING_NS_CFG_CMO_LOG_EN_LEN            1
#define STARS_PROFILING_NS_CFG_CMO_LOG_EN_OFFSET         0

#define STARS_PROFILING_NS_CFG_STARS_INFO_SAMPLE_EN_LEN    1
#define STARS_PROFILING_NS_CFG_STARS_INFO_SAMPLE_EN_OFFSET 12
#define STARS_PROFILING_NS_CFG_PCIE_BW_SAMPLE_EN_LEN       1
#define STARS_PROFILING_NS_CFG_PCIE_BW_SAMPLE_EN_OFFSET    11
#define STARS_PROFILING_NS_CFG_SOC_BW_SAMPLE_EN_LEN        1
#define STARS_PROFILING_NS_CFG_SOC_BW_SAMPLE_EN_OFFSET     8
#define STARS_PROFILING_NS_CFG_VPC_PMU_EN_LEN              1
#define STARS_PROFILING_NS_CFG_VPC_PMU_EN_OFFSET           4
#define STARS_PROFILING_NS_CFG_JPEGE_PMU_EN_LEN            1
#define STARS_PROFILING_NS_CFG_JPEGE_PMU_EN_OFFSET         3
#define STARS_PROFILING_NS_CFG_JPEGD_PMU_EN_LEN            1
#define STARS_PROFILING_NS_CFG_JPEGD_PMU_EN_OFFSET         2
#define STARS_PROFILING_NS_CFG_VDEC_PMU_EN_LEN             1
#define STARS_PROFILING_NS_CFG_VDEC_PMU_EN_OFFSET          1

#define STARS_PROFILING_NS_CFG_STARS_BUF_AF_INT_MAPPING_INDEX_LEN    9
#define STARS_PROFILING_NS_CFG_STARS_BUF_AF_INT_MAPPING_INDEX_OFFSET 0

#define STARS_PROFILING_NS_CFG_STARS_INFO_SAMPLE_WIN_LEN    22
#define STARS_PROFILING_NS_CFG_STARS_INFO_SAMPLE_WIN_OFFSET 0

#define STARS_PROFILING_NS_CFG_STARS_CHIP_BW_SAMPLE_WIN_LEN    22
#define STARS_PROFILING_NS_CFG_STARS_CHIP_BW_SAMPLE_WIN_OFFSET 0



#define STARS_PROFILING_NS_CFG_STARS_SOC_BW_SAMPLE_WIN_LEN    22
#define STARS_PROFILING_NS_CFG_STARS_SOC_BW_SAMPLE_WIN_OFFSET 0





#define STARS_PROFILING_NS_CFG_STARS_DVPP_PMU_SAMPLE_WIN_LEN    22
#define STARS_PROFILING_NS_CFG_STARS_DVPP_PMU_SAMPLE_WIN_OFFSET 0

#define STARS_PROFILING_NS_CFG_DVPP_UTILIZATION_EN_LEN    1
#define STARS_PROFILING_NS_CFG_DVPP_UTILIZATION_EN_OFFSET 0

#define STARS_PROFILING_NS_CFG_DVPP_UTILIZATION_WIN_LEN    12
#define STARS_PROFILING_NS_CFG_DVPP_UTILIZATION_WIN_OFFSET 0

#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_0_LEN    28
#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_1_LEN    28
#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_2_LEN    28
#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_3_LEN    28
#define STARS_PROFILING_NS_CFG_VPC_VF_BUSY_CNT_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_0_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_1_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_2_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_3_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGE_VF_BUSY_CNT_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_0_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_1_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_2_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_3_LEN    28
#define STARS_PROFILING_NS_CFG_JPEGD_VF_BUSY_CNT_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_4_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_5_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_6_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_7_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_8_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_9_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_10_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_11_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_12_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_13_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_14_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_15_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_L_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_4_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_4_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_4_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_5_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_5_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_5_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_6_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_6_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_6_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_7_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_7_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_7_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_8_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_8_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_8_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_9_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_9_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_9_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_10_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_10_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_10_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_11_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_11_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_11_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_12_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_12_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_12_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_13_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_13_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_13_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_14_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_14_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_14_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_IS_VIRTUAL_15_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_15_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_LOG_BASE_ADDR_H_15_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_0_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_1_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_2_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_3_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_4_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_5_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_6_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_7_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_8_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_9_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_10_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_11_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_12_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_13_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_14_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_15_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_LENGTH_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_0_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_1_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_2_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_3_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_4_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_5_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_6_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_7_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_8_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_9_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_10_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_11_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_12_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_13_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_14_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_15_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_AF_THRESHOLD_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_INITIAL_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_RPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_LOG_WPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_0_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_1_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_2_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_3_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_4_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_5_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_6_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_7_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_8_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_9_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_10_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_11_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_12_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_13_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_14_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_15_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_STREAMID_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_0_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_0_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_0_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_0_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_1_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_1_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_1_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_1_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_2_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_2_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_2_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_2_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_3_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_3_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_3_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_3_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_4_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_4_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_4_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_4_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_5_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_5_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_5_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_5_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_6_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_6_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_6_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_6_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_7_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_7_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_7_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_7_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_8_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_8_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_8_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_8_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_9_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_9_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_9_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_9_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_10_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_10_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_10_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_10_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_11_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_11_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_11_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_11_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_12_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_12_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_12_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_12_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_13_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_13_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_13_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_13_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_14_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_14_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_14_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_14_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_15_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SEC_EN_15_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_15_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_SSV_15_OFFSET    0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_4_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_5_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_6_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_7_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_8_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_9_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_10_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_11_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_12_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_13_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_14_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_15_LEN    32
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_L_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_4_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_4_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_4_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_5_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_5_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_5_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_6_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_6_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_6_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_7_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_7_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_7_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_8_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_8_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_8_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_9_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_9_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_9_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_10_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_10_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_10_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_11_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_11_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_11_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_12_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_12_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_12_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_13_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_13_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_13_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_14_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_14_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_14_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_IS_VIRTUAL_15_OFFSET 17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_15_LEN             17
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BASE_ADDR_H_15_OFFSET          0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_0_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_1_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_2_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_3_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_4_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_5_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_6_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_7_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_8_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_9_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_10_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_11_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_12_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_13_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_14_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_15_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_LENGTH_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_0_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_1_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_2_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_3_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_4_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_5_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_6_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_7_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_8_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_9_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_10_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_11_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_12_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_13_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_14_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_15_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_AF_THRESHOLD_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_0_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_0_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_1_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_1_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_2_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_2_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_3_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_3_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_4_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_4_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_5_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_5_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_6_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_6_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_7_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_7_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_8_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_8_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_9_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_9_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_10_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_10_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_11_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_11_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_12_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_12_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_13_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_13_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_14_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_14_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_15_LEN        1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_DROP_15_OFFSET     1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_INITIAL_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_RPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_WPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_0_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_1_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_2_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_3_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_4_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_5_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_6_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_7_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_8_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_9_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_10_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_11_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_12_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_13_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_14_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_15_LEN    32
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_L_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_0_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_0_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_0_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_1_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_1_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_1_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_2_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_2_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_2_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_3_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_3_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_3_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_4_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_4_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_4_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_5_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_5_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_5_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_6_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_6_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_6_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_7_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_7_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_7_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_8_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_8_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_8_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_9_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_9_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_9_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_10_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_10_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_10_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_11_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_11_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_11_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_12_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_12_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_12_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_13_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_13_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_13_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_14_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_14_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_14_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_IS_VIRTUAL_15_OFFSET 17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_15_LEN             17
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BASE_ADDR_H_15_OFFSET          0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_0_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_1_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_2_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_3_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_4_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_5_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_6_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_7_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_8_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_9_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_10_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_11_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_12_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_13_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_14_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_15_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_LENGTH_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_0_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_1_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_2_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_3_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_4_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_5_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_6_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_7_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_8_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_9_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_10_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_11_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_12_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_13_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_14_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_15_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_AF_THRESHOLD_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_0_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_1_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_2_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_3_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_4_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_5_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_6_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_7_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_8_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_9_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_10_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_11_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_12_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_13_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_14_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_15_LEN    1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_INITIAL_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_RPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_0_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_0_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_1_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_1_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_2_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_2_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_3_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_3_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_4_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_4_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_5_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_5_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_6_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_6_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_7_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_7_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_8_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_8_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_9_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_9_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_10_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_10_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_11_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_11_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_12_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_12_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_13_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_13_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_14_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_14_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_15_LEN    20
#define STARS_PROFILING_NS_CFG_VDEC_LOG_WPTR_15_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_L_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_L_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_IS_VIRTUAL_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_IS_VIRTUAL_OFFSET 17
#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_H_LEN             17
#define STARS_PROFILING_NS_CFG_SOC_PROF_BASE_ADDR_H_OFFSET          0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_LENGTH_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_LENGTH_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_AF_THRESHOLD_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_PROF_AF_THRESHOLD_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_WPTR_INITIAL_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_WPTR_INITIAL_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_RPTR_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_PROF_RPTR_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_WPTR_LEN    20
#define STARS_PROFILING_NS_CFG_SOC_PROF_WPTR_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_STREAMID_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_STREAMID_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_SEC_EN_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_SEC_EN_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_SSV_LEN       1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_SSV_OFFSET    0

#define STARS_PROFILING_NS_CFG_SOC_LOG_PROF_BUFF_ADDR_LOCKER_LEN    32
#define STARS_PROFILING_NS_CFG_SOC_LOG_PROF_BUFF_ADDR_LOCKER_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_RAW_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_RAW_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_FORCE_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_FORCE_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_CLR_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_CLR_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_STS2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MASK2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_RAW_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_RAW_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_FORCE_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_FORCE_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_CLR_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_CLR_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_STS2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MASK2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_RAW_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_RAW_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_FORCE_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_FORCE_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_CLR_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_CLR_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_STS2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MASK2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_RAW_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_RAW_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_FORCE_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_FORCE_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_CLR_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_CLR_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK0_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK1_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_STS2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK2_NS_LEN    16
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MASK2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_RAW_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_RAW_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_FORCE_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_FORCE_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_CLR_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_CLR_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS0_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK0_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK0_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS1_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK1_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK1_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS2_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_STS2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK2_NS_LEN    1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MASK2_NS_OFFSET 0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_RAW_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_RAW_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_RAW_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_RAW_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_RAW_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_RAW_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_RAW_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_RAW_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_RAW_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_RAW_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS0_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS0_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS0_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS0_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS0_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS0_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS0_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS1_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS1_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS1_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS1_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS1_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS1_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS1_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_STS2_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_STS2_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_STS2_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS2_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_STS2_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS2_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_STS2_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK0_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK0_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK0_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK0_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK0_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK0_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK0_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK0_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK1_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK1_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK1_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK1_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK1_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK1_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK1_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK1_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_SOC_PROF_BUF_AF_MERGE_MASK2_NS_OFFSET  4
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_FFTS_PMU_BUF_AF_MERGE_MASK2_NS_OFFSET  3
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK2_NS_LEN     1
#define STARS_PROFILING_NS_CFG_VDEC_LOG_BUF_AF_MERGE_MASK2_NS_OFFSET  2
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK2_NS_LEN    1
#define STARS_PROFILING_NS_CFG_TOPIC_LOG_BUF_AF_MERGE_MASK2_NS_OFFSET 1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK2_NS_LEN      1
#define STARS_PROFILING_NS_CFG_SOC_LOG_BUF_AF_MERGE_MASK2_NS_OFFSET   0

#define STARS_PROFILING_NS_CFG_PROF_BUF_AF_MERGE_STS2_LEN    1
#define STARS_PROFILING_NS_CFG_PROF_BUF_AF_MERGE_STS2_OFFSET 0

#define STARS_PROFILING_NS_CFG_PROF_BUF_AF_MERGE_CLR2_LEN    1
#define STARS_PROFILING_NS_CFG_PROF_BUF_AF_MERGE_CLR2_OFFSET 0

#endif // __STARS_PROFILING_NS_CFG_REG_OFFSET_FIELD_H__
