/*
 * Copyright     :  Copyright (C) 2022, Huawei Technologies Co. Ltd.
 * File name     :  stars_topic_sche_ns_cfg_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  xxx
 * Version       :  1
 * Date          :  2020/04/01
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  xxx 2022/03/16 11:06:47 Create file
 */

#ifndef __STARS_TOPIC_SCHE_NS_CFG_REG_OFFSET_FIELD_H__
#define __STARS_TOPIC_SCHE_NS_CFG_REG_OFFSET_FIELD_H__

#define STARS_TOPIC_SCHE_NS_CFG_SP_LEVEL_LEN    3
#define STARS_TOPIC_SCHE_NS_CFG_SP_LEVEL_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_LP_MODE_LEN     3
#define STARS_TOPIC_SCHE_NS_CFG_LP_MODE_OFFSET  0



#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT3_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT3_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT2_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT1_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT7_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT7_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT6_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT6_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT5_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT5_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT4_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_WRR_WEIGHT4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_JPEGD_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_JPEGD_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_JPEGE_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_JPEGE_OFFSET 15
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_VPC_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_VPC_OFFSET   14
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_DSA_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_DSA_OFFSET   13
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_SDMA_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_SDMA_OFFSET  12
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_HCPU_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_HCPU_OFFSET  11
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_AICPU_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_AICPU_OFFSET 10
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_VEC_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_VEC_OFFSET   9
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_AIC_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_SQ_FRIENDLY_AIC_OFFSET   8

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_SCHE_INIT_DONE_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_SCHE_INIT_DONE_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_SLOT_FSM_SEL_LEN    4
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_SLOT_FSM_SEL_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_SLOT_FSM_STATE_LEN    3
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_SLOT_FSM_STATE_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_BLK_FSM_SEL_LEN    4
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_BLK_FSM_SEL_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_GET_FSM_OST_CNT_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_GET_FSM_OST_CNT_OFFSET 20
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_FSM_OST_CNT_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_FSM_OST_CNT_OFFSET     16
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_GET_FSM_STATE_LEN      5
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_GET_FSM_STATE_OFFSET   8
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_BLK_FSM_STATE_LEN      5
#define STARS_TOPIC_SCHE_NS_CFG_DFX_TOPIC_BLK_FSM_STATE_OFFSET   0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_POOL_NO_ACPU_LEN    3
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_POOL_NO_ACPU_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_REDUNDANT_RSP_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_REDUNDANT_RSP_OFFSET      16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_REDUNDANT_RSP_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_REDUNDANT_RSP_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_REDUNDANT_RSP_LEN        8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_REDUNDANT_RSP_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_REDUNDANT_RSP_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_REDUNDANT_RSP_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_FREE_BITMAP_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_FREE_BITMAP_OFFSET      16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_FREE_BITMAP_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_FREE_BITMAP_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_FREE_BITMAP_LEN        8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_FREE_BITMAP_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_FREE_BITMAP_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_FREE_BITMAP_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_0_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_0_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_0_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_0_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_0_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_0_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_0_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_0_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_1_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_1_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_1_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_1_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_1_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_1_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_1_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_1_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_2_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_ENABLE_CTRL_NS_2_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_2_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_ENABLE_CTRL_NS_2_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_2_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_ENABLE_CTRL_NS_2_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_2_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_ENABLE_CTRL_NS_2_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_0_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_0_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_0_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_0_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_0_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_0_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_0_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_0_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_1_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_1_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_1_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_1_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_1_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_1_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_1_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_1_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_2_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_DISABLE_CTRL_NS_2_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_2_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_DISABLE_CTRL_NS_2_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_2_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_CTRL_CPU_DISABLE_CTRL_NS_2_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_2_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_DISABLE_CTRL_NS_2_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_ACPU_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DVPP_CPU_ENABLED_STATUS_NS_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DVPP_CPU_ENABLED_STATUS_NS_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_TS_CPU_ENABLED_STATUS_NS_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_TS_CPU_ENABLED_STATUS_NS_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_CTRL_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_CTRL_CPU_ENABLED_STATUS_NS_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DATA_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DATA_CPU_ENABLED_STATUS_NS_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DEVICE_ACPU_ENABLED_STATUS_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_DEVICE_ACPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DVPP_CPU_ENABLED_STATUS_NS_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DVPP_CPU_ENABLED_STATUS_NS_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_TS_CPU_ENABLED_STATUS_NS_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_TS_CPU_ENABLED_STATUS_NS_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_CTRL_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_CTRL_CPU_ENABLED_STATUS_NS_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DATA_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DATA_CPU_ENABLED_STATUS_NS_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DEVICE_ACPU_ENABLED_STATUS_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_DEVICE_ACPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DVPP_CPU_ENABLED_STATUS_NS_LEN       2
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DVPP_CPU_ENABLED_STATUS_NS_OFFSET    26
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_TS_CPU_ENABLED_STATUS_NS_LEN         2
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_TS_CPU_ENABLED_STATUS_NS_OFFSET      24
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_CTRL_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_CTRL_CPU_ENABLED_STATUS_NS_OFFSET    16
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DATA_CPU_ENABLED_STATUS_NS_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DATA_CPU_ENABLED_STATUS_NS_OFFSET    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DEVICE_ACPU_ENABLED_STATUS_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_DEVICE_ACPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CTRL_CPU_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL0_HOST_CTRL_CPU_ENABLED_STATUS_NS_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_POOL0_HOST_CTRL_CPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL1_HOST_CTRL_CPU_ENABLED_STATUS_NS_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_POOL1_HOST_CTRL_CPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_POOL2_HOST_CTRL_CPU_ENABLED_STATUS_NS_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_POOL2_HOST_CTRL_CPU_ENABLED_STATUS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_2_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_3_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_4_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_5_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_6_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_7_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_L_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_0_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_1_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_2_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_3_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_4_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_5_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_6_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_7_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_MAILBOX_ADDR_H_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_2_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_3_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_4_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_5_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_6_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_7_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_L_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_0_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_1_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_2_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_3_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_4_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_5_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_6_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_7_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_MAILBOX_ADDR_H_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_L_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_L_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_L_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_L_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_H_0_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_H_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_H_1_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_MAILBOX_ADDR_H_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_2_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_3_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_L_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_0_LEN          6
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_0_OFFSET       20
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_0_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_1_LEN          6
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_1_OFFSET       20
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_1_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_2_LEN          6
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_2_OFFSET       20
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_2_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_3_LEN          6
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_SHIFT_3_OFFSET       20
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_3_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_HOST_CPU_WAIT_MAILBOX_BASE_ADDR_H_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_MAILBOX_ADDR_IS_VIRTUAL_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_MAILBOX_ADDR_IS_VIRTUAL_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_MAILBOX_ADDR_LOCKER_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_MAILBOX_ADDR_LOCKER_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_MAP_TABLE_LOCKER_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TABLE_LOCKER_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_KERNEL_TYPE_CUST_LEN    7
#define STARS_TOPIC_SCHE_NS_CFG_KERNEL_TYPE_CUST_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_TASK_POOL_ID_LEN           2
#define STARS_TOPIC_SCHE_NS_CFG_DVPP_CPU_TASK_POOL_ID_OFFSET        12
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_TASK_POOL_ID_LEN             2
#define STARS_TOPIC_SCHE_NS_CFG_TS_CPU_TASK_POOL_ID_OFFSET          8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CTRL_CPU_TASK_POOL_ID_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CTRL_CPU_TASK_POOL_ID_OFFSET 4
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_TASK_POOL_ID_LEN           2
#define STARS_TOPIC_SCHE_NS_CFG_DATA_CPU_TASK_POOL_ID_OFFSET        0

#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_FLAG_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_FLAG_OFFSET 4
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_VFID_LEN    4
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_VFID_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_PID_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_PID_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_PID_ERR_CODE_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_MAP_TBL_MISS_PID_ERR_CODE_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_ECO_RSV_DEF0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_ECO_RSV_DEF0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_ECO_RSV_DEF1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_ECO_RSV_DEF1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_2_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_2_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_2_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_2_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_2_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_2_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_2_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_2_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_2_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_3_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_3_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_3_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_3_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_3_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_3_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_3_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_3_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_3_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_4_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_4_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_4_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_4_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_4_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_4_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_4_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_4_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_4_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_5_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_5_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_5_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_5_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_5_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_5_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_5_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_5_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_5_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_6_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_6_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_6_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_6_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_6_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_6_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_6_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_6_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_6_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_7_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_WARNING_NS_7_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_7_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_TRAP_NS_7_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_EXCEPTION_NS_7_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_7_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DEBUG_NS_7_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_7_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_DONE_NS_7_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_WAIT_TOPIC_NS_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_EN_NS_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_STATUS_ERROR_CODE_NS_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_STATUS_DONE_NS_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_0_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_0_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_0_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_1_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_1_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_1_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_2_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_2_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_2_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_3_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_3_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_3_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_4_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_4_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_4_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_5_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_5_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_5_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_6_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_6_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_6_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_SPLIT_TASK_NOT_EMPTY_NS_7_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_7_LEN               1
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_GET_TOPIC_NS_7_OFFSET            0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_TOPIC_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_TOPIC_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_TOPIC_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_WAIT_TOPIC_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_0_OFFSET 12
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_0_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_0_OFFSET    4
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_0_LEN     3
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_0_OFFSET  0

#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_1_OFFSET 12
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_1_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_1_OFFSET    4
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_1_LEN     3
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_1_OFFSET  0

#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_EN_NS_2_OFFSET 12
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_2_LEN       8
#define STARS_TOPIC_SCHE_NS_CFG_TIMEOUT_NS_2_OFFSET    4
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_2_LEN     3
#define STARS_TOPIC_SCHE_NS_CFG_QOS_LEVEL_NS_2_OFFSET  0

#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_0_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_0_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_0_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_1_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_1_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_1_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS3_WEIGHT_NS_2_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS2_WEIGHT_NS_2_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS1_WEIGHT_NS_2_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS0_WEIGHT_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_0_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_0_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_0_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_0_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_1_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_1_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_1_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_1_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS7_WEIGHT_NS_2_OFFSET 24
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS6_WEIGHT_NS_2_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS5_WEIGHT_NS_2_OFFSET 8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_2_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_QOS4_WEIGHT_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_2_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_3_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_4_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_5_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_6_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_7_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_L_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_0_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_1_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_2_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_3_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_4_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_5_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_6_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_7_LEN    17
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_BASE_ADDR_H_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TAIL_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_HEAD_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EN_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_0_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_1_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_2_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_3_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_4_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_5_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_6_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_EMPTY_7_OFFSET 16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_DEPTH_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_0_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_0_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_0_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_0_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_1_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_1_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_1_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_1_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_2_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_2_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_2_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_2_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_2_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_3_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_3_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_3_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_3_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_3_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_4_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_4_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_4_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_4_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_4_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_5_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_5_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_5_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_5_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_5_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_6_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_6_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_6_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_6_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_6_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_7_LEN     1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_BUSY_7_OFFSET  2
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_PREFETCH_PAUSE_7_OFFSET 1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_7_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_CPU_PORT_QUEUE_TASK_CLEAR_7_OFFSET     0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_0_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_1_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_2_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_USED_FLAG_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_HCCPU_USED_FLAG_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_DFX_EN_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_DFX_EN_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_CNT_SEL_LEN    9
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_CNT_SEL_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_CNT_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_QUEUE_CNT_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_SEND_TASK_CNT_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_TOPIC_SEND_TASK_CNT_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CPU_DONE_TASK_CNT_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_CPU_DONE_TASK_CNT_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_PID_ERR_CNT_LEN    32
#define STARS_TOPIC_SCHE_NS_CFG_PID_ERR_CNT_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_STS_NS_LEN     2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_STS_NS_OFFSET  16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_STS_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_STS_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_FORCE_NS_LEN     2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_FORCE_NS_OFFSET  16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_FORCE_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_FORCE_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_CLR_NS_LEN     2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_CLR_NS_OFFSET  16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_CLR_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_CLR_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_MASK_NS_LEN     2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_MASK_NS_OFFSET  16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_MASK_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_MASK_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_RAW_NS_LEN     2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_CPU_INT_RAW_NS_OFFSET  16
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_RAW_NS_LEN    8
#define STARS_TOPIC_SCHE_NS_CFG_DEVICE_CPU_INT_RAW_NS_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_OWN_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DEBUG_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_EXCEPTION_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_TRAP_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_DONE_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_ACPU_SLOT_PID_ERR_BITMAP_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_OWN_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DEBUG_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_EXCEPTION_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_TRAP_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_2_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_3_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_4_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_5_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_6_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_7_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_DONE_BITMAP0_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_2_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_3_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_4_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_4_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_5_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_5_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_6_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_6_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_7_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_CCPU_SLOT_PID_ERR_BITMAP_7_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_WAIT_TOPIC_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_WAIT_TOPIC_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_WAIT_TOPIC_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_WAIT_TOPIC_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF0_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_WAIT_TOPIC_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_WAIT_TOPIC_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_WAIT_TOPIC_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_WAIT_TOPIC_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF1_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_WAIT_TOPIC_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_WAIT_TOPIC_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_WAIT_TOPIC_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_WAIT_TOPIC_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF2_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_WARNING_NS_0_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_WARNING_NS_0_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_TRAP_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_TRAP_NS_0_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_EXCEPTION_NS_0_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DEBUG_NS_0_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DEBUG_NS_0_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DONE_NS_0_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DONE_NS_0_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_WARNING_NS_1_LEN      1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_WARNING_NS_1_OFFSET   4
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_TRAP_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_TRAP_NS_1_OFFSET      3
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_EXCEPTION_NS_1_OFFSET 2
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DEBUG_NS_1_LEN        1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DEBUG_NS_1_OFFSET     1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DONE_NS_1_LEN         1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_DONE_NS_1_OFFSET      0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_WAIT_TOPIC_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_WAIT_TOPIC_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_WAIT_TOPIC_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_WAIT_TOPIC_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_INT_EN_NS_0_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_INT_EN_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_INT_EN_NS_1_LEN    1
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_INT_EN_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_LEN    16
#define STARS_TOPIC_SCHE_NS_CFG_VF3_HOST_CTRLCPU_STATUS_ERROR_CODE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS2_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_FORCE_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_CLR_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK2_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_RAW_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_STS1_NS_3_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_0_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_0_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_1_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_1_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_2_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_2_OFFSET 0

#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_3_LEN    2
#define STARS_TOPIC_SCHE_NS_CFG_STARS_TOPIC_HOST_CTRL_CPU_INT_MASK1_NS_3_OFFSET 0

#endif // __STARS_TOPIC_SCHE_NS_CFG_REG_OFFSET_FIELD_H__
