// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_conds_ns_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/22 14:39:08 Create file
// ******************************************************************************

#ifndef __STARS_CONDS_NS_REG_REG_OFFSET_H__
#define __STARS_CONDS_NS_REG_REG_OFFSET_H__

/* STARS_CONDS_NS_REG Base address of Module's Register */
#define SOC_STARS_CONDS_NS_REG_BASE                       (0x2c80000)

/******************************************************************************/
/*                      SOC STARS_CONDS_NS_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_CONDS_NS_REG_STARS_PRIORITY_CTRL0_REG             (SOC_STARS_CONDS_NS_REG_BASE + 0x0)
#define SOC_STARS_CONDS_NS_REG_STARS_PRIORITY_CTRL1_REG             (SOC_STARS_CONDS_NS_REG_BASE + 0x4)
#define SOC_STARS_CONDS_NS_REG_STARS_PRIORITY_CTRL2_REG             (SOC_STARS_CONDS_NS_REG_BASE + 0x8)
#define SOC_STARS_CONDS_NS_REG_STARS_PRIORITY_CTRL3_REG             (SOC_STARS_CONDS_NS_REG_BASE + 0xC)
#define SOC_STARS_CONDS_NS_REG_STARS_FRIENDLY_CTRL_REG              (SOC_STARS_CONDS_NS_REG_BASE + 0x20)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_COMMON_CFG_REG           (SOC_STARS_CONDS_NS_REG_BASE + 0x800)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_FSM_SEL_REG              (SOC_STARS_CONDS_NS_REG_BASE + 0x810)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_FSM_STATE_REG            (SOC_STARS_CONDS_NS_REG_BASE + 0x814)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_REDUNDANT_RSP_REG        (SOC_STARS_CONDS_NS_REG_BASE + 0x820)
#define SOC_STARS_CONDS_NS_REG_STARS_FREE_CONDS_CORE_BITMAP_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x824)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_CNT_ENABLE_REG       (SOC_STARS_CONDS_NS_REG_BASE + 0x830)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_TASK_VLD_CNT_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x834)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_TASK_RSP_CNT_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x838)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_POOL_ENABLE_CTRL_NS_REG  (SOC_STARS_CONDS_NS_REG_BASE + 0x840)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_POOL_DISABLE_CTRL_NS_REG (SOC_STARS_CONDS_NS_REG_BASE + 0x880)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_POOL_STATUS0_NS_REG      (SOC_STARS_CONDS_NS_REG_BASE + 0x8C0)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_AXI_SETTING0_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x900)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_AXI_SETTING1_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x904)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_CQE_STATUS0_REG          (SOC_STARS_CONDS_NS_REG_BASE + 0x908)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_CQE_STATUS1_REG          (SOC_STARS_CONDS_NS_REG_BASE + 0x90C)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_EXECUTE_STATUS0_0_REG  (SOC_STARS_CONDS_NS_REG_BASE + 0x920)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_EXECUTE_STATUS1_0_REG  (SOC_STARS_CONDS_NS_REG_BASE + 0x924)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_ERROR_STATUS_REG     (SOC_STARS_CONDS_NS_REG_BASE + 0x928)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_EXEC_INSTR_DATA0_0_REG (SOC_STARS_CONDS_NS_REG_BASE + 0x930)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_DFX_EXEC_INSTR_DATA1_0_REG (SOC_STARS_CONDS_NS_REG_BASE + 0x934)
#define SOC_STARS_CONDS_NS_REG_STARS_CONDS_ERR_PROC_REG             (SOC_STARS_CONDS_NS_REG_BASE + 0x938)

#endif // __STARS_CONDS_NS_REG_REG_OFFSET_H__
