// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_s_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/22 14:38:32 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_S_REG_REG_OFFSET_H__
#define __STARS_ACSQINT_S_REG_REG_OFFSET_H__

/* STARS_ACSQINT_S_REG Base address of Module's Register */
#define SOC_STARS_ACSQINT_S_REG_BASE                       (0x4020000)

/******************************************************************************/
/*                      SOC STARS_ACSQINT_S_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_NORMAL_S_MASK0_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x20)   /* 上报TSCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_DEBUG_S_MASK0_REG        (SOC_STARS_ACSQINT_S_REG_BASE + 0x24)   /* 上报TSCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_ERROR_S_MASK0_REG        (SOC_STARS_ACSQINT_S_REG_BASE + 0x28)   /* 上报TSCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_NORMAL_S_STATUS0_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x2C)   /* 上报TSCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_DEBUG_S_STATUS0_REG      (SOC_STARS_ACSQINT_S_REG_BASE + 0x30)   /* 上报TSCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_ERROR_S_STATUS0_REG      (SOC_STARS_ACSQINT_S_REG_BASE + 0x34)   /* 上报TSCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_PRE_PAUSED_S_STS0_REG  (SOC_STARS_ACSQINT_S_REG_BASE + 0x110)  /* 向TSCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_POST_PAUSED_S_STS0_REG (SOC_STARS_ACSQINT_S_REG_BASE + 0x120)  /* 向TSCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_CQ_FULL_S_STS0_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x130)  /* 向TSCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_DEBUG_S_STS0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x140)  /* 向TSCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_ERROR_S_STS0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x150)  /* 向TSCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_TRAP_S_STS0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x160)  /* 向TSCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQE_ERROR_S_STS0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x170)  /* 向TSCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SW_STATUS_ERROR_S_STS0_REG    (SOC_STARS_ACSQINT_S_REG_BASE + 0x180)  /* 向TSCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQ_SEC_ERROR_S_STS0_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x190)  /* 向TSCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_PRE_PAUSED_S_CLR0_REG  (SOC_STARS_ACSQINT_S_REG_BASE + 0x1A0)  /* 向CtrlCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_POST_PAUSED_S_CLR0_REG (SOC_STARS_ACSQINT_S_REG_BASE + 0x1B0)  /* 向CtrlCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_CQ_FULL_S_CLR0_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x1C0)  /* 向TSCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_DEBUG_S_CLR0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x1D0)  /* 向TSCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_ERROR_S_CLR0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x1E0)  /* 向TSCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_TRAP_S_CLR0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x1F0)  /* 向TSCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQE_ERROR_S_CLR0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x200)  /* 向TSCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SW_STATUS_ERROR_S_CLR0_REG    (SOC_STARS_ACSQINT_S_REG_BASE + 0x210)  /* 向TSCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQ_SEC_ERROR_S_CLR0_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x220)  /* 向TSCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_NORMAL_S_MASK1_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x2020) /* 上报CtrlCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_DEBUG_S_MASK1_REG        (SOC_STARS_ACSQINT_S_REG_BASE + 0x2024) /* 上报CtrlCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_ERROR_S_MASK1_REG        (SOC_STARS_ACSQINT_S_REG_BASE + 0x2028) /* 上报CtrlCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_NORMAL_S_STATUS1_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x202C) /* 上报CtrlCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_DEBUG_S_STATUS1_REG      (SOC_STARS_ACSQINT_S_REG_BASE + 0x2030) /* 上报CtrlCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L1_ACSQ_ERROR_S_STATUS1_REG      (SOC_STARS_ACSQINT_S_REG_BASE + 0x2034) /* 上报CtrlCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_PRE_PAUSED_S_STS1_REG  (SOC_STARS_ACSQINT_S_REG_BASE + 0x2110) /* 向CtrlCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_POST_PAUSED_S_STS1_REG (SOC_STARS_ACSQINT_S_REG_BASE + 0x2120) /* 向CtrlCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_CQ_FULL_S_STS1_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x2130) /* 向CtrlCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_DEBUG_S_STS1_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x2140) /* 向CtrlCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_ERROR_S_STS1_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x2150) /* 向CtrlCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_TRAP_S_STS1_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x2160) /* 向CtrlCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQE_ERROR_S_STS1_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x2170) /* 向CtrlCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SW_STATUS_ERROR_S_STS1_REG    (SOC_STARS_ACSQINT_S_REG_BASE + 0x2180) /* 向CtrlCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQ_SEC_ERROR_S_STS1_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x2190) /* 向CtrlCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_PRE_PAUSED_S_CLR1_REG  (SOC_STARS_ACSQINT_S_REG_BASE + 0x21A0) /* 向CtrlCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_POST_PAUSED_S_CLR1_REG (SOC_STARS_ACSQINT_S_REG_BASE + 0x21B0) /* 向CtrlCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_CQ_FULL_S_CLR1_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x21C0) /* 向CtrlCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_DEBUG_S_CLR1_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x21D0) /* 向CtrlCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_ERROR_S_CLR1_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x21E0) /* 向CtrlCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_TRAP_S_CLR1_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x21F0) /* 向CtrlCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQE_ERROR_S_CLR1_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x2200) /* 向CtrlCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SW_STATUS_ERROR_S_CLR1_REG    (SOC_STARS_ACSQINT_S_REG_BASE + 0x2210) /* 向CtrlCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQ_SEC_ERROR_S_CLR1_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x2220) /* 向CtrlCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_PRE_PAUSED_S_RAW0_REG  (SOC_STARS_ACSQINT_S_REG_BASE + 0x4080) /* L2级PRE_PAUSED原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_POST_PAUSED_S_RAW0_REG (SOC_STARS_ACSQINT_S_REG_BASE + 0x4090) /* L2级POST_PAUSED原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_NORMAL_CQ_FULL_S_RAW0_REG     (SOC_STARS_ACSQINT_S_REG_BASE + 0x40A0) /* L2级CQ_FULL原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_DEBUG_S_RAW0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x40B0) /* L2级TASK_DEBUG原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_ERROR_S_RAW0_REG         (SOC_STARS_ACSQINT_S_REG_BASE + 0x40C0) /* L2级TASK_ERROR原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_TASK_TRAP_S_RAW0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x40D0) /* L2级TASK_TRAP原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQE_ERROR_S_RAW0_REG          (SOC_STARS_ACSQINT_S_REG_BASE + 0x40E0) /* L2级SQE_ERROR原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SW_STATUS_ERROR_S_RAW0_REG    (SOC_STARS_ACSQINT_S_REG_BASE + 0x40F0) /* L2级SW_STATUS_ERROR原始中断状态寄存器 */
#define SOC_STARS_ACSQINT_S_REG_STARS_L2_SQ_SEC_ERROR_S_RAW0_REG       (SOC_STARS_ACSQINT_S_REG_BASE + 0x4100) /* L2级SQ_SEC_ERROR原始中断状态寄存器 */

#endif // __STARS_ACSQINT_S_REG_REG_OFFSET_H__
