// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_host_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/23 09:26:03 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_HOST_REG_REG_OFFSET_H__
#define __STARS_CQINT_HOST_REG_REG_OFFSET_H__

/* STARS_CQINT_HOST_REG Base address of Module's Register */
#define SOC_STARS_CQINT_HOST_REG_BASE                       (0x10c00000)

/******************************************************************************/
/*                      SOC STARS_CQINT_HOST_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_0_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x100010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_1_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x110010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_2_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x120010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_3_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x130010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_4_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x140010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_5_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x150010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_6_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x160010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_7_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x170010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_8_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x180010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_9_REG                               (SOC_STARS_CQINT_HOST_REG_BASE + 0x190010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_10_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_11_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_12_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_13_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_14_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_STATUS2_15_REG                              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_0_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x100014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_1_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x110014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_2_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x120014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_3_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x130014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_4_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x140014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_5_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x150014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_6_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x160014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_7_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x170014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_8_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x180014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_9_REG                                  (SOC_STARS_CQINT_HOST_REG_BASE + 0x190014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_10_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_11_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_12_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_13_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_14_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_CQ_NS_CLR2_15_REG                                 (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_0_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x100020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_1_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x110020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_2_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x120020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_3_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x130020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_4_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x140020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_5_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x150020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_6_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x160020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_7_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x170020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_8_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x180020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_9_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x190020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_10_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_11_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_12_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_13_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_14_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK2_15_REG             (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_0_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_1_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_2_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x120034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_3_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x130034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_4_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x140034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_5_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x150034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_6_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x160034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_7_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x170034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_8_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x180034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_9_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x190034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_10_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_11_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_12_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_13_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_14_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS2_15_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0034) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_0_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x100040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_1_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x110040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_2_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x120040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_3_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x130040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_4_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x140040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_5_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x150040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_6_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x160040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_7_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x170040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_8_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x180040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_9_REG  (SOC_STARS_CQINT_HOST_REG_BASE + 0x190040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_10_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_11_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_12_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_13_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_14_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS2_15_REG (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0040) /* 向HostCPU上报的每128个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_0_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x100090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_1_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x110090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_2_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x120090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_3_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x130090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_4_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x140090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_5_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x150090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_6_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x160090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_7_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x170090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_8_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x180090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_9_REG            (SOC_STARS_CQINT_HOST_REG_BASE + 0x190090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_10_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_11_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_12_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_13_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_14_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS2_15_REG           (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F0090) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_0_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1000A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_1_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1100A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_2_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1200A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_3_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1300A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_4_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1400A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_5_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1500A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_6_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1600A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_7_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1700A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_8_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1800A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_9_REG               (SOC_STARS_CQINT_HOST_REG_BASE + 0x1900A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_10_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1A00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_11_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1B00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_12_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1C00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_13_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1D00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_14_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1E00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_HOST_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR2_15_REG              (SOC_STARS_CQINT_HOST_REG_BASE + 0x1F00A0) /* 向HostCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */

#endif // __STARS_CQINT_HOST_REG_REG_OFFSET_H__
