// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_host_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 09:26:03 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_HOST_REG_REG_OFFSET_FIELD_H__
#define __STARS_CQINT_HOST_REG_REG_OFFSET_FIELD_H__

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_0_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_1_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_2_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_3_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_4_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_5_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_6_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_7_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_8_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_9_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_10_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_11_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_12_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_13_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_14_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_15_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_STS2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_0_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_1_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_2_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_3_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_4_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_5_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_6_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_7_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_8_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_9_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_10_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_11_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_12_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_13_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_14_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_15_LEN    1
#define STARS_CQINT_HOST_REG_STARS_CQ_NORMAL_CLR2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_0_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_1_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_2_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_3_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_4_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_5_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_6_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_7_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_8_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_9_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_10_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_11_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_12_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_13_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_14_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_15_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_MASK2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_0_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_1_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_2_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_3_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_4_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_5_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_6_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_7_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_8_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_9_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_10_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_11_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_12_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_13_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_14_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_15_LEN    1
#define STARS_CQINT_HOST_REG_L1_CQE_WRITTEN_NS_STATUS2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_0_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_1_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_2_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_3_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_4_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_5_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_6_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_7_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_8_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_9_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_10_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_11_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_12_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_13_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_14_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_15_LEN    4
#define STARS_CQINT_HOST_REG_MID_CQE_WRITTEN_NS_STATUS2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_0_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_1_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_2_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_3_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_4_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_5_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_6_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_7_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_8_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_9_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_10_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_11_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_12_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_13_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_14_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_15_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_STATUS2_15_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_0_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_0_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_1_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_1_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_2_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_2_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_3_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_3_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_4_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_4_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_5_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_5_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_6_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_6_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_7_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_7_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_8_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_8_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_9_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_9_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_10_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_10_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_11_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_11_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_12_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_12_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_13_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_13_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_14_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_14_OFFSET 0

#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_15_LEN    32
#define STARS_CQINT_HOST_REG_L2_CQE_WRITTEN_NS_CLR2_15_OFFSET 0

#endif // __STARS_CQINT_HOST_REG_REG_OFFSET_FIELD_H__
