// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_s_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/22 14:38:31 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_S_REG_REG_OFFSET_FIELD_H__
#define __STARS_ACSQINT_S_REG_REG_OFFSET_FIELD_H__

#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_MASK0_LEN        1
#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_MASK0_OFFSET     2
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_MASK0_LEN    1
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_MASK0_OFFSET 1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_MASK0_LEN     1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_MASK0_OFFSET  0

#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_MASK0_LEN    1
#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_MASK0_OFFSET 0

#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_MASK0_LEN       1
#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_MASK0_OFFSET    4
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_MASK0_LEN    1
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_MASK0_OFFSET 3
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_MASK0_LEN          1
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_MASK0_OFFSET       2
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_MASK0_LEN          1
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_MASK0_OFFSET       1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_MASK0_LEN         1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_MASK0_OFFSET      0

#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_STATUS0_LEN        1
#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_STATUS0_OFFSET     2
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_STATUS0_LEN    1
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_STATUS0_OFFSET 1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_STATUS0_LEN     1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_STATUS0_OFFSET  0

#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_STATUS0_LEN    1
#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_STATUS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_STATUS0_LEN       1
#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_STATUS0_OFFSET    4
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_STATUS0_LEN    1
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_STATUS0_OFFSET 3
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_STATUS0_LEN          1
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_STATUS0_OFFSET       2
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_STATUS0_LEN          1
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_STATUS0_OFFSET       1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_STATUS0_LEN         1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_STATUS0_OFFSET      0

#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_STS0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_STS0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_CLR0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_CLR0_OFFSET 0

#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_MASK1_LEN        1
#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_MASK1_OFFSET     2
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_MASK1_LEN    1
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_MASK1_OFFSET 1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_MASK1_LEN     1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_MASK1_OFFSET  0

#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_MASK1_LEN    1
#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_MASK1_OFFSET 0

#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_MASK1_LEN       1
#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_MASK1_OFFSET    4
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_MASK1_LEN    1
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_MASK1_OFFSET 3
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_MASK1_LEN          1
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_MASK1_OFFSET       2
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_MASK1_LEN          1
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_MASK1_OFFSET       1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_MASK1_LEN         1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_MASK1_OFFSET      0

#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_STATUS1_LEN        1
#define STARS_ACSQINT_S_REG_L1_CQ_FULL_S_STATUS1_OFFSET     2
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_STATUS1_LEN    1
#define STARS_ACSQINT_S_REG_L1_POST_PAUSED_S_STATUS1_OFFSET 1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_STATUS1_LEN     1
#define STARS_ACSQINT_S_REG_L1_PRE_PAUSED_S_STATUS1_OFFSET  0

#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_STATUS1_LEN    1
#define STARS_ACSQINT_S_REG_L1_TASK_DEBUG_S_STATUS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_STATUS1_LEN       1
#define STARS_ACSQINT_S_REG_L1_SQ_SEC_ERROR_S_STATUS1_OFFSET    4
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_STATUS1_LEN    1
#define STARS_ACSQINT_S_REG_L1_SW_STATUS_ERROR_S_STATUS1_OFFSET 3
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_STATUS1_LEN          1
#define STARS_ACSQINT_S_REG_L1_SQE_ERROR_S_STATUS1_OFFSET       2
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_STATUS1_LEN          1
#define STARS_ACSQINT_S_REG_L1_TASK_TRAP_S_STATUS1_OFFSET       1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_STATUS1_LEN         1
#define STARS_ACSQINT_S_REG_L1_TASK_ERROR_S_STATUS1_OFFSET      0

#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_STS1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_STS1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_CLR1_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_CLR1_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_PRE_PAUSED_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_POST_PAUSED_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_CQ_FULL_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_DEBUG_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_ERROR_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_TASK_TRAP_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQE_ERROR_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SW_STATUS_ERROR_S_RAW0_OFFSET 0

#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_RAW0_LEN    32
#define STARS_ACSQINT_S_REG_L2_SQ_SEC_ERROR_S_RAW0_OFFSET 0

#endif // __STARS_ACSQINT_S_REG_REG_OFFSET_FIELD_H__
