// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_db_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2019/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 10:06:20 Create file
// ******************************************************************************

#ifndef __STARS_DB_REG_REG_OFFSET_FIELD_H__
#define __STARS_DB_REG_REG_OFFSET_FIELD_H__

#define STARS_DB_REG_ECC_PARITY_LEN      6
#define STARS_DB_REG_ECC_PARITY_OFFSET   16
#define STARS_DB_REG_ECC_ON_BRESP_LEN    1
#define STARS_DB_REG_ECC_ON_BRESP_OFFSET 1
#define STARS_DB_REG_ECC_BYPASS_LEN      1
#define STARS_DB_REG_ECC_BYPASS_OFFSET   0

#define STARS_DB_REG_ECC_ERR_SYN_LATCHED_LEN    6
#define STARS_DB_REG_ECC_ERR_SYN_LATCHED_OFFSET 16
#define STARS_DB_REG_ERR_ADDR_LATCHED_LEN       11
#define STARS_DB_REG_ERR_ADDR_LATCHED_OFFSET    0

#define STARS_DB_REG_ECC_2BIT_ERR_MASK_LEN    1
#define STARS_DB_REG_ECC_2BIT_ERR_MASK_OFFSET 1
#define STARS_DB_REG_ECC_1BIT_ERR_MASK_LEN    1
#define STARS_DB_REG_ECC_1BIT_ERR_MASK_OFFSET 0

#define STARS_DB_REG_ECC_2BIT_ERR_STATUS_LEN    1
#define STARS_DB_REG_ECC_2BIT_ERR_STATUS_OFFSET 1
#define STARS_DB_REG_ECC_1BIT_ERR_STATUS_LEN    1
#define STARS_DB_REG_ECC_1BIT_ERR_STATUS_OFFSET 0

#define STARS_DB_REG_DB_INT0_SUMMARY0_LEN    16
#define STARS_DB_REG_DB_INT0_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT1_SUMMARY0_LEN    16
#define STARS_DB_REG_DB_INT1_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT2_SUMMARY0_LEN    16
#define STARS_DB_REG_DB_INT2_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_INT3_SUMMARY0_LEN    16
#define STARS_DB_REG_DB_INT3_SUMMARY0_OFFSET 0

#define STARS_DB_REG_DB_SEC_EN_LEN    1
#define STARS_DB_REG_DB_SEC_EN_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS0_LEN    32
#define STARS_DB_REG_DB_INT_STATUS0_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS1_LEN    32
#define STARS_DB_REG_DB_INT_STATUS1_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS2_LEN    32
#define STARS_DB_REG_DB_INT_STATUS2_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS3_LEN    32
#define STARS_DB_REG_DB_INT_STATUS3_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS4_LEN    32
#define STARS_DB_REG_DB_INT_STATUS4_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS5_LEN    32
#define STARS_DB_REG_DB_INT_STATUS5_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS6_LEN    32
#define STARS_DB_REG_DB_INT_STATUS6_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS7_LEN    32
#define STARS_DB_REG_DB_INT_STATUS7_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS8_LEN    32
#define STARS_DB_REG_DB_INT_STATUS8_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS9_LEN    32
#define STARS_DB_REG_DB_INT_STATUS9_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS10_LEN    32
#define STARS_DB_REG_DB_INT_STATUS10_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS11_LEN    32
#define STARS_DB_REG_DB_INT_STATUS11_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS12_LEN    32
#define STARS_DB_REG_DB_INT_STATUS12_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS13_LEN    32
#define STARS_DB_REG_DB_INT_STATUS13_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS14_LEN    32
#define STARS_DB_REG_DB_INT_STATUS14_OFFSET 0

#define STARS_DB_REG_DB_INT_STATUS15_LEN    32
#define STARS_DB_REG_DB_INT_STATUS15_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK0_LEN    32
#define STARS_DB_REG_DB_INT0_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK1_LEN    32
#define STARS_DB_REG_DB_INT0_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK2_LEN    32
#define STARS_DB_REG_DB_INT0_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK3_LEN    32
#define STARS_DB_REG_DB_INT0_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK4_LEN    32
#define STARS_DB_REG_DB_INT0_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK5_LEN    32
#define STARS_DB_REG_DB_INT0_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK6_LEN    32
#define STARS_DB_REG_DB_INT0_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK7_LEN    32
#define STARS_DB_REG_DB_INT0_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK8_LEN    32
#define STARS_DB_REG_DB_INT0_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK9_LEN    32
#define STARS_DB_REG_DB_INT0_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK10_LEN    32
#define STARS_DB_REG_DB_INT0_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK11_LEN    32
#define STARS_DB_REG_DB_INT0_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK12_LEN    32
#define STARS_DB_REG_DB_INT0_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK13_LEN    32
#define STARS_DB_REG_DB_INT0_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK14_LEN    32
#define STARS_DB_REG_DB_INT0_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT0_MASK15_LEN    32
#define STARS_DB_REG_DB_INT0_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK0_LEN    32
#define STARS_DB_REG_DB_INT1_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK1_LEN    32
#define STARS_DB_REG_DB_INT1_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK2_LEN    32
#define STARS_DB_REG_DB_INT1_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK3_LEN    32
#define STARS_DB_REG_DB_INT1_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK4_LEN    32
#define STARS_DB_REG_DB_INT1_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK5_LEN    32
#define STARS_DB_REG_DB_INT1_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK6_LEN    32
#define STARS_DB_REG_DB_INT1_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK7_LEN    32
#define STARS_DB_REG_DB_INT1_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK8_LEN    32
#define STARS_DB_REG_DB_INT1_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK9_LEN    32
#define STARS_DB_REG_DB_INT1_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK10_LEN    32
#define STARS_DB_REG_DB_INT1_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK11_LEN    32
#define STARS_DB_REG_DB_INT1_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK12_LEN    32
#define STARS_DB_REG_DB_INT1_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK13_LEN    32
#define STARS_DB_REG_DB_INT1_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK14_LEN    32
#define STARS_DB_REG_DB_INT1_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT1_MASK15_LEN    32
#define STARS_DB_REG_DB_INT1_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK0_LEN    32
#define STARS_DB_REG_DB_INT2_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK1_LEN    32
#define STARS_DB_REG_DB_INT2_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK2_LEN    32
#define STARS_DB_REG_DB_INT2_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK3_LEN    32
#define STARS_DB_REG_DB_INT2_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK4_LEN    32
#define STARS_DB_REG_DB_INT2_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK5_LEN    32
#define STARS_DB_REG_DB_INT2_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK6_LEN    32
#define STARS_DB_REG_DB_INT2_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK7_LEN    32
#define STARS_DB_REG_DB_INT2_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK8_LEN    32
#define STARS_DB_REG_DB_INT2_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK9_LEN    32
#define STARS_DB_REG_DB_INT2_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK10_LEN    32
#define STARS_DB_REG_DB_INT2_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK11_LEN    32
#define STARS_DB_REG_DB_INT2_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK12_LEN    32
#define STARS_DB_REG_DB_INT2_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK13_LEN    32
#define STARS_DB_REG_DB_INT2_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK14_LEN    32
#define STARS_DB_REG_DB_INT2_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT2_MASK15_LEN    32
#define STARS_DB_REG_DB_INT2_MASK15_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK0_LEN    32
#define STARS_DB_REG_DB_INT3_MASK0_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK1_LEN    32
#define STARS_DB_REG_DB_INT3_MASK1_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK2_LEN    32
#define STARS_DB_REG_DB_INT3_MASK2_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK3_LEN    32
#define STARS_DB_REG_DB_INT3_MASK3_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK4_LEN    32
#define STARS_DB_REG_DB_INT3_MASK4_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK5_LEN    32
#define STARS_DB_REG_DB_INT3_MASK5_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK6_LEN    32
#define STARS_DB_REG_DB_INT3_MASK6_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK7_LEN    32
#define STARS_DB_REG_DB_INT3_MASK7_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK8_LEN    32
#define STARS_DB_REG_DB_INT3_MASK8_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK9_LEN    32
#define STARS_DB_REG_DB_INT3_MASK9_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK10_LEN    32
#define STARS_DB_REG_DB_INT3_MASK10_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK11_LEN    32
#define STARS_DB_REG_DB_INT3_MASK11_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK12_LEN    32
#define STARS_DB_REG_DB_INT3_MASK12_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK13_LEN    32
#define STARS_DB_REG_DB_INT3_MASK13_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK14_LEN    32
#define STARS_DB_REG_DB_INT3_MASK14_OFFSET 0

#define STARS_DB_REG_DB_INT3_MASK15_LEN    32
#define STARS_DB_REG_DB_INT3_MASK15_OFFSET 0

#endif // __STARS_DB_REG_REG_OFFSET_FIELD_H__
