// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_ns_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/22 14:38:32 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_NS_REG_REG_OFFSET_H__
#define __STARS_ACSQINT_NS_REG_REG_OFFSET_H__

/* STARS_ACSQINT_NS_REG Base address of Module's Register */
#define SOC_STARS_ACSQINT_NS_REG_BASE                       (0x20000)

/******************************************************************************/
/*                      SOC STARS_ACSQINT_NS_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_NORMAL_NS_MASK0_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x20)   /* 上报TSCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_DEBUG_NS_MASK0_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x24)   /* 上报TSCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_ERROR_NS_MASK0_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x28)   /* 上报TSCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS0_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2C)   /* 上报TSCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS0_REG       (SOC_STARS_ACSQINT_NS_REG_BASE + 0x30)   /* 上报TSCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_ERROR_NS_STATUS0_REG       (SOC_STARS_ACSQINT_NS_REG_BASE + 0x34)   /* 上报TSCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS0_REG   (SOC_STARS_ACSQINT_NS_REG_BASE + 0x420)  /* 向TSCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS0_REG  (SOC_STARS_ACSQINT_NS_REG_BASE + 0x430)  /* 向TSCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS0_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x440)  /* 向TSCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_DEBUG_NS_STS0_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x450)  /* 向TSCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_ERROR_NS_STS0_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x460)  /* 向TSCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_TRAP_NS_STS0_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x470)  /* 向TSCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQE_ERROR_NS_STS0_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x480)  /* 向TSCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SW_STATUS_ERROR_NS_STS0_REG     (SOC_STARS_ACSQINT_NS_REG_BASE + 0x490)  /* 向TSCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQ_SEC_ERROR_NS_STS0_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x4A0)  /* 向TSCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR0_REG   (SOC_STARS_ACSQINT_NS_REG_BASE + 0x540)  /* 向TSCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR0_REG  (SOC_STARS_ACSQINT_NS_REG_BASE + 0x550)  /* 向TSCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR0_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x560)  /* 向TSCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_DEBUG_NS_CLR0_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x570)  /* 向TSCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_ERROR_NS_CLR0_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x580)  /* 向TSCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_TRAP_NS_CLR0_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x590)  /* 向TSCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQE_ERROR_NS_CLR0_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x5A0)  /* 向TSCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR0_REG     (SOC_STARS_ACSQINT_NS_REG_BASE + 0x5B0)  /* 向TSCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR0_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x5C0)  /* 向TSCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_NORMAL_NS_MASK1_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2020) /* 上报CtrlCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_DEBUG_NS_MASK1_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2024) /* 上报CtrlCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_ERROR_NS_MASK1_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2028) /* 上报CtrlCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS1_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x202C) /* 上报CtrlCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS1_REG       (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2030) /* 上报CtrlCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L1_ACSQ_ERROR_NS_STATUS1_REG       (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2034) /* 上报CtrlCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS1_REG   (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2110) /* 向CtrlCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS1_REG  (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2120) /* 向CtrlCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS1_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2130) /* 向CtrlCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_DEBUG_NS_STS1_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2140) /* 向CtrlCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_ERROR_NS_STS1_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2150) /* 向CtrlCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_TRAP_NS_STS1_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2160) /* 向CtrlCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQE_ERROR_NS_STS1_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2170) /* 向CtrlCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SW_STATUS_ERROR_NS_STS1_REG     (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2180) /* 向CtrlCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQ_SEC_ERROR_NS_STS1_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2190) /* 向CtrlCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR1_REG   (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21A0) /* 向CtrlCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR1_REG  (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21B0) /* 向CtrlCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR1_REG      (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21C0) /* 向CtrlCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_DEBUG_NS_CLR1_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21D0) /* 向CtrlCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_ERROR_NS_CLR1_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21E0) /* 向CtrlCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_TRAP_NS_CLR1_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x21F0) /* 向CtrlCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQE_ERROR_NS_CLR1_REG           (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2200) /* 向CtrlCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR1_REG     (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2210) /* 向CtrlCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR1_REG        (SOC_STARS_ACSQINT_NS_REG_BASE + 0x2220) /* 向CtrlCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_FORCE_REG  (SOC_STARS_ACSQINT_NS_REG_BASE + 0x6080) /* 向CtrlCPU上报的L2级PRE_PAUSED中断强制状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_POST_PAUSED_NS_FORCE_REG (SOC_STARS_ACSQINT_NS_REG_BASE + 0x6090) /* 向CtrlCPU上报的L2级POST_PAUSED中断强制状态寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_NORMAL_CQ_FULL_NS_FORCE_REG     (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60A0) /* 向CtrlCPU上报的L2级CQ_FULL中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_DEBUG_NS_FORCE_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60B0) /* 向CtrlCPU上报的L2级TASK_DEBUG中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_ERROR_NS_FORCE_REG         (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60C0) /* 向CtrlCPU上报的L2级TASK_ERROR中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_TASK_TRAP_NS_FORCE_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60D0) /* 向CtrlCPU上报的L2级TASK_TRAP中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQE_ERROR_NS_FORCE_REG          (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60E0) /* 向CtrlCPU上报的L2级SQE_ERROR中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SW_STATUS_ERROR_NS_FORCE_REG    (SOC_STARS_ACSQINT_NS_REG_BASE + 0x60F0) /* 向CtrlCPU上报的L2级SW_STATUS_ERROR中断强制寄存器 */
#define SOC_STARS_ACSQINT_NS_REG_STARS_L2_SQ_SEC_ERROR_NS_FORCE_REG       (SOC_STARS_ACSQINT_NS_REG_BASE + 0x6100) /* 向CtrlCPU上报的L2级SQ_SEC_ERROR中断强制寄存器 */

#endif // __STARS_ACSQINT_NS_REG_REG_OFFSET_H__
