// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_int_ns_cfg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/23 09:24:07 Create file
// ******************************************************************************

#ifndef __STARS_INT_NS_CFG_REG_OFFSET_H__
#define __STARS_INT_NS_CFG_REG_OFFSET_H__

/* STARS_INT_NS_CFG Base address of Module's Register */
#define SOC_STARS_INT_NS_CFG_BASE                       (0x8000)

/******************************************************************************/
/*                      SOC STARS_INT_NS_CFG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_INT_NS_CFG_STARS_RAS_PFGCTL_REG                     (SOC_STARS_INT_NS_CFG_BASE + 0x800)  /* 故障注入控制寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_RAS_PFGDN_REG                      (SOC_STARS_INT_NS_CFG_BASE + 0x804)  /* 故障注入间隔寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_ERR_MISCL_REG                      (SOC_STARS_INT_NS_CFG_BASE + 0x808)  /* 错误记录信息寄存器低位 */
#define SOC_STARS_INT_NS_CFG_STARS_ERR_MISCH_REG                      (SOC_STARS_INT_NS_CFG_BASE + 0x80C)  /* 错误记录信息寄存器高位 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_SEC_LOCK_REG                   (SOC_STARS_INT_NS_CFG_BASE + 0x814)  /* 上报HOST中断安全锁 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_INT_PF_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x820)  /* 上报HOST中断PF设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_0_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x830)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_1_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x834)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_2_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x838)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_3_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x83C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_4_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x840)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_5_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x844)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_6_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x848)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_7_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x84C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_8_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x850)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_9_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x854)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_10_REG (SOC_STARS_INT_NS_CFG_BASE + 0x858)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_11_REG (SOC_STARS_INT_NS_CFG_BASE + 0x85C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_12_REG (SOC_STARS_INT_NS_CFG_BASE + 0x860)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_13_REG (SOC_STARS_INT_NS_CFG_BASE + 0x864)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_14_REG (SOC_STARS_INT_NS_CFG_BASE + 0x868)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_NORMAL_INT_ID_15_REG (SOC_STARS_INT_NS_CFG_BASE + 0x86C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_0_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x870)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_1_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x874)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_2_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x878)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_3_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x87C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_4_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x880)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_5_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x884)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_6_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x888)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_7_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x88C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_8_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x890)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_9_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x894)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_10_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x898)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_11_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x89C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_12_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8A0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_13_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8A4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_14_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8A8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_DEBUG_INT_ID_15_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8AC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_0_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8B0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_1_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8B4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_2_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8B8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_3_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8BC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_4_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8C0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_5_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8C4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_6_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8C8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_7_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8CC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_8_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8D0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_9_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x8D4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_10_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8D8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_11_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8DC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_12_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8E0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_13_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8E4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_14_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8E8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_RTSQ_ERROR_INT_ID_15_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8EC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_NORMAL_INT_ID_0_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8F0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_NORMAL_INT_ID_1_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8F4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_NORMAL_INT_ID_2_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8F8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_NORMAL_INT_ID_3_REG  (SOC_STARS_INT_NS_CFG_BASE + 0x8FC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_DEBUG_INT_ID_0_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x930)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_DEBUG_INT_ID_1_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x934)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_DEBUG_INT_ID_2_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x938)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_DEBUG_INT_ID_3_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x93C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_ERROR_INT_ID_0_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x970)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_ERROR_INT_ID_1_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x974)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_ERROR_INT_ID_2_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x978)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ACSQ_ERROR_INT_ID_3_REG   (SOC_STARS_INT_NS_CFG_BASE + 0x97C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_0_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9B0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_1_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9B4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_2_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9B8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_3_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9BC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_4_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9C0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_5_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9C4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_6_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9C8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_7_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9CC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_8_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9D0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_9_REG           (SOC_STARS_INT_NS_CFG_BASE + 0x9D4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_10_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9D8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_11_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9DC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_12_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9E0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_13_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9E4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_14_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9E8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CQ_INT_ID_15_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9EC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_0_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9F0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_1_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9F4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_2_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9F8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_3_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x9FC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_4_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA00)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_5_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA04)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_6_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA08)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_7_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA0C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_8_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA10)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_9_REG          (SOC_STARS_INT_NS_CFG_BASE + 0xA14)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_10_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA18)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_11_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA1C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_12_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA20)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_13_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA24)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_14_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA28)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CDQ_INT_ID_15_REG         (SOC_STARS_INT_NS_CFG_BASE + 0xA2C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HACPU_INT_ID_0_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA30)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HACPU_INT_ID_1_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA34)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HACPU_INT_ID_2_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA38)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HACPU_INT_ID_3_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA3C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HCCPU_INT_ID_0_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA70)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HCCPU_INT_ID_1_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA74)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HCCPU_INT_ID_2_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA78)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_TOPIC_HCCPU_INT_ID_3_REG  (SOC_STARS_INT_NS_CFG_BASE + 0xA7C)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_PROF_INT_ID_REG           (SOC_STARS_INT_NS_CFG_BASE + 0xAB0)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_ECC_INT_ID_REG            (SOC_STARS_INT_NS_CFG_BASE + 0xAB4)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_CONFIG_ERR_INT_ID_REG     (SOC_STARS_INT_NS_CFG_BASE + 0xAB8)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_HTIC_BUS_ERR_INT_ID_REG        (SOC_STARS_INT_NS_CFG_BASE + 0xABC)  /* 上报HOST中断ID设置寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_FORCE_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2000) /* pool_conflict和ecc_error中断注错寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_RAW_NS_REG          (SOC_STARS_INT_NS_CFG_BASE + 0x2004) /* pool_conflict和ecc_error原始中断状态寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_STS0_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2008) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_MASK0_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x200C) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_CLR0_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2010) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_STS1_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2014) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_MASK1_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2018) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_CLR1_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x201C) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_STS2_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2020) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至HOSTCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_MASK2_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2024) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至HOSTCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_CONFIG_ERR_CLR2_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2028) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_FORCE_NS_REG               (SOC_STARS_INT_NS_CFG_BASE + 0x2030) /* pool_conflict和ecc_error中断注错寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_RAW_NS_REG                 (SOC_STARS_INT_NS_CFG_BASE + 0x2034) /* pool_conflict和ecc_error原始中断状态寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_STS0_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2038) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_MASK0_NS_REG               (SOC_STARS_INT_NS_CFG_BASE + 0x203C) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_CLR0_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2040) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_CLR1_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2044) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_STS1_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2048) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_MASK1_NS_REG               (SOC_STARS_INT_NS_CFG_BASE + 0x204C) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_CLR2_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2050) /* pool_conflict和ecc_error中断清除寄存器 */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_STS2_NS_REG                (SOC_STARS_INT_NS_CFG_BASE + 0x2054) /* pool_conflict和ecc_error屏蔽后中断状态寄存器，上报至HOSTCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_ECC_MASK2_NS_REG               (SOC_STARS_INT_NS_CFG_BASE + 0x2058) /* pool_conflict和ecc_error中断屏蔽寄存器，上报至HOSTCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_MASK0_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2060) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_MASK1_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2064) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_MASK2_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2068) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至HOSTCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_STS0_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x206C) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_STS1_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2070) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_STS2_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2074) /* NOC_ARB0的bus erro中断屏蔽寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_CLR0_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2078) /* NOC_ARB0的bus erro中断清除寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_CLR1_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x207C) /* NOC_ARB0的bus erro中断清除寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_CLR2_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2080) /* NOC_ARB0的bus erro中断清除寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_RAW0_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2084) /* NOC_ARB0的bus erro中断原始寄存器，上报至TSCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_RAW1_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x2088) /* NOC_ARB0的bus erro中断原始寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_RAW2_NS_REG         (SOC_STARS_INT_NS_CFG_BASE + 0x208C) /* NOC_ARB0的bus erro中断原始寄存器，上报至ControlCPU */
#define SOC_STARS_INT_NS_CFG_STARS_INT_BUS0_ERROR_FORCE_NS_REG        (SOC_STARS_INT_NS_CFG_BASE + 0x2090) /* NOC_ARB0的bus erro中断原始寄存器，上报至ControlCPU */

#endif // __STARS_INT_NS_CFG_REG_OFFSET_H__
