// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_virtualization_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 09:26:35 Create file
// ******************************************************************************

#ifndef __STARS_VIRTUALIZATION_REG_REG_OFFSET_FIELD_H__
#define __STARS_VIRTUALIZATION_REG_REG_OFFSET_FIELD_H__

#define STARS_VIRTUALIZATION_REG_VIRTUALIZATION_MODE_LEN    1
#define STARS_VIRTUALIZATION_REG_VIRTUALIZATION_MODE_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_CHANGE_PENDING_SET_LEN    4
#define STARS_VIRTUALIZATION_REG_VF_CHANGE_PENDING_SET_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_CHANGE_PENDING_STATUS_LEN    4
#define STARS_VIRTUALIZATION_REG_VF_CHANGE_PENDING_STATUS_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF0_IS_VIP_LEN    1
#define STARS_VIRTUALIZATION_REG_VF0_IS_VIP_OFFSET 8
#define STARS_VIRTUALIZATION_REG_VF0_VFGID_LEN     1
#define STARS_VIRTUALIZATION_REG_VF0_VFGID_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_0_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_0_OFFSET 8
#define STARS_VIRTUALIZATION_REG_VF_VFGID_0_LEN     1
#define STARS_VIRTUALIZATION_REG_VF_VFGID_0_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_1_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_1_OFFSET 8
#define STARS_VIRTUALIZATION_REG_VF_VFGID_1_LEN     1
#define STARS_VIRTUALIZATION_REG_VF_VFGID_1_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_2_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_IS_VIP_2_OFFSET 8
#define STARS_VIRTUALIZATION_REG_VF_VFGID_2_LEN     1
#define STARS_VIRTUALIZATION_REG_VF_VFGID_2_OFFSET  0

#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_SQ_ENABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_SQ_ENABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_SQ_DISABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_SQ_DISABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_ENABLED_STATUS0_LEN    32
#define STARS_VIRTUALIZATION_REG_NORM_ACTIVE_ENABLED_STATUS0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_SQ_ENABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_SQ_ENABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_SQ_DISABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_SQ_DISABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_ENABLED_STATUS0_LEN    32
#define STARS_VIRTUALIZATION_REG_HIGH_ACTIVE_ENABLED_STATUS0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_SQ_ENABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_SQ_ENABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_SQ_DISABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_SQ_DISABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_ENABLED_STATUS0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_NORM_ACTIVE_ENABLED_STATUS0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_SQ_ENABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_SQ_ENABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_SQ_DISABLE_CTRL0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_SQ_DISABLE_CTRL0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_ENABLED_STATUS0_LEN    32
#define STARS_VIRTUALIZATION_REG_COMMON_HIGH_ACTIVE_ENABLED_STATUS0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_0_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_1_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_2_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_3_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_SHADOW_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_0_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_1_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_2_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_3_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_SHADOW_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_0_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_1_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_2_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_3_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_SHADOW_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_0_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_1_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_2_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_3_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_RUNTIME_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_0_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_1_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_2_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_3_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_THRESHOLD_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_0_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_1_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_2_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_3_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_MAX_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_0_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_1_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_2_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_3_LEN    8
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_H_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_REFILL_TOKEN_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_0_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_0_OFFSET 31
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_0_LEN     8
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_0_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_1_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_1_OFFSET 31
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_1_LEN     8
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_1_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_2_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_2_OFFSET 31
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_2_LEN     8
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_2_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_3_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TOKEN_TO_LIMIT_EN_3_OFFSET 31
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_3_LEN     8
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_H_3_OFFSET  0

#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_TO_TOKEN_LIMIT_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_0_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_1_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_2_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_3_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_TIMEOUT_STATE_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_ENABLED_VFG_NUM_LEN    1
#define STARS_VIRTUALIZATION_REG_ENABLED_VFG_NUM_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_0_LEN          1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_0_OFFSET       31
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_0_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_0_OFFSET 30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_0_LEN            30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_0_OFFSET         0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_1_LEN          1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_1_OFFSET       31
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_1_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_1_OFFSET 30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_1_LEN            30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_1_OFFSET         0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_2_LEN          1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_2_OFFSET       31
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_2_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_2_OFFSET 30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_2_LEN            30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_2_OFFSET         0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_3_LEN          1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_CLR_3_OFFSET       31
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_3_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_RECORD_EN_3_OFFSET 30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_3_LEN            30
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_H_3_OFFSET         0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_0_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_1_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_2_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_3_LEN    32
#define STARS_VIRTUALIZATION_REG_VF_WORKING_TIME_L_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_CLR_LEN          1
#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_CLR_OFFSET       31
#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_RECORD_EN_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_RECORD_EN_OFFSET 30
#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_OF_VFG_LEN       24
#define STARS_VIRTUALIZATION_REG_VF_SWITCH_TIME_OF_VFG_OFFSET    0

#define STARS_VIRTUALIZATION_REG_VF_RECORD_CLR_LEN    1
#define STARS_VIRTUALIZATION_REG_VF_RECORD_CLR_OFFSET 31
#define STARS_VIRTUALIZATION_REG_VF_SEL_EN_LEN        1
#define STARS_VIRTUALIZATION_REG_VF_SEL_EN_OFFSET     30
#define STARS_VIRTUALIZATION_REG_VF_SEL_LEN           2
#define STARS_VIRTUALIZATION_REG_VF_SEL_OFFSET        0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_0_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_0_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_1_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_1_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_2_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_2_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_3_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_3_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_4_LEN    9
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_RTSQID_4_OFFSET 0

#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_REQ_NUM_SUC_LEN    16
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_REQ_NUM_SUC_OFFSET 16
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_REQ_NUM_LEN        16
#define STARS_VIRTUALIZATION_REG_VF_SWAPIN_REQ_NUM_OFFSET     0

#endif // __STARS_VIRTUALIZATION_REG_REG_OFFSET_FIELD_H__
