// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cnt_notify_reg_define_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 10:07:31 Create file
// ******************************************************************************

#ifndef __STARS_CNT_NOTIFY_REG_DEFINE_REG_OFFSET_FIELD_H__
#define __STARS_CNT_NOTIFY_REG_DEFINE_REG_OFFSET_FIELD_H__

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_0_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_0_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_1_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_1_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_2_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_2_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_3_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_3_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_4_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_4_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_5_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_5_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_6_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_6_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_7_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_7_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_8_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_8_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_9_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_9_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_10_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_10_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_11_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_11_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_12_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_12_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_13_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_13_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_14_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_14_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_15_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_15_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_16_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_16_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_17_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_17_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_18_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_18_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_19_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_19_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_20_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_20_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_21_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_21_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_22_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_22_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_23_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_23_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_24_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_24_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_25_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_25_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_26_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_26_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_27_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_27_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_28_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_28_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_29_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_29_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_30_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_30_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_31_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_31_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_32_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_32_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_33_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_33_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_34_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_34_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_35_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_35_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_36_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_36_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_37_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_37_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_38_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_38_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_39_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_39_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_40_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_40_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_41_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_41_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_42_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_42_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_43_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_43_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_44_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_44_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_45_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_45_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_46_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_46_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_47_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_47_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_48_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_48_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_49_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_49_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_50_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_50_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_51_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_51_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_52_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_52_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_53_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_53_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_54_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_54_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_55_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_55_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_56_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_56_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_57_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_57_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_58_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_58_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_59_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_59_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_60_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_60_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_61_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_61_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_62_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_62_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_63_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_ADD_63_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_0_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_0_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_1_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_1_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_2_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_2_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_3_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_3_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_4_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_4_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_5_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_5_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_6_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_6_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_7_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_7_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_8_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_8_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_9_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_9_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_10_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_10_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_11_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_11_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_12_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_12_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_13_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_13_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_14_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_14_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_15_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_15_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_16_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_16_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_17_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_17_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_18_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_18_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_19_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_19_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_20_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_20_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_21_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_21_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_22_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_22_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_23_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_23_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_24_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_24_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_25_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_25_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_26_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_26_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_27_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_27_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_28_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_28_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_29_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_29_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_30_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_30_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_31_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_31_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_32_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_32_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_33_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_33_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_34_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_34_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_35_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_35_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_36_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_36_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_37_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_37_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_38_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_38_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_39_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_39_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_40_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_40_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_41_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_41_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_42_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_42_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_43_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_43_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_44_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_44_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_45_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_45_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_46_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_46_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_47_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_47_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_48_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_48_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_49_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_49_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_50_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_50_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_51_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_51_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_52_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_52_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_53_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_53_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_54_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_54_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_55_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_55_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_56_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_56_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_57_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_57_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_58_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_58_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_59_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_59_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_60_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_60_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_61_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_61_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_62_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_62_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_63_LEN    1
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_CLR_63_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_0_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_0_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_1_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_1_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_2_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_2_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_3_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_3_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_4_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_4_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_5_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_5_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_6_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_6_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_7_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_7_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_8_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_8_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_9_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_9_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_10_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_10_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_11_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_11_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_12_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_12_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_13_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_13_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_14_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_14_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_15_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_15_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_16_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_16_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_17_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_17_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_18_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_18_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_19_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_19_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_20_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_20_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_21_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_21_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_22_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_22_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_23_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_23_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_24_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_24_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_25_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_25_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_26_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_26_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_27_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_27_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_28_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_28_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_29_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_29_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_30_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_30_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_31_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_31_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_32_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_32_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_33_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_33_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_34_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_34_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_35_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_35_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_36_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_36_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_37_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_37_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_38_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_38_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_39_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_39_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_40_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_40_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_41_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_41_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_42_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_42_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_43_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_43_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_44_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_44_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_45_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_45_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_46_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_46_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_47_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_47_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_48_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_48_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_49_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_49_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_50_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_50_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_51_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_51_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_52_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_52_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_53_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_53_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_54_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_54_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_55_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_55_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_56_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_56_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_57_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_57_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_58_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_58_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_59_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_59_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_60_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_60_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_61_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_61_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_62_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_62_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_63_LEN    16
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_RT_63_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_RAW0_LEN    32
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_RAW0_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_RAW1_LEN    32
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_RAW1_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_CLR0_LEN    32
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_CLR0_OFFSET 0

#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_CLR1_LEN    32
#define STARS_CNT_NOTIFY_REG_DEFINE_CNT_NOTIFY_INT_CLR1_OFFSET 0

#endif // __STARS_CNT_NOTIFY_REG_DEFINE_REG_OFFSET_FIELD_H__
