// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_glb_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 09:23:44 Create file
// ******************************************************************************

#ifndef __STARS_GLB_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_GLB_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_GLB_NS_REG_SP_LEVEL_LEN    3
#define STARS_GLB_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_GLB_NS_REG_LP_MODE_LEN     3
#define STARS_GLB_NS_REG_LP_MODE_OFFSET  0



#define STARS_GLB_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_GLB_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_GLB_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_GLB_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_GLB_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_GLB_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_GLB_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_GLB_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_GLB_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_GLB_NS_REG_SQ_FRIENDLY_PCIEDMA_LEN    1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_PCIEDMA_OFFSET 17
#define STARS_GLB_NS_REG_SQ_FRIENDLY_JPEGD_LEN      1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_JPEGD_OFFSET   16
#define STARS_GLB_NS_REG_SQ_FRIENDLY_JPEGE_LEN      1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_JPEGE_OFFSET   15
#define STARS_GLB_NS_REG_SQ_FRIENDLY_VPC_LEN        1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_VPC_OFFSET     14
#define STARS_GLB_NS_REG_SQ_FRIENDLY_CMO_LEN        1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_CMO_OFFSET     13
#define STARS_GLB_NS_REG_SQ_FRIENDLY_SDMA_LEN       1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_SDMA_OFFSET    12
#define STARS_GLB_NS_REG_SQ_FRIENDLY_CONDS_LEN      1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_CONDS_OFFSET   11
#define STARS_GLB_NS_REG_SQ_FRIENDLY_ACPU_LEN       1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_ACPU_OFFSET    10
#define STARS_GLB_NS_REG_SQ_FRIENDLY_VEC_LEN        1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_VEC_OFFSET     9
#define STARS_GLB_NS_REG_SQ_FRIENDLY_FFTS_LEN       1
#define STARS_GLB_NS_REG_SQ_FRIENDLY_FFTS_OFFSET    8

#define STARS_GLB_NS_REG_CFG_FFTS_PLUS_EN_LEN    1
#define STARS_GLB_NS_REG_CFG_FFTS_PLUS_EN_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_0_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_1_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_2_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_3_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_3_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_4_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_4_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_5_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_5_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_6_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_6_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_7_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_7_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_8_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_8_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_9_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_9_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_10_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_10_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_11_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_11_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_12_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_12_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_13_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_13_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_14_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_14_OFFSET 0

#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_15_LEN    2
#define STARS_GLB_NS_REG_CFG_NOTIFYID_VFID_15_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_0_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_1_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_2_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_3_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_3_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_4_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_4_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_5_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_5_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_6_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_6_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_7_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_7_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_8_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_8_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_9_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_9_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_10_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_10_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_11_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_11_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_12_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_12_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_13_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_13_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_14_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_14_OFFSET 0

#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_15_LEN    2
#define STARS_GLB_NS_REG_CFG_RTSQ_SLICE_VFID_15_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_0_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_1_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_2_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_3_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_3_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_4_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_4_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_5_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_5_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_6_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_6_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_7_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_7_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_8_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_8_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_9_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_9_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_10_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_10_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_11_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_11_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_12_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_12_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_13_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_13_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_14_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_14_OFFSET 0

#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_15_LEN    2
#define STARS_GLB_NS_REG_CFG_CDQ_SLICE_VFID_15_OFFSET 0

#define STARS_GLB_NS_REG_RECORD_BLOCK_ACSQ_LEN                1
#define STARS_GLB_NS_REG_RECORD_BLOCK_ACSQ_OFFSET             25
#define STARS_GLB_NS_REG_ECC_BYPASS_LEN                       1
#define STARS_GLB_NS_REG_ECC_BYPASS_OFFSET                    24
#define STARS_GLB_NS_REG_SQE_ERR_BYPASS_LEN                   1
#define STARS_GLB_NS_REG_SQE_ERR_BYPASS_OFFSET                23
#define STARS_GLB_NS_REG_BUS_ERR_BYPASS_LEN                   1
#define STARS_GLB_NS_REG_BUS_ERR_BYPASS_OFFSET                22
#define STARS_GLB_NS_REG_JPEGD_TASK_TIMEOUT_BYPASS_LEN        1
#define STARS_GLB_NS_REG_JPEGD_TASK_TIMEOUT_BYPASS_OFFSET     21
#define STARS_GLB_NS_REG_JPEGE_TASK_TIMEOUT_BYPASS_LEN        1
#define STARS_GLB_NS_REG_JPEGE_TASK_TIMEOUT_BYPASS_OFFSET     20
#define STARS_GLB_NS_REG_VPC_TASK_TIMEOUT_BYPASS_LEN          1
#define STARS_GLB_NS_REG_VPC_TASK_TIMEOUT_BYPASS_OFFSET       19
#define STARS_GLB_NS_REG_CMO_TASK_TIMEOUT_BYPASS_LEN          1
#define STARS_GLB_NS_REG_CMO_TASK_TIMEOUT_BYPASS_OFFSET       18
#define STARS_GLB_NS_REG_WAIT_TASK_TIMEOUT_BYPASS_LEN         1
#define STARS_GLB_NS_REG_WAIT_TASK_TIMEOUT_BYPASS_OFFSET      17
#define STARS_GLB_NS_REG_COMMON_TASK_TIMEOUT_BYPASS_LEN       1
#define STARS_GLB_NS_REG_COMMON_TASK_TIMEOUT_BYPASS_OFFSET    16
#define STARS_GLB_NS_REG_SDMA_TASK_TIMEOUT_BYPASS_LEN         1
#define STARS_GLB_NS_REG_SDMA_TASK_TIMEOUT_BYPASS_OFFSET      15
#define STARS_GLB_NS_REG_FFTS_TASK_TIMEOUT_BYPASS_LEN         1
#define STARS_GLB_NS_REG_FFTS_TASK_TIMEOUT_BYPASS_OFFSET      14
#define STARS_GLB_NS_REG_CONDS_TASK_TIMEOUT_BYPASS_LEN        1
#define STARS_GLB_NS_REG_CONDS_TASK_TIMEOUT_BYPASS_OFFSET     13
#define STARS_GLB_NS_REG_ACPU_TASK_TIMEOUT_BYPASS_LEN         1
#define STARS_GLB_NS_REG_ACPU_TASK_TIMEOUT_BYPASS_OFFSET      12
#define STARS_GLB_NS_REG_PCIEDMA_TASK_TIMEOUT_BYPASS_LEN      1
#define STARS_GLB_NS_REG_PCIEDMA_TASK_TIMEOUT_BYPASS_OFFSET   11
#define STARS_GLB_NS_REG_PRE_POST_PAUSE_TIMEOUT_BYPASS_LEN    1
#define STARS_GLB_NS_REG_PRE_POST_PAUSE_TIMEOUT_BYPASS_OFFSET 10
#define STARS_GLB_NS_REG_TASK_LOG_TIMEOUT_BYPASS_LEN          1
#define STARS_GLB_NS_REG_TASK_LOG_TIMEOUT_BYPASS_OFFSET       9
#define STARS_GLB_NS_REG_FIRST_TASK_NOT_SWAPOUT_LEN           1
#define STARS_GLB_NS_REG_FIRST_TASK_NOT_SWAPOUT_OFFSET        6
#define STARS_GLB_NS_REG_STARS_SQE_SIZE_LEN                   1
#define STARS_GLB_NS_REG_STARS_SQE_SIZE_OFFSET                5
#define STARS_GLB_NS_REG_STARS_SKIP_WARNING_CHECK_LEN         1
#define STARS_GLB_NS_REG_STARS_SKIP_WARNING_CHECK_OFFSET      4
#define STARS_GLB_NS_REG_STARS_SKIP_RESET_LEN                 1
#define STARS_GLB_NS_REG_STARS_SKIP_RESET_OFFSET              3
#define STARS_GLB_NS_REG_STARS_FORCE_ICACHE_INV_LEN           1
#define STARS_GLB_NS_REG_STARS_FORCE_ICACHE_INV_OFFSET        2
#define STARS_GLB_NS_REG_STARS_FASTPATH_EN_LEN                1
#define STARS_GLB_NS_REG_STARS_FASTPATH_EN_OFFSET             1
#define STARS_GLB_NS_REG_STARS_BYPASS_LEN                     1
#define STARS_GLB_NS_REG_STARS_BYPASS_OFFSET                  0

#define STARS_GLB_NS_REG_FFTS_PLUS_NOTIFY_PUSH_EN_LEN    1
#define STARS_GLB_NS_REG_FFTS_PLUS_NOTIFY_PUSH_EN_OFFSET 0

#define STARS_GLB_NS_REG_FORCE_CONDS_PRE_P_LEN           1
#define STARS_GLB_NS_REG_FORCE_CONDS_PRE_P_OFFSET        2
#define STARS_GLB_NS_REG_SWSQ_EVENT_RECORD_PAUSE_LEN     1
#define STARS_GLB_NS_REG_SWSQ_EVENT_RECORD_PAUSE_OFFSET  1
#define STARS_GLB_NS_REG_SWSQ_EVENT_WAIT_FAIL_INT_LEN    1
#define STARS_GLB_NS_REG_SWSQ_EVENT_WAIT_FAIL_INT_OFFSET 0

#define STARS_GLB_NS_REG_COMMON_TASK_RUNTIME_LIMIT_EXP_LEN    6
#define STARS_GLB_NS_REG_COMMON_TASK_RUNTIME_LIMIT_EXP_OFFSET 16
#define STARS_GLB_NS_REG_ACPU_TASK_RUNTIME_LIMIT_EXP_LEN      6
#define STARS_GLB_NS_REG_ACPU_TASK_RUNTIME_LIMIT_EXP_OFFSET   8
#define STARS_GLB_NS_REG_FFTS_TASK_RUNTIME_LIMIT_EXP_LEN      6
#define STARS_GLB_NS_REG_FFTS_TASK_RUNTIME_LIMIT_EXP_OFFSET   0

#define STARS_GLB_NS_REG_PCIEDMA_TASK_RUNTIME_LIMIT_EXP_LEN    6
#define STARS_GLB_NS_REG_PCIEDMA_TASK_RUNTIME_LIMIT_EXP_OFFSET 16
#define STARS_GLB_NS_REG_CONDS_TASK_RUNTIME_LIMIT_EXP_LEN      6
#define STARS_GLB_NS_REG_CONDS_TASK_RUNTIME_LIMIT_EXP_OFFSET   8
#define STARS_GLB_NS_REG_SDMA_TASK_RUNTIME_LIMIT_EXP_LEN       6
#define STARS_GLB_NS_REG_SDMA_TASK_RUNTIME_LIMIT_EXP_OFFSET    0

#define STARS_GLB_NS_REG_CMO_TASK_RUNTIME_LIMIT_EXP_LEN      6
#define STARS_GLB_NS_REG_CMO_TASK_RUNTIME_LIMIT_EXP_OFFSET   24
#define STARS_GLB_NS_REG_JPEGE_TASK_RUNTIME_LIMIT_EXP_LEN    6
#define STARS_GLB_NS_REG_JPEGE_TASK_RUNTIME_LIMIT_EXP_OFFSET 16
#define STARS_GLB_NS_REG_JPEGD_TASK_RUNTIME_LIMIT_EXP_LEN    6
#define STARS_GLB_NS_REG_JPEGD_TASK_RUNTIME_LIMIT_EXP_OFFSET 8
#define STARS_GLB_NS_REG_VPC_TASK_RUNTIME_LIMIT_EXP_LEN      6
#define STARS_GLB_NS_REG_VPC_TASK_RUNTIME_LIMIT_EXP_OFFSET   0

#define STARS_GLB_NS_REG_STARS_CG_DLY_CNT_LEN      8
#define STARS_GLB_NS_REG_STARS_CG_DLY_CNT_OFFSET   24
#define STARS_GLB_NS_REG_NOTIFY_TBL_CG_MASK_LEN    1
#define STARS_GLB_NS_REG_NOTIFY_TBL_CG_MASK_OFFSET 5
#define STARS_GLB_NS_REG_EVENT_TBL_CG_MASK_LEN     1
#define STARS_GLB_NS_REG_EVENT_TBL_CG_MASK_OFFSET  4
#define STARS_GLB_NS_REG_SQCQ_CG_MASK_LEN          1
#define STARS_GLB_NS_REG_SQCQ_CG_MASK_OFFSET       3
#define STARS_GLB_NS_REG_NMANAGER_CG_MASK_LEN      1
#define STARS_GLB_NS_REG_NMANAGER_CG_MASK_OFFSET   2
#define STARS_GLB_NS_REG_RTSQ_CG_MASK_LEN          1
#define STARS_GLB_NS_REG_RTSQ_CG_MASK_OFFSET       1
#define STARS_GLB_NS_REG_STARS_EXE_CG_MASK_LEN     1
#define STARS_GLB_NS_REG_STARS_EXE_CG_MASK_OFFSET  0

#define STARS_GLB_NS_REG_DVPP_CPU_TASK_BYPASS_LEN              1
#define STARS_GLB_NS_REG_DVPP_CPU_TASK_BYPASS_OFFSET           20
#define STARS_GLB_NS_REG_TSCPU_TASK_BYPASS_LEN                 1
#define STARS_GLB_NS_REG_TSCPU_TASK_BYPASS_OFFSET              19
#define STARS_GLB_NS_REG_DEVICE_CTRLCPU_TASK_BYPASS_LEN        1
#define STARS_GLB_NS_REG_DEVICE_CTRLCPU_TASK_BYPASS_OFFSET     18
#define STARS_GLB_NS_REG_DATA_CPU_TASK_BYPASS_LEN              1
#define STARS_GLB_NS_REG_DATA_CPU_TASK_BYPASS_OFFSET           17
#define STARS_GLB_NS_REG_HOST_CTRLCPU_TASK_BYPASS_LEN          1
#define STARS_GLB_NS_REG_HOST_CTRLCPU_TASK_BYPASS_OFFSET       16
#define STARS_GLB_NS_REG_HOST_AICPU_FIRST_TASK_BYPASS_LEN      1
#define STARS_GLB_NS_REG_HOST_AICPU_FIRST_TASK_BYPASS_OFFSET   15
#define STARS_GLB_NS_REG_HOST_AICPU_ONLY_TASK_BYPASS_LEN       1
#define STARS_GLB_NS_REG_HOST_AICPU_ONLY_TASK_BYPASS_OFFSET    14
#define STARS_GLB_NS_REG_DEVICE_AICPU_FIRST_TASK_BYPASS_LEN    1
#define STARS_GLB_NS_REG_DEVICE_AICPU_FIRST_TASK_BYPASS_OFFSET 13
#define STARS_GLB_NS_REG_DEVICE_AICPU_ONLY_TASK_BYPASS_LEN     1
#define STARS_GLB_NS_REG_DEVICE_AICPU_ONLY_TASK_BYPASS_OFFSET  12
#define STARS_GLB_NS_REG_PCIEDMA_TASK_BYPASS_LEN               1
#define STARS_GLB_NS_REG_PCIEDMA_TASK_BYPASS_OFFSET            11
#define STARS_GLB_NS_REG_WR_VALUE_TASK_BYPASS_LEN              1
#define STARS_GLB_NS_REG_WR_VALUE_TASK_BYPASS_OFFSET           10
#define STARS_GLB_NS_REG_CDQM_TASK_BYPASS_LEN                  1
#define STARS_GLB_NS_REG_CDQM_TASK_BYPASS_OFFSET               8
#define STARS_GLB_NS_REG_PCIE_TASK_BYPASS_LEN                  1
#define STARS_GLB_NS_REG_PCIE_TASK_BYPASS_OFFSET               7
#define STARS_GLB_NS_REG_JPEGD_TASK_BYPASS_LEN                 1
#define STARS_GLB_NS_REG_JPEGD_TASK_BYPASS_OFFSET              6
#define STARS_GLB_NS_REG_JPEGE_TASK_BYPASS_LEN                 1
#define STARS_GLB_NS_REG_JPEGE_TASK_BYPASS_OFFSET              5
#define STARS_GLB_NS_REG_VPC_TASK_BYPASS_LEN                   1
#define STARS_GLB_NS_REG_VPC_TASK_BYPASS_OFFSET                4
#define STARS_GLB_NS_REG_SDMA_TASK_BYPASS_LEN                  1
#define STARS_GLB_NS_REG_SDMA_TASK_BYPASS_OFFSET               3
#define STARS_GLB_NS_REG_CMO_TASK_BYPASS_LEN                   1
#define STARS_GLB_NS_REG_CMO_TASK_BYPASS_OFFSET                2
#define STARS_GLB_NS_REG_FFTS_TASK_BYPASS_LEN                  1
#define STARS_GLB_NS_REG_FFTS_TASK_BYPASS_OFFSET               1
#define STARS_GLB_NS_REG_CONDS_TASK_BYPASS_LEN                 1
#define STARS_GLB_NS_REG_CONDS_TASK_BYPASS_OFFSET              0

#define STARS_GLB_NS_REG_HP_OVERRIDE_PERIOD_CYC_L_LEN    32
#define STARS_GLB_NS_REG_HP_OVERRIDE_PERIOD_CYC_L_OFFSET 0

#define STARS_GLB_NS_REG_HP_OVERRIDE_PERIOD_CYC_H_LEN    8
#define STARS_GLB_NS_REG_HP_OVERRIDE_PERIOD_CYC_H_OFFSET 0

#define STARS_GLB_NS_REG_HP_OVERRIDE_CYC_L_LEN    32
#define STARS_GLB_NS_REG_HP_OVERRIDE_CYC_L_OFFSET 0

#define STARS_GLB_NS_REG_HP_OVERRIDE_CYC_H_LEN    8
#define STARS_GLB_NS_REG_HP_OVERRIDE_CYC_H_OFFSET 0

#define STARS_GLB_NS_REG_AWSNOOP_DEVICE_CQ_LEN    1
#define STARS_GLB_NS_REG_AWSNOOP_DEVICE_CQ_OFFSET 27
#define STARS_GLB_NS_REG_AWCACHE_DEVICE_CQ_LEN    4
#define STARS_GLB_NS_REG_AWCACHE_DEVICE_CQ_OFFSET 23
#define STARS_GLB_NS_REG_ARSNOOP_DEVICE_SQ_LEN    1
#define STARS_GLB_NS_REG_ARSNOOP_DEVICE_SQ_OFFSET 20
#define STARS_GLB_NS_REG_ARCACHE_DEVICE_SQ_LEN    4
#define STARS_GLB_NS_REG_ARCACHE_DEVICE_SQ_OFFSET 16
#define STARS_GLB_NS_REG_AWSNOOP_HOST_CQ_LEN      1
#define STARS_GLB_NS_REG_AWSNOOP_HOST_CQ_OFFSET   12
#define STARS_GLB_NS_REG_AWCACHE_HOST_CQ_LEN      4
#define STARS_GLB_NS_REG_AWCACHE_HOST_CQ_OFFSET   8
#define STARS_GLB_NS_REG_ARSNOOP_HOST_SQ_LEN      1
#define STARS_GLB_NS_REG_ARSNOOP_HOST_SQ_OFFSET   4
#define STARS_GLB_NS_REG_ARCACHE_HOST_SQ_LEN      4
#define STARS_GLB_NS_REG_ARCACHE_HOST_SQ_OFFSET   0

#define STARS_GLB_NS_REG_ARSNOOP_WR_VALUE_LEN    1
#define STARS_GLB_NS_REG_ARSNOOP_WR_VALUE_OFFSET 4
#define STARS_GLB_NS_REG_ARCACHE_WR_VALUE_LEN    4
#define STARS_GLB_NS_REG_ARCACHE_WR_VALUE_OFFSET 0

#define STARS_GLB_NS_REG_HOST_CONNECT_MODE_LEN    1
#define STARS_GLB_NS_REG_HOST_CONNECT_MODE_OFFSET 4
#define STARS_GLB_NS_REG_HOST_SSV_LEN             1
#define STARS_GLB_NS_REG_HOST_SSV_OFFSET          3
#define STARS_GLB_NS_REG_PCIE_TH_LEN              1
#define STARS_GLB_NS_REG_PCIE_TH_OFFSET           2
#define STARS_GLB_NS_REG_PCIE_TH_DIRECT_LEN       2
#define STARS_GLB_NS_REG_PCIE_TH_DIRECT_OFFSET    0

#define STARS_GLB_NS_REG_SQ_DONE_BYPASS_LEN        1
#define STARS_GLB_NS_REG_SQ_DONE_BYPASS_OFFSET     1
#define STARS_GLB_NS_REG_CFG_BYPASS_SYS_CNT_LEN    1
#define STARS_GLB_NS_REG_CFG_BYPASS_SYS_CNT_OFFSET 0

#define STARS_GLB_NS_REG_DEBUG_INFO_LEN    32
#define STARS_GLB_NS_REG_DEBUG_INFO_OFFSET 0

#define STARS_GLB_NS_REG_NOC0_PARTID_SET_LEN    32
#define STARS_GLB_NS_REG_NOC0_PARTID_SET_OFFSET 0

#define STARS_GLB_NS_REG_NOC0_PMG_SET_LEN    8
#define STARS_GLB_NS_REG_NOC0_PMG_SET_OFFSET 0

#define STARS_GLB_NS_REG_NOC0_PARTID_CHNL_SET_LEN    32
#define STARS_GLB_NS_REG_NOC0_PARTID_CHNL_SET_OFFSET 0

#define STARS_GLB_NS_REG_NOC1_PARTID_SET_LEN    32
#define STARS_GLB_NS_REG_NOC1_PARTID_SET_OFFSET 0

#define STARS_GLB_NS_REG_NOC1_PMG_SET_LEN    8
#define STARS_GLB_NS_REG_NOC1_PMG_SET_OFFSET 0

#define STARS_GLB_NS_REG_NOC1_PARTID_CHNL_SET_LEN    32
#define STARS_GLB_NS_REG_NOC1_PARTID_CHNL_SET_OFFSET 0

#define STARS_GLB_NS_REG_ERRRSP_DISABLE_LEN      1
#define STARS_GLB_NS_REG_ERRRSP_DISABLE_OFFSET   1
#define STARS_GLB_NS_REG_BROADCAST_BYPASS_LEN    1
#define STARS_GLB_NS_REG_BROADCAST_BYPASS_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_0_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_1_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_2_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_3_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_AWUSER_3_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_0_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_1_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_2_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_3_LEN    32
#define STARS_GLB_NS_REG_CFG_STARS_ARUSER_3_OFFSET 0

#define STARS_GLB_NS_REG_NOC0_ERR_STOP_CTRL_EN_LEN    1
#define STARS_GLB_NS_REG_NOC0_ERR_STOP_CTRL_EN_OFFSET 28
#define STARS_GLB_NS_REG_NOC0_ERR_ID_LEN              8
#define STARS_GLB_NS_REG_NOC0_ERR_ID_OFFSET           20
#define STARS_GLB_NS_REG_NOC0_OST_RETRACT_LEN         1
#define STARS_GLB_NS_REG_NOC0_OST_RETRACT_OFFSET      19
#define STARS_GLB_NS_REG_NOC0_OST_CNT_W_LEN           8
#define STARS_GLB_NS_REG_NOC0_OST_CNT_W_OFFSET        11
#define STARS_GLB_NS_REG_NOC0_OST_CNT_R_LEN           8
#define STARS_GLB_NS_REG_NOC0_OST_CNT_R_OFFSET        3
#define STARS_GLB_NS_REG_NOC0_ERR_TYPE_LEN            3
#define STARS_GLB_NS_REG_NOC0_ERR_TYPE_OFFSET         0

#define STARS_GLB_NS_REG_NOC1_ERR_STOP_CTRL_EN_LEN    1
#define STARS_GLB_NS_REG_NOC1_ERR_STOP_CTRL_EN_OFFSET 28
#define STARS_GLB_NS_REG_NOC1_ERR_ID_LEN              8
#define STARS_GLB_NS_REG_NOC1_ERR_ID_OFFSET           20
#define STARS_GLB_NS_REG_NOC1_OST_RETRACT_LEN         1
#define STARS_GLB_NS_REG_NOC1_OST_RETRACT_OFFSET      19
#define STARS_GLB_NS_REG_NOC1_OST_CNT_W_LEN           8
#define STARS_GLB_NS_REG_NOC1_OST_CNT_W_OFFSET        11
#define STARS_GLB_NS_REG_NOC1_OST_CNT_R_LEN           8
#define STARS_GLB_NS_REG_NOC1_OST_CNT_R_OFFSET        3
#define STARS_GLB_NS_REG_NOC1_ERR_TYPE_LEN            3
#define STARS_GLB_NS_REG_NOC1_ERR_TYPE_OFFSET         0

#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_L_LEN    32
#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_L_OFFSET 0

#define STARS_GLB_NS_REG_NOC_0_WRITE_ERR_MODULE_ID_LEN    12
#define STARS_GLB_NS_REG_NOC_0_WRITE_ERR_MODULE_ID_OFFSET 19
#define STARS_GLB_NS_REG_NOC_0_WRITE_ERR_CLR_LEN          1
#define STARS_GLB_NS_REG_NOC_0_WRITE_ERR_CLR_OFFSET       18
#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_VIRTUAL_LEN     1
#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_VIRTUAL_OFFSET  17
#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_H_LEN           17
#define STARS_GLB_NS_REG_NOC_0_WRITE_ADDR_H_OFFSET        0

#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_L_LEN    32
#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_L_OFFSET 0

#define STARS_GLB_NS_REG_NOC_0_READ_ERR_MODULE_ID_LEN    12
#define STARS_GLB_NS_REG_NOC_0_READ_ERR_MODULE_ID_OFFSET 19
#define STARS_GLB_NS_REG_NOC_0_READ_ERR_CLR_LEN          1
#define STARS_GLB_NS_REG_NOC_0_READ_ERR_CLR_OFFSET       18
#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_VIRTUAL_LEN     1
#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_VIRTUAL_OFFSET  17
#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_H_LEN           17
#define STARS_GLB_NS_REG_NOC_0_READ_ADDR_H_OFFSET        0

#define STARS_GLB_NS_REG_NOC_0_WRITE_CHNL_ERR_LEN    16
#define STARS_GLB_NS_REG_NOC_0_WRITE_CHNL_ERR_OFFSET 16
#define STARS_GLB_NS_REG_NOC_0_READ_CHNL_ERR_LEN     16
#define STARS_GLB_NS_REG_NOC_0_READ_CHNL_ERR_OFFSET  0

#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_L_LEN    32
#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_L_OFFSET 0

#define STARS_GLB_NS_REG_NOC_1_WRITE_ERR_MODULE_ID_LEN    12
#define STARS_GLB_NS_REG_NOC_1_WRITE_ERR_MODULE_ID_OFFSET 19
#define STARS_GLB_NS_REG_NOC_1_WRITE_ERR_CLR_LEN          1
#define STARS_GLB_NS_REG_NOC_1_WRITE_ERR_CLR_OFFSET       18
#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_VIRTUAL_LEN     1
#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_VIRTUAL_OFFSET  17
#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_H_LEN           17
#define STARS_GLB_NS_REG_NOC_1_WRITE_ADDR_H_OFFSET        0

#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_L_LEN    32
#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_L_OFFSET 0

#define STARS_GLB_NS_REG_NOC_1_READ_ERR_MODULE_ID_LEN    12
#define STARS_GLB_NS_REG_NOC_1_READ_ERR_MODULE_ID_OFFSET 19
#define STARS_GLB_NS_REG_NOC_1_READ_ERR_CLR_LEN          1
#define STARS_GLB_NS_REG_NOC_1_READ_ERR_CLR_OFFSET       18
#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_VIRTUAL_LEN     1
#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_VIRTUAL_OFFSET  17
#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_H_LEN           17
#define STARS_GLB_NS_REG_NOC_1_READ_ADDR_H_OFFSET        0

#define STARS_GLB_NS_REG_NOC_1_WRITE_CHNL_ERR_LEN    16
#define STARS_GLB_NS_REG_NOC_1_WRITE_CHNL_ERR_OFFSET 16
#define STARS_GLB_NS_REG_NOC_1_READ_CHNL_ERR_LEN     16
#define STARS_GLB_NS_REG_NOC_1_READ_CHNL_ERR_OFFSET  0







#define STARS_GLB_NS_REG_ECO0_CFG_LEN    32
#define STARS_GLB_NS_REG_ECO0_CFG_OFFSET 0

#define STARS_GLB_NS_REG_ECO1_CFG_LEN    32
#define STARS_GLB_NS_REG_ECO1_CFG_OFFSET 0

#define STARS_GLB_NS_REG_ECO2_CFG_LEN    32
#define STARS_GLB_NS_REG_ECO2_CFG_OFFSET 0

#define STARS_GLB_NS_REG_ECO3_CFG_LEN    32
#define STARS_GLB_NS_REG_ECO3_CFG_OFFSET 0

#define STARS_GLB_NS_REG_ECO0_STATE_LEN    32
#define STARS_GLB_NS_REG_ECO0_STATE_OFFSET 0

#define STARS_GLB_NS_REG_ECO1_STATE_LEN    32
#define STARS_GLB_NS_REG_ECO1_STATE_OFFSET 0

#define STARS_GLB_NS_REG_ECO2_STATE_LEN    32
#define STARS_GLB_NS_REG_ECO2_STATE_OFFSET 0

#define STARS_GLB_NS_REG_ECO3_STATE_LEN    32
#define STARS_GLB_NS_REG_ECO3_STATE_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_W0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_W0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_W1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_W1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_R0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_R0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_R1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_QOS_R1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_W0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_W0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_W1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_W1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_R0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_R0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_R1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_PRESCALER_R1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_CNT_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_0_ARB_CNT_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_W0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_W0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_W1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_W1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_R0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_R0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_R1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_QOS_R1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_W0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_W0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_W1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_W1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_R0_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_R0_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_R1_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_PRESCALER_R1_OFFSET 0

#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_CNT_LEN    32
#define STARS_GLB_NS_REG_STARS_NOC_1_ARB_CNT_OFFSET 0

#define STARS_GLB_NS_REG_SP_RAM_TMOD_LEN    16
#define STARS_GLB_NS_REG_SP_RAM_TMOD_OFFSET 16
#define STARS_GLB_NS_REG_TP_RAM_TMOD_LEN    16
#define STARS_GLB_NS_REG_TP_RAM_TMOD_OFFSET 0

#define STARS_GLB_NS_REG_MEM_POWER_MODE_LEN    5
#define STARS_GLB_NS_REG_MEM_POWER_MODE_OFFSET 0

#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_SDMA_NS_LEN             7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_SDMA_NS_OFFSET          24
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_AIV_ONLY_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_AIV_ONLY_NS_OFFSET 16
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_CONDS_NS_LEN            7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_CONDS_NS_OFFSET         8
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_NS_LEN             7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_NS_OFFSET          0

#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_CMO_NS_LEN      7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_CMO_NS_OFFSET   24
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_JPEGE_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_JPEGE_NS_OFFSET 16
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_JPEGD_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_JPEGD_NS_OFFSET 8
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_VPC_NS_LEN      7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_VPC_NS_OFFSET   0

#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_AIC_ONLY_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_FFTS_AIC_ONLY_NS_OFFSET 24
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_MBLK_CPU_NS_LEN         7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_MBLK_CPU_NS_OFFSET      16
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_SBLK_CPU_NS_LEN         7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_SBLK_CPU_NS_OFFSET      8
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_PCIEDMA_NS_LEN          7
#define STARS_GLB_NS_REG_ACSQ_STRICT_MAX_PCIEDMA_NS_OFFSET       0

#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_SDMA_NS_LEN             7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_SDMA_NS_OFFSET          24
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_AIV_ONLY_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_AIV_ONLY_NS_OFFSET 16
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_CONDS_NS_LEN            7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_CONDS_NS_OFFSET         8
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_NS_LEN             7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_NS_OFFSET          0

#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_CMO_NS_LEN      7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_CMO_NS_OFFSET   24
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_JPEGE_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_JPEGE_NS_OFFSET 16
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_JPEGD_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_JPEGD_NS_OFFSET 8
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_VPC_NS_LEN      7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_VPC_NS_OFFSET   0

#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_AIC_ONLY_NS_LEN    7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_FFTS_AIC_ONLY_NS_OFFSET 24
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_MBLK_CPU_NS_LEN         7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_MBLK_CPU_NS_OFFSET      16
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_SBLK_CPU_NS_LEN         7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_SBLK_CPU_NS_OFFSET      8
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_PCIEDMA_NS_LEN          7
#define STARS_GLB_NS_REG_ACSQ_RELAX_MAX_PCIEDMA_NS_OFFSET       0

#define STARS_GLB_NS_REG_CFG_CQE_AFFECTING_RESULT_LEN    2
#define STARS_GLB_NS_REG_CFG_CQE_AFFECTING_RESULT_OFFSET 20
#define STARS_GLB_NS_REG_CFG_CQE_SUBMODULE_ID_LEN        5
#define STARS_GLB_NS_REG_CFG_CQE_SUBMODULE_ID_OFFSET     15
#define STARS_GLB_NS_REG_CFG_CQE_MODULE_ID_LEN           8
#define STARS_GLB_NS_REG_CFG_CQE_MODULE_ID_OFFSET        7
#define STARS_GLB_NS_REG_CFG_CQE_LETHAL_LEN              3
#define STARS_GLB_NS_REG_CFG_CQE_LETHAL_OFFSET           4
#define STARS_GLB_NS_REG_CFG_CQE_ERROR_LEN               2
#define STARS_GLB_NS_REG_CFG_CQE_ERROR_OFFSET            2
#define STARS_GLB_NS_REG_CFG_CQE_DEVICE_LEN              2
#define STARS_GLB_NS_REG_CFG_CQE_DEVICE_OFFSET           0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_0_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_0_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_1_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_1_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_2_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_2_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_3_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_3_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_4_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_4_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_5_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_5_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_6_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_6_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_7_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_7_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_8_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_8_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_9_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_9_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_10_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_10_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_11_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_11_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_12_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_12_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_13_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_13_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_14_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_14_OFFSET 0

#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_15_LEN    2
#define STARS_GLB_NS_REG_CFG_EVENTID_VFID_15_OFFSET 0

#define STARS_GLB_NS_REG_CFG_WR_VALUE_OST_LIM_LEN    8
#define STARS_GLB_NS_REG_CFG_WR_VALUE_OST_LIM_OFFSET 0

#define STARS_GLB_NS_REG_NOC0_RRESP_STATE_LEN     3
#define STARS_GLB_NS_REG_NOC0_RRESP_STATE_OFFSET  14
#define STARS_GLB_NS_REG_NOC0_BRESP_STATE_LEN     3
#define STARS_GLB_NS_REG_NOC0_BRESP_STATE_OFFSET  11
#define STARS_GLB_NS_REG_NOC0_POISON_STATE_LEN    4
#define STARS_GLB_NS_REG_NOC0_POISON_STATE_OFFSET 7
#define STARS_GLB_NS_REG_NOC0_WSTATE_LEN          6
#define STARS_GLB_NS_REG_NOC0_WSTATE_OFFSET       1
#define STARS_GLB_NS_REG_NOC0_RSTATE_LEN          1
#define STARS_GLB_NS_REG_NOC0_RSTATE_OFFSET       0

#define STARS_GLB_NS_REG_NOC1_RRESP_STATE_LEN     3
#define STARS_GLB_NS_REG_NOC1_RRESP_STATE_OFFSET  14
#define STARS_GLB_NS_REG_NOC1_BRESP_STATE_LEN     3
#define STARS_GLB_NS_REG_NOC1_BRESP_STATE_OFFSET  11
#define STARS_GLB_NS_REG_NOC1_POISON_STATE_LEN    4
#define STARS_GLB_NS_REG_NOC1_POISON_STATE_OFFSET 7
#define STARS_GLB_NS_REG_NOC1_WSTATE_LEN          6
#define STARS_GLB_NS_REG_NOC1_WSTATE_OFFSET       1
#define STARS_GLB_NS_REG_NOC1_RSTATE_LEN          1
#define STARS_GLB_NS_REG_NOC1_RSTATE_OFFSET       0

#endif // __STARS_GLB_NS_REG_REG_OFFSET_FIELD_H__
