// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_host_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/23 09:26:03 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_HOST_REG_REG_OFFSET_H__
#define __STARS_ACSQINT_HOST_REG_REG_OFFSET_H__

/* STARS_ACSQINT_HOST_REG Base address of Module's Register */
#define SOC_STARS_ACSQINT_HOST_REG_BASE                       (0x10a00000)

/******************************************************************************/
/*                      SOC STARS_ACSQINT_HOST_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_STATUS2_0_REG               (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_STATUS2_1_REG               (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_STATUS2_2_REG               (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_STATUS2_3_REG               (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130010) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_CLR2_0_REG                  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_CLR2_1_REG                  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_CLR2_2_REG                  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_ACSQ_NS_CLR2_3_REG                  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130014) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_MASK2_0_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_MASK2_1_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_MASK2_2_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_MASK2_3_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130020) /* 上报HostCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_MASK2_0_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100024) /* 上报HostCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_MASK2_1_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110024) /* 上报HostCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_MASK2_2_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120024) /* 上报HostCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_MASK2_3_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130024) /* 上报HostCPU的L1级Debug中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_MASK2_0_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100028) /* 上报HostCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_MASK2_1_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110028) /* 上报HostCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_MASK2_2_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120028) /* 上报HostCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_MASK2_3_REG        (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130028) /* 上报HostCPU的L1级Error中断屏蔽寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS2_0_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x10002C) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS2_1_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x11002C) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS2_2_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x12002C) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_NORMAL_NS_STATUS2_3_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x13002C) /* 上报HostCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS2_0_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100030) /* 上报HostCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS2_1_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110030) /* 上报HostCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS2_2_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120030) /* 上报HostCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_DEBUG_NS_STATUS2_3_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130030) /* 上报HostCPU的L1级Debug中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_STATUS2_0_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100034) /* 上报HostCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_STATUS2_1_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110034) /* 上报HostCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_STATUS2_2_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120034) /* 上报HostCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L1_ACSQ_ERROR_NS_STATUS2_3_REG      (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130034) /* 上报HostCPU的L1级Error中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS2_0_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100110) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS2_1_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110110) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS2_2_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120110) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_STS2_3_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130110) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS2_0_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100120) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS2_1_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110120) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS2_2_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120120) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_STS2_3_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130120) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS2_0_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100130) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS2_1_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110130) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS2_2_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120130) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_STS2_3_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130130) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_STS2_0_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100140) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_STS2_1_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110140) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_STS2_2_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120140) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_STS2_3_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130140) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_STS2_0_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100150) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_STS2_1_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110150) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_STS2_2_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120150) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_STS2_3_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130150) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_STS2_0_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100160) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_STS2_1_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110160) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_STS2_2_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120160) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_STS2_3_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130160) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_STS2_0_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100170) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_STS2_1_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110170) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_STS2_2_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120170) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_STS2_3_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130170) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_STS2_0_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100180) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_STS2_1_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110180) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_STS2_2_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120180) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_STS2_3_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130180) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_STS2_0_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100190) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_STS2_1_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110190) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_STS2_2_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120190) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_STS2_3_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130190) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR2_0_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001A0) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR2_1_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101A0) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR2_2_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201A0) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_PRE_PAUSED_NS_CLR2_3_REG  (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301A0) /* 向HostCPU上报的L2级PRE_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR2_0_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001B0) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR2_1_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101B0) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR2_2_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201B0) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_POST_PAUSED_NS_CLR2_3_REG (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301B0) /* 向HostCPU上报的L2级POST_PAUSED中断屏蔽后状态寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR2_0_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001C0) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR2_1_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101C0) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR2_2_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201C0) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_NORMAL_CQ_FULL_NS_CLR2_3_REG     (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301C0) /* 向HostCPU上报的L2级CQ_FULL中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_CLR2_0_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001D0) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_CLR2_1_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101D0) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_CLR2_2_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201D0) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_DEBUG_NS_CLR2_3_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301D0) /* 向HostCPU上报的L2级TASK_DEBUG中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_CLR2_0_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001E0) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_CLR2_1_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101E0) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_CLR2_2_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201E0) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_ERROR_NS_CLR2_3_REG         (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301E0) /* 向HostCPU上报的L2级TASK_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_CLR2_0_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1001F0) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_CLR2_1_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1101F0) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_CLR2_2_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1201F0) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_TASK_TRAP_NS_CLR2_3_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x1301F0) /* 向HostCPU上报的L2级TASK_TRAP中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_CLR2_0_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100200) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_CLR2_1_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110200) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_CLR2_2_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120200) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQE_ERROR_NS_CLR2_3_REG          (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130200) /* 向HostCPU上报的L2级SQE_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR2_0_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100210) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR2_1_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110210) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR2_2_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120210) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SW_STATUS_ERROR_NS_CLR2_3_REG    (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130210) /* 向HostCPU上报的L2级SW_STATUS_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR2_0_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x100220) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR2_1_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x110220) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR2_2_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x120220) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */
#define SOC_STARS_ACSQINT_HOST_REG_STARS_L2_SQ_SEC_ERROR_NS_CLR2_3_REG       (SOC_STARS_ACSQINT_HOST_REG_BASE + 0x130220) /* 向HostCPU上报的L2级SQ_SEC_ERROR中断屏蔽清除寄存器 */

#endif // __STARS_ACSQINT_HOST_REG_REG_OFFSET_H__
