// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_ns_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/10/22 14:39:25 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_NS_REG_REG_OFFSET_H__
#define __STARS_CQINT_NS_REG_REG_OFFSET_H__

/* STARS_CQINT_NS_REG Base address of Module's Register */
#define SOC_STARS_CQINT_NS_REG_BASE                       (0x28000)

/******************************************************************************/
/*                      SOC STARS_CQINT_NS_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_CQINT_NS_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK0_REG             (SOC_STARS_CQINT_NS_REG_BASE + 0x20)   /* 上报TSCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS0_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x24)   /* 上报TSCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS0_REG (SOC_STARS_CQINT_NS_REG_BASE + 0x40)   /* 向TSCPU上报的0~1023个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_MID_NORMAL_CQE_WRITTEN_AFTER_NS_STATUS0_REG    (SOC_STARS_CQINT_NS_REG_BASE + 0x44)   /* 向TSCPU上报的1024~2047个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_0_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x180)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_1_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x184)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_2_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x188)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_3_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x18C)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_4_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x190)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_5_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x194)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_6_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x198)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_7_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x19C)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_8_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x1A0)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_9_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x1A4)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_10_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1A8)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_11_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1AC)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_12_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1B0)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_13_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1B4)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_14_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1B8)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS0_15_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x1BC)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_0_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x280)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_1_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x284)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_2_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x288)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_3_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x28C)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_4_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x290)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_5_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x294)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_6_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x298)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_7_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x29C)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_8_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2A0)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_9_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2A4)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_10_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2A8)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_11_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2AC)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_12_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2B0)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_13_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2B4)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_14_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2B8)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR0_15_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2BC)  /* 向TSCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_MASK1_REG             (SOC_STARS_CQINT_NS_REG_BASE + 0x2020) /* 上报CtrlCPU的L1级Normal中断屏蔽寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L1_NORMAL_CQE_WRITTEN_NS_STATUS1_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x2024) /* 上报CtrlCPU的L1级Normal中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_MID_NORMAL_CQE_WRITTEN_PREVIOUS_NS_STATUS1_REG (SOC_STARS_CQINT_NS_REG_BASE + 0x2040) /* 向CtrlCPU上报的0~1023个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_MID_NORMAL_CQE_WRITTEN_AFTER_NS_STATUS1_REG    (SOC_STARS_CQINT_NS_REG_BASE + 0x2044) /* 向CtrlCPU上报的1024~2047个ACSQ的CQE_WRITTEN中断汇聚的中间级中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_0_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2180) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_1_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2184) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_2_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2188) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_3_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x218C) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_4_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2190) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_5_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2194) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_6_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x2198) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_7_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x219C) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_8_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x21A0) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_9_REG         (SOC_STARS_CQINT_NS_REG_BASE + 0x21A4) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_10_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21A8) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_11_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21AC) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_12_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21B0) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_13_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21B4) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_14_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21B8) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_STATUS1_15_REG        (SOC_STARS_CQINT_NS_REG_BASE + 0x21BC) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽后状态寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_0_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2280) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_1_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2284) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_2_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2288) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_3_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x228C) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_4_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2290) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_5_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2294) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_6_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x2298) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_7_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x229C) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_8_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x22A0) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_9_REG            (SOC_STARS_CQINT_NS_REG_BASE + 0x22A4) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_10_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22A8) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_11_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22AC) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_12_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22B0) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_13_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22B4) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_14_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22B8) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_CLR1_15_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x22BC) /* 向CtrlCPU上报的L2级CQE_WRITTEN中断屏蔽清除寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_0_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6080) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_1_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6084) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_2_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6088) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_3_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x608C) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_4_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6090) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_5_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6094) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_6_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x6098) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_7_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x609C) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_8_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x60A0) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_9_REG           (SOC_STARS_CQINT_NS_REG_BASE + 0x60A4) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_10_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60A8) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_11_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60AC) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_12_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60B0) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_13_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60B4) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_14_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60B8) /* L2级CQE_WRITTEN强制注错寄存器 */
#define SOC_STARS_CQINT_NS_REG_STARS_L2_NORMAL_CQE_WRITTEN_NS_FORCE_15_REG          (SOC_STARS_CQINT_NS_REG_BASE + 0x60BC) /* L2级CQE_WRITTEN强制注错寄存器 */

#endif // __STARS_CQINT_NS_REG_REG_OFFSET_H__
