// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_acsqint_host_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/10/23 09:26:03 Create file
// ******************************************************************************

#ifndef __STARS_ACSQINT_HOST_REG_REG_OFFSET_FIELD_H__
#define __STARS_ACSQINT_HOST_REG_REG_OFFSET_FIELD_H__

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_0_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_0_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_0_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_1_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_1_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_1_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_2_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_2_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_2_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_STS2_3_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_STS2_3_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_STS2_3_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_0_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_0_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_0_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_1_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_1_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_1_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_2_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_2_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_2_OFFSET  0

#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_NORMAL_CLR2_3_OFFSET 2
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_ERROR_CLR2_3_OFFSET  1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_STARS_ACSQ_DEBUG_CLR2_3_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_0_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_0_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_0_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_0_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_1_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_1_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_1_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_1_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_2_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_2_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_2_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_2_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_3_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_MASK2_3_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_MASK2_3_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_MASK2_3_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_MASK2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_0_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_0_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_0_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_0_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_0_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_0_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_0_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_0_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_0_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_1_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_1_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_1_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_1_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_1_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_1_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_1_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_1_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_1_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_2_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_2_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_2_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_2_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_2_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_2_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_2_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_2_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_2_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_3_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_MASK2_3_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_MASK2_3_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_3_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_MASK2_3_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_3_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_MASK2_3_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_3_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_MASK2_3_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_0_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_0_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_0_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_0_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_0_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_1_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_1_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_1_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_1_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_1_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_2_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_2_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_2_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_2_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_2_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_3_LEN        1
#define STARS_ACSQINT_HOST_REG_L1_CQ_FULL_NS_STATUS2_3_OFFSET     2
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_POST_PAUSED_NS_STATUS2_3_OFFSET 1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_3_LEN     1
#define STARS_ACSQINT_HOST_REG_L1_PRE_PAUSED_NS_STATUS2_3_OFFSET  0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_TASK_DEBUG_NS_STATUS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_0_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_0_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_0_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_0_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_0_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_0_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_0_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_0_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_0_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_0_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_1_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_1_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_1_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_1_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_1_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_1_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_1_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_1_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_1_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_1_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_2_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_2_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_2_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_2_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_2_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_2_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_2_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_2_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_2_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_2_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_3_LEN       1
#define STARS_ACSQINT_HOST_REG_L1_SQ_SEC_ERROR_NS_STATUS2_3_OFFSET    4
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_3_LEN    1
#define STARS_ACSQINT_HOST_REG_L1_SW_STATUS_ERROR_NS_STATUS2_3_OFFSET 3
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_3_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_SQE_ERROR_NS_STATUS2_3_OFFSET       2
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_3_LEN          1
#define STARS_ACSQINT_HOST_REG_L1_TASK_TRAP_NS_STATUS2_3_OFFSET       1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_3_LEN         1
#define STARS_ACSQINT_HOST_REG_L1_TASK_ERROR_NS_STATUS2_3_OFFSET      0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_STS2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_PRE_PAUSED_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_POST_PAUSED_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_CQ_FULL_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_DEBUG_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_ERROR_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_TASK_TRAP_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQE_ERROR_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SW_STATUS_ERROR_NS_CLR2_3_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_0_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_0_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_1_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_1_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_2_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_2_OFFSET 0

#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_3_LEN    32
#define STARS_ACSQINT_HOST_REG_L2_SQ_SEC_ERROR_NS_CLR2_3_OFFSET 0

#endif // __STARS_ACSQINT_HOST_REG_REG_OFFSET_FIELD_H__
