# SPDX-License-Identifier: GPL-2.0
obj-m := drv_serdes.o
drv_serdes-objs := src/sdk_hilink_common.o src/sdk_hilink_init.o src/sdk_hilink_cfg.o src/hilink_fw_data_h25.o src/drv_snapshot.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/src
ccflags-y += -DSNAPSHOT_ENABLE -DNOT_SUPPORT_OSNAME
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers

KBUILD_EXTRA_SYMBOLS := \
	$(wildcard $(src)/../bootdot/Module.symvers) \
	$(wildcard $(src)/../hsm_flash/Module.symvers)
