# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_xsmem.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
ccflags-y += -Wno-missing-field-initializers

ifneq ($(NOT_SUPPORT_SP), y)
ccflags-y += -fstack-protector-all
endif

ifeq ($(PRODUCT_SIDE),host)
ascend_xsmem-objs := \
	xsmem_host/xsmem_framework.o \
	xsmem_host/xsmem_ns_adapt.o \
	xsmem_host/xsmem_proc_fs.o \
	xsmem_host/xsmem_prop.o \
	xsmem_host/xsmem_res_idr.o \
	xsmem_host/xsmem_res_dispatch.o \
	xsmem_host/xsmem_algo_vma.o \
	xsmem_host/xsmem_algo_cache_vma.o

ccflags-y += -I$(src)/xsmem_host
ccflags-y += -Wno-implicit-fallthrough
ccflags-y += -DCFG_FEATURE_SUPPORT_VMA
ccflags-y += -DCFG_FEATURE_SUPPORT_CACHE

ifeq ($(filter $(PRODUCT), helper310p),)
ascend_xsmem-objs += xsmem_host/xsmem_modprobe_adapt.o
ccflags-y += -DCFG_FEATURE_EXTERNAL_CDEV
endif
else
ascend_xsmem-objs := \
	xsmem_device/xsmem_framework.o \
	xsmem_device/xsmem_ns_adapt.o \
	xsmem_device/xsmem_proc_fs.o \
	xsmem_device/xsmem_algo_sp.o \
	xsmem_device/xsmem_prop.o \
	xsmem_device/xsmem_res_idr.o \
	xsmem_device/xsmem_res_dispatch.o \
	xsmem_device/xsmem_algo_cache_sp.o \
	xsmem_device/xsmem_algo_vma.o

ccflags-y += -I$(src)/xsmem_device
ccflags-y += -DCFG_FEATURE_SUPPORT_SP
ccflags-y += -DCFG_FEATURE_EXTERNAL_CDEV
ccflags-y += -DCFG_FEATURE_SUPPORT_CACHE

ifeq ($(filter $(HELPER_KERNAL), openeuler),)
ccflags-y += -DCFG_FEATURE_SP_GRP_STANDALONE_VA
endif

ifneq ($(filter $(PRODUCT), ascend910B),)
ccflags-y += -DCFG_FEATURE_VFIO
endif

ifneq ($(filter $(PRODUCT), ascend310rc ascend310Brc helper310p),)
ccflags-y += -DCFG_FEATURE_SOC
endif
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
