# SPDX-License-Identifier: GPL-2.0

obj-m := drv_pcie_hdc_host.o
drv_pcie_hdc_host-objs := \
	hdcdrv_core.o \
	hdcdrv_core_com.o \
	hdcdrv_host.o \
	hdcdrv_mem.o \
	hdcdrv_mem_com.o \
	hdcdrv_epoll.o \
	hdcdrv_sysfs.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -DCFG_FEATURE_SHARE_LOG
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/include/hiss
ccflags-y += -I$(DRIVER_INC)/include/user_config -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/libc_sec/include -I$(src)

ifeq ($(PRODUCT),ascend920esl)
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA
else ifeq ($(PRODUCT),ascend910B)
ccflags-y += -DCFG_FEATURE_SRIOV -DCFG_DISABLE_TSD_NOTIFY
ccflags-y += -DCFG_FEATURE_SIMPLIFY_MODE
else ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_SOC_PLATFORM_CLOUD_HOST
ccflags-y += -DCFG_FEATURE_VFIO
else ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_FEATURE_VFIO
else ifeq ($(PRODUCT),ascend310B)
else
ccflags-y += -DCFG_SOC_PLATFORM_MINIV1 -DCFG_FEATURE_SIMPLIFY_MODE
ccflags-y += -DCFG_FEATURE_PROCESS_NUM_LITE
ifneq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_FEATURE_NOT_SUPPORT_UDA
endif
endif

ifneq ($(filter $(PRODUCT), ascend910 ascend310p),)
drv_pcie_hdc_host-objs += hdcdrv_adapter.o
endif

ifneq ($(filter $(PRODUCT), as31xm1),)
ccflags-y += -DCFG_FEATURE_HDC_REG_MEM -DCFG_SOC_PLATFORM_MDC_V11
ccflags-y += -I$(DRIVER_INC)/dms/include -I$(DRIVER_INC)/dms/config
ccflags-y += -I$(DRIVER_INC)/dms/event -I$(DRIVER_INC)/dms/core
drv_pcie_hdc_host-objs += hdcdrv_status.o
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wall -Werror -Wtrampolines $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef
ccflags-y += -funsigned-char -Wformat=2 -Wstack-usage=2048 -Wcast-align
ccflags-y += -Wextra -Wno-format-nonliteral -Wno-empty-body
