# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_trs_pm_adapt.o
ascend_trs_pm_adapt-objs := trs_device.o trs_device_comm.o trs_device_id.o trs_device_mbox.o \
	trs_device_ts_status.o trs_device_tsfw_shr_mem.o \
	chan/trs_device_chan.o chan/trs_chan_ops_mem.o chan/trs_chan_ops_mbox.o \
	chan/trs_chan_ops_rsv_mem.o chan/trs_chan_ops_irq.o \
	chan/stars_v1/trs_chan_ops.o chan/stars_v1/trs_chan_ops_stars.o chan/stars_v1/trs_chan_ops_db.o \
	core/trs_device_core.o core/trs_core_ops.o core/stars_v1/trs_stars_core_ops.o \
	comm/trs_device_notice.o comm/trs_device_ts_db.o
# tscpu objs removed - trs_get_task_sq/cq_db_cfg only available on mini_v2

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/soc/mini_v3 -I$(src)/chan -I$(src)/chan/stars_v1 -I$(src)/chan/tscpu -I$(src)/core -I$(src)/core/stars_v1 -I$(src)/core/tscpu -I$(src)/comm
ccflags-y += -DCFG_FEATURE_IRQ_BIND -DCFG_FEATURE_TS_ABNORMAL_INFO -DCFG_SOC_PLATFORM_MINIV3
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
