if (${PRODUCT_SIDE} STREQUAL device)
    add_subdirectory(board_config)
    add_subdirectory(cfg_persistent)
    add_subdirectory(chip_config)
else()
    add_subdirectory(soc_platform)
endif()

add_subdirectory(comm_algorithm)
add_subdirectory(dev_identity)
add_subdirectory(runenv_config)
add_subdirectory(soc_resmng)
add_subdirectory(uda)

if (${PRODUCT} STREQUAL helper310p)
    if (NOT ${PRODUCT_SIDE} STREQUAL host)
        add_subdirectory(dev_urd)
    endif()
else ()
    add_subdirectory(dev_urd)
endif()
