/*
 * Copyright     :  Copyright (C) 2022, Huawei Technologies Co. Ltd.
 * File name     :  biu_reg_offset_field.h
 * Project line  :  
 * Department    :  
 * Author        :  x198079
 * Version       :  V110
 * Date          :  Tester
 * Description   :  项目描述信息
 * Others        :  Generated automatically by nManager V5.1 
 * History       :  x198079 2022/03/04 09:31:54 Create file
 */

#ifndef __BIU_REG_OFFSET_FIELD_H__
#define __BIU_REG_OFFSET_FIELD_H__

#define BIU_LMTR1_EN_LEN            1
#define BIU_LMTR1_EN_OFFSET         63
#define BIU_LMTR1_TYPE_LEN          1
#define BIU_LMTR1_TYPE_OFFSET       62
#define BIU_LMTR1_BANDWIDTH_LEN     13
#define BIU_LMTR1_BANDWIDTH_OFFSET  48
#define BIU_LMTR1_SATURATION_LEN    14
#define BIU_LMTR1_SATURATION_OFFSET 32
#define BIU_LMTR0_EN_LEN            1
#define BIU_LMTR0_EN_OFFSET         31
#define BIU_LMTR0_TYPE_LEN          1
#define BIU_LMTR0_TYPE_OFFSET       30
#define BIU_LMTR0_BANDWIDTH_LEN     13
#define BIU_LMTR0_BANDWIDTH_OFFSET  16
#define BIU_LMTR0_SATURATION_LEN    14
#define BIU_LMTR0_SATURATION_OFFSET 0

#define BIU_OTSD3_LVL_LEN               8
#define BIU_OTSD3_LVL_OFFSET            56
#define BIU_OTSD2_LVL_LEN               8
#define BIU_OTSD2_LVL_OFFSET            48
#define BIU_STAT_EN_LEN                 1
#define BIU_STAT_EN_OFFSET              32
#define BIU_MTE_EVEN_DISTRB_EN_N_LEN    1
#define BIU_MTE_EVEN_DISTRB_EN_N_OFFSET 28
#define BIU_CLK_BIU_STAT_EN_MASK_LEN    1
#define BIU_CLK_BIU_STAT_EN_MASK_OFFSET 27
#define BIU_CLK_BIU_BWC_EN_MASK_LEN     1
#define BIU_CLK_BIU_BWC_EN_MASK_OFFSET  26
#define BIU_CLK_BIU_PERF_EN_MASK_LEN    1
#define BIU_CLK_BIU_PERF_EN_MASK_OFFSET 25
#define BIU_CLK_BIU_EN_MASK_LEN         1
#define BIU_CLK_BIU_EN_MASK_OFFSET      24
#define BIU_OTSD0_CFG_LEN               1
#define BIU_OTSD0_CFG_OFFSET            17
#define BIU_OTSD1_CFG_LEN               1
#define BIU_OTSD1_CFG_OFFSET            16
#define BIU_OTSD1_LVL_LEN               8
#define BIU_OTSD1_LVL_OFFSET            8
#define BIU_OTSD0_LVL_LEN               8
#define BIU_OTSD0_LVL_OFFSET            0

#define BIU_DFX_TBL_IDX_MST_LEN       2
#define BIU_DFX_TBL_IDX_MST_OFFSET    48
#define BIU_DFX_TBL_IDX_LEN           8
#define BIU_DFX_TBL_IDX_OFFSET        40
#define BIU_SOFT_PERF_RST_CTRL_LEN    1
#define BIU_SOFT_PERF_RST_CTRL_OFFSET 33
#define BIU_DFX_ERR_ENC_CLR_LEN       1
#define BIU_DFX_ERR_ENC_CLR_OFFSET    32
#define BIU_CFG_ARQOS_LEN             4
#define BIU_CFG_ARQOS_OFFSET          28
#define BIU_CFG_ARREGION_LEN          4
#define BIU_CFG_ARREGION_OFFSET       24
#define BIU_CFG_ARUSER_FNA_LEN        1
#define BIU_CFG_ARUSER_FNA_OFFSET     23
#define BIU_CFG_ARUSER_FA_LEN         1
#define BIU_CFG_ARUSER_FA_OFFSET      22
#define BIU_CFG_ARUSER_SSV_LEN        1
#define BIU_CFG_ARUSER_SSV_OFFSET     21
#define BIU_CFG_ARUSER_SNPATTR_LEN    1
#define BIU_CFG_ARUSER_SNPATTR_OFFSET 20
#define BIU_CFG_ARCACHE_LEN           4
#define BIU_CFG_ARCACHE_OFFSET        16
#define BIU_CFG_AWQOS_LEN             4
#define BIU_CFG_AWQOS_OFFSET          12
#define BIU_CFG_AWREGION_LEN          4
#define BIU_CFG_AWREGION_OFFSET       8
#define BIU_CFG_AWUSER_FNA_LEN        1
#define BIU_CFG_AWUSER_FNA_OFFSET     7
#define BIU_CFG_AWUSER_FA_LEN         1
#define BIU_CFG_AWUSER_FA_OFFSET      6
#define BIU_CFG_AWUSER_SSV_LEN        1
#define BIU_CFG_AWUSER_SSV_OFFSET     5
#define BIU_CFG_AWUSER_SNPATTR_LEN    1
#define BIU_CFG_AWUSER_SNPATTR_OFFSET 4
#define BIU_CFG_AWCACHE_LEN           4
#define BIU_CFG_AWCACHE_OFFSET        0

#define BIU_BIU_WCMD_NUM_LEN    8
#define BIU_BIU_WCMD_NUM_OFFSET 56
#define BIU_BIU_RCMD_NUM_LEN    8
#define BIU_BIU_RCMD_NUM_OFFSET 48
#define BIU_TBL_WCMD_NUM_LEN    8
#define BIU_TBL_WCMD_NUM_OFFSET 40
#define BIU_TBL_RCMD_NUM_LEN    8
#define BIU_TBL_RCMD_NUM_OFFSET 32
#define BIU_STAT_CYCLE_LEN      32
#define BIU_STAT_CYCLE_OFFSET   0

#define BIU_STAT_WCMD_NUM_LEN    32
#define BIU_STAT_WCMD_NUM_OFFSET 32
#define BIU_STAT_RCMD_NUM_LEN    32
#define BIU_STAT_RCMD_NUM_OFFSET 0

#define BIU_STAT_WLAT_RAW_LEN    32
#define BIU_STAT_WLAT_RAW_OFFSET 32
#define BIU_STAT_RLAT_RAW_LEN    32
#define BIU_STAT_RLAT_RAW_OFFSET 0

#define BIU_STAT_FLUX_WR_LEN    32
#define BIU_STAT_FLUX_WR_OFFSET 32
#define BIU_STAT_FLUX_RD_LEN    32
#define BIU_STAT_FLUX_RD_OFFSET 0

#define BIU_SMMU_STREAMID_LEN    16
#define BIU_SMMU_STREAMID_OFFSET 0

#define BIU_L2_PADDR_BASE_LEN    64
#define BIU_L2_PADDR_BASE_OFFSET 0

#define BIU_L2_REMAP_EN_LEN    1
#define BIU_L2_REMAP_EN_OFFSET 63
#define BIU_BIU_L2_SIZE_LEN    4
#define BIU_BIU_L2_SIZE_OFFSET 0

#define BIU_BIU_L2_PAGE_SIZE_LEN    4
#define BIU_BIU_L2_PAGE_SIZE_OFFSET 0

#define BIU_LMTR23_TYPE_LEN         1
#define BIU_LMTR23_TYPE_OFFSET      62
#define BIU_LMTR3_EN_LEN            1
#define BIU_LMTR3_EN_OFFSET         61
#define BIU_LMTR3_BANDWIDTH_LEN     13
#define BIU_LMTR3_BANDWIDTH_OFFSET  48
#define BIU_LMTR3_SATURATION_LEN    14
#define BIU_LMTR3_SATURATION_OFFSET 32
#define BIU_LMTR2_EN_LEN            1
#define BIU_LMTR2_EN_OFFSET         29
#define BIU_LMTR2_BANDWIDTH_LEN     13
#define BIU_LMTR2_BANDWIDTH_OFFSET  16
#define BIU_LMTR2_SATURATION_LEN    14
#define BIU_LMTR2_SATURATION_OFFSET 0

#define BIU_STAT_FLUX_WR_L2_LEN    32
#define BIU_STAT_FLUX_WR_L2_OFFSET 32
#define BIU_STAT_FLUX_RD_L2_LEN    32
#define BIU_STAT_FLUX_RD_L2_OFFSET 0

#define BIU_BIU_STREAM_NS_LEN    1
#define BIU_BIU_STREAM_NS_OFFSET 0

#define BIU_BIU_L2_WRITE_OOB_LEN    1
#define BIU_BIU_L2_WRITE_OOB_OFFSET 1
#define BIU_BIU_L2_READ_OOB_LEN     1
#define BIU_BIU_L2_READ_OOB_OFFSET  0

#define BIU_BIU_L2_WRITE_OOB_MASK_LEN    1
#define BIU_BIU_L2_WRITE_OOB_MASK_OFFSET 1
#define BIU_BIU_L2_READ_OOB_MASK_LEN     1
#define BIU_BIU_L2_READ_OOB_MASK_OFFSET  0

#define BIU_BIU_ERR_ADDR_LEN    25
#define BIU_BIU_ERR_ADDR_OFFSET 0

#define BIU_L2_REMAP_CFG0_LEN    64
#define BIU_L2_REMAP_CFG0_OFFSET 0

#define BIU_L2_REMAP_CFG1_LEN    64
#define BIU_L2_REMAP_CFG1_OFFSET 0

#define BIU_L2_REMAP_CFG2_LEN    64
#define BIU_L2_REMAP_CFG2_OFFSET 0

#define BIU_L2_REMAP_CFG3_LEN    64
#define BIU_L2_REMAP_CFG3_OFFSET 0

#define BIU_L2_REMAP_CFG4_LEN    64
#define BIU_L2_REMAP_CFG4_OFFSET 0

#define BIU_L2_REMAP_CFG5_LEN    64
#define BIU_L2_REMAP_CFG5_OFFSET 0

#define BIU_L2_REMAP_CFG6_LEN    64
#define BIU_L2_REMAP_CFG6_OFFSET 0

#define BIU_L2_REMAP_CFG7_LEN    64
#define BIU_L2_REMAP_CFG7_OFFSET 0

#define BIU_L2_VADDR_BASE_LEN    64
#define BIU_L2_VADDR_BASE_OFFSET 0

#define BIU_SMMU_SUBSTREAMID_LEN    16
#define BIU_SMMU_SUBSTREAMID_OFFSET 0

#define BIU_BIU_INSTR_LEN         1
#define BIU_BIU_INSTR_OFFSET      61
#define BIU_BIU_NON_SECURE_LEN    1
#define BIU_BIU_NON_SECURE_OFFSET 60
#define BIU_BIU_PRIVILEGE_LEN     1
#define BIU_BIU_PRIVILEGE_OFFSET  59

#define BIU_SOC_QOS_SEL_LEN       1
#define BIU_SOC_QOS_SEL_OFFSET    24
#define BIU_PQOS_OTSD2_LVL_LEN    8
#define BIU_PQOS_OTSD2_LVL_OFFSET 16
#define BIU_PQOS_OTSD1_LVL_LEN    8
#define BIU_PQOS_OTSD1_LVL_OFFSET 8
#define BIU_PQOS_OTSD0_LVL_LEN    8
#define BIU_PQOS_OTSD0_LVL_OFFSET 0

#endif // __BIU_REG_OFFSET_FIELD_H__
