// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_sdma_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:45:16 Create file
// ******************************************************************************

#ifndef __STARS_SDMA_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_SDMA_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_SDMA_NS_REG_SP_LEVEL_LEN    3
#define STARS_SDMA_NS_REG_SP_LEVEL_OFFSET 8
#define STARS_SDMA_NS_REG_LP_MODE_LEN     3
#define STARS_SDMA_NS_REG_LP_MODE_OFFSET  0



#define STARS_SDMA_NS_REG_WRR_WEIGHT3_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT3_OFFSET 24
#define STARS_SDMA_NS_REG_WRR_WEIGHT2_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT2_OFFSET 16
#define STARS_SDMA_NS_REG_WRR_WEIGHT1_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT1_OFFSET 8
#define STARS_SDMA_NS_REG_WRR_WEIGHT0_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT0_OFFSET 0

#define STARS_SDMA_NS_REG_WRR_WEIGHT7_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT7_OFFSET 24
#define STARS_SDMA_NS_REG_WRR_WEIGHT6_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT6_OFFSET 16
#define STARS_SDMA_NS_REG_WRR_WEIGHT5_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT5_OFFSET 8
#define STARS_SDMA_NS_REG_WRR_WEIGHT4_LEN    8
#define STARS_SDMA_NS_REG_WRR_WEIGHT4_OFFSET 0

#define STARS_SDMA_NS_REG_SQ_FRIENDLY_JPEGD_LEN    1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_JPEGD_OFFSET 16
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_JPEGE_LEN    1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_JPEGE_OFFSET 15
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_VPC_LEN      1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_VPC_OFFSET   14
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_DSA_LEN      1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_DSA_OFFSET   13
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_SDMA_LEN     1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_SDMA_OFFSET  12
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_HCPU_LEN     1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_HCPU_OFFSET  11
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_AICPU_LEN    1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_AICPU_OFFSET 10
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_VEC_LEN      1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_VEC_OFFSET   9
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_AIC_LEN      1
#define STARS_SDMA_NS_REG_SQ_FRIENDLY_AIC_OFFSET   8

#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_SEL_LEN    5
#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_SEL_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_OST_CNT_LEN    1
#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_OST_CNT_OFFSET 8
#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_STATE_LEN      5
#define STARS_SDMA_NS_REG_DFX_SDMA_BLK_FSM_STATE_OFFSET   0

#define STARS_SDMA_NS_REG_SDMA_REDUNDANT_RSP_LEN    32
#define STARS_SDMA_NS_REG_SDMA_REDUNDANT_RSP_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_CH_FREE_BITMAP_LEN    32
#define STARS_SDMA_NS_REG_SDMA_CH_FREE_BITMAP_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_0_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_0_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_1_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_1_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_2_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_2_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_3_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_3_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_4_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_4_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_5_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_5_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_6_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_6_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_7_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLE_CTRL_NS_7_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_0_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_0_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_1_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_1_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_2_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_2_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_3_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_3_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_4_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_4_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_5_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_5_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_6_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_6_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_7_LEN    32
#define STARS_SDMA_NS_REG_SDMA_DISABLE_CTRL_NS_7_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS0_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS0_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS1_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS1_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS2_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS2_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS3_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS3_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS4_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS4_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS5_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS5_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS6_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS6_NS_OFFSET 0

#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS7_NS_LEN    32
#define STARS_SDMA_NS_REG_SDMA_ENABLED_STATUS7_NS_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_0_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_0_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_1_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_1_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_2_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_2_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_3_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_3_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_4_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_4_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_5_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_5_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_6_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_6_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_7_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_7_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_8_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_8_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_9_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_9_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_10_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_10_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_11_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_11_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_12_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_12_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_13_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_13_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_14_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_14_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_15_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_15_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_16_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_16_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_17_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_17_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_18_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_18_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_19_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_19_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_20_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_20_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_21_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_21_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_22_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_22_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_23_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_23_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_24_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_24_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_25_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_25_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_26_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_26_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_27_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_27_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_28_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_28_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_29_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_29_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_30_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_30_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_31_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS0_31_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_0_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_0_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_1_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_1_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_2_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_2_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_3_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_3_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_4_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_4_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_5_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_5_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_6_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_6_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_7_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_7_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_8_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_8_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_9_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_9_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_10_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_10_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_11_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_11_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_12_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_12_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_13_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_13_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_14_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_14_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_15_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_15_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_16_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_16_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_17_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_17_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_18_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_18_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_19_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_19_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_20_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_20_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_21_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_21_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_22_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_22_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_23_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_23_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_24_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_24_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_25_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_25_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_26_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_26_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_27_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_27_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_28_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_28_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_29_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_29_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_30_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_30_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_31_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS1_31_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_0_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_0_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_1_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_1_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_2_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_2_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_3_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_3_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_4_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_4_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_5_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_5_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_6_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_6_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_7_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_7_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_8_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_8_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_9_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_9_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_10_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_10_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_11_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_11_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_12_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_12_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_13_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_13_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_14_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_14_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_15_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_15_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_16_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_16_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_17_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_17_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_18_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_18_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_19_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_19_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_20_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_20_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_21_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_21_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_22_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_22_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_23_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_23_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_24_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_24_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_25_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_25_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_26_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_26_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_27_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_27_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_28_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_28_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_29_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_29_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_30_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_30_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_31_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS2_31_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_0_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_0_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_1_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_1_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_2_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_2_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_3_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_3_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_4_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_4_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_5_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_5_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_6_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_6_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_7_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_7_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_8_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_8_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_9_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_9_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_10_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_10_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_11_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_11_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_12_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_12_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_13_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_13_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_14_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_14_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_15_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_15_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_16_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_16_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_17_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_17_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_18_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_18_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_19_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_19_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_20_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_20_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_21_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_21_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_22_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_22_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_23_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_23_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_24_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_24_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_25_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_25_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_26_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_26_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_27_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_27_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_28_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_28_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_29_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_29_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_30_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_30_OFFSET 0

#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_31_LEN    32
#define STARS_SDMA_NS_REG_DFX_SDMA_CQE_STATUS3_31_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_DEBUG_MODE_LEN    1
#define STARS_SDMA_NS_REG_FLOAT_DEBUG_MODE_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_EXCEPT_EN_RO_LEN    1
#define STARS_SDMA_NS_REG_FLOAT_EXCEPT_EN_RO_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_EXCEPT_EN_PULSE_LEN    1
#define STARS_SDMA_NS_REG_FLOAT_EXCEPT_EN_PULSE_OFFSET 0

#define STARS_SDMA_NS_REG_IP_ID_LEN      5
#define STARS_SDMA_NS_REG_IP_ID_OFFSET   26
#define STARS_SDMA_NS_REG_RTSQ_ID_LEN    11
#define STARS_SDMA_NS_REG_RTSQ_ID_OFFSET 15

#define STARS_SDMA_NS_REG_TASK_ID_LEN         16
#define STARS_SDMA_NS_REG_TASK_ID_OFFSET      16
#define STARS_SDMA_NS_REG_RT_STREAM_ID_LEN    16
#define STARS_SDMA_NS_REG_RT_STREAM_ID_OFFSET 0

#define STARS_SDMA_NS_REG_ACSQ_ID_LEN    7
#define STARS_SDMA_NS_REG_ACSQ_ID_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_GLOBAL_CNT_PULSE_LEN    32
#define STARS_SDMA_NS_REG_FLOAT_GLOBAL_CNT_PULSE_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_WARN_FIRST_STATUS_PULSE_LEN    5
#define STARS_SDMA_NS_REG_FLOAT_WARN_FIRST_STATUS_PULSE_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_WARN_STATUS_PULSE_LEN    5
#define STARS_SDMA_NS_REG_FLOAT_WARN_STATUS_PULSE_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_GLOBAL_CNT_RO_LEN    32
#define STARS_SDMA_NS_REG_FLOAT_GLOBAL_CNT_RO_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_WARN_FIRST_STATUS_RO_LEN    5
#define STARS_SDMA_NS_REG_FLOAT_WARN_FIRST_STATUS_RO_OFFSET 0

#define STARS_SDMA_NS_REG_FLOAT_WARN_STATUS_RO_LEN    5
#define STARS_SDMA_NS_REG_FLOAT_WARN_STATUS_RO_OFFSET 0

#endif // __STARS_SDMA_NS_REG_REG_OFFSET_FIELD_H__
