// ****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_rtsq_s_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2021/06/02 10:43:51 Create file
// ******************************************************************************

#ifndef __STARS_RTSQ_S_REG_REG_OFFSET_H__
#define __STARS_RTSQ_S_REG_REG_OFFSET_H__

/* STARS_RTSQ_S_REG Base address of Module's Register */
#define SOC_STARS_RTSQ_S_REG_BASE                       (0x4004000)

/******************************************************************************/
/*                      SOC STARS_RTSQ_S_REG Registers' Definitions                            */
/******************************************************************************/

#define SOC_STARS_RTSQ_S_REG_STARS_VFG_SEC_REG                      (SOC_STARS_RTSQ_S_REG_BASE + 0x10)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_0_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x14)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_1_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x18)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_2_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x1C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_3_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x20)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_4_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x24)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_5_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x28)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_6_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x2C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_7_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x30)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_8_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x34)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_9_REG                  (SOC_STARS_RTSQ_S_REG_BASE + 0x38)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_10_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x3C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_11_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x40)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_12_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x44)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_13_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x48)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_14_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x4C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_15_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x50)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_16_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x54)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_17_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x58)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_18_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x5C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_19_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x60)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_20_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x64)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_21_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x68)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_22_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x6C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_23_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x70)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_24_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x74)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_25_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x78)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_26_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x7C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_27_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x80)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_28_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x84)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_29_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x88)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_30_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x8C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_31_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x90)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_32_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x94)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_33_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x98)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_34_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x9C)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_35_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xA0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_36_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xA4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_37_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xA8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_38_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xAC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_39_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xB0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_40_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xB4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_41_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xB8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_42_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xBC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_43_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xC0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_44_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xC4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_45_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xC8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_46_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xCC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_47_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xD0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_48_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xD4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_49_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xD8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_50_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xDC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_51_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xE0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_52_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xE4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_53_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xE8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_54_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xEC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_55_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xF0)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_56_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xF4)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_57_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xF8)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_58_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0xFC)  
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_59_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x100) 
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_60_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x104) 
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_61_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x108) 
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_62_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x10C) 
#define SOC_STARS_RTSQ_S_REG_STARS_SQ_SEC_EN_63_REG                 (SOC_STARS_RTSQ_S_REG_BASE + 0x110) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPBUF_NS_AXPROT_SETTING3_REG   (SOC_STARS_RTSQ_S_REG_BASE + 0x800) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPBUF_S_AXPROT_SETTING3_REG    (SOC_STARS_RTSQ_S_REG_BASE + 0x804) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPBUF_NS_SETTING1_REG          (SOC_STARS_RTSQ_S_REG_BASE + 0x808) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_0_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x900) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_1_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x930) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_2_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x960) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_3_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x990) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_4_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9C0) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_5_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9F0) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_6_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA20) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL0_S_7_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA50) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_0_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x904) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_1_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x934) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_2_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x964) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_3_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x994) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_4_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9C4) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_5_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9F4) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_6_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA24) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL1_S_7_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA54) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_0_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x908) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_1_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x938) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_2_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x968) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_3_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x998) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_4_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9C8) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_5_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0x9F8) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_6_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA28) 
#define SOC_STARS_RTSQ_S_REG_STARS_SWAPIN_CTRL2_S_7_REG             (SOC_STARS_RTSQ_S_REG_BASE + 0xA58) 
#define SOC_STARS_RTSQ_S_REG_STARS_S_SQ_SWAP_BUF_BASE_ADDR_CFG0_REG (SOC_STARS_RTSQ_S_REG_BASE + 0xA00) 
#define SOC_STARS_RTSQ_S_REG_STARS_S_SQ_SWAP_BUF_BASE_ADDR_CFG1_REG (SOC_STARS_RTSQ_S_REG_BASE + 0xA04) 

#endif // __STARS_RTSQ_S_REG_REG_OFFSET_H__
