// ****************************************************************************** 
// Copyright     :  Copyright (C) 2022, Hisilicon Technologies Co. Ltd.
// File name     :  stars_cqint_ns_reg_reg_offset_field.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2020/04/01
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V5.1 
// History       :  xxx 2022/01/14 10:50:31 Create file
// ******************************************************************************

#ifndef __STARS_CQINT_NS_REG_REG_OFFSET_FIELD_H__
#define __STARS_CQINT_NS_REG_REG_OFFSET_FIELD_H__

#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_NS_MASK0_LEN    1
#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_NS_MASK0_OFFSET 0

#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_AFT_NS_STATUS0_LEN    1
#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_AFT_NS_STATUS0_OFFSET 1
#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_PRE_NS_STATUS0_LEN    1
#define STARS_CQINT_NS_REG_L1_CQE_WRITTEN_PRE_NS_STATUS0_OFFSET 0

#define STARS_CQINT_NS_REG_MID_CQE_WRITTEN_PRE_NS_STATUS0_LEN    32
#define STARS_CQINT_NS_REG_MID_CQE_WRITTEN_PRE_NS_STATUS0_OFFSET 0

#define STARS_CQINT_NS_REG_MID_CQE_WRITTEN_AFT_NS_STATUS0_LEN    32
#define STARS_CQINT_NS_REG_MID_CQE_WRITTEN_AFT_NS_STATUS0_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_0_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_0_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_1_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_1_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_2_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_2_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_3_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_3_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_4_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_4_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_5_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_5_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_6_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_6_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_7_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_7_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_8_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_8_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_9_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_9_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_10_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_10_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_11_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_11_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_12_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_12_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_13_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_13_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_14_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_14_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_15_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_15_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_16_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_16_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_17_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_17_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_18_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_18_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_19_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_19_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_20_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_20_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_21_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_21_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_22_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_22_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_23_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_23_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_24_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_24_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_25_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_25_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_26_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_26_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_27_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_27_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_28_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_28_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_29_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_29_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_30_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_30_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_31_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_31_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_32_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_32_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_33_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_33_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_34_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_34_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_35_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_35_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_36_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_36_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_37_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_37_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_38_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_38_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_39_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_39_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_40_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_40_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_41_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_41_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_42_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_42_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_43_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_43_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_44_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_44_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_45_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_45_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_46_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_46_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_47_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_47_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_48_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_48_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_49_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_49_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_50_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_50_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_51_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_51_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_52_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_52_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_53_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_53_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_54_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_54_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_55_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_55_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_56_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_56_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_57_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_57_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_58_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_58_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_59_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_59_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_60_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_60_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_61_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_61_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_62_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_62_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_63_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_STATUS0_63_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_0_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_0_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_1_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_1_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_2_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_2_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_3_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_3_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_4_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_4_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_5_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_5_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_6_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_6_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_7_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_7_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_8_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_8_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_9_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_9_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_10_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_10_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_11_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_11_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_12_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_12_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_13_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_13_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_14_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_14_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_15_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_15_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_16_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_16_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_17_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_17_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_18_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_18_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_19_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_19_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_20_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_20_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_21_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_21_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_22_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_22_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_23_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_23_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_24_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_24_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_25_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_25_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_26_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_26_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_27_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_27_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_28_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_28_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_29_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_29_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_30_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_30_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_31_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_31_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_32_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_32_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_33_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_33_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_34_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_34_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_35_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_35_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_36_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_36_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_37_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_37_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_38_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_38_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_39_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_39_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_40_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_40_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_41_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_41_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_42_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_42_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_43_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_43_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_44_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_44_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_45_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_45_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_46_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_46_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_47_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_47_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_48_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_48_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_49_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_49_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_50_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_50_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_51_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_51_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_52_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_52_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_53_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_53_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_54_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_54_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_55_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_55_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_56_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_56_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_57_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_57_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_58_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_58_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_59_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_59_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_60_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_60_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_61_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_61_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_62_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_62_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_63_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_CLR0_63_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_0_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_0_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_1_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_1_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_2_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_2_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_3_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_3_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_4_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_4_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_5_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_5_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_6_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_6_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_7_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_7_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_8_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_8_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_9_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_9_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_10_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_10_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_11_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_11_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_12_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_12_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_13_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_13_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_14_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_14_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_15_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_15_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_16_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_16_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_17_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_17_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_18_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_18_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_19_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_19_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_20_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_20_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_21_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_21_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_22_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_22_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_23_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_23_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_24_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_24_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_25_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_25_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_26_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_26_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_27_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_27_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_28_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_28_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_29_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_29_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_30_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_30_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_31_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_31_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_32_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_32_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_33_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_33_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_34_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_34_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_35_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_35_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_36_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_36_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_37_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_37_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_38_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_38_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_39_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_39_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_40_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_40_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_41_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_41_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_42_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_42_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_43_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_43_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_44_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_44_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_45_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_45_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_46_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_46_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_47_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_47_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_48_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_48_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_49_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_49_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_50_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_50_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_51_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_51_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_52_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_52_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_53_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_53_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_54_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_54_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_55_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_55_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_56_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_56_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_57_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_57_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_58_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_58_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_59_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_59_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_60_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_60_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_61_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_61_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_62_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_62_OFFSET 0

#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_63_LEN    32
#define STARS_CQINT_NS_REG_L2_CQE_WRITTEN_NS_FORCE_63_OFFSET 0

#endif // __STARS_CQINT_NS_REG_REG_OFFSET_FIELD_H__
