// ******************************************************************************
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co. Ltd.
// File name     :  stars_shim_reg_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1.0
// Date          :  2003/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2
// History       :  xxx 2021/12/04 10:42:26 Create file
// ******************************************************************************

#ifndef __STARS_SHIM_REG_REG_OFFSET_H__
#define __STARS_SHIM_REG_REG_OFFSET_H__

/* STARS_SHIM_REG Base address of Module's Register */
#define STARS_SHIM_REG_BASE                       (0x0)

/******************************************************************************/
/*                      xxx STARS_SHIM_REG Registers' Definitions                            */
/******************************************************************************/

#define STARS_SHIM_REG_SC_AWADDR_EXT_STARS_REG            (STARS_SHIM_REG_BASE + 0x0)   /* STARS写通道高位地址配置寄存器 */
#define STARS_SHIM_REG_SC_ARADDR_EXT_STARS_REG            (STARS_SHIM_REG_BASE + 0x4)   /* STARS读通道高位地址配置寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_0_REG           (STARS_SHIM_REG_BASE + 0x8)   /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_1_REG           (STARS_SHIM_REG_BASE + 0xC)   /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_2_REG           (STARS_SHIM_REG_BASE + 0x10)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_3_REG           (STARS_SHIM_REG_BASE + 0x14)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_4_REG           (STARS_SHIM_REG_BASE + 0x18)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_5_REG           (STARS_SHIM_REG_BASE + 0x1C)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_6_REG           (STARS_SHIM_REG_BASE + 0x20)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_7_REG           (STARS_SHIM_REG_BASE + 0x24)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_8_REG           (STARS_SHIM_REG_BASE + 0x28)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_9_REG           (STARS_SHIM_REG_BASE + 0x2C)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_10_REG          (STARS_SHIM_REG_BASE + 0x30)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_11_REG          (STARS_SHIM_REG_BASE + 0x34)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_12_REG          (STARS_SHIM_REG_BASE + 0x38)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_13_REG          (STARS_SHIM_REG_BASE + 0x3C)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_14_REG          (STARS_SHIM_REG_BASE + 0x40)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_15_REG          (STARS_SHIM_REG_BASE + 0x44)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_SHIM_CTRL_STARS_16_REG          (STARS_SHIM_REG_BASE + 0x48)  /* STARS AXI默认窗信号控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_0_REG  (STARS_SHIM_REG_BASE + 0x4C)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_1_REG  (STARS_SHIM_REG_BASE + 0x50)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_2_REG  (STARS_SHIM_REG_BASE + 0x54)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_3_REG  (STARS_SHIM_REG_BASE + 0x58)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_4_REG  (STARS_SHIM_REG_BASE + 0x5C)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_5_REG  (STARS_SHIM_REG_BASE + 0x60)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_6_REG  (STARS_SHIM_REG_BASE + 0x64)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_7_REG  (STARS_SHIM_REG_BASE + 0x68)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_8_REG  (STARS_SHIM_REG_BASE + 0x6C)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_9_REG  (STARS_SHIM_REG_BASE + 0x70)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_10_REG (STARS_SHIM_REG_BASE + 0x74)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_11_REG (STARS_SHIM_REG_BASE + 0x78)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_12_REG (STARS_SHIM_REG_BASE + 0x7C)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_13_REG (STARS_SHIM_REG_BASE + 0x80)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_14_REG (STARS_SHIM_REG_BASE + 0x84)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_15_REG (STARS_SHIM_REG_BASE + 0x88)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_CACHE_CTRL_STARS_DEFAULT_16_REG (STARS_SHIM_REG_BASE + 0x8C)  /* STARS AXCACHE控制寄存器 */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC00_STARS_REG      (STARS_SHIM_REG_BASE + 0x100) /* SC_ATS_ARADDR_SRC00_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN00_STARS_REG      (STARS_SHIM_REG_BASE + 0x104) /* SC_ATS_ARADDR_LEN00_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES00_STARS_REG      (STARS_SHIM_REG_BASE + 0x108) /* SC_ATS_ARADDR_DES00_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC01_STARS_REG      (STARS_SHIM_REG_BASE + 0x10C) /* SC_ATS_ARADDR_SRC01_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN01_STARS_REG      (STARS_SHIM_REG_BASE + 0x110) /* SC_ATS_ARADDR_LEN01_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES01_STARS_REG      (STARS_SHIM_REG_BASE + 0x114) /* SC_ATS_ARADDR_DES01_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC02_STARS_REG      (STARS_SHIM_REG_BASE + 0x118) /* SC_ATS_ARADDR_SRC02_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN02_STARS_REG      (STARS_SHIM_REG_BASE + 0x11C) /* SC_ATS_ARADDR_LEN02_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES02_STARS_REG      (STARS_SHIM_REG_BASE + 0x120) /* SC_ATS_ARADDR_DES02_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC03_STARS_REG      (STARS_SHIM_REG_BASE + 0x124) /* SC_ATS_ARADDR_SRC03_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN03_STARS_REG      (STARS_SHIM_REG_BASE + 0x128) /* SC_ATS_ARADDR_LEN03_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES03_STARS_REG      (STARS_SHIM_REG_BASE + 0x12C) /* SC_ATS_ARADDR_DES03_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC04_STARS_REG      (STARS_SHIM_REG_BASE + 0x130) /* SC_ATS_ARADDR_SRC04_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN04_STARS_REG      (STARS_SHIM_REG_BASE + 0x134) /* SC_ATS_ARADDR_LEN04_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES04_STARS_REG      (STARS_SHIM_REG_BASE + 0x138) /* SC_ATS_ARADDR_DES04_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC05_STARS_REG      (STARS_SHIM_REG_BASE + 0x13C) /* SC_ATS_ARADDR_SRC05_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN05_STARS_REG      (STARS_SHIM_REG_BASE + 0x140) /* SC_ATS_ARADDR_LEN05_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES05_STARS_REG      (STARS_SHIM_REG_BASE + 0x144) /* SC_ATS_ARADDR_DES05_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC06_STARS_REG      (STARS_SHIM_REG_BASE + 0x148) /* SC_ATS_ARADDR_SRC06_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN06_STARS_REG      (STARS_SHIM_REG_BASE + 0x14C) /* SC_ATS_ARADDR_LEN06_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES06_STARS_REG      (STARS_SHIM_REG_BASE + 0x150) /* SC_ATS_ARADDR_DES06_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC07_STARS_REG      (STARS_SHIM_REG_BASE + 0x154) /* SC_ATS_ARADDR_SRC07_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN07_STARS_REG      (STARS_SHIM_REG_BASE + 0x158) /* SC_ATS_ARADDR_LEN07_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES07_STARS_REG      (STARS_SHIM_REG_BASE + 0x15C) /* SC_ATS_ARADDR_DES07_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC08_STARS_REG      (STARS_SHIM_REG_BASE + 0x160) /* SC_ATS_ARADDR_SRC08_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN08_STARS_REG      (STARS_SHIM_REG_BASE + 0x164) /* SC_ATS_ARADDR_LEN08_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES08_STARS_REG      (STARS_SHIM_REG_BASE + 0x168) /* SC_ATS_ARADDR_DES08_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC09_STARS_REG      (STARS_SHIM_REG_BASE + 0x16C) /* SC_ATS_ARADDR_SRC09_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN09_STARS_REG      (STARS_SHIM_REG_BASE + 0x170) /* SC_ATS_ARADDR_LEN09_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES09_STARS_REG      (STARS_SHIM_REG_BASE + 0x174) /* SC_ATS_ARADDR_DES09_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC10_STARS_REG      (STARS_SHIM_REG_BASE + 0x178) /* SC_ATS_ARADDR_SRC10_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN10_STARS_REG      (STARS_SHIM_REG_BASE + 0x17C) /* SC_ATS_ARADDR_LEN10_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES10_STARS_REG      (STARS_SHIM_REG_BASE + 0x180) /* SC_ATS_ARADDR_DES10_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC11_STARS_REG      (STARS_SHIM_REG_BASE + 0x184) /* SC_ATS_ARADDR_SRC11_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN11_STARS_REG      (STARS_SHIM_REG_BASE + 0x188) /* SC_ATS_ARADDR_LEN11_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES11_STARS_REG      (STARS_SHIM_REG_BASE + 0x18C) /* SC_ATS_ARADDR_DES11_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC12_STARS_REG      (STARS_SHIM_REG_BASE + 0x190) /* SC_ATS_ARADDR_SRC12_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN12_STARS_REG      (STARS_SHIM_REG_BASE + 0x194) /* SC_ATS_ARADDR_LEN12_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES12_STARS_REG      (STARS_SHIM_REG_BASE + 0x198) /* SC_ATS_ARADDR_DES12_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC13_STARS_REG      (STARS_SHIM_REG_BASE + 0x19C) /* SC_ATS_ARADDR_SRC13_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN13_STARS_REG      (STARS_SHIM_REG_BASE + 0x1A0) /* SC_ATS_ARADDR_LEN13_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES13_STARS_REG      (STARS_SHIM_REG_BASE + 0x1A4) /* SC_ATS_ARADDR_DES13_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC14_STARS_REG      (STARS_SHIM_REG_BASE + 0x1A8) /* SC_ATS_ARADDR_SRC14_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN14_STARS_REG      (STARS_SHIM_REG_BASE + 0x1AC) /* SC_ATS_ARADDR_LEN14_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES14_STARS_REG      (STARS_SHIM_REG_BASE + 0x1B0) /* SC_ATS_ARADDR_DES14_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_ARADDR_SRC15_STARS_REG      (STARS_SHIM_REG_BASE + 0x1B4) /* SC_ATS_ARADDR_SRC15_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_LEN15_STARS_REG      (STARS_SHIM_REG_BASE + 0x1B8) /* SC_ATS_ARADDR_LEN15_STARS */
#define STARS_SHIM_REG_SC_ATS_ARADDR_DES15_STARS_REG      (STARS_SHIM_REG_BASE + 0x1BC) /* SC_ATS_ARADDR_DES15_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC00_STARS_REG      (STARS_SHIM_REG_BASE + 0x200) /* SC_ATS_AWADDR_SRC00_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN00_STARS_REG      (STARS_SHIM_REG_BASE + 0x204) /* SC_ATS_AWADDR_LEN00_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES00_STARS_REG      (STARS_SHIM_REG_BASE + 0x208) /* SC_ATS_AWADDR_DES00_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC01_STARS_REG      (STARS_SHIM_REG_BASE + 0x20C) /* SC_ATS_AWADDR_SRC01_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN01_STARS_REG      (STARS_SHIM_REG_BASE + 0x210) /* SC_ATS_AWADDR_LEN01_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES01_STARS_REG      (STARS_SHIM_REG_BASE + 0x214) /* SC_ATS_AWADDR_DES01_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC02_STARS_REG      (STARS_SHIM_REG_BASE + 0x218) /* SC_ATS_AWADDR_SRC02_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN02_STARS_REG      (STARS_SHIM_REG_BASE + 0x21C) /* SC_ATS_AWADDR_LEN02_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES02_STARS_REG      (STARS_SHIM_REG_BASE + 0x220) /* SC_ATS_AWADDR_DES02_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC03_STARS_REG      (STARS_SHIM_REG_BASE + 0x224) /* SC_ATS_AWADDR_SRC03_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN03_STARS_REG      (STARS_SHIM_REG_BASE + 0x228) /* SC_ATS_AWADDR_LEN03_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES03_STARS_REG      (STARS_SHIM_REG_BASE + 0x22C) /* SC_ATS_AWADDR_DES03_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC04_STARS_REG      (STARS_SHIM_REG_BASE + 0x230) /* SC_ATS_AWADDR_SRC04_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN04_STARS_REG      (STARS_SHIM_REG_BASE + 0x234) /* SC_ATS_AWADDR_LEN04_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES04_STARS_REG      (STARS_SHIM_REG_BASE + 0x238) /* SC_ATS_AWADDR_DES04_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC05_STARS_REG      (STARS_SHIM_REG_BASE + 0x23C) /* SC_ATS_AWADDR_SRC05_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN05_STARS_REG      (STARS_SHIM_REG_BASE + 0x240) /* SC_ATS_AWADDR_LEN05_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES05_STARS_REG      (STARS_SHIM_REG_BASE + 0x244) /* SC_ATS_AWADDR_DES05_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC06_STARS_REG      (STARS_SHIM_REG_BASE + 0x248) /* SC_ATS_AWADDR_SRC06_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN06_STARS_REG      (STARS_SHIM_REG_BASE + 0x24C) /* SC_ATS_AWADDR_LEN06_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES06_STARS_REG      (STARS_SHIM_REG_BASE + 0x250) /* SC_ATS_AWADDR_DES06_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC07_STARS_REG      (STARS_SHIM_REG_BASE + 0x254) /* SC_ATS_AWADDR_SRC07_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN07_STARS_REG      (STARS_SHIM_REG_BASE + 0x258) /* SC_ATS_AWADDR_LEN07_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES07_STARS_REG      (STARS_SHIM_REG_BASE + 0x25C) /* SC_ATS_AWADDR_DES07_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC08_STARS_REG      (STARS_SHIM_REG_BASE + 0x260) /* SC_ATS_AWADDR_SRC08_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN08_STARS_REG      (STARS_SHIM_REG_BASE + 0x264) /* SC_ATS_AWADDR_LEN08_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES08_STARS_REG      (STARS_SHIM_REG_BASE + 0x268) /* SC_ATS_AWADDR_DES08_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC09_STARS_REG      (STARS_SHIM_REG_BASE + 0x26C) /* SC_ATS_AWADDR_SRC09_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN09_STARS_REG      (STARS_SHIM_REG_BASE + 0x270) /* SC_ATS_AWADDR_LEN09_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES09_STARS_REG      (STARS_SHIM_REG_BASE + 0x274) /* SC_ATS_AWADDR_DES09_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC10_STARS_REG      (STARS_SHIM_REG_BASE + 0x278) /* SC_ATS_AWADDR_SRC10_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN10_STARS_REG      (STARS_SHIM_REG_BASE + 0x27C) /* SC_ATS_AWADDR_LEN10_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES10_STARS_REG      (STARS_SHIM_REG_BASE + 0x280) /* SC_ATS_AWADDR_DES10_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC11_STARS_REG      (STARS_SHIM_REG_BASE + 0x284) /* SC_ATS_AWADDR_SRC11_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN11_STARS_REG      (STARS_SHIM_REG_BASE + 0x288) /* SC_ATS_AWADDR_LEN11_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES11_STARS_REG      (STARS_SHIM_REG_BASE + 0x28C) /* SC_ATS_AWADDR_DES11_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC12_STARS_REG      (STARS_SHIM_REG_BASE + 0x290) /* SC_ATS_AWADDR_SRC12_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN12_STARS_REG      (STARS_SHIM_REG_BASE + 0x294) /* SC_ATS_AWADDR_LEN12_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES12_STARS_REG      (STARS_SHIM_REG_BASE + 0x298) /* SC_ATS_AWADDR_DES12_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC13_STARS_REG      (STARS_SHIM_REG_BASE + 0x29C) /* SC_ATS_AWADDR_SRC13_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN13_STARS_REG      (STARS_SHIM_REG_BASE + 0x2A0) /* SC_ATS_AWADDR_LEN13_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES13_STARS_REG      (STARS_SHIM_REG_BASE + 0x2A4) /* SC_ATS_AWADDR_DES13_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC14_STARS_REG      (STARS_SHIM_REG_BASE + 0x2A8) /* SC_ATS_AWADDR_SRC14_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN14_STARS_REG      (STARS_SHIM_REG_BASE + 0x2AC) /* SC_ATS_AWADDR_LEN14_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES14_STARS_REG      (STARS_SHIM_REG_BASE + 0x2B0) /* SC_ATS_AWADDR_DES14_STARS 低32bit */
#define STARS_SHIM_REG_SC_ATS_AWADDR_SRC15_STARS_REG      (STARS_SHIM_REG_BASE + 0x2B4) /* SC_ATS_AWADDR_SRC15_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_LEN15_STARS_REG      (STARS_SHIM_REG_BASE + 0x2B8) /* SC_ATS_AWADDR_LEN15_STARS */
#define STARS_SHIM_REG_SC_ATS_AWADDR_DES15_STARS_REG      (STARS_SHIM_REG_BASE + 0x2BC) /* SC_ATS_AWADDR_DES15_STARS 低32bit */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x300) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x320) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x340) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x360) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x380) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3A0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3C0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3E0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x400) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x420) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x440) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x460) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x480) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4A0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4C0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4E0) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_0_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x500) /* AXI协议AWUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x304) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x324) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x344) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x364) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x384) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3A4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3C4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3E4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x404) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x424) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x444) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x464) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x484) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4A4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4C4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4E4) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_1_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x504) /* AXI协议AWUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x308) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x328) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x348) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x368) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x388) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3A8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3C8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3E8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x408) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x428) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x448) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x468) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x488) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4A8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4C8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4E8) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_2_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x508) /* AXI协议AWUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x30C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x32C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x34C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x36C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x38C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3AC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3CC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3EC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x40C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x42C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x44C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x46C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x48C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4AC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4CC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4EC) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_AWUSER_3_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x50C) /* AXI协议AWUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x310) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x330) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x350) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x370) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x390) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3B0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3D0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3F0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x410) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x430) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x450) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x470) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x490) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4B0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4D0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4F0) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_0_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x510) /* AXI协议ARUSER的[31:0]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x314) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x334) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x354) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x374) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x394) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3B4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3D4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3F4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x414) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x434) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x454) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x474) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x494) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4B4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4D4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4F4) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_1_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x514) /* AXI协议ARUSER的[63:32]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x318) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x338) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x358) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x378) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x398) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3B8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3D8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3F8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x418) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x438) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x458) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x478) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x498) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4B8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4D8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4F8) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_2_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x518) /* AXI协议ARUSER的[95:64]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_0_REG            (STARS_SHIM_REG_BASE + 0x31C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_1_REG            (STARS_SHIM_REG_BASE + 0x33C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_2_REG            (STARS_SHIM_REG_BASE + 0x35C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_3_REG            (STARS_SHIM_REG_BASE + 0x37C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_4_REG            (STARS_SHIM_REG_BASE + 0x39C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_5_REG            (STARS_SHIM_REG_BASE + 0x3BC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_6_REG            (STARS_SHIM_REG_BASE + 0x3DC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_7_REG            (STARS_SHIM_REG_BASE + 0x3FC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_8_REG            (STARS_SHIM_REG_BASE + 0x41C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_9_REG            (STARS_SHIM_REG_BASE + 0x43C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_10_REG           (STARS_SHIM_REG_BASE + 0x45C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_11_REG           (STARS_SHIM_REG_BASE + 0x47C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_12_REG           (STARS_SHIM_REG_BASE + 0x49C) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_13_REG           (STARS_SHIM_REG_BASE + 0x4BC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_14_REG           (STARS_SHIM_REG_BASE + 0x4DC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_15_REG           (STARS_SHIM_REG_BASE + 0x4FC) /* AXI协议ARUSER的[103:96]配置寄存器 */
#define STARS_SHIM_REG_SC_ARUSER_3_STARS_16_REG           (STARS_SHIM_REG_BASE + 0x51C) /* AXI协议ARUSER的[103:96]配置寄存器 */

#endif // __STARS_SHIM_REG_REG_OFFSET_H__
