//****************************************************************************** 
// Copyright     :  Copyright (C) 2021, Hisilicon Technologies Co., Ltd.
// File name     :  sysctrl_cfg_reg_offset_field.h
// Author        :  xxx
// Version       :  1.0 
// Date          :  2021-06-02
// Description   :  Define all registers/tables for xxx
// Others        :  Generated automatically by nManager V4.0 
// History       :  xxx 2021-06-02 Create file
//******************************************************************************

#ifndef __SYSCTRL_CFG_REG_OFFSET_FIELD_H__
#define __SYSCTRL_CFG_REG_OFFSET_FIELD_H__

#define SYSCTRL_CFG_PLL_TIME_LEN     25 
#define SYSCTRL_CFG_PLL_TIME_OFFSET  3  
#define SYSCTRL_CFG_PLL_EN_SW_LEN    1  
#define SYSCTRL_CFG_PLL_EN_SW_OFFSET 1  
#define SYSCTRL_CFG_PLL_OVER_LEN     1  
#define SYSCTRL_CFG_PLL_OVER_OFFSET  0  

#define SYSCTRL_CFG_MODECTRL_LEN    3 
#define SYSCTRL_CFG_MODECTRL_OFFSET 0 

#define SYSCTRL_CFG_ALL_SCAN_DISABLE_LEN    1 
#define SYSCTRL_CFG_ALL_SCAN_DISABLE_OFFSET 0 

#define SYSCTRL_CFG_SYS_SOFT_RST_LEN    32 
#define SYSCTRL_CFG_SYS_SOFT_RST_OFFSET 0  

#define SYSCTRL_CFG_WDOG_RESET_CFG_LEN    32 
#define SYSCTRL_CFG_WDOG_RESET_CFG_OFFSET 0  

#define SYSCTRL_CFG_ICG_EN_PROBE_LEN    1 
#define SYSCTRL_CFG_ICG_EN_PROBE_OFFSET 0 

#define SYSCTRL_CFG_ICG_DIS_PROBE_LEN    1 
#define SYSCTRL_CFG_ICG_DIS_PROBE_OFFSET 0 

#define SYSCTRL_CFG_ICG_EN_DJTAG_LEN    1 
#define SYSCTRL_CFG_ICG_EN_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_ICG_DIS_DJTAG_LEN    1 
#define SYSCTRL_CFG_ICG_DIS_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_ICG_EN_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_ICG_EN_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_ICG_DIS_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_ICG_DIS_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_ICG_EN_SYSCNT_LEN    1 
#define SYSCTRL_CFG_ICG_EN_SYSCNT_OFFSET 0 

#define SYSCTRL_CFG_ICG_DIS_SYSCNT_LEN    1 
#define SYSCTRL_CFG_ICG_DIS_SYSCNT_OFFSET 0 

#define SYSCTRL_CFG_SRST_REQ_STATUS_LEN    1 
#define SYSCTRL_CFG_SRST_REQ_STATUS_OFFSET 0 

#define SYSCTRL_CFG_SRST_DREQ_STATUS_LEN    1 
#define SYSCTRL_CFG_SRST_DREQ_STATUS_OFFSET 0 

#define SYSCTRL_CFG_SRST_REQ_DJTAG_LEN    1 
#define SYSCTRL_CFG_SRST_REQ_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_SRST_DREQ_DJTAG_LEN    1 
#define SYSCTRL_CFG_SRST_DREQ_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_SRST_REQ_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_SRST_REQ_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_SRST_DREQ_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_SRST_DREQ_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_SRST_REQ_SYSCNT_LEN    1 
#define SYSCTRL_CFG_SRST_REQ_SYSCNT_OFFSET 0 

#define SYSCTRL_CFG_SRST_DREQ_SYSCNT_LEN    1 
#define SYSCTRL_CFG_SRST_DREQ_SYSCNT_OFFSET 0 

#define SYSCTRL_CFG_FUNC_MBIST_CLK_SEL_LEN    1 
#define SYSCTRL_CFG_FUNC_MBIST_CLK_SEL_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_FUNC_CLK_SEL_LEN    2 
#define SYSCTRL_CFG_DJTAG_FUNC_CLK_SEL_OFFSET 0 

#define SYSCTRL_CFG_SIOE_IO_MIRROR_MODE_LEN    1 
#define SYSCTRL_CFG_SIOE_IO_MIRROR_MODE_OFFSET 0 

#define SYSCTRL_CFG_DBGACK_EN_LEN     1 
#define SYSCTRL_CFG_DBGACK_EN_OFFSET  1 
#define SYSCTRL_CFG_DBGACK_SEL_LEN    1 
#define SYSCTRL_CFG_DBGACK_SEL_OFFSET 0 

#define SYSCTRL_CFG_SYSTEM_COUNTER_MODE_LEN    1 
#define SYSCTRL_CFG_SYSTEM_COUNTER_MODE_OFFSET 0 

#define SYSCTRL_CFG_MBIST_CPUI_ENABLE_LEN    1 
#define SYSCTRL_CFG_MBIST_CPUI_ENABLE_OFFSET 0 

#define SYSCTRL_CFG_MBIST_CPUI_DATAIN_LEN    32 
#define SYSCTRL_CFG_MBIST_CPUI_DATAIN_OFFSET 0  

#define SYSCTRL_CFG_MBIST_CPUI_WRITE_EN_LEN    1 
#define SYSCTRL_CFG_MBIST_CPUI_WRITE_EN_OFFSET 0 

#define SYSCTRL_CFG_MBIST_SMS_FUNC_MBIST_RESET_LEN    1 
#define SYSCTRL_CFG_MBIST_SMS_FUNC_MBIST_RESET_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_LEN    1 
#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_INT_MASK_LEN    1 
#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_INT_MASK_OFFSET 0 

#define SYSCTRL_CFG_XTAL_TIME_LEN     16 
#define SYSCTRL_CFG_XTAL_TIME_OFFSET  3  
#define SYSCTRL_CFG_XTAL_EN_SW_LEN    1  
#define SYSCTRL_CFG_XTAL_EN_SW_OFFSET 1  
#define SYSCTRL_CFG_XTAL_OVER_LEN     1  
#define SYSCTRL_CFG_XTAL_OVER_OFFSET  0  

#define SYSCTRL_CFG_ITCR_LEN    1 
#define SYSCTRL_CFG_ITCR_OFFSET 0 

#define SYSCTRL_CFG_ITIR0_LEN    13 
#define SYSCTRL_CFG_ITIR0_OFFSET 0  

#define SYSCTRL_CFG_ITOR_LEN    11 
#define SYSCTRL_CFG_ITOR_OFFSET 0  

#define SYSCTRL_CFG_CNT_DATA_CFG_LEN    25 
#define SYSCTRL_CFG_CNT_DATA_CFG_OFFSET 0  



#define SYSCTRL_CFG_TEST_LOAD_TIME_LEN    1 
#define SYSCTRL_CFG_TEST_LOAD_TIME_OFFSET 2 
#define SYSCTRL_CFG_TEST_PLL_EN_LEN       1 
#define SYSCTRL_CFG_TEST_PLL_EN_OFFSET    1 
#define SYSCTRL_CFG_TEST_MODE_EN_LEN      1 
#define SYSCTRL_CFG_TEST_MODE_EN_OFFSET   0 

#define SYSCTRL_CFG_IN_MD_TYPE_LEN    1 
#define SYSCTRL_CFG_IN_MD_TYPE_OFFSET 7 
#define SYSCTRL_CFG_IT_MD_CLK_LEN     3 
#define SYSCTRL_CFG_IT_MD_CLK_OFFSET  4 
#define SYSCTRL_CFG_IT_MD_CTRL_LEN    3 
#define SYSCTRL_CFG_IT_MD_CTRL_OFFSET 1 
#define SYSCTRL_CFG_IT_MD_EN_LEN      1 
#define SYSCTRL_CFG_IT_MD_EN_OFFSET   0 

#define SYSCTRL_CFG_IT_MD_STAT_LEN    1 
#define SYSCTRL_CFG_IT_MD_STAT_OFFSET 0 

#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_VALUE_LEN    16 
#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_VALUE_OFFSET 0  

#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_EN_LEN    1 
#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_EN_OFFSET 0 

#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR0_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR1_LEN    32 
#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_EN_LEN    16 
#define SYSCTRL_CFG_BROADCAST_EN_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_CORE_EVENT_LEN    32 
#define SYSCTRL_CFG_BROADCAST_CORE_EVENT_OFFSET 0  



#define SYSCTRL_CFG_PLL_ON_LEN    1 
#define SYSCTRL_CFG_PLL_ON_OFFSET 0 

#define SYSCTRL_CFG_SYS_MODE_LEN    4 
#define SYSCTRL_CFG_SYS_MODE_OFFSET 0 

#define SYSCTRL_CFG_WARM_RST_ACKED_LEN    1 
#define SYSCTRL_CFG_WARM_RST_ACKED_OFFSET 0 

#define SYSCTRL_CFG_ICG_ST_PROBE_LEN    1 
#define SYSCTRL_CFG_ICG_ST_PROBE_OFFSET 0 

#define SYSCTRL_CFG_ICG_ST_DJTAG_LEN    1 
#define SYSCTRL_CFG_ICG_ST_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_ICG_ST_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_ICG_ST_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_ICG_ST_SYSCNT_LEN    1 
#define SYSCTRL_CFG_ICG_ST_SYSCNT_OFFSET 0 

#define SYSCTRL_CFG_SRST_ST_STATUS_LEN    1 
#define SYSCTRL_CFG_SRST_ST_STATUS_OFFSET 0 

#define SYSCTRL_CFG_SRST_ST_DJTAG_LEN    1 
#define SYSCTRL_CFG_SRST_ST_DJTAG_OFFSET 0 

#define SYSCTRL_CFG_SRST_ST_FUNC_MBIST_LEN    1 
#define SYSCTRL_CFG_SRST_ST_FUNC_MBIST_OFFSET 0 

#define SYSCTRL_CFG_SYSCNT_SRST_ST_LEN    1 
#define SYSCTRL_CFG_SYSCNT_SRST_ST_OFFSET 0 

#define SYSCTRL_CFG_MBIST_CPUI_DATAOUT_LEN    32 
#define SYSCTRL_CFG_MBIST_CPUI_DATAOUT_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_TIMEOUT_INT_STATUS_LEN    1 
#define SYSCTRL_CFG_DJTAG_TIMEOUT_INT_STATUS_OFFSET 0 

#define SYSCTRL_CFG_XTAL_ON_LEN    1 
#define SYSCTRL_CFG_XTAL_ON_OFFSET 0 

#define SYSCTRL_CFG_XTAL_PLL_TIMEOUT_LEN    1 
#define SYSCTRL_CFG_XTAL_PLL_TIMEOUT_OFFSET 0 

#define SYSCTRL_CFG_ITIR0_TST_LEN    13 
#define SYSCTRL_CFG_ITIR0_TST_OFFSET 0  

#define SYSCTRL_CFG_ITOR_TST_LEN    11 
#define SYSCTRL_CFG_ITOR_TST_OFFSET 0  

#define SYSCTRL_CFG_CNT_DATA_LEN    25 
#define SYSCTRL_CFG_CNT_DATA_OFFSET 0  

#define SYSCTRL_CFG_BROADCAST_BERROR_LEN     1 
#define SYSCTRL_CFG_BROADCAST_BERROR_OFFSET  8 
#define SYSCTRL_CFG_SYSCNT_CURR_STAT_LEN     4 
#define SYSCTRL_CFG_SYSCNT_CURR_STAT_OFFSET  4 
#define SYSCTRL_CFG_AXI_SYSCNT_WR_ERR_LEN    1 
#define SYSCTRL_CFG_AXI_SYSCNT_WR_ERR_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_SEC_ACC_EN_LEN    1 
#define SYSCTRL_CFG_DJTAG_SEC_ACC_EN_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_MSTR_ADDR_LEN    31 
#define SYSCTRL_CFG_DJTAG_MSTR_ADDR_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_MSTR_DATA_LEN    32 
#define SYSCTRL_CFG_DJTAG_MSTR_DATA_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_MSTR_DISABLE_LEN    1  
#define SYSCTRL_CFG_DJTAG_MSTR_DISABLE_OFFSET 31 
#define SYSCTRL_CFG_DJTAG_NOR_CFG_EN_LEN      1  
#define SYSCTRL_CFG_DJTAG_NOR_CFG_EN_OFFSET   30 
#define SYSCTRL_CFG_DJTAG_MSTR_WR_LEN         1  
#define SYSCTRL_CFG_DJTAG_MSTR_WR_OFFSET      29 
#define SYSCTRL_CFG_DEBUG_MODULE_SEL_LEN      12 
#define SYSCTRL_CFG_DEBUG_MODULE_SEL_OFFSET   16 
#define SYSCTRL_CFG_CHAIN_UNIT_CFG_EN_LEN     16 
#define SYSCTRL_CFG_CHAIN_UNIT_CFG_EN_OFFSET  0  

#define SYSCTRL_CFG_DJTAG_MSTR_START_EN_LEN    1 
#define SYSCTRL_CFG_DJTAG_MSTR_START_EN_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_CPUI_PIPE_EN_LEN          1 
#define SYSCTRL_CFG_DJTAG_CPUI_PIPE_EN_OFFSET       8 
#define SYSCTRL_CFG_DJTAG_MSTR_PIPE_WAIT_NUM_LEN    7 
#define SYSCTRL_CFG_DJTAG_MSTR_PIPE_WAIT_NUM_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_TMOUT_LEN    32 
#define SYSCTRL_CFG_DJTAG_TMOUT_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_SEC_MODE_LEN    1 
#define SYSCTRL_CFG_DJTAG_SEC_MODE_OFFSET 0 

#define SYSCTRL_CFG_AXI_MSTR_SEC_ACC_EN_LEN    1 
#define SYSCTRL_CFG_AXI_MSTR_SEC_ACC_EN_OFFSET 0 

#define SYSCTRL_CFG_AXI_MSTR_CACHE_LEN      4  
#define SYSCTRL_CFG_AXI_MSTR_CACHE_OFFSET   28 
#define SYSCTRL_CFG_AXI_USER_SNPATTR_LEN    1  
#define SYSCTRL_CFG_AXI_USER_SNPATTR_OFFSET 27 
#define SYSCTRL_CFG_AXI_USER_PKG_LEN        1  
#define SYSCTRL_CFG_AXI_USER_PKG_OFFSET     26 
#define SYSCTRL_CFG_AXI_USER_FNA_LEN        1  
#define SYSCTRL_CFG_AXI_USER_FNA_OFFSET     25 
#define SYSCTRL_CFG_AXI_USER_FA_LEN         1  
#define SYSCTRL_CFG_AXI_USER_FA_OFFSET      24 
#define SYSCTRL_CFG_AXI_USER_STRMID_LEN     24 
#define SYSCTRL_CFG_AXI_USER_STRMID_OFFSET  0  

#define SYSCTRL_CFG_AXI_MSTR_WDATA0_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_WDATA0_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_WDATA1_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_WDATA1_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_WDATA2_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_WDATA2_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_WDATA3_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_WDATA3_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_QOS_LEN    4 
#define SYSCTRL_CFG_AXI_MSTR_QOS_OFFSET 4 
#define SYSCTRL_CFG_AXI_MSTR_WR_LEN     1 
#define SYSCTRL_CFG_AXI_MSTR_WR_OFFSET  0 

#define SYSCTRL_CFG_AXI_MSTR_ADDR0_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_ADDR0_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_ADDR1_LEN    32 
#define SYSCTRL_CFG_AXI_MSTR_ADDR1_OFFSET 0  

#define SYSCTRL_CFG_AXI_MSTR_START_EN_LEN    1 
#define SYSCTRL_CFG_AXI_MSTR_START_EN_OFFSET 0 

#define SYSCTRL_CFG_DJTAG_NS_ALLOW_ST_LEN    1 
#define SYSCTRL_CFG_DJTAG_NS_ALLOW_ST_OFFSET 0 

#define SYSCTRL_CFG_LAST_RST_STATUS_LEN    20 
#define SYSCTRL_CFG_LAST_RST_STATUS_OFFSET 0  

#define SYSCTRL_CFG_PAD_JTAG_AUTH_RES_IN_LEN    1 
#define SYSCTRL_CFG_PAD_JTAG_AUTH_RES_IN_OFFSET 2 
#define SYSCTRL_CFG_DFT_DISABLE_LEN             1 
#define SYSCTRL_CFG_DFT_DISABLE_OFFSET          1 
#define SYSCTRL_CFG_DJTAG_DISABLE_LEN           1 
#define SYSCTRL_CFG_DJTAG_DISABLE_OFFSET        0 

#define SYSCTRL_CFG_CFG_VERSION_LEN    32 
#define SYSCTRL_CFG_CFG_VERSION_OFFSET 0  

#define SYSCTRL_CFG_CFG_MAGIC_WORD_LEN    32 
#define SYSCTRL_CFG_CFG_MAGIC_WORD_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG0_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG0_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG1_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG1_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG2_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG2_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG3_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG3_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA0_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA0_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA1_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA1_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA2_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA2_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA3_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA3_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA4_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA4_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA5_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA5_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA6_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA6_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA7_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA7_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA8_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA8_OFFSET 0  

#define SYSCTRL_CFG_DJTAG_RD_DATA9_LEN    32 
#define SYSCTRL_CFG_DJTAG_RD_DATA9_OFFSET 0  

#define SYSCTRL_CFG_RDATA_CHANGED_LEN    10 
#define SYSCTRL_CFG_RDATA_CHANGED_OFFSET 16 
#define SYSCTRL_CFG_DEBUG_BUS_EN_LEN     1  
#define SYSCTRL_CFG_DEBUG_BUS_EN_OFFSET  9  
#define SYSCTRL_CFG_DJTAG_OP_DONE_LEN    1  
#define SYSCTRL_CFG_DJTAG_OP_DONE_OFFSET 8  
#define SYSCTRL_CFG_UNIT_CONFLICT_LEN    8  
#define SYSCTRL_CFG_UNIT_CONFLICT_OFFSET 0  

#define SYSCTRL_CFG_AXI_RD_DATA0_LEN    32 
#define SYSCTRL_CFG_AXI_RD_DATA0_OFFSET 0  

#define SYSCTRL_CFG_AXI_RD_DATA1_LEN    32 
#define SYSCTRL_CFG_AXI_RD_DATA1_OFFSET 0  

#define SYSCTRL_CFG_AXI_RD_DATA2_LEN    32 
#define SYSCTRL_CFG_AXI_RD_DATA2_OFFSET 0  

#define SYSCTRL_CFG_AXI_RD_DATA3_LEN    32 
#define SYSCTRL_CFG_AXI_RD_DATA3_OFFSET 0  

#define SYSCTRL_CFG_AXI_OP_CONFLICT_LEN    1 
#define SYSCTRL_CFG_AXI_OP_CONFLICT_OFFSET 3 
#define SYSCTRL_CFG_AXI_WR_ERROR_LEN       1 
#define SYSCTRL_CFG_AXI_WR_ERROR_OFFSET    2 
#define SYSCTRL_CFG_AXI_RD_ERROR_LEN       1 
#define SYSCTRL_CFG_AXI_RD_ERROR_OFFSET    1 
#define SYSCTRL_CFG_AXI_OP_DONE_LEN        1 
#define SYSCTRL_CFG_AXI_OP_DONE_OFFSET     0 

#define SYSCTRL_CFG_NORESET_0_LEN    32 
#define SYSCTRL_CFG_NORESET_0_OFFSET 0  

#define SYSCTRL_CFG_NORESET_1_LEN    32 
#define SYSCTRL_CFG_NORESET_1_OFFSET 0  

#define SYSCTRL_CFG_NORESET_2_LEN    32 
#define SYSCTRL_CFG_NORESET_2_OFFSET 0  

#define SYSCTRL_CFG_NORESET_3_LEN    32 
#define SYSCTRL_CFG_NORESET_3_OFFSET 0  

#define SYSCTRL_CFG_NORESET_4_LEN    32 
#define SYSCTRL_CFG_NORESET_4_OFFSET 0  

#define SYSCTRL_CFG_NORESET_5_LEN    32 
#define SYSCTRL_CFG_NORESET_5_OFFSET 0  

#define SYSCTRL_CFG_NORESET_6_LEN    32 
#define SYSCTRL_CFG_NORESET_6_OFFSET 0  

#define SYSCTRL_CFG_NORESET_7_LEN    32 
#define SYSCTRL_CFG_NORESET_7_OFFSET 0  

#define SYSCTRL_CFG_NORESET_8_LEN    32 
#define SYSCTRL_CFG_NORESET_8_OFFSET 0  

#define SYSCTRL_CFG_NORESET_9_LEN    32 
#define SYSCTRL_CFG_NORESET_9_OFFSET 0  

#define SYSCTRL_CFG_NORESET_10_LEN    32 
#define SYSCTRL_CFG_NORESET_10_OFFSET 0  

#define SYSCTRL_CFG_NORESET_11_LEN    32 
#define SYSCTRL_CFG_NORESET_11_OFFSET 0  

#define SYSCTRL_CFG_NORESET_12_LEN    32 
#define SYSCTRL_CFG_NORESET_12_OFFSET 0  

#define SYSCTRL_CFG_NORESET_13_LEN    32 
#define SYSCTRL_CFG_NORESET_13_OFFSET 0  

#define SYSCTRL_CFG_NORESET_14_LEN    32 
#define SYSCTRL_CFG_NORESET_14_OFFSET 0  

#define SYSCTRL_CFG_NORESET_15_LEN    32 
#define SYSCTRL_CFG_NORESET_15_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_LOCK_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_LOCK_OFFSET 0  

#define SYSCTRL_CFG_SYSCTRL_UNLOCK_LEN    32 
#define SYSCTRL_CFG_SYSCTRL_UNLOCK_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED0_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED0_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED1_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED1_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED2_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED2_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED3_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED3_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED4_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED4_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED5_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED5_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED6_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED6_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED7_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED7_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED8_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED8_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED9_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED9_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED10_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED10_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED11_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED11_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED12_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED12_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED13_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED13_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED14_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED14_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED15_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED15_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED16_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED16_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED17_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED17_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED18_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED18_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED19_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED19_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED20_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED20_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED21_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED21_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED22_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED22_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED23_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED23_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED24_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED24_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED25_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED25_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED26_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED26_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED27_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED27_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED28_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED28_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED29_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED29_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED30_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED30_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED31_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED31_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED32_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED32_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED33_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED33_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED34_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED34_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED35_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED35_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED36_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED36_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED37_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED37_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED38_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED38_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED39_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED39_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED40_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED40_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED41_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED41_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED42_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED42_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED43_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED43_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED44_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED44_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED45_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED45_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED46_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED46_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED47_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED47_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED48_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED48_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED49_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED49_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED50_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED50_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED51_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED51_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED52_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED52_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED53_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED53_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED54_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED54_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED55_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED55_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED56_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED56_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED57_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED57_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED58_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED58_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED59_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED59_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED60_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED60_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED61_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED61_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED62_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED62_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED63_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED63_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED64_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED64_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED65_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED65_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED66_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED66_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED67_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED67_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED68_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED68_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED69_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED69_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED70_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED70_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED71_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED71_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED72_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED72_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED73_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED73_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED74_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED74_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED75_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED75_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED76_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED76_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED77_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED77_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED78_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED78_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED79_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED79_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED80_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED80_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED81_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED81_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED82_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED82_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED83_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED83_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED84_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED84_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED85_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED85_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED86_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED86_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED87_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED87_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED88_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED88_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED89_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED89_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED90_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED90_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED91_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED91_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED92_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED92_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED93_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED93_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED94_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED94_OFFSET 0  

#define SYSCTRL_CFG_SW_RESERVED95_LEN    32 
#define SYSCTRL_CFG_SW_RESERVED95_OFFSET 0  

#define SYSCTRL_CFG_ECO_RSV0_LEN    32 
#define SYSCTRL_CFG_ECO_RSV0_OFFSET 0  

#define SYSCTRL_CFG_ECO_RSV1_LEN    32 
#define SYSCTRL_CFG_ECO_RSV1_OFFSET 0  

#define SYSCTRL_CFG_ECO_RSV2_LEN    32 
#define SYSCTRL_CFG_ECO_RSV2_OFFSET 0  

#define SYSCTRL_CFG_ECO_RSV3_LEN    32 
#define SYSCTRL_CFG_ECO_RSV3_OFFSET 0  

#define SYSCTRL_CFG_PROTOTYPE_CLK_LEN    32 
#define SYSCTRL_CFG_PROTOTYPE_CLK_OFFSET 0  

#define SYSCTRL_CFG_PROTOTYPE_RST_N_LEN    32 
#define SYSCTRL_CFG_PROTOTYPE_RST_N_OFFSET 0  

#define SYSCTRL_CFG_MONITOR_TEST0_LEN    32 
#define SYSCTRL_CFG_MONITOR_TEST0_OFFSET 0  

#define SYSCTRL_CFG_MONITOR_TEST1_LEN    32 
#define SYSCTRL_CFG_MONITOR_TEST1_OFFSET 0  

#define SYSCTRL_CFG_SPECIAL_CODE_LEN    12 
#define SYSCTRL_CFG_SPECIAL_CODE_OFFSET 20 
#define SYSCTRL_CFG_CHIP_NAME_LEN       16 
#define SYSCTRL_CFG_CHIP_NAME_OFFSET    4  
#define SYSCTRL_CFG_CHIP_VERSION_LEN    4  
#define SYSCTRL_CFG_CHIP_VERSION_OFFSET 0  

#define SYSCTRL_CFG_VER_NUM_LEN    32 
#define SYSCTRL_CFG_VER_NUM_OFFSET 0  

#endif // __SYSCTRL_CFG_REG_OFFSET_FIELD_H__
