/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2012-2018. All rights reserved.
 * Automatically generated C config: don't edit
 */

#ifndef AUTO_CONF_H
#define AUTO_CONF_H

/*
 * General Setup
 */
#define CONFIG_HI_CHIP_TYPE 0x3000A100
#ifndef __LITEOS__
#define CONFIG_SMP 1
#endif

/*
 * media audio config
 */

#define CONFIG_AUDIO_V200_SUPPORT_FPGA 1
#define CONFIG_OT_AUDIO_SUPPORT 1
#define CONFIG_OT_ACODEC_SUPPORT 1
#define CONFIG_OT_ACODEC_VERSION "RemixV100"
#define CONFIG_OT_ACODEC_MAX_GAIN 56
#define CONFIG_OT_ACODEC_MIN_GAIN 0
#define CONFIG_OT_ACODEC_GAIN_STEP 3
#define CONFIG_OT_ACODEC_FAST_POWER_SUPPORT 1
#define CONFIG_OT_DOWNVQE_SUPPORT 1
#define CONFIG_OT_TALKVQE_SUPPORT 1
#define CONFIG_OT_RECORDVQE_SUPPORT 1
#define CONFIG_OT_TALKVQEV2_SUPPORT 1
#define CONFIG_OT_TALKVQEV2_WNR_SUPPORT 1
#define CONFIG_OT_AUDIO_STATIC_REGISTER_SUPPORT 1

#define CONFIG_AUDIO_V200_SUPPORT 1
#define CONFIG_OT_PLATFORM_V8 1
#define CONFIG_AUDIO_FROM_H8_TO_H7 1

/*
 * media vi config
 */
#define CONFIG_HI_VI_SUPPORT 1
#define CONFIG_HI_VI_MIPI 1
#define CONFIG_HI_VI_LDCV1_SUPPORT 1
#define CONFIG_HI_VI_LDCV2_SUPPORT 1
#define CONFIG_HI_VI_SENDYUV_SUPPORT 1
#define CONFIG_HI_VI_USERPIC_SUPPORT 1
#define CONFIG_HI_VI_COVEREX_OVERLAYEX_SUPPORT 1
#define CONFIG_HI_VI_LUMA_SUPPORT 1
#define CONFIG_HI_VI_FPN_SUPPORT 1
#define CONFIG_HI_VI_SRC_SUPPORT 1
#define CONFIG_HI_VI_EXTCHN_SUPPORT 1
#define CONFIG_HI_SNAP_SUPPORT 1
#define CONFIG_HI_PIPE_RECEIVER 1

/*
 * media isp config
 */
#define CONFIG_HI_ISP_SUPPORT 1
#define CONFIG_HI_ISP_CR_SUPPORT 1
#define CONFIG_HI_ISP_PREGAMMA_SUPPORT 1
#define CONFIG_HI_ISP_GCAC_SUPPORT 1
#define CONFIG_HI_ISP_CA_SUPPORT 1
#define CONFIG_HI_ISP_EDGEMARK_SUPPORT 1
#define CONFIG_HI_ISP_HLC_SUPPORT 1
#define CONFIG_HI_ISP_SPECAWB_SUPPORT 1
#define CONFIG_HI_ISP_PQ_FOR_AI_SUPPORT 1
#define CONFIG_HI_ISP_DPC_STATIC_TABLE_SUPPORT 1

/*
 * media dis config
 */
#define CONFIG_HI_DIS_SUPPORT 1
#define HI_SUBMIT_GME_TO_VGS 1
// gyro
#define CONFIG_HI_MOTIONFUSION_SUPPORT 1

/*
 * media vpss config
 */
#define CONFIG_HI_VPSS_SUPPORT 1
#define CONFIG_HI_VPSS_3DNR_SUPPORT 1
#define CONFIG_HI_VPSS_LUMA_STAT_SUPPORT 0
#define CONFIG_HI_VPSS_COVER_SUPPORT 1
#ifdef CAMERA_MDC130
    #define CONFIG_HI_VPSS_MOSAIC_SUPPORT 0
#else
    #define CONFIG_HI_VPSS_MOSAIC_SUPPORT 1
#endif
#define CONFIG_HI_VPSS_BUF_SHARE_SUPPORT 0
#define CONFIG_HI_VPSS_SPREAD_SUPPORT 0
#define CONFIG_HI_VPSS_AUTO_SUPPORT 1
/*
 * media avs config
 */

/*
 * media gdc config
 */
#define CONFIG_HI_GDC_SUPPORT 1
#define CONFIG_HI_GDC_LOWDELAY_SUPPORT 1
#define CONFIG_HI_GDC_FISHEYE_SUPPORT 1
#define CONFIG_HI_GDC_FISHEYE_LMF_SUPPORT 1

/*
 * media vgs config
*/

#define CONFIG_HI_VGS_SUPPORT 1
#define CONFIG_HI_VGS_LUMA_STAT_SUPPORT 1

/*
 * media chnl config
 */
#define CONFIG_HI_CHNL_SUPPORT 1

/*
 * media venc config
 */
#define CONFIG_HI_VENC_SUPPORT 1

/*
 * media vdec config
 */
#define CONFIG_HI_VDEC_SUPPORT 1
#define CONFIG_VDEC_IP "VDEC_IP_VDH"
#define CONFIG_HI_JPEGD_SUPPORT 1
#define CONFIG_VDEC_ROTATION_SUPPORT 1
#define CONFIG_VDEC_USERPIC_SUPPORT 1

/*
 * media vo config
 */
#define CONFIG_HI_VO_SUPPORT 1

#define CONFIG_OT_VO_SUPPORT 1
#define CONFIG_OT_VO_HD 1
#define CONFIG_OT_VO_VPSS_AUTO 1
#define CONFIG_OT_VO_LUMA 1
#define CONFIG_OT_VO_VIRTDEV_SUPPORT 1
#define CONFIG_OT_VO_VGS 1
#define CONFIG_OT_VO_GRAPH 1
#define CONFIG_OT_VO_BATCH 1
#define CONFIG_OT_VO_CVBS 1
#define CONFIG_OT_VO_BT1120 1
#define CONFIG_OT_VO_HDMI 1
#define CONFIG_OT_VO_DEV_BYPASS 1
#define CONFIG_OT_VO_EXPORT_FUNCTION 1
#define CONFIG_OT_VO_FB_SEPARATE 1
#define CONFIG_OT_VO_PROC_SHOW_SUPPORT 1
/*
 * media hdmi config
 */
#define CONFIG_OT_HDMI_SUPPORT 1

/*
 * media vga config
 */
#define CONFIG_OT_VO_VGA 1

/*
 * media region config
*/

#define CONFIG_HI_REGION_SUPPORT 0
#define CONFIG_HI_RGN_VGS_QUICKCOPY_SUPPORT 0

/*
 * media hdr config
 */

/*
 * media mcf config

#define CONFIG_HI_MONO_COLOR_FUSION_SUPPORT 1
*/

/*
 * Device Driver Setup
 */

/*
 * drv config
 */
#define CONFIG_DRV 1
#define CONFIG_EXTDRV 1
#define CONFIG_INTERDRV 1
#define CONFIG_CIPHER 1
#define CONFIG_HIUSER 1
#define CONFIG_MIPI_TX 1
#define CONFIG_MIPI_RX 1
#define CONFIG_HI_IR 1
#define CONFIG_HI_WDG 1
#define CONFIG_HI_SYSCFG 1
#define CONFIG_HI_LSADC 1
/*
 * Component Setup
 */

/*
 * Component hifb Config

#define CONFIG_HI_HIFB_SUPPORT 1
*/

/*
 * Component svp Config
 */
#define CONFIG_HI_SVP_DPU_RECT 1
#define CONFIG_HI_SVP_DPU_MATCH 1

/*
 * Component pciv Config
 */
#define CONFIG_HI_PCIV_SUPPORT 1
#define CONFIG_HI_PROC_SHOW_SUPPORT 1

// 不加VENC会少一个SEI
#ifdef USE_DVPP_FWK
#define CONFIG_HI_HDR_SUPPORT 1
#endif
#endif
