obj-m := ascend_virtmng_resmgr.o
ascend_virtmng_resmgr-objs := vmng_resource_mgr.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/virtmng -I$(src)
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers


KBUILD_EXTRA_SYMBOLS := $(src)/../davinci_intf/Module.symvers \
	$(src)/../virtmng/Module.symvers