# SPDX-License-Identifier: GPL-2.0

obj-m :=

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifeq ($(PRODUCT_SIDE),host)
obj-m += drv_devmng_host.o
ifneq ($(filter $(PRODUCT),ascend910 ascend310p),)
obj-m += drv_vdevmng.o
endif

# Match the source Makefile's product-specific host header visibility so
# shared sources resolve against the same devmng headers as before migration.
ccflags-y += -I$(src)/drv_devmng/drv_devmng_inc
ccflags-y += -I$(src)/drv_devmng/drv_devmng_vm
ccflags-y += -I$(src)/event/host -I$(src)/time/host
ccflags-y += -I$(DRIVER_INC)/tsdrv_host -I$(DRIVER_INC)/tsdrv_host/ts_drv_common
ccflags-y += -I$(DRIVER_INC)/soft_fault -I$(DRIVER_INC)/virtmng
ccflags-y += -DCFG_HOST_ENV -DCFG_FEATURE_DEV_TOPOLOGY
ccflags-y += -DCFG_FEATURE_SHARE_LOG -DCFG_SURPPORT_PCIE_HOST_DEVICE_COMM
ccflags-y += -DCFG_FEATURE_HOTRESET -DCFG_FEATURE_DMS_PRODUCT_HOST

ifneq ($(filter $(PRODUCT),ascend310 ascend310p ascend910 ascend910B ascend310B),)
ccflags-y += -DCFG_FEATURE_HEART_BEAT -DCFG_FEATURE_HEALTH_ERR_CODE
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc ascend910B as31xm1),)
ccflags-y += -DCFG_FEATURE_NEW_EVENT_CODE
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc ascend910B),)
ccflags-y += -DCFG_FEATURE_ERRORCODE_ON_NEW_CHIPS -DCFG_TRS_HB_REFACTOR_FEATURE
endif
ifneq ($(filter $(PRODUCT),ascend910 ascend310 ascend310p ascend310B ascend310Besl ascend310Bemu),)
ccflags-y += -DCFG_FEATURE_TOPOLOGY_BY_SMP
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl),)
ccflags-y += -DCFG_FEATURE_PG -DCFG_FEATURE_VFG
ccflags-y += -DCFG_FEATURE_SRIOV -DCFG_FEATURE_TOPOLOGY_BY_HCCS_LINK_STATUS
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Brc ascend310Brcesl as31xm1),)
ccflags-y += -DCFG_FEATURE_PG
ifeq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif
endif
ifeq ($(PRODUCT),ascend310Besl)
ccflags-y += -DCFG_FEATURE_HEALTH_ERR_CODE
endif
ifneq ($(filter $(PRODUCT),ascend310rc helper310p ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_DEVICE_CONTAINER
endif
ifneq ($(filter $(PRODUCT),ascend920esl ascend310Besl ascend310Brcesl),)
ccflags-y += -DCFG_ENV_ESL
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
ccflags-y += -DCFG_FEATURE_UNSUPPORT_FAULT_MANAGE
endif

drv_devmng_host-objs := \
	core/dms_init.o \
	core/dms_probe.o \
	core/dms_sysfs.o \
	core/dms_timer.o \
	event/host/dms_event_host.o \
	event/dms_adapt.o \
	power/dms_power.o \
	power/dms_hotreset.o \
	product/dms_product.o \
	product/dms_product_host.o \
	status/dms_basic_info.o \
	status/dms_chip_info.o \
	status/dms_dev_topology.o \
	status/dms_vdev.o

ifneq ($(filter $(PRODUCT),ascend310 ascend310B ascend310Besl ascend310Bemu ascend310p ascend910 ascend910B ascend920esl ascend920emu),)
drv_devmng_host-objs += time/host/dms_time_host.o
ccflags-y += -DCFG_FEATURE_TIMESYNC
endif

ifneq ($(filter $(PRODUCT),ascend910B),)
drv_devmng_host-objs += status/dms_host_aicpu_info.o
endif
ifneq ($(filter $(PRODUCT),ascend310p ascend310B ascend910 ascend910B),)
drv_devmng_host-objs += status/dms_osc_freq.o
ccflags-y += -DCFG_FEATURE_OSC_FREQ
endif

ifneq ($(filter $(PRODUCT),ascend910 ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_SOC_PLATFORM_CLOUD_HOST
ccflags-y += -DCFG_FEATURE_VASCEND -DCFG_FEATURE_VFIO
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_host/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_common
ifneq ($(filter $(PRODUCT),ascend910B),)
ccflags-y += -DCFG_FEATURE_HOST_AICPU -DCFG_CHIP_INFO_FROM_DEVINFO
endif
ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_FEATURE_NOTIFY_REBOOT
ccflags-y += -DCFG_FEATURE_SMP_VDEV_NOT_SUPPORT -DCFG_FEATURE_DDR
ccflags-y += -DCFG_CHIP_INFO_FROM_VMNG -DCFG_FEATURE_OLD_ALL_DEVICE_RESET_FLAG
ccflags-y += -DCFG_FEATURE_DMS_SVM_DEV
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2 -DCFG_FEATURE_CHIP_DIE
ccflags-y += -DCFG_FEATURE_PCIE_BBOX_ADDR -DCFG_FEATURE_VF_USE_DEVID
ccflags-y += -DCFG_FEATURE_VDEV_MEMORY_FROM_DEVMNG_H2D -DCFG_FEATURE_BIND_TGID
endif
drv_devmng_host-objs += \
	drv_devmng/drv_devmng_host/ascend910/devdrv_pcie.o \
	drv_devmng/drv_devmng_host/ascend910/hvdevmng_init.o \
	drv_devmng/drv_devmng_host/ascend910/hvdevmng_cmd_proc.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_pid_map.o \
	drv_devmng/drv_devmng_common/dev_mnt_vdevice.o
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
drv_devmng_host-objs += drv_devmng/drv_devmng_host/ascend910/devdrv_chip_dev_map.o
endif
drv_devmng_host-objs += \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_msg.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_pm.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_ipc_msg.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_driver_pm.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_rand.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_black_box.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_container.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_device_online.o \
	drv_devmng/drv_devmng_host/ascend910/drv_log.o \
	drv_devmng/drv_devmng_host/ascend910/tsdrv_status.o
else ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Bemu ascend610 ascend610Lite ascend610Liteesl bs9sx1a ascend310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_DDR
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend610
ccflags-y += -I$(src)/drv_devmng/drv_devmng_host/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_common
ifeq ($(PRODUCT),bs9sx1a)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_BS9SX1A
endif
ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_FEATURE_VASCEND -DCFG_FEATURE_VFIO -DCFG_FEATURE_VFG
ccflags-y += -DCFG_FEATURE_NOTIFY_REBOOT -DCFG_FEATURE_DEVICE_SHARE
ccflags-y += -DCFG_CHIP_INFO_FROM_VMNG -DCFG_FEATURE_OLD_ALL_DEVICE_RESET_FLAG
ccflags-y += -DCFG_FEATURE_DMS_SVM_DEV
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Bemu),)
ccflags-y += -DCFG_FEATURE_PCIE_BBOX_ADDR
endif
drv_devmng_host-objs += \
	drv_devmng/drv_devmng_host/ascend910/devdrv_pcie.o \
	drv_devmng/drv_devmng_host/ascend910/hvdevmng_init.o \
	drv_devmng/drv_devmng_host/ascend910/hvdevmng_cmd_proc.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_pid_map.o \
	drv_devmng/drv_devmng_common/dev_mnt_vdevice.o
ifeq ($(PRODUCT),ascend310p)
drv_devmng_host-objs += drv_devmng/drv_devmng_host/ascend910/devdrv_manager_dev_share.o
endif
drv_devmng_host-objs += \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_msg.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_pm.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_ipc_msg.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_driver_pm.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_rand.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_black_box.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_manager_container.o \
	drv_devmng/drv_devmng_host/ascend910/devdrv_device_online.o \
	drv_devmng/drv_devmng_host/ascend910/drv_log.o \
	drv_devmng/drv_devmng_host/ascend910/tsdrv_status.o
else
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend310
ccflags-y += -I$(src)/drv_devmng/drv_devmng_host/ascend310
ifeq ($(PRODUCT),ascend310)
ccflags-y += -DCFG_FEATURE_OLD_ALL_DEVICE_RESET_FLAG
endif
drv_devmng_host-objs += \
	drv_devmng/drv_devmng_host/ascend310/devdrv_host_drvops.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_nsm.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager_container_noplugin.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager_dev_share.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager_msg.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_pm.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_ipc_msg.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_driver_pm.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager_rand.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_black_box.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_manager_container.o \
	drv_devmng/drv_devmng_host/ascend310/devdrv_device_online.o \
	drv_devmng/drv_devmng_host/ascend310/drv_log.o \
	drv_devmng/drv_devmng_host/ascend310/tsdrv_status.o
endif

drv_vdevmng-objs := \
	drv_devmng/drv_devmng_vm/vdevmng_init.o \
	drv_devmng/drv_devmng_vm/vdevmng_agent.o \
	drv_devmng/drv_devmng_vm/vdevmng_cmd_proc.o \
	drv_devmng/drv_devmng_vm/drv_log.o
else
obj-m += drv_devmng.o

cloud_products := ascend910 ascend910B ascend920esl ascend920emu
cloud_v2_products := ascend910B ascend920esl ascend920emu
mini_products := ascend310 ascend310rc
mini_v2_products := ascend310p helper310p
mini_v3_products := ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu as31xm1
mdc_products := ascend610 bs9sx1a ascend610Lite ascend610Liteesl
ep_mode_products := ascend310 ascend310rc ascend310p ascend910 ascend910B ascend920esl ascend920emu ascend310B ascend310Besl ascend310Bemu
rc_mode_products := helper310p ascend310Brc ascend310Brcesl ascend310Brcemu as31xm1 ascend610 bs9sx1a ascend610Lite ascend610Liteesl
mini_910_products := $(mini_v2_products) $(mini_v3_products)
ascend910_prefix_products := $(mini_910_products) $(mdc_products) $(cloud_products)

device_devmng_prefix :=
ifneq ($(filter $(PRODUCT),$(mini_products)),)
device_devmng_prefix := drv_devmng/drv_devmng_device/ascend310
else ifneq ($(filter $(PRODUCT),$(ascend910_prefix_products)),)
device_devmng_prefix := drv_devmng/drv_devmng_device/ascend910
endif

ccflags-y += -I$(src)/ipc -I$(src)/lpm -I$(src)/mem -I$(src)/status
ccflags-y += -I$(src)/event -I$(src)/event/device -I$(src)/devid -I$(src)/custom
ccflags-y += -I$(src)/product -I$(src)/xpc -I$(src)/time -I$(src)/time/device
ccflags-y += -I$(src)/power -I$(src)/ts -I$(src)/hccs
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device -I$(src)/drv_devmng/drv_devmng_inc
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend_common/ipc
ccflags-y += -I$(src)/drv_devmng/drv_devmng_common
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox/device
ccflags-y += -I$(DRIVER_INC)/../kernel-tools/spmi_hisi/include
ifneq ($(device_devmng_prefix),)
ccflags-y += -I$(src)/$(device_devmng_prefix)
endif
ccflags-y += -DCFG_FEATURE_IPC_NOTIFY

ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a ascend610Lite ascend610Liteesl as31xm1 ascend310Brc helper310p),)
else
ccflags-y += -DCFG_SURPPORT_PCIE_HOST_DEVICE_COMM
endif

ifneq ($(filter $(PRODUCT),$(cloud_products)),)
ccflags-y += -DCFG_FEATURE_IMU_ENABLE -DCFG_SOC_PLATFORM_CLOUD -DCFG_FEATURE_VFIO
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910/cloud
ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_FEATURE_PSS_SIGN -DCFG_FEATURE_DDR
endif
ifneq ($(filter $(PRODUCT),$(cloud_v2_products)),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2 -DCFG_FEATURE_IPC_FORMAT_V2_CRC
ccflags-y += -DCFG_FEATURE_CHIP_DIE -DCFG_FEATURE_HISS -DCFG_FEATURE_HW_INFO_FROM_BIOS
ccflags-y += -DCFG_FEATURE_SRIOV -DCFG_TRS_REFACTOR_FEATURE
ccflags-y += -DCFG_FEATURE_CHIP_OFFSET_OUTSIDE_2G -DCFG_FEATURE_VF_USE_DEVID
endif
else ifneq ($(filter $(PRODUCT),$(mini_products)),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_DDR
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend310
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend310
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend310/mini
else ifneq ($(filter $(PRODUCT),$(mini_910_products)),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_DDR
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_FEATURE_MULTI_TS
ccflags-y += -I$(DRIVER_INC)/include/media
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend610
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910/miniv2
ifneq ($(filter $(PRODUCT),$(mini_v2_products)),)
ccflags-y += -DCFG_FEATURE_CAPABILITY_GROUP
endif
ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_FEATURE_VFIO -DCFG_FEATURE_HISS -DCFG_FEATURE_PSS_SIGN
ccflags-y += -DCFG_FEATURE_NOTIFY_REBOOT -DCFG_FEATURE_DEVICE_SHARE
endif
ifeq ($(PRODUCT),helper310p)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER -DCFG_FEATURE_CPU_NUMS_FIXED
ccflags-y += -DCFG_FEATURE_HISS -DCFG_FEATURE_BIND_TGID
endif
ifneq ($(filter $(PRODUCT),$(mini_v3_products)),)
ccflags-y += -DCFG_FEATURE_IMU_ENABLE -DCFG_FEATURE_IPC_FORMAT_V2_CRC
ccflags-y += -DCFG_FEATURE_CPU_NUMS_FIXED -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DCFG_FEATURE_HISS -DCFG_TRS_REFACTOR_FEATURE -DCFG_FEATURE_LLC_STUB
ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Bemu),)
ccflags-y += -DCFG_FEATURE_DEVMNG_BAR
endif
ifeq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif
endif
else ifneq ($(filter $(PRODUCT),$(mdc_products)),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI -DCFG_FEATURE_DDR
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DCFG_FEATURE_CAPABILITY_GROUP -DCFG_FEATURE_BIN_DOWN
ccflags-y += -DCFG_FEATURE_HISS -DCFG_FEATURE_IPC_CRC -DCFG_FEATURE_BOARD_ID_EXPAND
ccflags-y += -I$(DRIVER_INC)/include/media
ccflags-y += -I$(DRIVER_INC)/ts_platform/ascend610
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910
ccflags-y += -I$(src)/drv_devmng/drv_devmng_device/ascend910/mdc
ifeq ($(PRODUCT),ascend610Lite)
ccflags-y += -DCFG_SOC_MDC_V51_LITE
endif
ifeq ($(PRODUCT),ascend610Liteesl)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_LITE_ESL -DCFG_SOC_MDC_V51_LITE
endif
ifeq ($(PRODUCT),bs9sx1a)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_BS9SX1A
endif
endif

ifneq ($(filter $(PRODUCT),$(mdc_products) ascend310p helper310p),)
ccflags-y += -DCFG_FEATURE_LP_ENABLE
endif
ifneq ($(filter $(PRODUCT),$(mdc_products) as31xm1),)
ccflags-y += -DCFG_FEATURE_REBOOT_REASON
endif
ifneq ($(filter $(PRODUCT),$(rc_mode_products)),)
ccflags-y += -DCFG_FEATURE_RC_MODE -DCFG_FEATURE_HOST_UNBIND
endif
ifneq ($(filter $(PRODUCT),$(ep_mode_products)),)
ccflags-y += -DCFG_FEATURE_EP_MODE
endif
ifneq ($(filter $(PRODUCT),ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_VFIO -DCFG_FEATURE_DEVICE_DEVID_CONVERT
ccflags-y += -DCFG_FEATURE_VF_SINGLE_AICORE -DCFG_FEATURE_VF_USE_DEVID
ccflags-y += -DCFG_FEATURE_VFIO_SOC -DCFG_FEATURE_BIND_TGID
ccflags-y += -DCFG_FEATURE_DEVICE_QUERY_RESOURCE
endif

ifneq ($(filter $(PRODUCT),ascend310p ascend910 ascend910B),)
ccflags-y += -DSUPPORT_VDEV_MEM
endif
ifneq ($(filter $(PRODUCT),ascend310p helper310p ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_FEATURE_AIC_AIV_UTIL_FROM_TS
endif
ifneq ($(filter $(PRODUCT),ascend910B),)
ccflags-y += -DCFG_FEATURE_AIC_AIV_UTIL_FROM_TS -DCFG_FEATURE_IPC_FORMAT_V2 -DCFG_FEATURE_HCCS
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc ascend310Besl ascend310Brcesl ascend310Bemu as31xm1),)
ccflags-y += -DCFG_FEATURE_AIC_AIV_UTIL_FROM_TS -DCFG_FEATURE_IPC_FORMAT_V2
endif
ifneq ($(filter $(PRODUCT),ascend910),)
ccflags-y += -DCONFIG_IPC_COMM_FROM_IMU_V1
endif
ifneq ($(filter $(PRODUCT),ascend610 ascend610Lite ascend610Liteesl bs9sx1a ascend310p helper310p),)
ccflags-y += -DCONFIG_IPC_COMM_FROM_LP
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
ccflags-y += -DCONFIG_IPC_COMM_FROM_LPM
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCONFIG_IPC_COMM_FROM_IMU_V2
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu as31xm1),)
ccflags-y += -DCONFIG_IPC_COMM_FROM_IMU_STUB
endif
ifneq ($(filter $(PRODUCT),ascend310Brc),)
ccflags-y += -DCFG_CHIP_INFO_FROM_VMNG
endif
ifneq ($(filter $(PRODUCT),ascend910),)
ccflags-y += -DCFG_FEATURE_AI_UTIL_BY_CALCULATE -DCFG_FEATURE_TS_FAULT_MASK
ccflags-y += -DCFG_UTIL_BY_CALCULATE
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
ccflags-y += -DCFG_FEATURE_AI_UTIL_FROM_IPC
endif
ifneq ($(filter $(PRODUCT),ascend610 ascend610Lite ascend610Liteesl bs9sx1a ascend310p helper310p),)
ccflags-y += -DCFG_UTIL_BY_CALCULATE
endif
ifneq ($(filter $(PRODUCT),ascend310p),)
ccflags-y += -DCFG_EDP_MSG
endif
ifneq ($(filter $(PRODUCT),helper310p ascend310Brc ascend610 bs9sx1a ascend610Lite ascend610Liteesl as31xm1),)
ccflags-y += -DCFG_FEATURE_OSC_FREQ
endif

ifneq ($(filter $(PRODUCT),ascend910B),)
ccflags-y += -DCFG_FEATURE_HBM -DCFG_MEMORY_NODE_CONFIG_3
ccflags-y += -DCFG_FEATURE_GET_MEM_FROM_VIRMNG
endif
ifneq ($(filter $(PRODUCT),ascend910),)
ccflags-y += -DCFG_FEATURE_HBM -DCFG_MEMORY_NODE_CONFIG_1
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc),)
ccflags-y += -DCFG_MEMORY_NODE_CONFIG_2 -DCFG_FEATURE_ADD_CGROUP_SIZE
endif
ifneq ($(filter $(PRODUCT),ascend310p),)
ccflags-y += -DCFG_MEMORY_NODE_CONFIG_2 -DCFG_FEATURE_ADD_CGROUP_SIZE
endif
ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_MEMORY_NODE_CONFIG_5
endif
ifneq ($(filter $(PRODUCT),helper310p),)
ccflags-y += -DCFG_MEMORY_NODE_CONFIG_4 -DCFG_FEATURE_ADD_CGROUP_SIZE
endif
ifneq ($(filter $(PRODUCT),as31xm1),)
ccflags-y += -DCFG_MEMORY_NODE_CONFIG_2
endif

ifneq ($(filter $(PRODUCT),ascend310 ascend310p ascend910 ascend910B ascend310B),)
ccflags-y += -DCFG_FEATURE_HEART_BEAT -DCFG_FEATURE_HEALTH_ERR_CODE
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc ascend910B as31xm1),)
ccflags-y += -DCFG_FEATURE_NEW_EVENT_CODE
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Brc ascend910B),)
ccflags-y += -DCFG_FEATURE_ERRORCODE_ON_NEW_CHIPS -DCFG_TRS_HB_REFACTOR_FEATURE
endif
ifneq ($(filter $(PRODUCT),ascend910 ascend310 ascend310p ascend310B ascend310Besl ascend310Bemu),)
ccflags-y += -DCFG_FEATURE_TOPOLOGY_BY_SMP
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl),)
ccflags-y += -DCFG_FEATURE_PG -DCFG_FEATURE_VFG
ccflags-y += -DCFG_FEATURE_SRIOV -DCFG_FEATURE_TOPOLOGY_BY_HCCS_LINK_STATUS
endif
ifneq ($(filter $(PRODUCT),ascend310B ascend310Besl ascend310Brc ascend310Brcesl as31xm1),)
ccflags-y += -DCFG_FEATURE_PG
ifeq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc helper310p ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_DEVICE_SHARE
endif

drv_devmng-y += \
	core/dms_init.o \
	core/dms_probe.o \
	core/dms_sysfs.o \
	core/dms_timer.o \
	core/workqueue_affinity.o \
	event/device/dms_event_device.o \
	event/dms_adapt.o \
	ipc/dms_ipc_common.o \
	lpm/dms_lpm.o \
	lpm/dms_lpm_common.o \
	lpm/dms_lpm_info.o \
	lpm/dms_lpm_info_stub.o \
	lpm/dms_lpm_info_from_ipc.o \
	lpm/dms_lpm_info_from_register.o \
	lpm/dms_lpm_info_from_devinfo.o \
	lpm/dms_lpm_scan.o \
	mem/dms_mem_info.o \
	mem/dms_mem_common.o \
	mem/dms_ddr_info.o \
	product/dms_product.o \
	status/dms_basic_info.o \
	status/dms_chip_info.o \
	status/dms_vdev.o \
	status/dms_pg_info.o \
	status/dms_bbox.o \
	ts/dms_ts_info.o \
	xpc/dms_xpc_common.o \
	time/device/dms_device_time_zone.o

ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
drv_devmng-y += core/drv_cpu_type.o
endif
ifneq ($(filter $(PRODUCT),ascend910),)
drv_devmng-y += ipc/dms_ipc_from_imu.o
endif
ifneq ($(filter $(PRODUCT),ascend610 ascend610Lite ascend610Liteesl bs9sx1a ascend310p helper310p),)
drv_devmng-y += ipc/dms_ipc_from_lp.o
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
drv_devmng-y += ipc/dms_ipc_from_lpm.o
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
drv_devmng-y += ipc/dms_ipc_format_v2.o
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
drv_devmng-y += hccs/dms_hccs_feature.o
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend910),)
drv_devmng-y += mem/dms_hbm_info.o
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend910 ascend310 ascend310p ascend310B),)
drv_devmng-y += status/dms_dev_topology.o
endif
ifneq ($(filter $(PRODUCT),helper310p ascend310Brc ascend610 ascend610Lite ascend610Liteesl as31xm1),)
drv_devmng-y += status/dms_osc_freq.o
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc ascend310B ascend310Besl ascend310Bemu ascend310p ascend910 ascend910B ascend920esl ascend920emu),)
drv_devmng-y += time/device/dms_time_device.o
endif
ifneq ($(filter $(PRODUCT),ascend910 ascend310 ascend310rc),)
drv_devmng-y += ts/dms_ts_scan.o
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920emu),)
drv_devmng-y += lpm/dms_lpm_pass_through_mcu.o
endif
ifneq ($(filter $(PRODUCT),ascend910),)
drv_devmng-y += lpm/dms_lpm_pass_through_mcu.o
endif
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
drv_devmng-y += lpm/dms_lpm_info_from_pmu.o
endif

ifneq ($(filter $(PRODUCT),$(mini_products)),)
drv_devmng-y += \
	$(device_devmng_prefix)/devdrv_manager.o \
	$(device_devmng_prefix)/devdrv_cache_flush.o \
	$(device_devmng_prefix)/devdrv_manager_msg.o \
	$(device_devmng_prefix)/tsdrv_status.o \
	$(device_devmng_prefix)/devdrv_pm.o \
	$(device_devmng_prefix)/devdrv_ipc_msg.o \
	$(device_devmng_prefix)/devdrv_ipc.o \
	$(device_devmng_prefix)/devdrv_driver_pm.o \
	$(device_devmng_prefix)/devdrv_gpioirq_register.o \
	$(device_devmng_prefix)/devdrv_black_box.o \
	$(device_devmng_prefix)/devdrv_manager_container.o \
	$(device_devmng_prefix)/devdrv_manager_time.o \
	$(device_devmng_prefix)/devdrv_manager_freq.o \
	$(device_devmng_prefix)/devdrv_i2c_ina2xx.o \
	$(device_devmng_prefix)/devdrv_platform_drvops.o \
	$(device_devmng_prefix)/devdrv_info.o \
	$(device_devmng_prefix)/devdrv_manager_container_noplugin.o \
	$(device_devmng_prefix)/appmon_black_box.o \
	$(device_devmng_prefix)/devdrv_flash_config.o \
	$(device_devmng_prefix)/mini/devdrv_adapt_manager.o
endif

ifneq ($(filter $(PRODUCT),$(ascend910_prefix_products)),)
drv_devmng-y += \
	$(device_devmng_prefix)/devdrv_manager.o \
	$(device_devmng_prefix)/devdrv_cache_flush.o \
	$(device_devmng_prefix)/devdrv_manager_msg.o \
	$(device_devmng_prefix)/tsdrv_status.o \
	$(device_devmng_prefix)/devdrv_pm.o \
	$(device_devmng_prefix)/devdrv_ipc_msg.o \
	$(device_devmng_prefix)/devdrv_ipc.o \
	$(device_devmng_prefix)/devdrv_driver_pm.o \
	$(device_devmng_prefix)/devdrv_gpioirq_register.o \
	$(device_devmng_prefix)/devdrv_black_box.o \
	$(device_devmng_prefix)/devdrv_manager_container.o \
	$(device_devmng_prefix)/devdrv_manager_time.o \
	$(device_devmng_prefix)/devdrv_manager_freq.o \
	$(device_devmng_prefix)/devdrv_i2c_ina2xx.o \
	$(device_devmng_prefix)/devdrv_pcie.o \
	$(device_devmng_prefix)/appmon_black_box.o \
	$(device_devmng_prefix)/devdrv_dsmi/devdrv_info.o \
	$(device_devmng_prefix)/devdrv_manager_rand.o
endif

ifneq ($(filter $(PRODUCT),ascend310 ascend310rc helper310p ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
drv_devmng-y += $(device_devmng_prefix)/devdrv_manager_dev_share.o
endif
ifneq ($(filter $(PRODUCT),ascend310Brc ascend310Brcesl ascend310Brcemu),)
drv_devmng-y += \
	drv_devmng/drv_devmng_common/dev_mnt_vdevice.o \
	drv_devmng/drv_devmng_common/devdrv_pcie.o
endif

ifneq ($(filter $(PRODUCT),$(cloud_products)),)
drv_devmng-y += \
	$(device_devmng_prefix)/cloud/devdrv_adapt_manager.o \
	$(device_devmng_prefix)/devdrv_dsmi/devdrv_manager_hccs.o \
	$(device_devmng_prefix)/devdrv_dsmi/devdrv_manager_llc.o \
	$(device_devmng_prefix)/devdrv_flow_control_mpam.o \
	$(device_devmng_prefix)/devdrv_manager_pid_map.o
endif
ifneq ($(filter $(PRODUCT),$(mini_products)),)
drv_devmng-y += $(device_devmng_prefix)/mini/devdrv_adapt_manager.o
endif
ifneq ($(filter $(PRODUCT),$(mini_v3_products) $(mini_v2_products)),)
drv_devmng-y += \
	$(device_devmng_prefix)/miniv2/devdrv_adapt_manager.o \
	$(device_devmng_prefix)/devdrv_dsmi/devdrv_manager_llc.o \
	$(device_devmng_prefix)/devdrv_manager_pid_map.o
endif
ifneq ($(filter $(PRODUCT),$(mdc_products)),)
drv_devmng-y += \
	$(device_devmng_prefix)/miniv2/devdrv_adapt_manager.o \
	$(device_devmng_prefix)/mdc/devmng_dts.o \
	$(device_devmng_prefix)/mdc/devdrv_os_power.o \
	$(device_devmng_prefix)/devdrv_dsmi/devdrv_manager_llc.o \
	$(device_devmng_prefix)/devdrv_manager_pid_map.o
endif
ifneq ($(filter $(PRODUCT),$(cloud_v2_products)),)
drv_devmng-y += $(device_devmng_prefix)/devdrv_chip_dev_map.o
endif

drv_devmng-objs := $(drv_devmng-y)
endif

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(DRIVER_INC)/dbl/dev_urd -I$(DRIVER_INC)/common
ccflags-y += -I$(src) -I$(src)/include -I$(src)/config -I$(src)/core
ccflags-y += -I$(src)/event -I$(src)/power -I$(src)/product -I$(src)/status
ccflags-y += -I$(src)/time -I$(src)/devid -I$(src)/custom -I$(src)/xpc

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ifeq ($(PRODUCT_SIDE),host)
ccflags-y += -include $(DRIVER_INC)/include/internal/host_config.h
endif
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-format-nonliteral -Wno-empty-body
