# SPDX-License-Identifier: GPL-2.0
obj-m := drv_soft_fault.o

drv_soft_fault-objs := soft_fault.o
drv_soft_fault-objs += dms_sensor_interface.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP), y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/toolchain/bbox
ccflags-y += -I$(DRIVER_INC)/include/devmng -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers

ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
else ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
endif

ifneq ($(filter $(PRODUCT), ascend310 ascend310rc ascend310B ascend310Brc as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI
endif

ifneq ($(filter $(PRODUCT), ascend310 ascend310p ascend910 ascend910B ascend310B),)
ccflags-y += -DCFG_FEATURE_EP_MODE -DCFG_FEATURE_HEART_BEAT
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310p ascend910 ascend910B),)
ccflags-y += -DCFG_FEATURE_OS_INIT_EVENT
endif

ifneq ($(filter $(PRODUCT), ascend910B),)
ccflags-y += -DCFG_FEATURE_SRIOV
endif

ifeq ($(PRODUCT_SIDE),host)
drv_soft_fault-objs += heartbeat_host.o
ccflags-y += -DCFG_HOST_ENV
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend910

ifneq ($(filter $(PRODUCT), ascend910 ascend910B),)
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend910
endif

ifneq ($(filter $(PRODUCT), ascend310p ascend310B),)
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend610
endif

ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend310
endif
else
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910

ifneq ($(filter $(PRODUCT), ascend910 ascend910B),)
ccflags-y += -I$(DRIVER_INC)/ts_platform/tsdrv_pdata/ascend910
endif

ifneq ($(filter $(PRODUCT), ascend310p helper310p ascend310B ascend310Brc as31xm1),)
ccflags-y += -I$(DRIVER_INC)/ts_platform/tsdrv_pdata/ascend610
endif

ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
ccflags-y += -I$(DRIVER_INC)/ts_platform/tsdrv_pdata/ascend310
endif

ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a ascend610Lite ascend610Liteesl),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
endif

ifneq ($(filter $(PRODUCT), ascend310 ascend310B ascend310p ascend910 ascend910B),)
drv_soft_fault-objs += heartbeat_device.o
endif

ifneq ($(filter $(PRODUCT), ascend310B ascend310p ascend910 ascend910B),)
drv_soft_fault-objs += os_reset.o
endif
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h


KBUILD_EXTRA_SYMBOLS := $(src)/../dms_dtm/Module.symvers \
	$(src)/../dms_smf/Module.symvers \
	$(src)/../uda/Module.symvers \
	$(src)/../urd/Module.symvers
