# SPDX-License-Identifier: GPL-2.0

obj-m := drv_vpc_agent.o

drv_vpc_agent-objs := \
	virtmng_msg_pub.o \
	virtmng_msg_common.o \
	virtmng_msg_admin.o \
	virtmng_extension.o \
	virtmng_stack.o \
	virtmng_resource.o \
	vpc_agent/virtmngagent_msg.o \
	vpc_agent/virtmngagent_msg_common.o \
	vpc_agent/virtmngagent_msg_admin.o \
	vpc_agent/virtmngagent_vpc.o \
	vpc_agent/virtmngagent_vpc_unit.o \
	vpc_agent/vmnga_vpc_interface.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -Wall -Werror -Wtrampolines $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char
ccflags-y += -Wformat=2 -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-empty-body
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/internal
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(src) -I$(src)/vpc_agent

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
