/**
 * @file bbox_proxy_config_milanr3.h
 *
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef BBOX_PROXY_CONFIG_MILANR3_H
#define BBOX_PROXY_CONFIG_MILANR3_H

#include "bbox_proxy_config.h"
#include "device/bbox_pub.h"

/*
 * 说明：模块代理及异常注册
 * 各模块通过模板宏初始化 struct bbox_proxy_info 结构体，黑匣子引用该头文件并将初始化结构体实例化
 *
 * 示例：
 * 各模块通过BBOX_PROXY_MODULE_XXX宏定义初始化 struct bbox_proxy_module_info 结构体
 * #define BBOX_PROXY_MODULE_LPM { \
 *     .coreid = BBOX_LPM, \
 *     .flag = BBOX_PROXY_CAPACITY_REGISTER | BBOX_PROXY_CAPACITY_DUMP | BBOX_PROXY_CAPACITY_LOG, \
 *     .name = "lpm", \
 *     .log_addr = 0xA00000, \
 *     .log_len = 0x400000, \
 *     .wait_timeout = 20000, \ // wait timeout will be restricted <= 20s
 *     .e_count = 3, \
 * }
 * 各模块通过BBOX_PROXY_EXCEPTION_XXX宏定义初始化 struct bbox_proxy_exception_info 结构体
 * #define BBOX_PROXY_EXCEPTION_LPM { \
 *     {0xA819320F, BBOX_DEAD, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW,
 *          BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "tsensor error"}, \
 *     {0xA619FFFF, BBOX_ERR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW,
 *          BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm heartbeat lost"}, \
 *     {0xA819FFFF, BBOX_DEAD, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW,
 *          BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm startup error"}, \
 * }
 * 各模块通过BBOX_PROXY_CTRL_XXX宏定义初始化 struct bbox_proxy_ctrl_info 结构体
 * #define BBOX_PROXY_CTRL_LPM { \
 *     .e_block_num = 2, \
 *     .block_info = { \
 *         {BLOCK_TYPE_STARTUP, CHECK_NONE, 0, 0x200000}, \
 *         {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, \
 *          0x200000, 0x200000}, \
 *     } \
 * }
 * 各模块通过修改DEFINE_BBOX_PROXY(x)宏定义增加自身模块在黑匣子代码中实例化 struct bbox_proxy_info 结构体
 * #define BBOX_PROXY_INITIALIZER(name) { \
 *     .module = BBOX_PROXY_MODULE_##name, \
 *     .exception = BBOX_PROXY_EXCEPTION_##name, \
 *     .ctrl = BBOX_PROXY_CTRL_##name, \
 * }
 * DEFINE_BBOX_PROXY(x) struct bbox_proxy_info x[] = { \
 *     BBOX_PROXY_INITIALIZER(TS), \
 *     BBOX_PROXY_INITIALIZER(LPM), \
 * }
 */
#define BBOX_PROXY_MODULE_TS { \
    .coreid = BBOX_TS, \
    .flag = BBOX_PROXY_CAPACITY_REGISTER | BBOX_PROXY_CAPACITY_DUMP_DDR | BBOX_PROXY_CAPACITY_TRANS_ID, \
    .name = "ts", \
    .log_addr = 0, \
    .log_len = 0, \
    .wait_timeout = 10000, \
    .e_count = 22, \
}

#define BBOX_PROXY_EXCEPTION_TS { \
    {0xA607FFFF, BBOX_MAJOR, BBOX_REBOOT_WAIT, HEARTBEAT_EXCEPTION, BBOX_REENTRANT_DISALLOW,  \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts heartbeat lost"}, \
    {0xA807FFFF, BBOX_CRITICAL, BBOX_REBOOT_WAIT, STARTUP_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts startup error"}, \
    {0xA6060000, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "data abort"}, \
    {0xA6060001, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "instr abort"}, \
    {0xA6060002, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "pc align fault"}, \
    {0xA6060003, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "sp align fault"}, \
    {0xA6060004, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "infinite loop"}, \
    {0xA6060005, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "unknow exception"}, \
    {0xB4060006, BBOX_MINOR, BBOX_REBOOT_NO, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "aicore exception"}, \
    {0xB4060007, BBOX_MINOR, BBOX_REBOOT_NO, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "aicore timeout"}, \
    {0xB4060008, BBOX_MAJOR, BBOX_REBOOT_NO, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "sdma init fault"}, \
    {0xB4060009, BBOX_MINOR, BBOX_REBOOT_NO, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "sdma timeout"}, \
    {0xA606000A, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "hwts bus error"}, \
    {0xB606000B, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "hwts sqe error"}, \
    {0xA606000C, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "hwts ecc error"}, \
    {0xB406000D, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts aicpu exception"}, \
    {0xB406000E, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts npu exception"}, \
    {0xA606000F, BBOX_MAJOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "aicore reset timeout"}, \
    {0xA4060011, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts npu timeout"}, \
    {0xB4060012, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts aiv exception"}, \
    {0xB4060013, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts aiv timeout"}, \
    {0xB406009C, BBOX_MINOR, BBOX_REBOOT_WAIT, TS_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_TS), BBOX_COREID_MASK(BBOX_TS), "ts aicpu timeout"}, \
}

#define BBOX_PROXY_CTRL_TS { \
    .e_block_num = 4, \
    .padding = {0}, \
    .block_info = { \
        {BLOCK_TYPE_STARTUP, CHECK_NONE, \
            0x200,    0x19000}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_HEARTBEAT_EXCEPID, \
            0x19200,  0x100}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_HEARTBEAT_EXCEPID, \
            0x19300,  0xE6C00}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_HEARTBEAT_EXCEPID, \
            0xFFF00,  0x80}, \
    } \
}

#define BBOX_PROXY_MODULE_HSM { \
    .coreid = BBOX_HSM, \
    .flag = BBOX_PROXY_CAPACITY_REGISTER | BBOX_PROXY_CAPACITY_DUMP_DDR | BBOX_PROXY_CAPACITY_DUMP_LOG, \
    .name = "hsm", \
    .log_addr = 0x3000000, \
    .log_len = 0x100000, \
    .wait_timeout = 10000, \
    .e_count = 3, \
}

#define BBOX_PROXY_EXCEPTION_HSM { \
    {0xa6360000, BBOX_MAJOR, BBOX_REBOOT_WAIT, STARTUP_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_HSM), BBOX_COREID_MASK(BBOX_HSM), "HSM startup exception"}, \
    {0xa6361000, BBOX_MAJOR, BBOX_REBOOT_WAIT, HEARTBEAT_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_HSM), BBOX_COREID_MASK(BBOX_HSM), "HSM heartbeat exception"}, \
    {0xa6362000, BBOX_MAJOR, BBOX_REBOOT_NO, HSM_EXCEPTION, BBOX_REENTRANT_ALLOW, \
        BBOX_COREID_MASK(BBOX_HSM), BBOX_COREID_MASK(BBOX_HSM), "HSM resource shortage exception"}, \
}

#define BBOX_PROXY_CTRL_HSM { \
    .e_block_num = 5, \
    .padding = {0}, \
    .block_info = { \
        {BLOCK_TYPE_STARTUP, CHECK_NONE, 0x200,  0x1000}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x1200, 0x1000}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x2200, 0x1000}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x3200, 0x1000}, \
        {BLOCK_TYPE_NORMAL,  CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x4200, 0x1000}, \
    } \
}

#define BBOX_PROXY_MODULE_LPM { \
    .coreid = BBOX_LPM, \
    .flag = BBOX_PROXY_CAPACITY_REGISTER | BBOX_PROXY_CAPACITY_DUMP_DDR | BBOX_PROXY_CAPACITY_DUMP_LOG, \
    .name = "lpm", \
    .log_addr = 0x3100000, \
    .log_len = 0x20000, \
    .wait_timeout = 30000, \
    .e_count = 48, \
}

#define BBOX_PROXY_EXCEPTION_LPM { \
    {0xA4183200, BBOX_MAJOR, BBOX_REBOOT_WAIT, STARTUP_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm startup error"}, \
    {0xA4183201, BBOX_MAJOR, BBOX_REBOOT_WAIT, STARTUP_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm suspend error"}, \
    {0xA4183202, BBOX_MAJOR, BBOX_REBOOT_WAIT, STARTUP_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm resume error"}, \
    {0xA6193203, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm os panic"}, \
    {0xA6183204, BBOX_MAJOR, BBOX_REBOOT_WAIT, HEARTBEAT_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm heartbeat lost"}, \
    {0xA6193205, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm tsensor error"}, \
    {0xA6183206, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm low temperature"}, \
    {0xA6183207, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm high temperature"}, \
    {0xA4183208, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm edp software alert"}, \
    {0xA4183209, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm edp hardware alert"}, \
    {0xA418320a, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm edp aicore error"}, \
    {0xA418320b, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm edp bus error"}, \
    {0xA418320c, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm ipc timeout"}, \
    {0xA418320d, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm ipc queue error"}, \
    {0xA418320e, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm pmu config error"}, \
    {0xA418320f, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm pmbus error"}, \
    {0xA4183210, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm avsbus error"}, \
    {0xA6183211, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm aicore frequency error"}, \
    {0xA6183212, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm bus frequency error"}, \
    {0xA6193213, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm aicore voltage error"}, \
    {0xA6183214, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm bus voltage error"}, \
    {0xA6193215, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm get current error"}, \
    {0xA6183216, BBOX_MAJOR, BBOX_REBOOT_WAIT, LPM_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm pll unlocked error"}, \
    {0xA2182224, BBOX_NOTICE, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr low temperature"}, \
    {0xA6182225, BBOX_MAJOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr high temperature"}, \
    {0xA8192226, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr phyram merr"}, \
    {0xA8192227, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr uceram merr"}, \
    {0xA8192228, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr wsram merr"}, \
    {0xA8192229, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr sref err"}, \
    {0xA819222A, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr rpram merr"}, \
    {0xA819222B, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr sbram merr"}, \
    {0xA819222C, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr aref alarm"}, \
    {0xA819222D, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr rd timeout"}, \
    {0xA419222E, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr uceram serr"}, \
    {0xA419222F, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr phyram serr"}, \
    {0xA4192230, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr rpram serr"}, \
    {0xA4192231, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr sbram serr"}, \
    {0xA4192232, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr wsram serr"}, \
    {0xA8182233, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc derr"}, \
    {0xA4182234, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc serr"}, \
    {0xA8192235, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc wbuf derr"}, \
    {0xA4192236, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc wbuf serr"}, \
    {0xA8192237, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc rbuf derr"}, \
    {0xA4192238, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc rbuf serr"}, \
    {0xA8192239, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc sbram derr"}, \
    {0xA419223A, BBOX_MINOR, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc sbram serr"}, \
    {0xA819223B, BBOX_CRITICAL, BBOX_REBOOT_WAIT, DDR_FATAL_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "ddr iecc exp ob"}, \
    {0xA6192D15, BBOX_MAJOR, BBOX_REBOOT_WAIT, HEARTBEAT_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_LPM), BBOX_COREID_MASK(BBOX_LPM), "lpm heart error"}, \
}

#define BBOX_PROXY_CTRL_LPM { \
    .e_block_num = 6, \
    .padding = {0}, \
    .block_info = { \
        {BLOCK_TYPE_STARTUP, CHECK_NONE, 0x0400, 0x4C00}, \
        {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x5000,  0xF000}, \
        {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x14000, 0xF000}, \
        {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x23000, 0xF000}, \
        {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x32000, 0xF000}, \
        {BLOCK_TYPE_NORMAL, CHECK_RUNTIME_EXCEPID | CHECK_RUNTIME_TMSTMP | CHECK_HEARTBEAT_EXCEPID, 0x41000, 0xF000}, \
    } \
}

#define BBOX_PROXY_MODULE_BIOS { \
    .coreid = BBOX_BIOS, \
    .flag = BBOX_PROXY_CAPACITY_REGISTER, \
    .name = "bios", \
    .log_addr = 0x0, \
    .log_len = 0x0, \
    .wait_timeout = 10000, \
    .e_count = 1, \
}

#define BBOX_PROXY_EXCEPTION_BIOS { \
    {0xA8280000, BBOX_CRITICAL, BBOX_REBOOT_WAIT, ATF_EXCEPTION, BBOX_REENTRANT_DISALLOW, \
        BBOX_COREID_MASK(BBOX_BIOS), BBOX_COREID_MASK(BBOX_BIOS), "atf panic exception"}, \
}

#define BBOX_PROXY_CTRL_BIOS { \
    .e_block_num = 1, \
    .padding = {0}, \
    .block_info = { \
        {BLOCK_TYPE_STARTUP, CHECK_NONE, 0x400, 0xF800}, \
    } \
}

#define DEFINE_BBOX_PROXY(x) struct bbox_proxy_info x[] = { \
    BBOX_PROXY_INITIALIZER(LPM), \
    BBOX_PROXY_INITIALIZER(TS), \
    BBOX_PROXY_INITIALIZER(HSM), \
    BBOX_PROXY_INITIALIZER(BIOS), \
}

#endif

