# SPDX-License-Identifier: GPL-2.0
obj-m :=

ifeq ($(PRODUCT_SIDE),host)
obj-m += drv_devdrv_host.o
endif

DRIVER_INC := $(src)/..

ccflags-y += -I$(src) -I$(src)/ts_drv_common
ccflags-y += -I$(src)/ts_drv_common/devdrv_callback
ccflags-y += -I$(src)/ts_drv_common/tsdrv_dev
ccflags-y += -I$(src)/ts_drv_common/tsdrv_id
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme/logic
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme/shm
ccflags-y += -I$(src)/ts_drv_common/tsdrv_nvme/sync_cb
ccflags-y += -I$(src)/ts_drv_common/tsdrv_osal
ccflags-y += -I$(src)/ts_drv_common/tsdrv_hotreset
ccflags-y += -I$(src)/ts_drv_common/tsdrv_cdqm
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check
ccflags-y += -I$(src)/tsdrv_virt -I$(src)/tsdrv_cdqm -I$(src)/tsdrv_conflict_check
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -DCFG_MANAGER_HOST_ENV -DCFG_FEATURE_SHARE_LOG
ccflags-y += -DCFG_FEATURE_IPC_NOTIFY -DCFG_FEATURE_HOTRESET
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wno-format-nonliteral -Wno-empty-body

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ifeq ($(TARGET_BUILD_TYPE),debug)
ccflags-y += -DCFG_BUILD_DEBUG
endif

ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
drv_devdrv_host-objs := \
	ts_drv_common/devdrv_cqsq.o \
	ts_drv_common/devdrv_devinit.o \
	tsdrv_get_ssid.o \
	ts_drv_common/devdrv_functional_cqsq.o \
	ts_drv_common/devdrv_mailbox.o \
	ts_drv_common/tsdrv_delay_recycle.o \
	ts_drv_common/devdrv_id.o \
	ts_drv_common/devdrv_recycle.o \
	ts_drv_common/devdrv_shm.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cbcq.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_sync_cbctrl.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cbsq.o \
	ts_drv_common/tsdrv_nvme/sync_cb/devdrv_cb_stub.o \
	ts_drv_common/tsdrv_dev/tsdrv_device.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx.o \
	ts_drv_common/tsdrv_dev/tsdrv_capacity.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo_platform.o \
	ts_drv_common/tsdrv_dev/tsdrv_dev_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_mailbox_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_comm_fops.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_event_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_config_dfx.o \
	ts_drv_common/tsdrv_id/tsdrv_id.o \
	ts_drv_common/tsdrv_id/tsdrv_sync.o \
	ts_drv_common/tsdrv_nvme/tsdrv_nvme.o \
	ts_drv_common/tsdrv_nvme/shm/shm_sqcq.o \
	ts_drv_common/tsdrv_nvme/logic/logic_cq.o \
	ts_drv_common/tsdrv_nvme/logic/tsdrv_logic_cq.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id_event.o \
	ts_drv_common/tsdrv_id/hvtsdrv_cqsq.o \
	ts_drv_common/devdrv_ipc_notify.o \
	devdrv_config_p2p.o \
	tsdrv_drvops.o \
	tsdrv_notify.o \
	tsdrv_conflict_check/tsdrv_bar_init.o \
	tsdrv_virt/hvtsdrv_init.o \
	tsdrv_virt/hvtsdrv_proc.o \
	tsdrv_virt/hvtsdrv_cb.o \
	tsdrv_virt/hvtsdrv_logic_cq.o \
	tsdrv_virt/hvtsdrv_shm_sqcq.o \
	ts_drv_common/tsdrv_vsq.o \
	ts_drv_common/hvtsdrv_tsagent.o
else
drv_devdrv_host-objs := \
	ts_drv_common/devdrv_cqsq.o \
	ts_drv_common/devdrv_devinit.o \
	tsdrv_get_ssid.o \
	ts_drv_common/devdrv_functional_cqsq.o \
	ts_drv_common/devdrv_mailbox.o \
	ts_drv_common/tsdrv_delay_recycle.o \
	ts_drv_common/devdrv_id.o \
	ts_drv_common/devdrv_recycle.o \
	ts_drv_common/devdrv_shm.o \
	ts_drv_common/devdrv_callback/devdrv_cb.o \
	ts_drv_common/devdrv_callback/devdrv_cbctrl.o \
	ts_drv_common/devdrv_callback/tsdrv_cb_pm.o \
	ts_drv_common/tsdrv_dev/tsdrv_device.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx.o \
	ts_drv_common/tsdrv_dev/tsdrv_capacity.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo.o \
	ts_drv_common/tsdrv_dev/tsdrv_hwinfo_platform.o \
	ts_drv_common/tsdrv_dev/tsdrv_dev_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_mailbox_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_comm_fops.o \
	ts_drv_common/tsdrv_dev/tsdrv_ctx_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_event_id_dfx.o \
	ts_drv_common/tsdrv_dev/tsdrv_id_config_dfx.o \
	ts_drv_common/tsdrv_id/tsdrv_id.o \
	ts_drv_common/tsdrv_id/tsdrv_sync.o \
	ts_drv_common/tsdrv_nvme/tsdrv_nvme.o \
	ts_drv_common/tsdrv_nvme/shm/shm_sqcq.o \
	ts_drv_common/tsdrv_nvme/logic/logic_cq.o \
	ts_drv_common/tsdrv_nvme/logic/tsdrv_logic_cq.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id.o \
	ts_drv_common/tsdrv_id/hvtsdrv_id_event.o \
	ts_drv_common/tsdrv_id/hvtsdrv_cqsq.o \
	ts_drv_common/devdrv_ipc_notify.o \
	ts_drv_common/devdrv_nsm.o \
	devdrv_config_p2p.o \
	tsdrv_drvops.o \
	tsdrv_notify.o \
	tsdrv_conflict_check/tsdrv_bar_init.o \
	tsdrv_virt/hvtsdrv_init.o \
	tsdrv_virt/hvtsdrv_proc.o \
	tsdrv_virt/hvtsdrv_cb.o \
	tsdrv_virt/hvtsdrv_logic_cq.o \
	tsdrv_virt/hvtsdrv_shm_sqcq.o \
	ts_drv_common/tsdrv_vsq.o \
	ts_drv_common/hvtsdrv_tsagent.o
endif

drv_devdrv_host-objs += \
	ts_drv_common/tsdrv_osal/tsdrv_osal_intr.o \
	ts_drv_common/tsdrv_osal/tsdrv_osal_mm.o \
	ts_drv_common/tsdrv_hotreset/tsdrv_hotreset.o \
	ts_drv_common/tsdrv_hotreset/tsdrv_dms_notifier.o

ifneq ($(filter $(PRODUCT),ascend910 ascend910B ascend920esl ascend920emu),)
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend910
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v1
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend910
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend910
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_FEATURE_USE_MAILBOX_RECYCLE
ccflags-y += -DCFG_FEATURE_VFIO
drv_devdrv_host-objs += ts_drv_common/tsdrv_conflict_check/ascend910/tsdrv_set_runtime_conflict_check.o
ifneq ($(filter $(PRODUCT),ascend910),)
ccflags-y += -DCFG_FEATURE_RUNTIME_NO_THREAD
endif
ifneq ($(filter $(PRODUCT),ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2 -DCFG_FEATURE_CDQM
ccflags-y += -DCFG_FEATURE_CALLBACK_EVENT -DCFG_FEATURE_SQ_HOST_MEM
ccflags-y += -DCFG_FEATURE_CQ_HOST_MEM -DCFG_FEATURE_SUPPORT_VSQ_MNG
ccflags-y += -DCFG_FEATURE_RUNTIME_NO_THREAD -DCFG_FEATURE_STARS
ccflags-y += -DVER_CDQM_B607
drv_devdrv_host-objs += tsdrv_cdqm/tsdrv_cdqm_host.o
drv_devdrv_host-objs += tsdrv_cdqm/cdq_manager.o
drv_devdrv_host-objs += ts_drv_common/tsdrv_cdqm/tsdrv_cdqm_module.o
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_sriov.o
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_sriov_id.o
else
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_mdev.o
endif
else ifneq ($(filter $(PRODUCT),ascend310 ascend310rc ascend310B ascend310Besl ascend310p),)
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(DRIVER_INC)/include/soc/mini_v1
ifneq ($(filter $(PRODUCT),ascend310 ascend310rc),)
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend310
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend310
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend310
drv_devdrv_host-objs += ts_drv_common/tsdrv_conflict_check/ascend310/tsdrv_set_runtime_conflict_check.o
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_mdev.o
else
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend910
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend610
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend610
drv_devdrv_host-objs += ts_drv_common/tsdrv_conflict_check/ascend610/tsdrv_set_runtime_conflict_check.o
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_mdev.o
ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_CQ_HOST_MEM
ccflags-y += -DCFG_FEATURE_IPC_NOTIFY_WITH_EVENTID -DCFG_FEATURE_RUNTIME_NO_THREAD
ccflags-y += -DCFG_SOC_PLATFORM_HOST -DCFG_FEATURE_VFIO
ccflags-y += -DCFG_FEATURE_ID_MAPING -DCFG_FEATURE_USE_MAILBOX_RECYCLE
else
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_SOC_PLATFORM_HOST
ccflags-y += -DCFG_FEATURE_CDQM -DCFG_FEATURE_CMO
ccflags-y += -DCFG_FEATURE_SUPPORT_VSQ_MNG -DCFG_FEATURE_USE_MAILBOX_RECYCLE
ccflags-y += -DCFG_FEATURE_RUNTIME_NO_THREAD -DCFG_FEATURE_STARS
ccflags-y += -DCFG_FEATURE_CALLBACK_EVENT
drv_devdrv_host-objs += tsdrv_cdqm/tsdrv_cdqm_host.o
drv_devdrv_host-objs += ts_drv_common/tsdrv_cmo_id.o
drv_devdrv_host-objs += ts_drv_common/tsdrv_cdqm/tsdrv_cdqm_module.o
drv_devdrv_host-objs += tsdrv_cdqm/cdq_manager.o
endif
endif
else
ccflags-y += -I$(DRIVER_INC)/include/soc/mini_v1
drv_devdrv_host-objs += tsdrv_virt/hvtsdrv_mdev.o
ifneq ($(filter $(PRODUCT),ascend610 bs9sx1a),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_FEATURE_RUNTIME_NO_THREAD
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend910
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend610
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend610
drv_devdrv_host-objs += ts_drv_common/tsdrv_conflict_check/ascend610/tsdrv_set_runtime_conflict_check.o
else
ccflags-y += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_host/ascend310
ccflags-y += -I$(DRIVER_INC)/ts_platform_host/ascend310
ccflags-y += -I$(src)/ts_drv_common/tsdrv_conflict_check/ascend310
drv_devdrv_host-objs += ts_drv_common/tsdrv_conflict_check/ascend310/tsdrv_set_runtime_conflict_check.o
endif
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/internal/host_config.h
ccflags-y += -include $(DRIVER_INC)/include/compat.h
