# SPDX-License-Identifier: GPL-2.0
obj-m := drv_pcie_hdc.o
drv_pcie_hdc-objs := hdcdrv_core.o hdcdrv_core_com.o hdcdrv_device.o hdcdrv_mem.o hdcdrv_mem_com.o hdcdrv_epoll.o hdcdrv_sysfs.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) 
ccflags-y += -DHDC_ENV_DEVICE

ifeq ($(PRODUCT),ascend920esl)
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA
else ifeq ($(PRODUCT),ascend910B)
ccflags-y += -DCFG_FEATURE_SRIOV -DCFG_FEATURE_MIRROR -DCFG_FEATURE_SIMPLIFY_MODE
else ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_FEATURE_VFIO_DEVICE
else ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_FEATURE_VFIO_DEVICE
else ifeq ($(PRODUCT),ascend310B)
else
ccflags-y += -DCFG_SOC_PLATFORM_MINIV1 -DCFG_FEATURE_SIMPLIFY_MODE -DCFG_FEATURE_PROCESS_NUM_LITE
endif

ifneq ($(filter $(PRODUCT), as31xm1),)
ccflags-y += -DCFG_FEATURE_HDC_REG_MEM -DCFG_SOC_PLATFORM_MDC_V11
ccflags-y += -I$(DRIVER_INC)/dms/include -I$(DRIVER_INC)/dms/config
ccflags-y += -I$(DRIVER_INC)/dms/event -I$(DRIVER_INC)/dms/core
drv_pcie_hdc-objs += hdcdrv_status.o
endif

KBUILD_EXTRA_SYMBOLS := $(src)/../dbl_chip_config/Module.symvers \
	$(src)/../pcie/Module.symvers \
	$(src)/../uda/Module.symvers \
	$(src)/../vpcie/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
