/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Description:
 * Author: huawei
 * Create: 2019-10-15
 */
#ifndef DEVDRV_PLATFORM_REGISTER_H
#define DEVDRV_PLATFORM_REGISTER_H

#define SOC_HARDWARE_VERSION DEVDRV_PLATFORM_MINI_V1
#define SOC_CPU_CLUSTER_CFG_BASE                                 0x1000e0000
#define SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_REQ_REG            (SOC_CPU_CLUSTER_CFG_BASE + 0xA00)
#define SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_DREQ_REG           (SOC_CPU_CLUSTER_CFG_BASE + 0xA04)
#define SOC_CPU_CLUSTER_CFG_SC_CLUS0_CTRL_RVBA0_REG              (SOC_CPU_CLUSTER_CFG_BASE + 0x2128)
#define SOC_CPU_CLUSTER_CFG_PMC_CORE_POWER_UP_REQ_REG            (SOC_CPU_CLUSTER_CFG_BASE + 0x80C4)
#define SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_ST_REG             (SOC_CPU_CLUSTER_CFG_BASE + 0x5A00)

#define FIRMWARE_CLUSTER_RESET_REG_OFFSET       (SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_REQ_REG -   \
        SOC_CPU_CLUSTER_CFG_BASE) // (0xA00)
#define FIRMWARE_CLUSTER_DERESET_REG_OFFSET     (SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_DREQ_REG -  \
        SOC_CPU_CLUSTER_CFG_BASE) // (0xA04)
#define FIRMWARE_CLUSTER_ENTRY_REG_OFFSET       (SOC_CPU_CLUSTER_CFG_SC_CLUS0_CTRL_RVBA0_REG -     \
        SOC_CPU_CLUSTER_CFG_BASE) // (0x2128)
#define FIRMWARE_CORE_POWERUP_REG_OFFSET        (SOC_CPU_CLUSTER_CFG_PMC_CORE_POWER_UP_REQ_REG -   \
        SOC_CPU_CLUSTER_CFG_BASE) // (0x80C4)
#define FIRMWARE_CLUSTER_STATUS_OFFSET          (SOC_CPU_CLUSTER_CFG_SC_CLUS_CRG_RESET_ST_REG -    \
        SOC_CPU_CLUSTER_CFG_BASE) // (0x5A00)

#define DEVDRV_TS_SYSCTL(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_TS_SUBSYSCTL_INDEX, chip_id)) // (0x1F0030000ULL)
#define DEVDRV_TS_SYSCTL_SIZE              0x10000
#define SOC_TS_SYSCTRL_BASE                0x1f0030000
#define SOC_TS_SYSCTRL_SC_TESTREG0_REG  (SOC_TS_SYSCTRL_BASE + 0xBE0)
#define SOC_TS_SYSCTRL_PERIPHCTRL6_REG  (SOC_TS_SYSCTRL_BASE + 0xB4)
#define SOC_TS_SYSCTRL_PERIPHCTRL7_REG  (SOC_TS_SYSCTRL_BASE + 0xB8)
#define SOC_TS_SYSCTRL_PERIPHCTRL8_REG  (SOC_TS_SYSCTRL_BASE + 0xBC)
#define SOC_TS_SYSCTRL_PERIPHCTRL9_REG  (SOC_TS_SYSCTRL_BASE + 0xC0)
#define SOC_TS_SYSCTRL_PERIPHCTRL11_REG (SOC_TS_SYSCTRL_BASE + 0xC8)
#define SOC_TS_SYSCTRL_PERIPHCTRL12_REG (SOC_TS_SYSCTRL_BASE + 0xCC)
#define SOC_TS_SYSCTRL_PERIPHCTRL13_REG (SOC_TS_SYSCTRL_BASE + 0xD0)
#define SOC_TS_SYSCTRL_SC_SYSSTAT14_REG (SOC_TS_SYSCTRL_BASE + 0x40)
#define SOC_TS_SYSCTRL_SC_TESTREG0_REG  (SOC_TS_SYSCTRL_BASE + 0xBE0)
#define SOC_TS_SYSCTRL_PERIPHCTRL32_REG (SOC_TS_SYSCTRL_BASE + 0x11C)

#define DEVDRV_SC_TESTREG_OFFSET           (SOC_TS_SYSCTRL_SC_TESTREG0_REG - SOC_TS_SYSCTRL_BASE)    // (0x0BE0)
#define TSCPU_BOOT_ADDR0_REG_OFFSET        (SOC_TS_SYSCTRL_PERIPHCTRL6_REG - SOC_TS_SYSCTRL_BASE)    // (0xB4)
#define TSCPU_BOOT_ADDR1_REG_OFFSET        (SOC_TS_SYSCTRL_PERIPHCTRL7_REG - SOC_TS_SYSCTRL_BASE)    // (0xB8)
#define TSCPU_CLOCK_GATE_ENABLE_REG_OFFSET (SOC_TS_SYSCTRL_PERIPHCTRL8_REG - SOC_TS_SYSCTRL_BASE)    // (0xBC)
#define TSCPU_CLOCK_DISABLE_REG_OFFSET     (SOC_TS_SYSCTRL_PERIPHCTRL9_REG - SOC_TS_SYSCTRL_BASE)    // (0xC0)
#define TSCPU_SOFT_RESET_ENABLE_REG_OFFSET (SOC_TS_SYSCTRL_PERIPHCTRL11_REG - SOC_TS_SYSCTRL_BASE)   // (0xC8)
#define LOW_POWER_DEBUG                    (SOC_TS_SYSCTRL_PERIPHCTRL12_REG - SOC_TS_SYSCTRL_BASE)   // (0xCC)
#define TSCPU_SOFT_STATUS_REG_OFFSET       (SOC_TS_SYSCTRL_PERIPHCTRL13_REG - SOC_TS_SYSCTRL_BASE)   // (0xD0)
#define TSCPU_IDLE_STATUS_REG_OFFSET       (SOC_TS_SYSCTRL_SC_SYSSTAT14_REG - SOC_TS_SYSCTRL_BASE)   // (0x40)
#define DEVDRV_SC_TESTREG_OFFSET           (SOC_TS_SYSCTRL_SC_TESTREG0_REG - SOC_TS_SYSCTRL_BASE)    // (0x0BE0)
#define TSCPU_PERIPHCTRL7(chip_id)         (DEVDRV_TS_SYSCTL(chip_id) + TSCPU_BOOT_ADDR1_REG_OFFSET) // ADDR[39:32]
#define TSCPU_PERIPHCTRL6(chip_id)         (DEVDRV_TS_SYSCTL(chip_id) + TSCPU_BOOT_ADDR0_REG_OFFSET) // ADDR[31:2]
#define TSCPU_PERIPHCTRL32_OFFSET          (SOC_TS_SYSCTRL_PERIPHCTRL32_REG - SOC_TS_SYSCTRL_BASE)

#define DEVDRV_DISP_BASE_ADDR(chip_id)  (devdrv_get_addr_base(DEVDRV_DTS_DISPATCH_INDEX, chip_id)) // (0x102060000ULL)
#define DEVDRV_DISP_SIZE                         0x4000

#define SOC_CFG_DISP_DAVINCI_PERI_BASE                       0xfc000000
#define SOC_CFG_DISP_DAVINCI_PERI_DISP_DAW_EN_REG            (SOC_CFG_DISP_DAVINCI_PERI_BASE + 0xD0)
#define SOC_CFG_DISP_DAVINCI_PERI_DISP_INTMASK0_REG          (SOC_CFG_DISP_DAVINCI_PERI_BASE + 0x804)
#define SOC_CFG_DISP_DAVINCI_PERI_DISP_INTSTAT0_REG          (SOC_CFG_DISP_DAVINCI_PERI_BASE + 0x808)
#define SOC_CFG_DISP_DAVINCI_PERI_DISP_INTCLR0_REG           (SOC_CFG_DISP_DAVINCI_PERI_BASE + 0x80C)
#define DEVDRV_DISP_DAW_EN   (SOC_CFG_DISP_DAVINCI_PERI_DISP_DAW_EN_REG - SOC_CFG_DISP_DAVINCI_PERI_BASE)   // (0x00D0)
#define DEVDRV_DISP_INTMASK0 (SOC_CFG_DISP_DAVINCI_PERI_DISP_INTMASK0_REG - SOC_CFG_DISP_DAVINCI_PERI_BASE) // (0x0804)
#define DEVDRV_DISP_INTSTAT0 (SOC_CFG_DISP_DAVINCI_PERI_DISP_INTSTAT0_REG - SOC_CFG_DISP_DAVINCI_PERI_BASE) // (0x0808)
#define DEVDRV_DISP_INTCLR0  (SOC_CFG_DISP_DAVINCI_PERI_DISP_INTCLR0_REG - SOC_CFG_DISP_DAVINCI_PERI_BASE)  // (0x080C)

#define DEVDRV_SYSCTL_BASE(chip_id)         (devdrv_get_addr_base(DEVDRV_DTS_SYSCTL_INDEX, chip_id)) // (0x1100c0000ULL)
#define DEVDRV_SYSCTL_REG_SIZE              0x10000

#define SOC_CPU_CLUSTER_CFG_BASE                       0x1000e0000
#define SOC_SYSCTRL_CFG_BASE                           0x100c0000
#define SOC_SYSCTRL_CFG_SC_PLL_PROF_CFG1_REG           (SOC_SYSCTRL_CFG_BASE + 0x3690)
#define SOC_CPU_CLUSTER_CFG_FPGA_VER_REG    (SOC_CPU_CLUSTER_CFG_BASE + 0xFFFC)
#define SOC_SYSCTRL_CFG_SC_BAK_DATA9_REG    (SOC_SYSCTRL_CFG_BASE + 0x3434)
#define DEVDRV_SYSCTL_VERSION_REG_OFFSET    (SOC_CPU_CLUSTER_CFG_FPGA_VER_REG - SOC_CPU_CLUSTER_CFG_BASE)    // (0xFFFC)
#define DEVDRV_SYSCTL_PLL_CFG1              (SOC_SYSCTRL_CFG_SC_PLL_PROF_CFG1_REG - SOC_SYSCTRL_CFG_BASE)    // 0x3690
#define DEVDRV_SYSCTL_VERSION_PHYS(chip_id) (DEVDRV_SYSCTL_BASE(chip_id) +      \
        DEVDRV_SYSCTL_VERSION_REG_OFFSET) // (0x01100cfffcULL)
#define DEVDRV_SYSCTL_VERSION_PLAT_MASK     0x3UL
#define DEVDRV_SYSCTL_PROFILE_RATE          (SOC_SYSCTRL_CFG_SC_BAK_DATA9_REG - SOC_SYSCTRL_CFG_BASE) // 0x3434

#define GIC_BASE_ADDR(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_GIC_BASE_INDEX, chip_id))  // (0x109000000ULL)

#define DEVDRV_TS_DOORBELL_ADDR(chip_id) (devdrv_get_addr_base(DEVDRV_DTS_TS_DOORBELL_INDEX, chip_id))  // (0x1F0400000)

#endif
