/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#include <linux/types.h>
#include <linux/module.h>
#include <linux/delay.h>
#include <linux/irqchip/arm-gic-v3.h>

#include "tsdrv_intr_comm.h"
#include "tsdrv_log.h"

#define CLOUD_CPUID_BIT_MASK      0x3
#define CLOUD_CPUID_BIT_OFFSET    8
#define CLOUD_CLUSTER_BIT_MASK    0x7
#define CLOUD_CLUSTER_BIT_OFFSET  16
#define CLOUD_SCLID_BIT_MASK      0x3
#define CLOUD_SCLID_BIT_OFFSET    19
#define CLOUD_DEVID_BIT_MASK      0x3
#define CLOUD_DEVID_BIT_OFFSET    21

#define CLOUDV2_CLUSTER_BIT_MASK   0x3
#define CLOUDV2_CLUSTER_BIT_OFFSET 8
#define CLOUDV2_SCLID_BIT_MASK     0x7
#define CLOUDV2_SCLID_BIT_OFFSET   16
#define CLOUDV2_DIE_ID_BIT_MASK           0x1
#define CLOUDV2_DIE_ID_BIT_OFFSET         19
#define CLOUDV2_SOCKET_ID_BIT_MASK        0xF
#define CLOUDV2_SOCKET_ID_BIT_OFFSET      20

#ifdef CFG_SOC_PLATFORM_CLOUD_V2
/* The irq is same for every device, only die is diff for one devie on cloud_v2 */
/* If all irqs are list, there are 16 members in the array */
STATIC struct tsdrv_intr_config cloudv2_intr_config[DEVDRV_MAX_DAVINCI_NUM][TSDRV_MAX_INTR_ROUTE_NUM] = {
    {
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ0",  346, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ1",  347, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ2",  348, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ3",  349, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ4",  350, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ5",  351, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ6",  352, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ7",  353, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ8",  354, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ9",  355, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ10",  356, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ11",  357, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ12",  358, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ13",  359, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ14",  360, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ15",  361, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ16",  362, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ17",  363, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ18",  364, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ19",  365, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ20",  366, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ21",  367, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ22",  368, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ23",  369, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ24",  370, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ25",  371, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ26",  372, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ27",  373, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ28",  374, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ29",  375, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ30",  376, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ31",  377, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ32",  378, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, -1, "FFTS_IRQ33",  379, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array */
        {0, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_DISABLE},
    },
    {
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ0",  762, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ1",  763, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ2",  764, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ3",  765, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ4",  766, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ5",  767, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ6",  768, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ7",  769, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ8",  770, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ9",  771, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ10",  772, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ11",  773, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ12",  774, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ13",  775, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ14",  776, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ15",  777, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ16",  778, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ17",  779, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ18",  780, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ19",  781, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ20",  782, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ21",  783, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ22",  784, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ23",  785, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ24",  786, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ25",  787, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ26",  788, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ27",  789, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ28",  790, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ29",  791, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ30",  792, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ31",  793, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ32",  794, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, -1, "FFTS_IRQ33",  795, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array */
        {1, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_DISABLE},
    },
};
#else
/* maximum device number is 4 for cloud */
STATIC struct tsdrv_intr_config cloud_intr_config[DEVDRV_MAX_DAVINCI_NUM][TSDRV_MAX_INTR_ROUTE_NUM] = {
    {
        {0, TSDRV_TSCPU, 1, "doorbell",    103, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "hwts_normal", 99,  TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "hwts_error",  100, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "hwts_debug",  101, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array */
        {0, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_DISABLE},
    },
    {
        {1, TSDRV_TSCPU, 1, "doorbell",    151, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, 0, "hwts_normal", 147, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, 0, "hwts_error",  148, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {1, TSDRV_TSCPU, 0, "hwts_debug",  149, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array */
        {1, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_DISABLE},
    },
    {
        {2, TSDRV_TSCPU, 1, "doorbell",    199, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {2, TSDRV_TSCPU, 0, "hwts_normal", 195, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {2, TSDRV_TSCPU, 0, "hwts_error",  196, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {2, TSDRV_TSCPU, 0, "hwts_debug",  197, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array, irq name must be NULL */
        {2, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_DISABLE},
    },
    {
        {3, TSDRV_TSCPU, 1, "doorbell",    247, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {3, TSDRV_TSCPU, 0, "hwts_normal", 243, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {3, TSDRV_TSCPU, 0, "hwts_error",  244, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {3, TSDRV_TSCPU, 0, "hwts_debug",  245, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* end of array, irq name must be NULL */
        {3, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_DISABLE},
    },
};
#endif

struct tsdrv_intr_config *tsdrv_get_intr_config(u32 devid, u32 chipid, u32 dieid)
{
#ifdef CFG_SOC_PLATFORM_CLOUD_V2
    return cloudv2_intr_config[dieid];
#else
    return cloud_intr_config[devid];
#endif
}

u64 tsdrv_get_irq_affinity(u32 chipid, u32 dieid, u32 sclid, u32 cluster, u32 cpuid)
{
    u64 affinity;
    TSDRV_PRINT_DEBUG("chip(%u), dieid(%u), sclid(%u), cluster(%u), cpuid(%u)\n", chipid, dieid, sclid, cluster, cpuid);

#ifdef CFG_SOC_PLATFORM_CLOUD_V2
    affinity = (((chipid & CLOUDV2_SOCKET_ID_BIT_MASK) << CLOUDV2_SOCKET_ID_BIT_OFFSET) |
        (((dieid) & CLOUDV2_DIE_ID_BIT_MASK) << CLOUDV2_DIE_ID_BIT_OFFSET) |
        (((sclid) & CLOUDV2_SCLID_BIT_MASK) << CLOUDV2_SCLID_BIT_OFFSET) |
        (((cluster) & CLOUDV2_CLUSTER_BIT_MASK) << CLOUDV2_CLUSTER_BIT_OFFSET));
#else
    affinity = ((((chipid) & CLOUD_DEVID_BIT_MASK) << CLOUD_DEVID_BIT_OFFSET) |
        (((sclid) & CLOUD_SCLID_BIT_MASK) << CLOUD_SCLID_BIT_OFFSET) |
        (((cluster) & CLOUD_CLUSTER_BIT_MASK) << CLOUD_CLUSTER_BIT_OFFSET) |
        (((cpuid) & CLOUD_CPUID_BIT_MASK) << CLOUD_CPUID_BIT_OFFSET));
#endif

    return affinity;
}
