/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#ifndef DRV_MEMORY_DDR_INFO_H
#define DRV_MEMORY_DDR_INFO_H

#include "memory_ddr_reg.h"

#ifndef CFG_MEMORY_DDR_STUB
/* DDR hardware info */
typedef struct _ddr_hw_info {
	unsigned int channel_num;
	unsigned int channel_bitmap;
	unsigned long long reg_base[DDR_MAX_CHAN_NUM];
} ddr_hw_info_t;

#ifdef CFG_DDR_REG_ADDR_310
STATIC ddr_hw_info_t g_ddr_hw_info = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE, DDRC_CHAN1_REG_BASE,
	DDRC_CHAN2_REG_BASE, DDRC_CHAN3_REG_BASE,
	DDRC_CHAN4_REG_BASE, DDRC_CHAN5_REG_BASE,
	DDRC_CHAN6_REG_BASE, DDRC_CHAN7_REG_BASE
}};
#endif

#ifdef CFG_DDR_REG_ADDR_710
STATIC ddr_hw_info_t g_ddr_hw_info = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE, DDRC_CHAN1_REG_BASE,
	DDRC_CHAN2_REG_BASE, DDRC_CHAN3_REG_BASE,
	DDRC_CHAN4_REG_BASE, DDRC_CHAN5_REG_BASE,
	DDRC_CHAN6_REG_BASE, DDRC_CHAN7_REG_BASE,
	DDRC_CHAN8_REG_BASE, DDRC_CHAN9_REG_BASE,
	DDRC_CHAN10_REG_BASE, DDRC_CHAN11_REG_BASE,
	DDRC_CHAN12_REG_BASE, DDRC_CHAN13_REG_BASE,
	DDRC_CHAN14_REG_BASE, DDRC_CHAN15_REG_BASE,
	DDRC_CHAN16_REG_BASE, DDRC_CHAN17_REG_BASE,
	DDRC_CHAN18_REG_BASE, DDRC_CHAN19_REG_BASE,
	DDRC_CHAN20_REG_BASE, DDRC_CHAN21_REG_BASE,
	DDRC_CHAN22_REG_BASE, DDRC_CHAN23_REG_BASE
}};

#ifdef CFG_SOC_PLATFORM_MDC_V51
#define BS9SX1A_DDRC_REG_OFFSET 0x30000
STATIC ddr_hw_info_t g_ddr_hw_info_bs9sx1a = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN1_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN2_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN3_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN4_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN5_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN6_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN7_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN8_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN9_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN10_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN11_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN12_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN13_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN14_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN15_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN16_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN17_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN18_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN19_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN20_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN21_REG_BASE + BS9SX1A_DDRC_REG_OFFSET,
	DDRC_CHAN22_REG_BASE + BS9SX1A_DDRC_REG_OFFSET, DDRC_CHAN23_REG_BASE + BS9SX1A_DDRC_REG_OFFSET
}};
#endif
#endif

#ifdef CFG_DDR_REG_ADDR_610VER3
#define DDRC_REG_OFFSET 0x30000
STATIC ddr_hw_info_t g_ddr_hw_info = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN1_REG_BASE + DDRC_REG_OFFSET,
	DDRC_CHAN2_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN3_REG_BASE + DDRC_REG_OFFSET,
	DDRC_CHAN4_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN5_REG_BASE + DDRC_REG_OFFSET,
	DDRC_CHAN6_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN7_REG_BASE + DDRC_REG_OFFSET,
	DDRC_CHAN8_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN9_REG_BASE + DDRC_REG_OFFSET,
	DDRC_CHAN10_REG_BASE + DDRC_REG_OFFSET, DDRC_CHAN11_REG_BASE + DDRC_REG_OFFSET,
}};
#endif

#ifdef CFG_DDR_REG_ADDR_910
STATIC ddr_hw_info_t g_ddr_hw_info = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE, DDRC_CHAN1_REG_BASE
}};
#endif

#ifdef CFG_DDR_REG_ADDR_310B
STATIC ddr_hw_info_t g_ddr_hw_info = { DDR_MAX_CHAN_NUM, 0xff, {
	DDRC_CHAN0_REG_BASE, DDRC_CHAN1_REG_BASE,
	DDRC_CHAN2_REG_BASE, DDRC_CHAN3_REG_BASE,
	DDRC_CHAN4_REG_BASE, DDRC_CHAN5_REG_BASE
}};
#endif
#endif
#endif
