# SPDX-License-Identifier: GPL-2.0

ifneq ($(filter $(PRODUCT), ascend910 ascend310p ascend610 ascend610Liteesl ascend610Lite \
	bs9sx1a ascend310 ascend310rc ascend310B as31xm1 ascend310Brc \
	ascend310Brcesl ascend310Besl ascend910B ascend920esl ascend920emu helper310p),)
obj-m += drv_prof.o
else
obj-$(CONFIG_NPU_PROF_DEVDRV) += drv_prof.o
endif

drv_prof-objs := prof_drv_dev.o
drv_prof-objs += prof_ts.o
drv_prof-objs += prof_peripheral.o
drv_prof-objs += prof_mem_sample/prof_mem_sample_by_dev.o
drv_prof-objs += prof_mem_sample/prof_mem_sample_by_proc.o

DRIVER_INC := $(src)/..

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/toolchain/bbox
ccflags-y += -I$(DRIVER_INC)/include/devmng -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src) -I$(src)/prof_inc -I$(src)/prof_mem_sample
ccflags-y += -DCFG_FEATURE_PROF

ifeq ($(fpga),true)
ccflags-y += -DTEMP_FPGA_B100
endif

ifeq ($(PRODUCT),helper310p)
ccflags-y += -DCFG_SOC_PLATFORM_HELPER -DCFG_FEATURE_KTHREAD_BIND_CORE
endif

ifneq ($(filter $(PRODUCT), ascend310Brc ascend310Brcesl ascend310Brcemu),)
ccflags-y += -DCFG_FEATURE_RC_MODE -DCFG_FEATURE_SRIOV
ccflags-y += -DCFG_FEATURE_NO_SUPPORT_NODE_DIVIDE
ccflags-y += -I$(src)/prof_virt
endif

ifeq ($(PRODUCT),ascend610)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
endif

ifeq ($(PRODUCT),bs9sx1a)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51
endif

ifneq ($(filter $(PRODUCT), ascend610Liteesl ascend610Lite),)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_SOC_MDC_V51_LITE
endif

ifeq ($(PRODUCT),as31xm1)
ccflags-y += -DCFG_SOC_PLATFORM_MDC_V11
endif

ifeq ($(PRODUCT),ascend910)
drv_prof-objs += ascd910/prof.o
drv_prof-objs += prof_drv_hdc_dev.o
ccflags-y += -I$(src)/ascd910 -I$(DRIVER_INC)/include/soc/cloud_v1
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -DCFG_FEATURE_KTHREAD_BIND_CORE -DCFG_FEATURE_HOST_COLLECTION
else ifneq ($(filter $(PRODUCT), ascend310p ascend610 ascend610Liteesl ascend610Lite bs9sx1a helper310p),)
drv_prof-objs += ascd610/prof.o
ccflags-y += -I$(src)/ascd610
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ifneq ($(filter $(PRODUCT), ascend310p),)
drv_prof-objs += ascd610/prof_hwts_init.o
drv_prof-objs += prof_drv_hdc_dev.o
ccflags-y += -DCFG_FEATURE_KTHREAD_BIND_CORE -DCFG_FEATURE_HOST_COLLECTION
ccflags-y += -DCFG_FEATURE_PROF_HWTS_THROUGH
endif
ifneq ($(filter $(PRODUCT), ascend610 ascend610Liteesl ascend610Lite bs9sx1a),)
drv_prof-objs += ascd610/drv_cpu_type.o
endif
else ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
drv_prof-objs += ascd310/prof.o
ccflags-y += -I$(src)/ascd310
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ifneq ($(filter $(PRODUCT), ascend310),)
drv_prof-objs += prof_drv_hdc_dev.o
ccflags-y += -DCFG_FEATURE_HOST_COLLECTION
endif
else ifneq ($(filter $(PRODUCT), ascend310B as31xm1 ascend310Brc ascend310Brcesl ascend310Besl),)
drv_prof-objs += ascd310B/prof.o
ccflags-y += -I$(src)/ascd310B
ccflags-y += -DCFG_SOC_PLATFORM_MINIV3
ccflags-y += -DCFG_FEATURE_KTHREAD_BIND_CORE -DCFG_FEATURE_STARS
ifneq ($(filter $(PRODUCT), ascend310B ascend310Besl),)
drv_prof-objs += prof_drv_hdc_dev.o
ccflags-y += -DCFG_FEATURE_HOST_COLLECTION
endif
ifneq ($(filter $(PRODUCT), ascend310Brc ascend310Brcesl),)
drv_prof-objs += prof_virt/dvprof_init.o
ccflags-y += -I$(src)/prof_virt
endif
drv_prof-objs += prof_chan.o
ccflags-y += -DCFG_TRS_REFACTOR_FEATURE
else ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
drv_prof-objs += ascd910B/prof.o
drv_prof-objs += prof_drv_hdc_dev.o
drv_prof-objs += prof_virt/dvprof_init.o
drv_prof-objs += prof_chan.o
ccflags-y += -I$(src)/ascd910B -I$(src)/prof_virt
ccflags-y += -I$(DRIVER_INC)/include/soc/cloud_v2
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
ccflags-y += -DCFG_FEATURE_KTHREAD_BIND_CORE -DCFG_FEATURE_HOST_COLLECTION
ccflags-y += -DCFG_FEATURE_STARS -DCFG_FEATURE_SRIOV
ccflags-y += -DCFG_TRS_REFACTOR_FEATURE
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers


KBUILD_EXTRA_SYMBOLS := \
	$(wildcard $(src)/../dbl_chip_config/Module.symvers) \
	$(wildcard $(src)/../dms/Module.symvers) \
	$(wildcard $(src)/../soc_resmng/Module.symvers) \
	$(wildcard $(src)/../trs_chan/Module.symvers) \
	$(wildcard $(src)/../trs_kunpeng/Module.symvers) \
	$(wildcard $(src)/../trs_pm_adapt/Module.symvers) \
	$(wildcard $(src)/../uda/Module.symvers) \
	$(wildcard $(src)/../virtmng/Module.symvers)
