# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_urd.o
ascend_urd-objs := urd_feature.o urd_init.o urd_notifier.o urd_container.o urd_acc_ctrl.o urd_kv.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(src)
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/bbox/drv_common

# Ascend310Brc device defines
ccflags-y += -DCFG_FEATURE_DEVICE_ENV -DCFG_FEATURE_RC_MODE

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
