# SPDX-License-Identifier: GPL-2.0
# drv_dfm.ko - Distributed Fault Management driver
# Depends on: mntn_bbox

obj-m := drv_dfm.o

DRIVER_INC := $(src)/..

ccflags-y += -I$(DRIVER_INC)/include/kernel
ccflags-y += -I$(DRIVER_INC)/include/kernel/ascend_platform
ccflags-y += -I$(DRIVER_INC)/include/platform
ccflags-y += -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include/toolchain
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox

ifneq ($(filter $(PRODUCT), ascend910 ascend910B ascend920esl ascend920emu),)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
ccflags-y += -I$(src)/ascd910
ifneq ($(filter $(PRODUCT), ascend910),)
ccflags-y += -DCFG_FEATURE_DFM_WITH_DVPP
endif
drv_dfm-objs := ascd910/devdrv_dfm_cloud.o
else ifneq ($(filter $(PRODUCT), ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu ascend610 bs9sx1a ascend310p helper310p ascend610Lite ascend610Liteesl as31xm1),)
ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
ccflags-y += -I$(src)/ascd610
drv_dfm-objs := ascd610/devdrv_dfm_miniv2.o
else
ccflags-y += -DCFG_SOC_PLATFORM_MINI
ccflags-y += -I$(src)/ascd310
drv_dfm-objs := ascd310/devdrv_dfm_mini.o
endif


# Feature config
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)

# Compat layer
ccflags-y += -include $(DRIVER_INC)/include/compat.h

# Dependency: bbox Module.symvers
KBUILD_EXTRA_SYMBOLS := $(src)/../bbox/Module.symvers

ccflags-y += -Wno-unused-parameter -Wno-sign-compare
