/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __OPIAI_MINI_V1_HIPCIEC_NVME_GLOBAL_REG_REG_OFFSET_H__
#define __OPIAI_MINI_V1_HIPCIEC_NVME_GLOBAL_REG_REG_OFFSET_H__

#include "../cloud_v1/hipciec_nvme_global_reg_reg_offset.h"

#ifndef HiPCIECTRL40V200_HIPCIEC_NVME_GLOBAL_REG_PF0_DB_INT_MASK0_REG
#define HiPCIECTRL40V200_HIPCIEC_NVME_GLOBAL_REG_PF0_DB_INT_MASK0_REG \
	HiPCIECTRL40V200_HIPCIEC_NVME_GLOBAL_REG_SQDB_INT_MASK0_REG
#endif

#endif
