# SPDX-License-Identifier: GPL-2.0

obj-m := drv_virtmng_host_stub.o
drv_virtmng_host_stub-objs := \
	virtmnghost_ctrl_stub.o \
	virtmnghost_msg_common_stub.o \
	virtmnghost_vpc_stub.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -DVIRTMNG_HOST
ccflags-y += -Wall -Werror -Wtrampolines $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char
ccflags-y += -Wformat=2 -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-empty-body
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/internal
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/driver

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
