# SPDX-License-Identifier: GPL-2.0
obj-m := drv_ascend_ctl.o
drv_ascend_ctl-objs := ascend_ctl_dev.o ascend_ctl_sysfs.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include -I$(src)
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
