# SPDX-License-Identifier: GPL-2.0
obj-m := drv_log.o

drv_log-objs := \
	log_drv_dev.o \
	log_drv_conn/log_drv_ipc.o \
	log_drv_conn/log_drv_shm.o \
	log_drv_conn/log_drv_sqcq.o \
	log_drv_res/log_drv_res_common.o

DRIVER_INC := $(src)/..
log_local_inc := -I$(src) -I$(src)/log_agent -I$(src)/log_drv_conn
log_local_inc += -I$(src)/log_drv_res -I$(src)/log_xpc -I$(src)/log_bind_core
log_product_inc :=

ccflags-y += -fstack-protector-all
ccflags-y += -Wall -Werror -Wtrampolines
ccflags-y += $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char -Wformat=2
ccflags-y += -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers

ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/include/platform
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox/device
ccflags-y += -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/ts_platform -I$(DRIVER_INC)/ipcdrv -I$(DRIVER_INC)/hdcdrv/hdcdrv
ccflags-y += $(log_local_inc)

ifneq ($(filter $(PRODUCT), ascend910),)
	ccflags-y += -DCFG_SOC_PLATFORM_CLOUD
	log_product_inc += -I$(src)/log_drv_res/ascd910
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend910
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/cloud_v1
else ifneq ($(filter $(PRODUCT), ascend910B ascend920esl ascend920emu),)
	ccflags-y += -DCFG_SOC_PLATFORM_CLOUD_V2
	log_product_inc += -I$(src)/log_drv_res/ascd910b
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend910
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/cloud_v2
	ifeq ($(PRODUCT),ascend910B)
		ccflags-y += -DCFG_TRS_REFACTOR_FEATURE
		drv_log-objs += log_drv_conn/log_drv_chan.o
	endif
else ifneq ($(filter $(PRODUCT), ascend310 ascend310rc),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINI
	log_product_inc += -I$(src)/log_drv_res/ascd310
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend310
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend310
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ascend310
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/mini_v1
else ifneq ($(filter $(PRODUCT), ascend310p helper310p),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINIV2
	log_product_inc += -I$(src)/log_drv_res/ascd310p
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend610
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/cloud_v1
else ifneq ($(filter $(PRODUCT), ascend310B ascend310Besl ascend310Bemu ascend310Brc ascend310Brcesl ascend310Brcemu),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_TRS_REFACTOR_FEATURE
	log_product_inc += -I$(src)/log_drv_res/ascd310b
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend610
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/mini_v3
	drv_log-objs += log_drv_conn/log_drv_chan.o
else ifneq ($(filter $(PRODUCT), as31xm1),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINIV3 -DCFG_SOC_PLATFORM_MDC_V11 -DCFG_TRS_REFACTOR_FEATURE
	ccflags-y += -DCFG_FEATURE_HISTORY_CONFIG
	log_product_inc += -I$(src)/log_drv_res/as31xm1
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend610
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/mini_v3
	drv_log-objs += log_drv_conn/log_drv_chan.o
else ifneq ($(filter $(PRODUCT), ascend610 bs9sx1a),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MDC_V51
	ccflags-y += -DCFG_FEATURE_HISTORY_CONFIG
	ifeq ($(PRODUCT),bs9sx1a)
		ccflags-y += -DCFG_SOC_PLATFORM_MDC_BS9SX1A
	endif
	log_product_inc += -I$(src)/log_drv_res/ascd610
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend610
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ascend610
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/cloud_v1
	drv_log-objs += log_xpc/log_xpc.o log_xpc/log_xpc_server.o log_bind_core/drv_cpu_type.o
else ifneq ($(filter $(PRODUCT), ascend610Lite ascend610Liteesl),)
	ccflags-y += -DCFG_SOC_PLATFORM_MINIV2 -DCFG_SOC_PLATFORM_MDC_V51 -DCFG_SOC_MDC_V51_LITE
	ifeq ($(PRODUCT),ascend610Lite)
		ccflags-y += -DCFG_SOC_MDC_V51_LITE_FPGA
	endif
	log_product_inc += -I$(src)/log_drv_res/ascd610lite
	log_product_inc += -I$(DRIVER_INC)/ts_platform/ascend610
	log_product_inc += -I$(DRIVER_INC)/dms/drv_devmng/drv_devmng_device/ascend910
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ascend610
	log_product_inc += -I$(DRIVER_INC)/tsdrv/ts_drv_common -I$(DRIVER_INC)/tsdrv/ts_drv_common/tsdrv_dev
	log_product_inc += -I$(DRIVER_INC)/include/soc/cloud_v1
	drv_log-objs += log_xpc/log_xpc.o log_xpc/log_xpc_server.o log_bind_core/drv_cpu_type.o
endif

ccflags-y += $(log_product_inc)
ccflags-y += -I$(DRIVER_INC)/include/devmng -I$(DRIVER_INC)/include/tsdrv
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h


KBUILD_EXTRA_SYMBOLS := $(src)/../dbl_chip_config/Module.symvers \
	$(src)/../dms/Module.symvers \
	$(src)/../icm/Module.symvers \
	$(src)/../soc_resmng/Module.symvers \
	$(src)/../trs_chan/Module.symvers \
	$(src)/../trs_kunpeng/Module.symvers \
	$(src)/../tsdrv/Module.symvers \
	$(src)/../uda/Module.symvers
