# SPDX-License-Identifier: GPL-2.0

obj-m := drv_vhdc.o
drv_vhdc-objs := \
	vhdc_agent.o \
	vhdc_core.o \
	vhdc_mem.o \
	hdcdrv_core_com.o \
	hdcdrv_mem_com.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -DCFG_FEATURE_SHARE_LOG
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/include/hiss
ccflags-y += -I$(DRIVER_INC)/include/user_config -I$(DRIVER_INC)/include/dbl
ccflags-y += -I$(DRIVER_INC)/libc_sec/include -I$(src)

ifeq ($(PRODUCT),ascend910)
ccflags-y += -DCFG_SOC_PLATFORM_CLOUD -DCFG_SOC_PLATFORM_CLOUD_HOST
ccflags-y += -DCFG_FEATURE_VFIO
else ifeq ($(PRODUCT),ascend310p)
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA -DCFG_SOC_PLATFORM_MDC_V51
ccflags-y += -DCFG_FEATURE_VFIO
endif

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
ccflags-y += -Wall -Werror -Wtrampolines $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef
ccflags-y += -funsigned-char -Wformat=2 -Wstack-usage=2048 -Wcast-align
ccflags-y += -Wextra
