/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2022. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* Description:
* Author: huawei
* Create: 2019-10-15
*/

#include <linux/types.h>
#include <linux/module.h>
#include <linux/delay.h>
#include <linux/irqchip/arm-gic-v3.h>

#include "tsdrv_intr_comm.h"
#include "tsdrv_log.h"

#define CPUID_BIT_MASK        0x7
#define CPUID_BIT_OFFSET      8
#define CLUSTER_BIT_MASK      0x3
#define CLUSTER_BIT_OFFSET    16
#define SCLID_BIT_MASK        0x3
#define SCLID_BIT_OFFSET      18
#define DEVID_BIT_MASK        0x3
#define DEVID_BIT_OFFSET      21

/* maximum device number is 1 for mini */
STATIC struct tsdrv_intr_config mini_intr_config[DEVDRV_MAX_DAVINCI_NUM][TSDRV_MAX_INTR_ROUTE_NUM] = {
    {
        {0, TSDRV_TSCPU, 0, "TS_BS_taskdone", 323, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* mailbox ack interrupt between aicpu and ts */
        {0, TSDRV_TSCPU, 0, "HOSTCPU0_MBOX_ACL_TO_TS", 327, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU0_MBOX_ACK_TO_TS", 328, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 0, "TS_MBOX_ACK_TO_AICPU0", 329, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU1_MBOX_ACK_TO_TS", 330, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 1, "TS_MBOX_ACK_TO_AICPU1", 331, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU2_MBOX_ACK_TO_TS", 332, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 2, "TS_MBOX_ACK_TO_AICPU2", 333, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU3_MBOX_ACK_TO_TS", 334, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 3, "TS_MBOX_ACK_TO_AICPU3", 335, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU4_MBOX_ACK_TO_TS", 336, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 4, "TS_MBOX_ACK_TO_AICPU4", 337, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU5_MBOX_ACK_TO_TS", 338, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 5, "TS_MBOX_ACK_TO_AICPU5", 339, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU6_MBOX_ACK_TO_TS", 340, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 6, "TS_MBOX_ACK_TO_AICPU6", 341, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "AICPU7_MBOX_ACK_TO_TS", 342, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 7, "TS_MBOX_ACK_TO_AICPU7", 343, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},

        /* sdma interrupt for ts */
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int0", 167, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int1", 168, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int2", 169, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int3", 170, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int4", 171, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int5", 172, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int6", 173, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int7", 174, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int8", 175, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int9", 176, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int10", 177, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int11", 178, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int12", 179, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int13", 180, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int14", 181, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOC_int15", 182, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int0", 183, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int1", 184, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int2", 185, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int3", 186, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int4", 187, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int5", 188, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int6", 189, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int7", 190, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int8", 191, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int9", 192, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int10", 193, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int11", 194, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int12", 195, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int13", 196, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int14", 197, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "SDMA_CH_IOE_int15", 198, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},

        /* pcie dma interrupt for ts */
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS12", 588, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS13", 589, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS14", 590, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS15", 591, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS28", 604, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS29", 605, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS30", 606, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "PCIE_DMA_TO_TS31", 607, TSDRV_IRQ_EDGE_TRIGGER, TSDRV_IRQ_ENABLE},

        /* ipc ack interrupt to ts */
        {0, TSDRV_TSCPU, 0, "IPC_ACK_INT0", 199, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* ipc ack interrupt to aicpu */
        {0, TSDRV_AICPU, 4, "IPC_ACK_INT5", 205, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 5, "IPC_ACK_INT6", 206, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 6, "IPC_ACK_INT7", 207, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 7, "IPC_ACK_INT8", 208, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* ipc data interrupt to ts */
        {0, TSDRV_TSCPU, 0, "IPC_MBOX_INT0", 209, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_TSCPU, 0, "IPC_MBOX_INT1", 210, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* ipc data interrupt to control cpu (is this necessary ?) */
        {0, TSDRV_AICPU, 0, "IPC_MBOX_INT4", 213, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 0, "IPC_MBOX_INT5", 214, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 1, "IPC_MBOX_INT6", 215, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 1, "IPC_MBOX_INT7", 216, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 2, "IPC_MBOX_INT8", 217, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 2, "IPC_MBOX_INT9", 218, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 3, "IPC_MBOX_INT10", 219, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 3, "IPC_MBOX_INT11", 220, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 4, "IPC_MBOX_INT12", 221, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 4, "IPC_MBOX_INT13", 222, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 5, "IPC_MBOX_INT14", 223, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 5, "IPC_MBOX_INT15", 224, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 6, "IPC_MBOX_INT16", 225, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 6, "IPC_MBOX_INT17", 226, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 7, "IPC_MBOX_INT18", 227, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},
        {0, TSDRV_AICPU, 7, "IPC_MBOX_INT19", 228, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

        /* doorbell to ts */
        {0, TSDRV_TSCPU, 0, "DOORBELL_TO_TS", 325, TSDRV_IRQ_LEVEL_TRIGGER, TSDRV_IRQ_ENABLE},

       /* end of array */
        {0, TSDRV_INVALID, -1, NULL, -1, TSDRV_IRQ_NONE_TRIGGER, TSDRV_IRQ_DISABLE},
    },
};

struct tsdrv_intr_config *tsdrv_get_intr_config(u32 devid, u32 chipid, u32 dieid)
{
    return mini_intr_config[devid];
}

u64 tsdrv_get_irq_affinity(u32 chipid, u32 dieid, u32 sclid, u32 cluster, u32 cpuid)
{
    u64 affinity;

    affinity = (((chipid & DEVID_BIT_MASK) << DEVID_BIT_OFFSET) |
        (((sclid) & SCLID_BIT_MASK) << SCLID_BIT_OFFSET) |
        (((cluster) & CLUSTER_BIT_MASK) << CLUSTER_BIT_OFFSET) |
        (((cpuid) & CPUID_BIT_MASK) << CPUID_BIT_OFFSET));

    return affinity;
}
