# SPDX-License-Identifier: GPL-2.0
obj-m := ascend_virtmng_dev.o
ascend_virtmng_dev-objs := virtmngdev_pci.o virtmngdev_proc_fs.o \
	soc/virtmngdev_element.o soc/virtmngdev_res_common.o \
	soc/common/virtmngdev_common_resource.o soc/common/virtmngdev_res_mng.o \
	soc/common/virtmngdev_client_online.o \
	soc/adapt/virtmngdev_resource_register.o soc/adapt/virtmngdev_resource.o \
	soc/adapt/virtmngdev_mia_cfg.o soc/adapt/virtmngdev_memory.o \
	soc/adapt/virtmngdev_ts.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/dms
ccflags-y += -I$(DRIVER_INC)/include/internal -I$(DRIVER_INC)/include/rms
ccflags-y += -I$(DRIVER_INC)/include/platform -I$(DRIVER_INC)/include/soc/mini_v3
ccflags-y += -I$(DRIVER_INC)/include/toolchain/bbox -I$(DRIVER_INC)/include/devmng
ccflags-y += -I$(DRIVER_INC)/include/tsdrv -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(DRIVER_INC)/include/hiss -I$(DRIVER_INC)/include/user_config
ccflags-y += -I$(src) -I$(src)/soc -I$(src)/soc/common -I$(src)/soc/adapt -I$(DRIVER_INC)/include/dbl  -I$(DRIVER_INC)/include/dbl -I$(src)/soc/mini_v3 -I$(src)/soc/mini_v3
ccflags-y += -DVIRTMNG_DEV -DCFG_SOC_PLATFORM_MINIV3 -DCFG_FEATURE_SOC_VIRTMNG -DCFG_SURPPORT_PCIE_HOST_DEVICE_COMM -DCFG_FEATURE_VIRTMNG_SUPPORT_UDA
KBUILD_EXTRA_SYMBOLS := $(src)/../dbl_chip_config/Module.symvers \
	$(src)/../dbl_runenv_config/Module.symvers \
	$(src)/../icm/Module.symvers \
	$(src)/../soc_resmng/Module.symvers \
	$(src)/../uda/Module.symvers \
	$(src)/../user_cfg/Module.symvers
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
