# SPDX-License-Identifier: GPL-2.0

obj-m := drv_vpcie.o

drv_vpcie-objs := \
	virtmngagent_pci.o \
	virtmngagent_ctrl.o \
	virtmngagent_unit.o \
	virtmngagent_extension.o

DRIVER_INC := $(src)/..

ifneq ($(NOT_SUPPORT_SP),y)
ccflags-y += -fstack-protector-all
endif

ccflags-y += -DVIRTMNG_AGENT
ccflags-y += -Wall -Werror -Wtrampolines $(WDATE_TIME) -Wfloat-equal -Wvla -Wundef -funsigned-char
ccflags-y += -Wformat=2 -Wstack-usage=2048 -Wcast-align -Wextra
ccflags-y += -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-empty-body
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include/internal
ccflags-y += -I$(DRIVER_INC)/include -I$(DRIVER_INC)/include/driver
ccflags-y += -I$(DRIVER_INC)/include/dbl -I$(DRIVER_INC)/libc_sec/include
ccflags-y += -I$(src)

-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
