# SPDX-License-Identifier: GPL-2.0
obj-m := drv_icm.o
drv_icm-objs := icm_core.o icm_interface.o icm_ipc.o

DRIVER_INC := $(src)/..
ccflags-y += -I$(DRIVER_INC)/include/kernel -I$(DRIVER_INC)/include
ccflags-y += -I$(src)
ccflags-y += -DCFG_SOC_PLATFORM_ESL_FPGA -DCFG_SOC_PLATFORM_MINIV3
-include $(DRIVER_INC)/config/feature_config/feature.mk
ccflags-y += $(CONFIG_DEFINES)
ccflags-y += -include $(DRIVER_INC)/include/compat.h
ccflags-y += -Wno-unused-parameter -Wno-sign-compare
